[Step3] 리뷰 요청 드립니다.
next-step/jwp-qna pull request #101
Opened 2021-06-01 15:35 UTC by sojeong-park

리뷰 요청 드립니다.
감사합니다 : )

2021-06-02 11:35 UTC, tearight requested changes
워낙 완벽하게 잘해주셔서 코멘트를 드릴 점이 거의 없네요. 👍
현재 몇가지 테스트가 실패하는 것 같아요. 이 부분과 소정의 코멘트를 확인 부탁드립니다.

2021-06-02 11:35 UTC, tearight commented on src/main/java/qna/domain/Answers.java
> +        return this.answers;
this 를 사용하는 기준이 무엇일까요 ?
이것은 지극히 취향의 영역이라 궁금해서 질문드립니다. 🙂
저는 this 는 멤버변수와 파라메터 명이 같을때만 사용하고 있어요.

2021-06-02 11:35 UTC, tearight commented on src/main/java/qna/domain/Question.java
> +        deleteHistories.addDeleteHistory(new DeleteHistory(ContentType.QUESTION, id, writer, LocalDateTime.now()));
LocalDateTime 을 주입받으면 어떨까요?
현재 코드에서는 저 시간 값에 대한 검증을 하기 어려워 보이네요.
제가 속한 팀에서는 LocalDateTimeProvider 라는 컴포넌트를 만들어서 이 컴포넌트를 통해 시간을 받아오고 있어요.
또 그렇게 된다면 어떤 장점이 있을지 생각해보시는 것도 좋을 것 같아요.

2021-06-02 11:35 UTC, tearight commented on src/main/java/qna/domain/Answers.java
> +public class Answers {
일급콜렉션을 JPA 에서 사용하는것 너무 좋네요. 👍

2021-06-02 11:35 UTC, tearight commented on src/main/java/qna/domain/Answers.java
> +            answer.validOwner(loginUser);
`객체에게 묻지말고 시켜라` 👍

2021-06-02 11:43 UTC, sojeong-park commented on src/main/java/qna/domain/Answers.java
> +        return this.answers;
지금 생각해보니 기준이 딱히 없었던거 같아요
멤버변수이면 this를 붙여줬던거 같은데 이것도 마음 내킬때 했던거 같네요 😂😂
리뷰어님과 같이 this 는 멤버변수와 파라메터 명이 같을때만 사용하는 기준을 잡고 하면 좋을거 같아요!
좋은 지적 감사합니다 : )

2021-06-02 13:12 UTC, sojeong-park commented on src/main/java/qna/domain/Question.java
> +        deleteHistories.addDeleteHistory(new DeleteHistory(ContentType.QUESTION, id, writer, LocalDateTime.now()));
LocalDateTime을 주입받도록 수정하였습니다 : )
그런데 한가지 궁금한것이 현재시간을 주입받는건 변함 없어 보이는데 시간값 자체를 검증한다는 말씀일까요?.?

2021-06-02 14:26 UTC, tearight commented on src/main/java/qna/domain/Question.java
> +        deleteHistories.addDeleteHistory(new DeleteHistory(ContentType.QUESTION, id, writer, LocalDateTime.now()));
이번 과제에서는 시간값을 검증하는데에 필요하기도 합니다.
그리고 Question 의 삭제 시각과 Answer 의 삭제 시각을 동일하게 가져가기 위해서도 필요할 것 같아요.
(동일한 삭제 시간임을 검증하는 테스트코드가 작성될 수도 있겠네요.)

---

LocalDateTime.now() 를 호출하면 호출할 때마다 nanomills(ns) 또는 millisecond(ms) 가 조금씩 증가해 있을 거에요.
이런 차이로 초 단위가 최대 5초까지 차이나는 경우도 있을 것 같아요.

현재 시각(LocalDateTime.now) 를 사용하지 않는 상황은 아래와 같은 경우가 있을 것 같은데요.
1. 특정 테이블과 로그테이블의 타임스탬프가 동일해야 하는 경우
2. API 호출 받은 시간으로 타임스탬프를 등록해야 하는 경우

제 경우는 운영중 데이터에 문제가 생겨서 시간순으로 테이블 레코드를 비교해봐야 할 때 시간차가 조금 나는 것으로 불편하거나 검증할 수 없는 상황이 발생한 적도 있습니다.

따라서 당장의 문제가 발생한다기 보다 운영중의 문제를 해결하는데 방해가 되지 않도록 시간을 주입하는게 좋다 라고 생각하시면 될 것 같아요.

2021-06-02 14:28 UTC, tearight approved these changes
이번 JPA 미션은 너무 잘해주신 덕에 수월하게 끝난 느낌이네요. 👍
미션은 이것으로 종료하겠습니다. 항상 화이팅입니다!

2021-06-02 14:29 UTC, merged

2021-06-03 01:54 UTC, sojeong-park commented on src/main/java/qna/domain/Question.java
> +        deleteHistories.addDeleteHistory(new DeleteHistory(ContentType.QUESTION, id, writer, LocalDateTime.now()));
제가 간과하고있던 부분인데 자세히 알려주셔서 감사합니다! 👍