[step3] 질문 삭제하기 리팩터링 리뷰 요청 드립니다.
next-step/jwp-qna pull request #105
Opened 2021-06-01 17:27 UTC by prodo-developer

안녕하세요 규남 리뷰어님

어느덧 JPA 마무리 3단계 리뷰 요청 드립니다.

이번 과정은 리팩터링 및 분리하는 과정에서 많은 걸 느꼈고,
매일 동기들과 일과 후에 카페에서 모각코를 통해 꿀 팁도 얻고 좋은 시간들을 가지고 있습니다.

다음 ATDD에 가기 위한 단계로 생각도 들었으며, 1,2단계에 중간 중간에  꿀팁들을 알려주셔서 감사합니다! ㅎㅎ

마지막까지 좋은 피드백은 언제든지 환영합니다.

2021-06-02 14:52 UTC, kyucumber requested changes
안녕하세요

몇가지 코멘트 남겨두었으니 확인 부탁드립니다.

2021-06-02 14:52 UTC, kyucumber commented on src/main/java/qna/domain/Answer.java
> +        return new DeleteHistory(ContentType.ANSWER, id, writer, LocalDateTime.now());
`Answer`가 delete시 `DeleteHistory`를 반환하도록 구현해주셨네요.

`DeleteHistory`는 `Answer`, `Question` 이외에 늘어나는 여러 엔티티들과 결합이 될 가능성이 높아보입니다.

설계의 관점에서 늘어나는 모든 엔티티들이 아래와 같이 참조를 하면 어떻게 될까요?

`Answer` -> `DeleteHistory`
`Question` -> `DeleteHistory`
`NewEntity` -> `DeleteHistory`

늘어나는 여러 엔티티가 `DeleteHistory`와 결합을 하게 되며, `DeleteHistory`의 수정에 여러 엔티티가 변경될 가능성이 높아집니다.

Service 레이어의 코드가 조금 더 길어질 순 있겠지만 결합도를 낮추는 관점에서는 Service 레이어에 DeleteHistory의 생성 관련된 코드를 넣는 부분도 고려해보시면 좋을 것 같아요.

이외에도 스프링의 이벤트 리스너 등을 통해서도 해당 부분을 분리하거나 할 수 있을 것 같습니다.
관심 있으시면 한번 학습해보셔도 좋을 것 같네요.

2021-06-02 14:52 UTC, kyucumber commented on src/main/java/qna/domain/DeleteHistories.java
> +        return histories;
아래 부분을 추가해주려고 toUnmodifiableList와 같은 이름을 지어주신걸까요?

```java
return Collections.unmodifiableList(histories);
```

2021-06-02 14:52 UTC, kyucumber commented on src/main/java/qna/domain/Question.java
> +    private List<Answer> wroteQuestions  = new ArrayList<>();
```java
@OneToMany(mappedBy = "question")
private List<Answer> answers = new ArrayList<>();
```

위 맨 위에 있는 엔티티 매핑은 정상적으로 이루어진 것으로 보입니다.

`wroteAnswers` `wroteQuestions`를 추가해주신 이유가 잘 이해되지 않네요. 의도를 알 수 있을까요?

사용되는 부분이 보이지 않는 것 같아요.

2021-06-02 14:52 UTC, kyucumber commented on src/main/java/qna/domain/Question.java
> +    private List<DeleteHistory> deleteHistories = new ArrayList<>();
이미 삭제된 질문을 먼저 조회한 다음에 `DeleteHistory`를 찾기 보다는

`Question` 아이디를 통해 바로 `DeleteHistory`를 조회하지 않을까요?

이 연관관계 매핑이 필요할까요?

2021-06-02 14:52 UTC, kyucumber commented on src/main/java/qna/service/QnaService.java
> +        deleteHistoryService.saveAll(delete);
번거로울 수 있겠지만, 히스토리가 여러개인 의도를 나타내주시면 어떨까요?

```suggestion
        DeleteHistories deleteHistories = question.delete(loginUser);
        deleteHistoryService.saveAll(deleteHistories);
```

2021-06-02 15:00 UTC, prodo-developer commented on src/main/java/qna/domain/DeleteHistories.java
> +        return histories;
넵 위와 같이 선언하려다가 객체를 재활용하고 싶어, 저렇게 선언하였습니다.
"컬렉션에서 리스트에 데이터를 추가한 뒤 더 이상 데이터 삭제, 추가를 막기 위한 방법"
-> return Collections.unmodifiableList(histories); 이 방법이 더 좋을까요?

2021-06-02 15:02 UTC, prodo-developer commented on src/main/java/qna/domain/Question.java
> +    private List<Answer> wroteQuestions  = new ArrayList<>();
잘못된 질문들, 답변들을 담기 위한 걸로 생각했는데 생각해보니 필요가 없고 answers만 필요한 것으로 보여서
삭제하였습니다. 

"질문 조회시에 삭제내역을 볼필요가 없다."

감사합니다.

2021-06-02 15:03 UTC, prodo-developer commented on src/main/java/qna/domain/Question.java
> +    private List<DeleteHistory> deleteHistories = new ArrayList<>();
위와 마찬가지로 필요없는 객체 여서 삭제 하였습니다.
감사합니다.

2021-06-04 15:41 UTC, prodo-developer commented on src/main/java/qna/domain/Question.java
> +    private List<DeleteHistory> deleteHistories = new ArrayList<>();
"답변 조회시에 삭제내역을 볼필요가 없다." 
-> 미션에 없는내용이므로 삭제하였습니다.

감사합니다.

2021-06-04 15:43 UTC, prodo-developer commented on src/main/java/qna/domain/Answer.java
> +        return new DeleteHistory(ContentType.ANSWER, id, writer, LocalDateTime.now());
도메인에 있던 delete기능들을 QnaService로 분리하였으며,

"Service 레이어의 코드가 조금 더 길어질 순 있겠지만 결합도를 낮추는 관점에서는 Service 레이어에 DeleteHistory의 생성 관련된 코드를 넣는 부분도 고려해보시면 좋을 것 같아요."

의도에 맞도록 수정 해 보았습니다.

2021-06-05 05:03 UTC, kyucumber commented on src/main/java/qna/domain/DeleteHistories.java
> +        return histories;
재활용 하는 부분이 좋은 방법으로 보이진 않는데 그냥 의도한대로 해주셔도 무방할 듯 합니다.

2021-06-05 05:04 UTC, kyucumber approved these changes
마지막 단계까지 진행하시느라 고생 많으셨습니다.

다음 단계 진행을 위해 머지하겠습니다.

2021-06-05 05:04 UTC, merged