Step1 - 엔티티 매핑
next-step/jwp-qna pull request #111
Opened 2021-06-02 09:26 UTC by wrallee

안녕하세요
JPA 1단계 미션 제출합니다.
잘 부탁 드리겠습니다~! 😊

2021-06-03 04:08 UTC, parkeeseul requested changes
안녕하세요 우찬님! JPA 미션을 함께하게 된 박이슬 입니다!
첫 번째 단계 잘 구현해주셨네요! 👍 
몇 가지 코멘트 남겨두었으니 확인 부탁드리겠습니다!
함께 이번 미션 잘 풀어나가보아요! 화이팅 입니다! 🔥

2021-06-03 04:08 UTC, parkeeseul commented on src/main/java/qna/domain/Answer.java
> +    @Column(name = "id")
혹시 따로 컬럼 명을 지정하신 이유가 있으실까요? 😄

2021-06-03 04:08 UTC, parkeeseul commented on src/main/java/qna/domain/Question.java
> +    @Column(name = "title", nullable = false)
DDL을 보시면 title의 length 에 대한 내용이 있는데요
요구사항을 한번 확인 해주세요! 😄 
```suggestion
    @Column(name = "title", nullable = false, length = 100)
```

2021-06-03 04:08 UTC, parkeeseul commented on src/main/java/qna/domain/User.java
> +public class User extends BaseTimeEntity {
다음 요구사항은 어떻게 반영해주면 좋을까요? 😄 
```
alter table user
    add constraint UK_a3imlf41l37utmxiquukk8ajc unique (user_id)
```

또한 User 엔티티의 각 컬럼들의 length에 대한 조건도 함께 확인 부탁드립니다 😄

2021-06-03 04:08 UTC, parkeeseul commented on src/main/java/qna/domain/Answer.java
>      private String contents;
현재 contents 는 varchar 로 지정되어 있는데요
요구사항은 clob 이네요 😄 
어떻게 수정해보면 좋을까요?

2021-06-03 04:46 UTC, wrallee commented
리뷰 감사드립니다!
컬럼명은 구체적으로 명시하는것이 좋지 않을까 생각해서 전부 명시했는데요. 생각해보니 카멜케이스로 잘 작성하는것만으로도 충분하겠군요.. 😰
요구사항을 빼먹은게 많네요. 수정해서 다시 요청드리겠습니다!

2021-06-04 10:51 UTC, parkeeseul approved these changes
피드백 잘 반영해주셨네요! 👍 
다음 단계 진행해주세요! 😄 
오늘은 즐거운 금요일! 내일은 즐거운 주말!
미션 화이팅 입니다 ! 🔥

2021-06-04 10:53 UTC, merged