[Step 1] 엔티티 매핑 리뷰 요청 드립니다.
next-step/jwp-qna pull request #116
Opened 2021-06-02 17:06 UTC by chae-yh

### Description
스텝 1 엔티티 매핑 입니다. Q&A 서비스에 대한 관계형 테이블을 기반으로 엔티티 및 레포지토리를 작성하였습니다.

jpa 는 얘기는 많이 들었지만 실제 사용해본적이 없어 과제 시작부터 많이 당황하면서 시작했던 것 같습니다. 처음에 잘 이해가 되지 않아 소스 작성도 힘들었지만, 영한님의 강의와 인터넷에 있는 자료로 공부하면서, 부족한 점이 많지만 그래도 제출할 만한 소스 상태가 된 듯 합니다. jpa 를 많이 사용해보지 않아 미숙한 점이 많을 것 같은데 그런 부분에 대한 많은 조언 부탁드립니다 : )

추가로, 코드 작성 중 해결이 안됐던 부분이 있어 pr 과 동시에 문의 드립니다. QuestionTest 의use_written_method_findByDeletedFalse 메소드가 해당 테스트만 수행하면 테스트가 성공하는데, QuestionTest를 전체 테스트 실행하면 테스트가 실패합니다. 테스트의 의도는, deleted 필드를 true 한 후 findByDeletedFalse 메소드를 사용했을 때 아무런 데이터를 가져오지 못하고, Q1.setDeleted(false) 로, 해당 필드를 false 로 업데이트 후 재 조회 했을 때 데이터를 가져오는 부분입니다. 전체 테스트 실행을 하면 Q1.setDeleted(false)를 해도 해당 필드가 업데이트가 안됩니다. 영속성 컨텍스트 이슈 일 것 같은데 정확한 이유를 잘 모르겠어서 문의 드립니다.

내용 확인 부탁드립니다. 감사합니다 : )

### Commits
* docs : write to-do list of jpa q&a
* feat : jpa test of save and identical test
* feat : add test code that deals with written method
* feat : add question test that uses wriiten methods
* feat : add default vlaue to not null column
* feat : add user test code that uses written method and relative user class
* chore : modify application
* feat : add between query in delete history repository
* feat : add select less than in delete history repository
* feat : select like and order by
* feat : add select like statement concerning email using jpql

2021-06-04 10:42 UTC, kingbbode requested changes
코멘트 작성해두었습니다 :)
확인 부탁드려요.

2021-06-04 10:42 UTC, kingbbode commented on src/main/java/qna/domain/Answer.java
> +	}
모든 필드의 `setter` 를 만들어둔 이유는 무엇인가요?

2021-06-04 10:42 UTC, kingbbode commented on src/test/java/qna/domain/AnswerTest.java
> +	public static final Answer A2 = new Answer(UserTest.SANJIGI, QuestionTest.Q1, "Answers Contents2");
JPA 를 사용할 때에는 객체의 영속 상태를 조심스럽게 다루어야 합니다. 이런 공유객체를 사용하면서 `DataJpaTest` 를 사용하게 되었을 때 발생하는 문제점이 많습니다 :)

전역으로 선언된 이 객체가 테스트가 진행되는 동안 언제 어떻게 영속 상태의 변화를 받는지 알아보시면 좋을 것 같습니다 :)

`DataJpaTest` 는 트랜잭션이 전역으로 포함된 테스트입니다.
객체의 영속 상태와, 언제 어떻게 쿼리가 발생하는지를 엮어서 공부해보신다면 질문주신 내용이 함께 해소될 것으로 보입니다.

---

모든 테스트는 상호 독립적으로 작성되어야 하는 것이 테스트의 필수 조건이기도 합니다. `A1`, `A2` 는 JPA 특성상 단순 객체를 넘어서 모든 테스트에 공유가 되고 있습니다.

각 테스트의 조건은 각 테스트 안에서만 동작하도록 변경 부탁드립니다 :)

2021-06-05 10:23 UTC, chae-yh commented on src/main/java/qna/domain/Answer.java
> +	}
jpa에서 update 구문은 각 클래스의 필드를 변경해줌으로써 가능하고, 모든 필드에서 udpate가 일어날 수 있다고 생각하여 모든 필드에 setter를 추가했습니다.

이 부분은 제가 jpa 에 대해 잘 못 이해하고 있어서 생길 수 있는 구조일 수도 있을 것 같습니다. 혹시 더 좋은 구조가 있을까요....?

2021-06-05 10:24 UTC, chae-yh commented on src/test/java/qna/domain/AnswerTest.java
> +	public static final Answer A2 = new Answer(UserTest.SANJIGI, QuestionTest.Q1, "Answers Contents2");
각 테스트에 대해 독립적으로 실행할 수 있도록 구조를 변경하였습니다. 기존에 발생하던 오류는 이제 발생하지 않는데, 제가 영속 상태와 쿼리 발생에 대한 부분을 정확히 이해하지 못한 것 같습니다. 관련해서 자세한 내용은 DM 드려 다시 한번 여쭤보겠습니다 : )

2021-06-05 10:25 UTC, chae-yh commented
문의 주신 부분 답변 및 수정 요청 부분 변경 완료하여 push 완료 하였습니다.
내용 확인 부탁드립니다.

감사합니다 : )

2021-06-05 17:23 UTC, kingbbode requested changes
코멘트 작성해두었습니다. 
확인 부탁드립니다 :)

2021-06-05 17:23 UTC, kingbbode commented on src/main/java/qna/domain/Answer.java
> +	}
이 내용은 다음 단계에서 추가로 확인하도록 하겠습니다 :)

(`Entity` 이건 일반 클래스이건 모두 객체라는 관점에서 질문을 드렸습니다.)

2021-06-05 17:23 UTC, kingbbode commented on src/test/java/qna/domain/AnswerTest.java
> +		A2 = new Answer(SANJIGI, Q1, "Answers Contents2");
테스트의 조건은 테스트 안에서 작성이 되어야합니다.
테스트의 `setup` 단계는 테스트를 위한 환경을 세팅하는 단계입니다.

이 테스트가 조건인지 환경인지가 구분이 어려울 수도 있는데요.
setup 에서 설치된 환경이 테스트 안에서 변경될 수 있다면 그것은 테스트의 조건일 가능성이 높습니다.

작성하신 setup의 내용은 테스트의 조건에 해당하는 것으로 보입니다 :)

2021-06-06 07:15 UTC, chae-yh commented on src/test/java/qna/domain/AnswerTest.java
> +		A2 = new Answer(SANJIGI, Q1, "Answers Contents2");
넵 해당 하는 부분 각 테스트 메소드로 이동 하여 적용하였습니다. 확인 감사합니다. : )

2021-06-06 07:17 UTC, chae-yh commented on src/main/java/qna/domain/Answer.java
> +	}
혹시 말씀주신 부분은, 객체는 기본적으로 불변 객체(setter를 가능한 사용하지 않아 객체 내 데이터의 변경을 막아야함)를 지향해야 한다는 의미에서 말씀주신 것인지 여쭤봐도 될까요...?
setter 를 쓰지 않고 jpa 내에서 업데이트 하는 방법에 대해 조금 더 보도록 하겠습니다 : )

2021-06-06 07:19 UTC, chae-yh commented
새벽에 바로 확인하고 pr 드릴 걸 조금 늦었네요...ㅠ 
말씀 주신 내용 반영하여 다시 pr 드렸습니다. 확인 부탁드립니다.

2021-06-06 13:31 UTC, kingbbode approved these changes
잘 반영해주셨네요 :)
이만 머지하겠습니다.

2021-06-06 13:31 UTC, merged