Add Step1 : JPA entity mapping
next-step/jwp-qna pull request #123
Opened 2021-06-04 06:34 UTC by junhee-ko

"JPA : 1단계 - 엔티티 매핑" 구현입니다.

2021-06-04 07:20 UTC, neojjc2 commented
#tag @neojjc2

2021-06-04 07:31 UTC, neojjc2 requested changes
안녕하세요 준희님 🙇 
이번 JPA 미션 리뷰를 맡게된 정준철 이라고 합니다 😄 
만나서 정말 반갑습니다 🙇 

1단계 구현 잘 해주셨습니다 💯 
다만 공통적으로 사용되고 있는 부분에 대한 개선 및 
테스트 코드 작성이 누락되어 있어서 
이 부분 추가되면 좋을 것 같아서 `Request changes` 하도록 하겠습니다 😄 

확인 해주시면 감사하겠습니다 🙇  

그럼 미션 마지막 까지 잘 부탁 드리겠습니다 🙇

2021-06-04 07:31 UTC, neojjc2 commented on src/main/java/qna/domain/Answer.java
> +    private LocalDateTime createdAt;
이 부분은 계속 중복이 되고 있는 부분입니다 😄 
`MappedSuperclass`를 통해서 추출되면 더 좋을 것 같습니다 😄 

이 부분 한번 정리하고 가시면 좋을 것 같습니다 🙇 
> https://ict-nroo.tistory.com/129

2021-06-04 07:31 UTC, neojjc2 commented on src/main/java/qna/domain/Question.java
> +    private LocalDateTime createdAt;
위에서 의견 드렸지만 중복되는 부분이므로 같이 공통 객체로 추출되면 좋을 것 같습니다 😄

2021-06-04 07:31 UTC, neojjc2 commented on src/test/java/qna/domain/AnswerRepositoryTest.java
> +  void name() {
아직 테스트 작성이 안되신 것 같습니다 😄 
이 부분도 추가작성 부탁 드리겠습니다 🙇

2021-06-07 05:48 UTC, junhee-ko commented on src/main/java/qna/domain/Answer.java
> +    private LocalDateTime createdAt;
done : f518ba01daba8a7effff997baa4dff7876252d49

2021-06-07 05:48 UTC, junhee-ko commented on src/test/java/qna/domain/AnswerRepositoryTest.java
> +  void name() {
done : a4b54d7f0a45df5fae4920a9402bfb578e3762ac

2021-06-07 23:49 UTC, neojjc2 approved these changes
안녕하세요 준희님 🙇 

수정 요청 사항 잘 반영해주셨네요 💯 👍 

다음단계 진행부탁 드립니다 😄 🙇

2021-06-07 23:49 UTC, neojjc2 commented on src/test/java/qna/domain/AnswerRepositoryTest.java
> +  void save() {
`@DisplayName`도 챙겨주시면 더 좋을 것 같습니다 😄

2021-06-07 23:49 UTC, merged