Step3 - QnA 서비스 리팩터링 리뷰요청드립니다.
next-step/jwp-qna pull request #127
Opened 2021-06-04 17:33 UTC by yzzzzun

안녕하세요 리뷰어님 QnA서비스 리팩터링 리뷰요청 드립니다

createDate equal정의 때문에 테스트에서 한참 막혀있다가 이제야 리뷰요청을 드리네요..
많은 지적 부탁드립니다 :)

2021-06-05 07:04 UTC, tearight requested changes
요구사항은 만족하셨지만 테스트를 위한 코드가 다수 들어가 있네요.
이번 단계에서는 테스트를 위한 코드를 제거하는 것을 목표로 해보시는건 어떨까요 ?
그 이외에도 코멘트를 드렸으니 확인 부탁드립니다.

2021-06-05 07:04 UTC, tearight commented on src/main/java/qna/domain/Answer.java
> +	public Answer(Long id, User writer, Question question, String contents) {
테스트를 위해서 존재하는 생성자 같은데요, 아마 ID 에 대한 테스트 때문인 걸로 보입니다.
테스트를 위한 메소드는 제품 구현할 때 실수로라도 사용할 수 있는 여지가 있기 때문에 최대한 지양하는게 좋은데요,
이때는 mockito 를 활용해서 getId() 를 stubbing 하는 것이 어떨까요 ?
https://bestalign.github.io/2016/07/08/intro-mockito-1/

2021-06-05 07:04 UTC, tearight commented on src/main/java/qna/domain/Answer.java
> +			this.question.getAnswers().removeAnswer(this);
명확한 메소드명이네요. 👍

2021-06-05 07:04 UTC, tearight commented on src/main/java/qna/domain/Answer.java
> +		return new DeleteHistory(ContentType.ANSWER, this.id, this.writer, LocalDateTime.now());
LocalDateTime 을 주입받는 건 어떨까요 ?
실무에서는 서버의 시간 뿐만 아니라 API 요청 시간을 넣어야 할 때도 있고, TDD 에서도 시간에 대한 값은 검증하기 어려워 보이네요.

2021-06-05 07:04 UTC, tearight commented on src/main/java/qna/domain/DeleteHistory.java
> -	public String toString() {
Entity 코드를 작성할 때에 toString 은 왠만하면 구현해주시는게 좋아요.
가장 큰 이유는 나중에 로그를 통해서 entity 의 값을 확인할 수 있기 때문에 쉽게 버그를 찾을 수 있다는 점인 것 같네요.

2021-06-05 07:04 UTC, tearight commented on src/main/java/qna/domain/Question.java
> +	public Answers getAnswers() {
테스트 코드를 위한 코드 인 것 같은데 Question.isAnswerContains() 로 외부 노출을 피할 수 있지 않을까요 ?

2021-06-05 07:04 UTC, tearight commented on src/main/java/qna/domain/Answers.java
> +public class Answers {
제가 지난번 리뷰에서 빠트린 것 같은데
모든 entity 와 embeddable 객체는 파라메터가 없는 빈 생성자를 명시해주는 것이 좋아요.
대신 protected 로 바깥에 공개하지 않아야겠군요.

2021-06-05 07:04 UTC, tearight commented on src/main/java/qna/domain/Question.java
> +	public void toWriter(User user) {
toWriter 또한 테스트를 위한 메소드 인 것 같네요.
mocking 등의 방법을 통해서 줄이는 것이 좋아보입니다.

2021-06-05 07:04 UTC, tearight commented on src/main/java/qna/domain/Question.java
> +		this.setDeleted(true);
파라메터가 true 로 들어가는 케이스만 있네요.
question.delete() 로 실행하게 하는건 어떨까요?
entity 는 setter 를 최대한 지양하고 도메인 언어로 행위를 표현할 수 있어야 합니다.

2021-06-05 07:04 UTC, tearight commented on src/main/java/qna/domain/Question.java
> +			LocalDateTime.now());
여기도 LocalDateTime 을 주입받을 필요가 있어보이네요.

2021-06-05 08:15 UTC, yzzzzun commented on src/main/java/qna/domain/Answer.java
> +	public Answer(Long id, User writer, Question question, String contents) {
테스트가 지속적으로 실패해서 ID 문제인가 싶어서 추가했었는데 다시 제거하도록 하겠습니다.
id가 필요한 상황이라면 stubbing하는 방식이 좋은 방법이겠네요.. 올려주신글 잘읽었습니다. :)

2021-06-05 08:17 UTC, yzzzzun commented on src/main/java/qna/domain/Question.java
> +	public Answers getAnswers() {
getter를 제거하도록 하겠습니다.

2021-06-05 08:18 UTC, yzzzzun commented on src/main/java/qna/domain/Answers.java
> +public class Answers {
생성자 추가하겠습니다.

2021-06-05 08:59 UTC, yzzzzun commented on src/main/java/qna/domain/DeleteHistory.java
> -	public String toString() {
테스트 오류에서 toString이 있으니까 파악하기 좋은것 같습니다.

엔티티의 경우 서로 참조하는경우가 있는데 그런경우 ID를 출력해주는게 좋을까요?? 무한루프에 빠질수있겠다는 생각이들어서요..

2021-06-05 10:20 UTC, yzzzzun commented on src/main/java/qna/domain/Question.java
> +	public void toWriter(User user) {
연관관계 편의메서드를 정의하려고 한건데 writeBy에 로직을 정의하는걸로 수정했습니다.

2021-06-05 12:11 UTC, yzzzzun commented on src/main/java/qna/domain/Question.java
> +		this.setDeleted(true);
deleted를 일급객체로 분리하여 Answer, Question에서 값타입으로 사용하도록 개선했습니다.

2021-06-05 15:44 UTC, yzzzzun commented on src/main/java/qna/domain/Question.java
> +			LocalDateTime.now());
delete메서드를 통해 DateTime을 주입받도록 개선했습니다.

2021-06-05 15:46 UTC, yzzzzun commented on src/main/java/qna/domain/Answer.java
> +		return new DeleteHistory(ContentType.ANSWER, this.id, this.writer, LocalDateTime.now());
제가 리뷰어님의 의견을 제대로 이해한건지 모르겠네요..
delete메서드를 통해 DateTime을 주입받도록 개선했습니다. service layer에서 LocalDateTime을 입력받음으로써 테스트가 가능해지고 시간에 대한 설정을 좀더 확장성 있게 가져갈 수 있다는 말씀이신걸로 이해하면 될까요?

2021-06-06 07:33 UTC, tearight commented on src/main/java/qna/domain/User.java
> +		question.writeBy(this);
훨씬 자연스러워졌네요 👍

2021-06-06 07:39 UTC, tearight commented on src/main/java/qna/domain/Answer.java
> +		return new DeleteHistory(ContentType.ANSWER, this.id, this.writer, LocalDateTime.now());
네 맞습니다. 시간의 확장성에 대한 필요는 프로젝트 초기에는 인지하기 어렵지만, 서비스를 운영하면서 필요로 하게 됩니다.
가장 대표적인 케이스는 특정 버그를 찾기 위해 로그 및 DB 레코드를 통해서 API 가 호출/데이터가 생성된 시간을 순차적으로 비교해보는 케이스입니다. 조금 귀찮을 수 있어도 나중에 버그를 찾는 시간을 줄여준다는 점에서 고려하면 좋을듯 합니다.

2021-06-06 07:41 UTC, tearight approved these changes
피드백 잘 반영해주셨네요. 👍
이만 qna 미션을 마무리하도록 하겠습니다.
다음 미션도 화이팅입니다!

2021-06-06 07:41 UTC, merged