Step1 - 엔티티 매핑
next-step/jwp-qna pull request #13
Opened 2021-05-26 08:33 UTC by bbbnam

안녕하세요 리뷰어님-!!

JPA 예전에 공부하긴 했었는데
실무에서 사용하지 않다보니
다 까먹어서 다시 김영한님 강의 듣고 시작해보았네요 ㅠ

제대로 한건지 모르겠습니다;

가감없이 팍팍 지적 부탁드립니다.

p.s 테스트 코드 작성시 도메인 객체들의 public 메소드들 전체 다 테스트 코드를 작성했어야 했을까요...?
일단 엔티티 매핑을 중점으로 진행하긴 했습니다만...😥

2021-05-26 12:01 UTC, young891221 requested changes
안녕하세요, 자룡님!
강의까지 들으시면서 미션 구현하시다니ㅎㅎ 훌륭하시네요 👍 
테스트 관련하여 몇 가지 코멘트 남겼습니다. 확인 부탁드려요~!

2021-05-26 12:01 UTC, young891221 commented on src/main/java/qna/domain/Question.java
> +public class Question extends BaseEntity{
띄어쓰기 컨벤션 부탁드려요!

2021-05-26 12:01 UTC, young891221 commented on src/main/resources/application.properties
> +spring.jpa.hibernate.ddl-auto=create-drop
연습 프로젝트라서 문제 없지만 실무에서는 위험한 셋팅이네요ㅎ

2021-05-26 12:01 UTC, young891221 commented on src/test/java/qna/domain/AnswerRepositoryTest.java
> +        answerRepository.deleteAll();
@DataJpaTest 어노테이션 자체가 테스트가 끝나고 자동 롤백처리가 되기 때문에 후처리는 필요 없을것 같습니다 ㅎ

2021-05-26 12:01 UTC, young891221 commented on src/test/java/qna/domain/AnswerRepositoryTest.java
> +        saved.setContents("내용 바꿔보기");
"내용 바꿔보기" 중복되니 변수로 빼서 활용하는게 좋을것 같습니다

2021-05-26 12:01 UTC, young891221 commented on src/test/java/qna/domain/AnswerRepositoryTest.java
> +        assertThat(answers).isEmpty();
saved를 contains하고 있는데 테스트하는게 명확해 보입니다ㅎ

2021-05-26 12:01 UTC, young891221 commented on src/test/java/qna/domain/AnswerRepositoryTest.java
> +        assertThat(answers).isEmpty();
테스트마다 코멘트 드린 내용이 중복되는데 모두 변경해 주세요!ㅎ

2021-05-26 14:08 UTC, bbbnam commented on src/test/java/qna/domain/AnswerRepositoryTest.java
> +        answerRepository.deleteAll();
메신져에서 확인해주신 이후로 
혹시나 다른 방법이 있을까 더 찾아보았지만, 
일단 
`@AutoConfigureTestDatabase(replace = Replace.NONE)`
이 속성을 이용해서 실제 DB를 사용하는 이상 auto-increment 때문에 id값이 증가하여
save - update로 이어지는 테스트에서는 테스트 격리가 제대로 이루어지지 않는 것 같습니다. (제가 찾은 한도내에서는요😭)

애초에 설계를 바꿨어야 하는 문제일까요? 
(실제 DB테스트가 아니라 mock객체 등으로 테스트 하자니...@DataJpaTest 테스트 요지에서 벗어나는 것 같고, [DataJpaTest 테스트는 JPA를 통해 데이터 베이스에 값이 저장, 수정 등이 정상적으로 되는지 테스트 하는 것이라고 알고 있습니다..😖])

혹시 제가 잘못 알고 있거나 다른 방법이 있다면,
방향성이나 조언 부탁드립니다ㄷㄷ;

2021-05-26 14:28 UTC, bbbnam commented on src/main/resources/application.properties
> +spring.jpa.hibernate.ddl-auto=create-drop
앗 넵 ㅎ 
어플리케이션 실행시켜서 DDL 맞는지 확인해보려고 해놓은 옵션이었습니다 ㄷㄷ
수정하겠습니다 😅

2021-05-26 14:28 UTC, bbbnam commented on src/test/java/qna/domain/AnswerRepositoryTest.java
> +        assertThat(answers).isEmpty();
넵-! ㅎㅎ 리뷰 감사합니다

2021-05-26 15:29 UTC, bbbnam commented
안녕하세요 리뷰어님-!
빠른 답변을 기대하고 메시지 드린건 아니었는데,
죄송하게도... 늦은 시간이었는데, 답변해주셔서 너무 감사드립니다.

말씀해주신 피드백대로 리팩토링 진행해보았습니다.

p.s
https://github.com/next-step/jwp-qna/pull/13#discussion_r639763017
이부분만 조금 확인해주셨으면 합니다 

감사합니다-!!😆

2021-05-27 01:46 UTC, young891221 commented on src/test/java/qna/domain/AnswerRepositoryTest.java
> +        answerRepository.deleteAll();
@AfterEach에서 매번 테스트 데이터를 일괄적으로 비워주고 시작하는데 실제로는 어떤 데이터가 들어있는지 모르는 상황에서 테스트 코드가 작성되는게 적절해 보입니다. 생성했다면 쭉 나열된 데이터 중에 내가 원하는 데이터가 진짜 있는지, 업데이트 했다면 정말 내가 원하는 데이터만 업데이트 되었는지 등으로 테스트해야 실제로 쓰이는 형태로 보입니다 ㅎ

2021-05-27 01:47 UTC, young891221 approved these changes
코멘트 반영 감사합니다 :)
질문 주신 부분에 대해 답변드렸는데 다음 단계 진행시 이 부분도 고려하여 테스트 작성 부탁드립니다ㅎ
머지할게요!

2021-05-27 01:48 UTC, merged

2021-05-27 01:52 UTC, bbbnam commented on src/test/java/qna/domain/AnswerRepositoryTest.java
> +        answerRepository.deleteAll();
저도 이부분 계속 걸려서 다른분이 pr한 것도 보고, 지금 써주신 이글 보니까 
뭔가 감이 오는것 같습니다😳

인사이트가 온거 같은데
일단 다음 단계에서 해보겠습니다.
또 채찍질 부탁드립니다 ㅋ😁

답변해주셔서 감사합니다-!!