🚀 3단계 - 질문 삭제하기 리팩터링
next-step/jwp-qna pull request #140
Opened 2021-06-06 10:31 UTC by mskangg

안녕하세요 현구님!
3단계 미션 제출합니당
머지하기 전에 다음 단계를 진행중에 있어서 이번엔 비교적 빠르게 PR을 보냅니당 :)

이번에는 궁금했던 사항 한가지만 질문드리겠습니다. 😀
1. 모든 원시 값과 문자열을 포장한다 라는 요구사항에 맞게 Entity의 원시값들을 포장하였습니다. 허나 현재 비즈니스상 Contents의 역할이 보이지 않아 원시값을 포장하는 것에 이점이 없어보입니다.. 
이럴 경우에는 추가적인 비즈니스가 나올때를 대비하여 미리 원시값을 포장하곤하나요??

피드백 부탁드립니다.
감사합니다. :)

2021-06-08 01:58 UTC, kang-hyungu commented
> 안녕하세요 현구님!
> 3단계 미션 제출합니당
> 머지하기 전에 다음 단계를 진행중에 있어서 이번엔 비교적 빠르게 PR을 보냅니당 :)
> 
> 이번에는 궁금했던 사항 한가지만 질문드리겠습니다. 😀
> 
>     1. 모든 원시 값과 문자열을 포장한다 라는 요구사항에 맞게 Entity의 원시값들을 포장하였습니다. 허나 현재 비즈니스상 Contents의 역할이 보이지 않아 원시값을 포장하는 것에 이점이 없어보입니다..
>        이럴 경우에는 추가적인 비즈니스가 나올때를 대비하여 미리 원시값을 포장하곤하나요??
> 
> 
> 피드백 부탁드립니다.
> 감사합니다. :)

A.
객체로 만들 필요가 없다면 당연히 미리 기본타입을 유지합니다.
하지만 Contents는 객체로 만들면 이점이 있습니다.
피드백으로 남겨둘게요

2021-06-08 02:17 UTC, kang-hyungu requested changes
민수님 리뷰가 늦었네요. 죄송합니다.
3단계 미션도 구현 잘해주셨네요
질문 주신 내용에 코멘트 남겼으니 참고하세요
몇 가지 남긴 피드백 적용해보시고 리뷰 재요청주세요

2021-06-08 02:17 UTC, kang-hyungu commented on src/main/java/qna/domain/Answer.java
> +    private Deleted deleted;
Deleted는 객체로 만들 필요 없습니다.
다시 boolean으로 원복하는게 좋겠네요.

2021-06-08 02:17 UTC, kang-hyungu commented on src/main/java/qna/domain/Answer.java
> +    public Deleted isDeleted() {
```suggestion
    public boolean isDeleted() {
```
관례적으로 is를 붙이면 반환타입은 boolean을 사용합니다.

2021-06-08 02:17 UTC, kang-hyungu commented on src/main/java/qna/domain/Answer.java
> +        return DeleteHistory.ofAnswer(id, writer, LocalDateTime.now());
오 정적 팩토리 메서드 추가 좋네요
객체 생성일자도 클라이언트가 임의로 정하게 만드는 것보다 객체 내부에서 만들어주는게 어떨까요

2021-06-08 02:17 UTC, kang-hyungu commented on src/main/java/qna/domain/Answers.java
> +    public DeleteHistories deleteAll(User loginUser) {
```java
    public DeleteHistories deleteAll(User loginUser) {
        return answers.stream()
                .map(answer -> answer.delete(loginUser))
                .collect(Collectors.collectingAndThen(Collectors.toList(), DeleteHistories::new));
    }
```
stream을 활용해보면 어떨까요

2021-06-08 02:17 UTC, kang-hyungu commented on src/main/java/qna/domain/Contents.java
> +    public Contents(String contents) { //TODO: 컨텐츠의 역할이 흐릿함.. 비즈니스가 추가된 후에 검증로직 추가해야 할듯
contents는 null 또는 빈문자열을 허용하나요?

이외에도 실무에서 고려해야될 포인트가 있는데 현재 미션에서는 null, 빈문자열 여부만 체크해도 충분해보이네요
- 만약에 어떤 사용자가 악의적인 자바스크립트를 작성하게 허용한다면 다른 사용자들의 컴퓨터에 문제를 일으킬 수도 있겠네요.
- html 태그도 허용할까요?
- 이모지도 허용되나요?

2021-06-08 02:17 UTC, kang-hyungu commented on src/main/java/qna/domain/DeleteHistory.java
> +    public static DeleteHistory ofQuestion(Long contentId, User deletedBy, LocalDateTime createDate) {
정적 팩토리 메서드를 사용하신다면 생성자는 사용 못하게 막는게 좋겠네요
그래야 의도한 값을 가진 객체만 만들도록 강제할 수 있으니깐요

2021-06-08 02:17 UTC, kang-hyungu commented on src/test/java/qna/domain/AnswerTest.java
>  }
생성자에 있는 예외 처리도 잘 동작하는지 테스트로 검증해보아요

2021-06-08 02:17 UTC, kang-hyungu commented on src/test/java/qna/domain/EmailTest.java
> +    @DisplayName("기본적인 이메일 형식을 가져야 하며 최대 50자리가 넘지 않아야 한다.")
기본적인 이메일 형식이 뭘까요?
구체적으로 어떤 포멧인지 테스트 코드로 작성해보는게 좋겠네요.

50자리가 넘지 않아야 된다는 내용은 validateEmailLengthException 테스트에 추가해주는게 좋겠네요
이 테스트와는 관련 없는 내용입니다.

2021-06-08 02:17 UTC, kang-hyungu commented on src/test/java/qna/domain/NameTest.java
> +    @DisplayName("이름은 영문, 한글, 숫자 조합으로 최대 20자리가 넘지 않아야 한다.")
허용하지 않는 케이스는 예외가 발생하는지 확인하는 테스트들을 추가해보는게 좋겠네요

2021-06-08 02:17 UTC, kang-hyungu commented on src/test/java/qna/domain/PasswordTest.java
> +    @DisplayName("비밀번호는 영문(대소문자 구분) + 숫자 + 특수문자 조합으로 9~20 자리여야한다.")
비밀번호도 마찬가지입니다.
예외가 발생하는 케이스도 테스트해보아요

2021-06-08 02:20 UTC, kang-hyungu commented
> > 안녕하세요 현구님!
> > 3단계 미션 제출합니당
> > 머지하기 전에 다음 단계를 진행중에 있어서 이번엔 비교적 빠르게 PR을 보냅니당 :)
> > 이번에는 궁금했던 사항 한가지만 질문드리겠습니다. 😀
> > ```
> > 1. 모든 원시 값과 문자열을 포장한다 라는 요구사항에 맞게 Entity의 원시값들을 포장하였습니다. 허나 현재 비즈니스상 Contents의 역할이 보이지 않아 원시값을 포장하는 것에 이점이 없어보입니다..
> >    이럴 경우에는 추가적인 비즈니스가 나올때를 대비하여 미리 원시값을 포장하곤하나요??
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 피드백 부탁드립니다.
> > 감사합니다. :)
> 
> A.
> 객체로 만들 필요가 없다면 당연히 미리 기본타입을 유지합니다.
> 하지만 Contents는 객체로 만들면 이점이 있습니다.
> 피드백으로 남겨둘게요

리뷰 남기고 보니 전부 다 객체로 포장하셨군요;;
만들어 보셔서 아시겠지만 객체로 만드는게 항상 장점만 있는 건 아닙니다.
지금처럼 거의다 객체로 만들경우 어떤 점이 좋았고 어떤 점이 개발하는데 불편했을까요?
실무에서 어느 선까지 객체로 만드는게 좋을지 고민해보는 것도 좋을 것 같네요

2021-06-08 02:32 UTC, mskangg commented on src/main/java/qna/domain/Answer.java
> +    private Deleted deleted;
만들면서도 음... 했었는데 시원하게 답변해주시고 감사합니다~ 😀

2021-06-08 02:33 UTC, mskangg commented on src/main/java/qna/domain/Answer.java
> +    public Deleted isDeleted() {
반영하였습니다. 😀

2021-06-08 02:39 UTC, mskangg commented on src/main/java/qna/domain/Answer.java
> +        return DeleteHistory.ofAnswer(id, writer, LocalDateTime.now());
오 역시! 한결 깔끔해졌네요 👍 
감사합니다 :)

2021-06-08 02:42 UTC, mskangg commented on src/main/java/qna/domain/Answers.java
> +    public DeleteHistories deleteAll(User loginUser) {
오.. Collectors.collectingAndThen() 이 구문 꿀팁이네요!
감사합니다 👍

2021-06-08 02:58 UTC, mskangg commented on src/main/java/qna/domain/Contents.java
> +    public Contents(String contents) { //TODO: 컨텐츠의 역할이 흐릿함.. 비즈니스가 추가된 후에 검증로직 추가해야 할듯
음.. 생각보다 다양한 요구사항이 추가될 수 있을 것 같네요!
null 빈문자열 체크 검증 추가했습니다.
감사합니다 👍

2021-06-08 03:00 UTC, mskangg commented on src/main/java/qna/domain/DeleteHistory.java
> +    public static DeleteHistory ofQuestion(Long contentId, User deletedBy, LocalDateTime createDate) {
접근제한을 하니 정적팩터리 적용하기전에 사용됐던 생성자 코드가 남아있는 것을 발견했네요.. 😥
강제하는 것은 굉장히 중요하다는 것을 깨닫게 됐네요 ㅎㅎ
피드백 감사합니다. 👍

2021-06-08 03:06 UTC, mskangg commented on src/test/java/qna/domain/AnswerTest.java
>  }
앗..! 테스트 코드 추가했습니다. 😀

2021-06-08 03:10 UTC, mskangg commented on src/test/java/qna/domain/EmailTest.java
> +    @DisplayName("기본적인 이메일 형식을 가져야 하며 최대 50자리가 넘지 않아야 한다.")
기본적인 이메일 형식 영문,숫자 @ 도메인 주소라고 생각했습니다.
정확하게 설명해주는 것이 바람직해 보이네요!
감사합니다. 😀

2021-06-08 03:17 UTC, mskangg commented on src/test/java/qna/domain/NameTest.java
> +    @DisplayName("이름은 영문, 한글, 숫자 조합으로 최대 20자리가 넘지 않아야 한다.")
이 테스트코드 밑에 validateNameTypeException() 과 validateNameLengthException() 의 테스트 코드가 있습니다!
추가설명이 부족해보여 @DisplayName으로 달아놨습니다.
감사합니다. 😀

2021-06-08 03:39 UTC, mskangg commented on src/test/java/qna/domain/PasswordTest.java
> +    @DisplayName("비밀번호는 영문(대소문자 구분) + 숫자 + 특수문자 조합으로 9~20 자리여야한다.")
Name 과 마찬가지로 밑에 테스트 코드 작성이 되어있습니다!
@DisplayName으로 추가설명되어있지 않다보니 알아보기 힘든 부분이 있는 것 같아 추가하였습니다.
이름 길이 예외 메세지도 추가하였습니다.
감사합니다. 😀

2021-06-08 03:49 UTC, mskangg commented
> > > 안녕하세요 현구님!
> > > 3단계 미션 제출합니당
> > > 머지하기 전에 다음 단계를 진행중에 있어서 이번엔 비교적 빠르게 PR을 보냅니당 :)
> > > 이번에는 궁금했던 사항 한가지만 질문드리겠습니다. 😀
> > > ```
> > > 1. 모든 원시 값과 문자열을 포장한다 라는 요구사항에 맞게 Entity의 원시값들을 포장하였습니다. 허나 현재 비즈니스상 Contents의 역할이 보이지 않아 원시값을 포장하는 것에 이점이 없어보입니다..
> > >    이럴 경우에는 추가적인 비즈니스가 나올때를 대비하여 미리 원시값을 포장하곤하나요??
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 피드백 부탁드립니다.
> > > 감사합니다. :)
> > 
> > 
> > A.
> > 객체로 만들 필요가 없다면 당연히 미리 기본타입을 유지합니다.
> > 하지만 Contents는 객체로 만들면 이점이 있습니다.
> > 피드백으로 남겨둘게요
> 
> 리뷰 남기고 보니 전부 다 객체로 포장하셨군요;;
> 만들어 보셔서 아시겠지만 객체로 만드는게 항상 장점만 있는 건 아닙니다.
> 지금처럼 거의다 객체로 만들경우 어떤 점이 좋았고 어떤 점이 개발하는데 불편했을까요?
> 실무에서 어느 선까지 객체로 만드는게 좋을지 고민해보는 것도 좋을 것 같네요

프로그래밍 요구사항에 `모든 원시 값과 문자열을 포장한다` 라는 것이 조건이어서 다 포장하였습니다.. ㅎㅎ
이번 테크캠프 과정상 극한의 상황까지 하는 것이 목표라고 말씀하셨어서 진행하였어요! 🧐
진행하면서 불필요하다고 느낀 것은 `Deleted`라는 원시값 객체였습니다.
현재 `Deleted`라는 객체는 검증할 부분이 `true`, `false`, `null` 체크 정도인데 이 부분은 `boolean` 이란 값객체를 써도 충분히 대체가능하기 때문에 장점이 없어보였습니다.
오히려 객체 추가로 인해 코드가 복잡해보이는 단점만 있는 것 같았습니다. 😥
무조건적인 원시값래핑은 오히려 오버엔지니어링이 된다는 것을 몸소 체험했네요 ㅎㅎ
다른 원시값들은 비즈니스적으로 요구사항이 추가된다면 검증로직이 꽤나 복잡하게 진화할 수 있을 것 같아 원시값포장에 대한 이점이 많아보였습니다.
많이 배우게된 미션이었습니다. 🧐
코멘트 감사합니다! 💯

2021-06-09 01:08 UTC, kang-hyungu approved these changes
민수님 피드백 반영 잘 해주셨어요 👍 
pr은 머지 처리하겠습니다. 수고하셨습니다!

2021-06-09 01:08 UTC, merged