step2 연관관계 리뷰
next-step/jwp-qna pull request #152
Opened 2021-06-08 17:23 UTC by yevgnenll

연관관계 리뷰 요청 드립니다

`@ForeignKey` 는 처음 써봤어요 ㅎㅎ

변경이 전역적으로 일어나서 commit 을 원자적으로 나누질 못했습니다 ㅠㅠ..

2021-06-10 09:05 UTC, kingbbode requested changes
코멘트 작성해두었습니다 :)
확인 부탁드려요.

2021-06-10 09:05 UTC, kingbbode commented on src/main/java/qna/domain/Answer.java
>      public void toQuestion(Question question) {
JPA 는 객체 관점과 데이터베이스 관점에서 오는 사상의 불일치를 제거해주는 기술입니다.
구현을 하시면서 정말 사상의 불일치를 해소하셨는지 확인해보시면 좋을 것 같네요.
데이터베이스 관점에서는 Answer 가 연관관계의 주인인 반면, 객체 입장에서는 Answer 는 Question 의 하부에 종속되는 콜렉션입니다. Question 에서 Answer 를 콜렉션으로 다루지 못하는 의존관계는 사상의 불일치를 해소해주지 못하고 있는 것 같네요 :)

그렇다면 단방향 OneToMany를 고려해볼 수 있는데요. 객체의 의존관계 입장에서는 단방향으로 관계를 맺는게 좋습니다. JPA도 이를 지원하구요 :) 그렇지만, 이 부분에 대해서는 성능에 대한 트레이드오프를 해야합니다. 단방향일 때와 양방향일 때 추가,제거,조회 에서 각각 쿼리가 어떻게 동작하시는지 비교해보시고, 의견을 남겨주시면 좋겠네요 :)

2021-06-10 09:05 UTC, kingbbode commented on src/main/java/qna/domain/Answer.java
> +    public void setQuestion(Question question) {
각 종 `getter` 와 `setter` 는 필요에 의해 개방되었을까요?

우리는 객체의 상태를 보호해야 합니다.
setter 는 변경을 외부에 공개함으로서, 외부 어디에서라도 객체의 상태를 변경할 수 있도록 합니다. Entity 는 이런 상태의 변경으로부터 더욱 민감한 객체입니다. setter 는 사용하지 않는 것을 권장합니다.

2021-06-10 09:05 UTC, kingbbode commented on src/main/java/qna/domain/Question.java
>      public void addAnswer(Answer answer) {
필드로 가지고 있는 `answers` 에는 `answer`가 추가되지 않았고, `answer` 은 `question` 을 가지고 있네요 :)
데이터베이스 중심적인 관계 작성임과 동시에, 데이터베이스 기준 상태와 객체의 상태가 불일치하는 문제점이 있습니다.

2021-06-10 09:05 UTC, kingbbode commented on src/main/java/qna/service/QnAService.java
>              answer.setDeleted(true);
의미있는 행위를 객체에게 명령하려면, `setDeleted(true)` 보다는 `delete()` 라고 명령할 수 있지 않을까요?

2021-06-10 15:01 UTC, yevgnenll commented on src/main/java/qna/service/QnAService.java
>              answer.setDeleted(true);
일단 가장 빠르게 변경할 수 있는 부분이라 얼른 반영했습니다 ㅎㅎ

2021-06-10 15:07 UTC, yevgnenll commented on src/main/java/qna/domain/Answer.java
> +    public void setQuestion(Question question) {
필요에 의해 개방되지 않았습니다.
저는 사실 `setter` 를 철저하게 지양하는 편입니다.
생성되어 있는 코드를 꼼꼼하게 읽지 않은게 가장 큰 문제네요... ㅠㅠ

2021-06-10 15:28 UTC, yevgnenll commented on src/main/java/qna/domain/Answer.java
>      public void toQuestion(Question question) {
개인적으로 단방향을 더 추구합니다.

가장 직관적인 이유는 개발과 관리가 편하다는 점이고 그렇게 되는 이유는 의도하지 않은 쿼리가 동작하기 때문입니다.
-> 연관관계 주인이 누구인가(단방향이라면 1 -> N 인가, N -> 1 인가)
예를들면, 연관관계 주인에서 추가, 제거, 조회를 일으키는데 1 -> N 에서 1을 주인으로 했을 때 1을 수정했는데 N까지 수정하게 되는것과 같이 의도하지 않는 쿼리가 동작하기 때문입니다. (생각만 해도... ㅎㄷㄷ)

그래서 구현상 어쩔 수 없이 양방향을 구현해야 한다면 언제 쿼리의 실행을 의도적으로 끊을 것인가
그것을 어떻게 제어해야 할까에 대해 많이 고민해왔습니다. 이것을 제어하지 않는다면 객체의 그래프 탐색에 의해
객체의 참조를 타고 타고 타고 들어가서 신입때 상당히 당황했던 기억이 있습니다

말씀하신대로 단반향이 좋으며, 최종적으로는 `@ManyToOne` 으로 가는것이 맞겠습니다 :D

하지만, 현재와 같이 양방향으로 구성해본 것은 collection 을 객체지향적으로 다루는 강의 내용을 듣고 따라해보고 싶다는 생각이 들었는데 역시 잘 되지 않았네요... ㅠㅠ

2021-06-10 15:36 UTC, yevgnenll commented on src/main/java/qna/domain/Answer.java
>      public void toQuestion(Question question) {
```java
 public void toQuestion(Question question) {
        if (Objects.isNull(question) || Objects.isNull(question.getId()) || question.equals(this.question)) {
            return;
        }

        this.question = question;
        this.question.addAnswer(this);
    }
```

이렇게 수정해보았는데 어떨까요??

2021-06-10 17:21 UTC, kingbbode requested changes
추가 의견을 남겨두었습니다 :)
확인 부탁드립니다.

2021-06-10 17:21 UTC, kingbbode commented on src/main/java/qna/domain/Answer.java
>      public void toQuestion(Question question) {
`@ManyToOne` 으로 가는 이유를 잘 이해를 하지 못했습니다.

앞서 말씀드렸듯 JPA 는 사상의 불일치를 해소하기 위한 기술입니다. 답변주신 내용은 연관관계의 주인이라는 데이터베이스 기준으로 말씀주셔서, 계속하여 데이터베이스 중심적인 사고를 하게 된다면 JPA 를 사용하는게 의미가 없어보입니다.

질의와 응답은 현실세계의 개념으로도 명확하게 질의에 응답이 포함되는 관계입니다. 현실세계의 문제를 해결하기 위한 코드를 작성하면서 우리는 현실세계와 닮은 객체를 작성하게 됩니다. 하지만 JPA를 사용하면서도 결국 데이터베이스 관점으로 돌아온다는 것은 무언가 잘못된 것 같네요 :)

---

`연관관계 주인에서 추가, 제거, 조회를 일으키는데 1 -> N 에서 1을 주인으로 했을 때 1을 수정했는데 N까지 수정하게 되는것과 같이 의도하지 않는 쿼리가 동작` 이라는 의견에도 공감하기가 어렵습니다.

사상이 불일치하는 관계를 다루는 상황에서 객체 관점의 관계를 잘 옮겼다면 말씀하신 수정이 일어날 수 없도록 철저하게 캡슐화하고, 코드로서 관리되어야 합니다.  의도하지 않은 쿼리가 발생했다면, 그것은 트랜잭션의 단위나 영속성의 단위를 잘못 사용하고 있을 가능성이 큽니다. `ManyToOne` 이 올바른 객체의 관계가 있기도 하며, `OneToMany` 가 올바른 객체의 관계가 존재하기도 합니다. 이 부분도 고려해보시면 좋을 것 같습니다.


---

앞서 말씀드렸듯 단방향일 때와 양방향일 때 추가,제거,조회 에서 각각 쿼리가 어떻게 동작하시는지 비교해주시고 의견을 남겨주시면 좋을 것 같습니다. 대용량 트래픽을 다루는 도메인에서 대부분 양방향을 선택을 하고 있습니다. 쿼리가 각각 어떻게 동작하는지 이곳에 말씀해주시고, 그 데이터를 근거로 트레이드 오프된 결과를 말씀주시면 좋겠습니다.

2021-06-11 12:44 UTC, yevgnenll commented on src/main/java/qna/domain/Answer.java
>      public void toQuestion(Question question) {
말씀해주신 답변을 듣고보니 사상의 불일치 해소를 충분히 경험과 이해하지 못한것 같습니다

먼저 Question-Answer 양방향입니다
Question 을 select 하여 question.getAnswers() 를 호출하고, answer 를 출력하면 다음과 같습니다

```java
System.out.println("start !!!");
Question question = questionRepository.findById(5L).get();
for (Answer answer : question.getAnswers()) {
    System.out.println(answer);
}
```

1. select * from question where id = ?
2. select * from answer where question_id = ?
3. select * from user where user_id = ?
4. select * from user where user_id = ?
5. select * from user where user_id = ?

이 상황에서 다음의 코드로 Answer 를 추가하고자 하면 insert 수행이 되지 않습니다

```java
User writer = userRepository.findById(8L).get();
question.addAnswer(new Answer(writer, question, "new answer"));
```

하지만, 저는 객체지향적(?) 혹은 사상 불일치를 해결하려면 Question 에서 addAnswer, deleteAnswer 의 함수를 실행했을때
insert, delete 쿼리가 실행되는 것이 맞다고 생각합니다

그렇다면 Question entity에

```
@OneToMany(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
@JoinColumn(name = "question_id")
private List<Answer> answers = new ArrayList<>();
```
와 같이 연관관계를 설정해두고 addAnswer를 실행한다면 

```sql
    insert 
    into
        answer
        (id, created_at, updated_at, contents, deleted, question_id, writer_id) 
    values
        (null, ?, ?, ?, ?, ?, ?)
``` 
과 같이 insert 문이 실행됩니다

2021-06-11 12:46 UTC, yevgnenll commented on src/main/java/qna/domain/Answer.java
>      public void toQuestion(Question question) {
단방향이라면
아니, 사상불일치를 해소하지 못한다면 

answer = answerRepository.save(answer);

question.addAnswer(answer);
```
와 같은 별도의 작업이 필요하여 말씀하신대로 JPA 를 사용하지 않는것과 같습니다

2021-06-12 01:39 UTC, kingbbode approved these changes
감사합니다 :)
머지하겠습니다.

2021-06-12 01:39 UTC, merged