Step3 pr입니다.
next-step/jwp-qna pull request #163
Opened 2021-06-10 16:40 UTC by cupeanimus

안녕하세요.
3단계 작업 PR 요청입니다.

기능요구사항대로 서비스 로직을 Question과 answer에서 처리하도록 위임하고 삭제작업을 TDD로 리팩토링 하였습니다.
도메인에 해당되기 때문에 테스트는 해당 에러부분 중점으로 TDD 작업을 하였으며, 
너무 간단하게 끝나 뭔가 빠뜨린게 있지 않을까 조금 염려되니 부족한 부분이 있다면 편히 리뷰 부탁드립니다.

감사합니다.

2021-06-11 02:42 UTC, kang-hyungu requested changes
기호님 몇 가지 피드백 남겼어요
수정해보시고 궁금한 점 생기면 dm 주시거나 코멘트 남겨주세요.

2021-06-11 02:42 UTC, kang-hyungu commented on src/main/java/qna/domain/Answer.java
>  public class Answer extends BaseEntity{
```suggestion
public class Answer extends BaseEntity {
```

2021-06-11 02:42 UTC, kang-hyungu commented on src/main/java/qna/domain/Answer.java
>      public void toQuestion(Question question) {
```java
    public void toQuestion(Question question) {
        question.addAnswer(this);
        this.question = question;
    }
```

1. 객체 설정을 먼저 끝내고 인스턴스 변수를 교체하는게 좋지 않을까요? 객체 설정 중간에 유효성 검사를 통과하지 못하는 경우가 생길수도 있을테니깐요.
2. 이미 존재하는 질문인지 체크하는 유효성 검사는 클라이언트가 아닌 객체 내부에서 처리해주는게 좋겠네요.

2021-06-11 02:42 UTC, kang-hyungu commented on src/main/java/qna/domain/Answer.java
> +        if (!isOwner(loginUser)) {
삭제를 먼저 하고 유효성 검사를 하면 이미 삭제 됐는데 검사하는 의미가 있나요?

2021-06-11 02:42 UTC, kang-hyungu commented on src/main/java/qna/domain/Answers.java
> +    public List<DeleteHistory> delete(User loginUser) throws CannotDeleteException {
```suggestion
    public List<DeleteHistory> delete(User loginUser) {
```
unchecked 검사로 만들어주세요

2021-06-11 02:42 UTC, kang-hyungu commented on src/main/java/qna/domain/DeleteHistory.java
> +    public void setDeleteUser(User deleteUser) {
setter가 필요할까요?

2021-06-11 02:42 UTC, kang-hyungu commented on src/main/java/qna/domain/Question.java
>  public class Question extends BaseEntity{
```suggestion
public class Question extends BaseEntity {
```

2021-06-11 02:42 UTC, kang-hyungu commented on src/main/java/qna/domain/Question.java
> +    public List<DeleteHistory> delete(User loginUser) throws CannotDeleteException {
```suggestion
    public List<DeleteHistory> delete(User loginUser) {
```

2021-06-11 02:42 UTC, kang-hyungu commented on src/main/java/qna/domain/Question.java
>  public class Question extends BaseEntity{
객체지향 생활체조
규칙 9: 게터/세터/프로퍼티를 쓰지 않는다.

setter는 전부 삭제해주세요.

2021-06-11 02:42 UTC, kang-hyungu commented on src/main/java/qna/domain/Question.java
> +        List<DeleteHistory> deleteHistories = new ArrayList<>();
answers.delete 메서드에서 list를 반환해주는 걸 활용해도 되지 않을까요

2021-06-11 03:43 UTC, cupeanimus commented on src/main/java/qna/domain/Answer.java
>  public class Answer extends BaseEntity{
스타일때문에 애 먹습니다. 스타일 체크나 자동 설정하는 툴이 있을 것 같은데 관련 팁을 주실 수 있나요?

2021-06-11 04:28 UTC, cupeanimus commented on src/main/java/qna/domain/Answer.java
>      public void toQuestion(Question question) {
양쪽에서 셋을 하거나 추가할 때 함께 변경되도록 작업하면서 무한루프에 빠질 수 있어서 이전과 같은 방법으로 하였습니다.
때문에 처음 set과 같은 역할을 하는 toQuestion 메서드에 answer에 다시 question을 체크하는 부분을 넣었으나, 해당 부분은 설정하면서 불필요해보여 setQuestion으로 수정하고 값을 입력만 받도록 수정하였습니다. 
즉, Many쪽에서 add하는 경우에만 연관관계를 맺는 값들 모두 입력되도록 수정해보았습니다.

2021-06-11 04:36 UTC, cupeanimus commented on src/main/java/qna/domain/Answer.java
> +        if (!isOwner(loginUser)) {
에러가 발생하면 해당 메서드 작업이 모두 취소되는 것이라 생각하여 순서에 크게 신경을 안썼습니다.
따로 설정을 하지 않았는데도 위와같은경우 동일 유저 체크에서 에러가 발생하면, 먼저 작업된 answer가 소프트 delete된 상태인가요??

2021-06-11 04:43 UTC, cupeanimus commented on src/main/java/qna/domain/DeleteHistory.java
> +    public void setDeleteUser(User deleteUser) {
history같은 경우 확실히 필요 없어 삭제하였습니다.

2021-06-11 04:48 UTC, cupeanimus commented on src/main/java/qna/domain/Question.java
>  public class Question extends BaseEntity{
사용하지 않는 부분은 모두 삭제하였습니다. 
setDelete같은 경우도 삭제해야할까요?
수정가능한 개체(entity)인 경우 set을 통한 수정이 있을 수 있는데 이런경우에는 좀 더 명확한 이름의 메서드로 해당 역할을 수행하도록 하고 원칙대로 setter를 삭제하는걸까요?

2021-06-11 04:51 UTC, cupeanimus commented on src/main/java/qna/domain/Question.java
> +        List<DeleteHistory> deleteHistories = new ArrayList<>();
Question삭제 - 답변 삭제 순으로 해야하는 것 같아 따로 생성을 하였습니다.
말씀하신대로 수정해보았습니다.

2021-06-13 00:01 UTC, kang-hyungu commented on src/main/java/qna/domain/Answer.java
>  public class Answer extends BaseEntity{
사용하시는 ide에서 제공하는 스타일 체크 툴을 사용하는 방법도 있겠네요
checkstyle로 검색하시면 될거에요

2021-06-13 00:02 UTC, kang-hyungu commented on src/main/java/qna/domain/Answer.java
> +        if (!isOwner(loginUser)) {
트랜잭션이랑 헷갈리신 것 같네요.
자바 객체의 상태를 바꾸신 것이니 롤백되지 않습니다.

2021-06-13 00:03 UTC, kang-hyungu commented on src/main/java/qna/domain/Question.java
>  public class Question extends BaseEntity{
필요하다면 setter를 둘 수 있겠지만 접근제어자는 private으로 막아놔야겠죠.

2021-06-13 00:15 UTC, kang-hyungu requested changes
기호님 피드백 반영하신 내용 확인했습니다
조금 더 살펴보면 좋을 부분에 코멘트 남겼어요
수정해보시고 리뷰 재요청주세요~!

2021-06-13 00:15 UTC, kang-hyungu commented on src/main/java/qna/domain/Answer.java
>      public void setWriter(User writer) {
이 메서드는 삭제해도 되겠네요

2021-06-13 00:15 UTC, kang-hyungu commented on src/main/java/qna/domain/Answer.java
> +    public void deleted(boolean deleted) {
answer 내부에서만 사용하고 있으니 private으로 막아두는게 좋겠네요

2021-06-13 00:15 UTC, kang-hyungu commented on src/main/java/qna/domain/Question.java
> +    public void deleted(boolean deleted) {
이 메서드도 없애도 되겠네요

2021-06-13 00:15 UTC, kang-hyungu commented on src/main/java/qna/domain/User.java
> +    private Answers answers;
Answer 객체가 User 객체를 이미 가지고 있는데 User도 Answer를 가지고 있어야 할 필요가 있을까요?
양방향 관계 매핑하려고 하신걸까요?

2021-06-13 00:15 UTC, kang-hyungu commented on src/main/java/qna/domain/User.java
>      public void addAnswer(Answer answer) {
사용하지 않는 메서드는 정리하는게 좋겠네요

2021-06-13 00:41 UTC, cupeanimus commented on src/main/java/qna/domain/User.java
> +    private Answers answers;
이전 스텝에서 연습으로 양방향으로 맺었던 것라 활용하였는데 user객채에서 answer를 추가하는 경우는 없으니 관계를 끊고, 다대일 단방향으로 수정하였습니다.

2021-06-13 00:46 UTC, cupeanimus commented on src/main/java/qna/domain/Answer.java
>  public class Answer extends BaseEntity{
ide에 설치만 해두고 적극 사용하지 않았네요. 사용법을 알아보고 좀 더 적극적으로 사용해봐야겠네요.

2021-06-13 00:53 UTC, cupeanimus commented on src/main/java/qna/domain/Answer.java
> +        if (!isOwner(loginUser)) {
해당 요청에서 소프트삭제가 이루어진 후 유효성검사 실패를 하였는데도 다시 상태를 보려는 경우가 없을 것 같고, Answer가 변경된 것이 flush되지 않을거라 생각으로 위와같은 생각을 가졌었습니다.
말씀하신대로 주의하는게 좋으니 순서를 신경써야겠지만 의문이 생겨서 질문을 드립니다.
바뀐 객체가 이후 유효성 검사 실패를 하였을때, 어떤 경우에 영향을 미칠까요?

2021-06-13 01:01 UTC, cupeanimus commented on src/main/java/qna/domain/Question.java
> +    public void deleted(boolean deleted) {
deleted 매소드에서 내부 호출하고 있어 answer처럼 private로 막아두겠습니다.

2021-06-13 01:02 UTC, cupeanimus commented on src/main/java/qna/domain/User.java
>      public void addAnswer(Answer answer) {
해당 기능을 완전한 상태라 두고, 나중을 대비해 사용하지 않는 메서드를 남겨두는 일 없이 사용하지 않는 메서드는 다 정리해봤습니다.

2021-06-13 01:21 UTC, kang-hyungu commented on src/main/java/qna/domain/Answer.java
> +        if (!isOwner(loginUser)) {
본인만 답변을 삭제 할 수 있는데 본인이 아닌 사용자가 삭제한 것으로 처리하면 안돼죠.
실제 웹에서 질문, 답변을 노출하게 되면 사용자에게는 삭제한걸로 나오겠죠.

2021-06-13 01:22 UTC, kang-hyungu approved these changes
기호님 빠르게 피드백 반영해주셨네요
pr은 머지 처리하겠습니다 수고하셨어요~!

2021-06-13 01:22 UTC, merged