3단계 - 질문 삭제하기 리팩터링
next-step/jwp-qna pull request #180
Opened 2021-06-25 16:18 UTC by ascii92der

안녕하세요.

개인적인 이유(회사)로 인해 미션 진행이 늦어 피드백 페이지까지 미리 보고 반영하려고 노력했습니다.

리뷰 요청드립니다 (_ _)

2021-06-26 21:06 UTC, kingbbode requested changes
코멘트 작성해두었습니다 :)
확인 부탁드려요.

2021-06-26 21:06 UTC, kingbbode commented on src/main/java/qna/domain/Answer.java
>      }
`delete` 란 메서드를 통해 `DeleteHistory` 를 생성하는게 메서드가 가진 책임에 부합하는지, `Answer` 가 가져야할 책임인지 생각해보면 좋을 것 같습니다.

2021-06-26 21:06 UTC, kingbbode commented on src/main/java/qna/domain/Question.java
>      }
`isOwner` 란 메서드와 `CannotDeleteException` 를 발생시키는게 어색하네요 :)

소유자인지를 확인하는 메서드에서 삭제할 수 없다는 예외가 발생하네요 :)

비지니스의 책임이 잘못되지 않았을까요?

2021-06-28 11:32 UTC, ascii92der commented on src/main/java/qna/domain/Question.java
>      }
말씀하신것처럼 ```CannotDeleteException ```이  isOwner에서 발생하는게 어색한 것 같네요
더불어 isOwner 자체가 Answer나 Question 객체에서 확인하는게 이상해보여 User로 보내봤습니다.
User에서 ```UnAuthenticationException```가 발생하도록 했고, 삭제시 ```try-catch```로 잡아 처리하도록 해보았습니다.

2021-06-28 11:38 UTC, ascii92der commented on src/main/java/qna/domain/Answer.java
>      }
```delete``` 메소드에서 ```DeleteHistory```를 생성하는게 어색한것 같아 primitive type 랩핑을 통해 생성된 ```Deletion```쪽으로 책임을 넘겨보았습니다.

그게 맞는거 같아 넘겼는데....
```Answer``` 와 ```Question``` 에서 삭제하지 않아, 삭제 주체에 대한 정보를 넣어 줄수 없게 되어 
```
 public static DeleteHistory addHistory(Object content) {
        if (content instanceof Answer) {
            return deleteAnswer((Answer) content);
        }
        if (content instanceof Question) {
            return deleteQuestion((Question) content);
        }
        return null;
    }
```` 
와 같은 메소드가 생성되었습니다...

이게 뭔가 깔끔해보이지 않는데... 좋은 방법을 고민해봐도 잘 모르겠네요 ㅠㅠ
혹시 의견 주실 부분이 있을까요?

2021-06-29 20:23 UTC, kingbbode requested changes
코멘트 작성해두었습니다 :)
확인 부탁드려요!

2021-06-29 20:23 UTC, kingbbode commented on src/main/java/qna/domain/User.java
> +    public void isOwner(User user) throws UnAuthenticationException {
`is` 로 시작하는 메서드는 흔히 boolean 을 반환할 것으로 기대가 됩니다.
예외 모델로 처리해야하는 이유가 무엇일까요?

2021-06-29 20:23 UTC, kingbbode commented on src/main/java/qna/domain/User.java
> +    public void isOwner(User user) throws UnAuthenticationException {
`User` 에게 `isOwner` 라는 메서드명은 어울리지 않아보여요.

2021-06-29 20:23 UTC, kingbbode commented on src/main/java/qna/domain/Deletion.java
> +public class Deletion {
`Deletion` 클래스까지 만들어졌군요.

제가 피드백을 작성했던 최초 의도는 `delete` 와 `history` 는 내포된 기능이 아니라, 분리되어야 하는 기능이 아닐까 였습니다 :)

이 객체에서 삭제하면서 history 가 생성된다고 하지만, 이 history 가 저장이 된다는 보장은 없습니다.

결국 서비스 레이어에서 서로 다른 기능을 엮어주는 일을 하게 됩니다. 
```
deleteHistoryService.saveAll(question.delete(loginUser).histories());
```

history 에 대한 책임이 너무 많은 곳에 분산되어 있다고 생각이 되네요 :)

question 은 삭제 기능에 집중하고, history 적재는 history를 적재하는 곳에서 집중하도록 작성해보는게 어떨까하는게 코멘트를 작성했던 의도였습니다.

```
question.delete(loginUser);
deleteHistoryRepository.saveAll(DeleteHistories.of(question).histories());
```

2021-06-30 17:33 UTC, ascii92der commented on src/main/java/qna/domain/User.java
> +    public void isOwner(User user) throws UnAuthenticationException {
```Question```과 ```Answer```에 있는 ```isOwner```의 중복을 줄이기 위해서 ```User```로 이동시켰는데
```this.user.XXX(user)```와 같이 사용하였을 때, 적당한 명칭이 없어보입니다.

아마 ```User```에서 권한이 있는지 확인하는 메서드가 있는 것이 부자연스러워서 인것 같습니다.
그래서  원래대로 변경하고 return을 boolean으로 하였습니다.

2021-06-30 17:35 UTC, ascii92der commented on src/main/java/qna/domain/Deletion.java
> +public class Deletion {
Delete하는 것과 DeleteHistory가 생기는 것을 분리될 수 없는 기능이라 생각했던것 같습니다.

힌트를 주신대로, 

```
question.delete(loginUser);
``` 
에서는 delete의 권한과 flag값 변경을,

```
deleteHistoryRepository.saveAll(DeleteHistories.of(question).histories());
```
에서는 삭제된 히스토리를 적재하는 기능으로 분리하였습니다.

2021-07-04 02:15 UTC, kingbbode approved these changes
수고 많으셨습니다 :)
이만 머지하겠습니다.

2021-07-04 02:15 UTC, merged