[step2] feat: 연관 관계 매핑
next-step/jwp-qna pull request #186
Opened 2021-07-05 17:58 UTC by aterilio

과제의 DLL 힌트를 보고 fk_answer_to_question, fk_answer_writer 용어 차이에 따른
양방향, 단방향(단순 참조)를 구분해서 매핑해보았습니다.

리뷰 부탁드립니다 :)

2021-07-06 16:36 UTC, kingbbode requested changes
코멘트 작성해두었습니다.
확인 부탁드려요 :)

2021-07-06 16:36 UTC, kingbbode commented on src/main/java/qna/domain/Question.java
>      public void addAnswer(Answer answer) {
필드로 가지고 있는 answers 에는 answer가 추가되지 않았고, answer 은 question 을 가지고 있네요 :)
데이터베이스 중심적인 관계 작성임과 동시에, 데이터베이스 기준 상태와 객체의 상태가 불일치하는 문제점이 있습니다.

2021-07-06 16:36 UTC, kingbbode commented on src/main/java/qna/service/QnaService.java
관계에 대한 구현만 있고, 관계를 통한 객체지향적인 코드 작성은 보이지가 않네요 :)

2021-07-07 20:44 UTC, aterilio commented on src/main/java/qna/service/QnaService.java
deleteQuestion 메서드에 리팩토링 여지가 더 남아 있지만
다음 step3 가 리팩토링이라 우선 요기까지 끊어보았습니다.

그런데 하다보니 궁금한 부분이 생겼는데요,
기존에는 deleteQuestion 메서드에서 answers 반복문을 수행했었는데 이 부분을 Question 클래스 내부에서 수행하도록 변경하였거든요. 이 때 Question 클래스의 List<Answer> answers 에 변동이 생기면 그 부분이 자동으로 DB 에 반영되는 게 맞나요?
단위 테스트가 통과했으니까 맞는 거 같긴한데, '질문 삭제' 관련 로직에서 AnswerRepository 에 대한 처리를 하지 않으니까 저장이 반영되지 않을 것 같기도 해서 헷갈려서 여쭤봅니다 ㅠㅠ

그 부분 확인을 하고 싶어서 QnaServiceTest 클래스의 테스트 진행 시 DataJpaTest 어노테이션도 줘보았는데 테스트라서 그런지 실행 쿼리가 출력되지는 않아서요 ㅠ
(spring.jpa.show-sql 는 true 로 설정되어 있습니다.)

2021-07-09 17:04 UTC, kingbbode approved these changes
확인했습니다 :)
머지하겠습니다.

2021-07-09 17:04 UTC, merged

2021-07-09 17:09 UTC, kingbbode commented on src/main/java/qna/service/QnaService.java
JPA 를 학습하고 계시기 때문에 반드시 알고 넘어가야하는 부분인 것 같네요 :) 질문하신 내용을 보았을 때 영속 상태나 1차 캐시, 영속성 컨텍스트와 같은 기본 원리를 제대로 알고 계시지 않은 것 같네요. 단순히 사용법을 아는 것으로는 JPA를 다룰 수 없습니다.

`변동이 생기면 그 부분이 자동으로 DB 에 반영` 이라는게 어떤 원리로 동작하는지 반드시 살펴보시길 바랍니다 :)

영속 상태의 객체에서 연관관계에 대한 영속 관계가 성립될 때 객체의 변동사항을 기록해두었다가 변경사항을 쿼리로 반영해주게 됩니다. 이것을 이해하려면 영속 상태가 무엇인지, 영속성이란 무엇인지를 아셔야 하고 어떤 원리로 어느 객체가 변경사항을 반영하는지도 반드시 찾아보셔야 합니다 :)