Step2
next-step/jwp-qna pull request #199
Opened 2021-11-06 08:04 UTC by IW-MOON

안녕하세요 리뷰어님, 문인우입니다. 
1단게 피드백 감사드립니다. 😄 

이어서 2단계 연관관계 맵핑 미션 개발 완료하였습니다. 
감사합니다^^

2021-11-06 09:07 UTC, IW-MOON commented
2단계 연관관계 맵핑 미션입니다.
감사합니다^^

2021-11-06 14:29 UTC, nokchax requested changes
안녕하세요, 인우님
두번쨰 단계도 빠르게 진행해 주셨네요.
관계설정이 꼬여서 전반적으로 코드 수정이 필요해 보입니다.
관계 설정 뿐만 아니라 이를 활용해서 객체지향적인 코드가 되도록 수정해보시면 좋을거 같아요 :)
코멘트 확인후 재요청 부탁드립니다!

2021-11-06 14:29 UTC, nokchax commented on src/main/java/qna/domain/DeleteHistory.java
> +                Objects.equals(deletedBy.getId(), that.deletedBy.getId());
```suggestion
                Objects.equals(deletedBy, that.deletedBy);
```
로 충분하지 않을까요?

2021-11-06 14:29 UTC, nokchax commented on src/main/java/qna/domain/Question.java
>      public boolean isDeleted() {
`규칙 9: 게터/세터/프로퍼티를 쓰지 않는다.`

setter와 사용하는 getter를 제외하고는 삭제해 주세요 :)
꼭 set을 써야한다면 의미있는 함수명과 유효성 검증으로 객체지향 적으로 만들어주세요!

2021-11-06 14:29 UTC, nokchax commented on src/main/java/qna/domain/Answer.java
> +    private Question question;
Question 과 Answer 간의 관계에 대해서 한번 생각해 봐야할 것 같아요.
지금은 다대일 단방향 관계로 설정해 주셨는데요, 이러면서 Question 에서 Answer를 다루기 힘들게 됐습니다.

QnA 서비스를 생각해볼게요, 하나의 Answer에서 Question을 참조할 일이 많을까요?
아니면 하나의 Question에서 여러 Answer를 가져다 사용할 일이 많을까요?

2021-11-07 05:14 UTC, nokchax approved these changes
리뷰 잘 반영해 주셨습니다 :)
다음 단계 진행해주세요

2021-11-07 05:14 UTC, nokchax commented on src/main/java/qna/domain/Question.java
> +    private List<Answer> answers = new ArrayList<>();
👍

2021-11-07 05:14 UTC, merged