3단계 - 질문 삭제하기 리팩터링
next-step/jwp-qna pull request #215
Opened 2021-11-08 14:00 UTC by bgpark82

안녕하세요! 마지막 미션이네요

리뷰 잘 부탁드립니다 🙇‍♂️

2021-11-09 05:08 UTC, leeyohan93 requested changes
벌써 마지막 3단계 미션이네요!
요구사항 잘 구현해주셨습니다 👍 
몇가지 코멘트들을 남겨드렸으니 확인 부탁드릴게요 :)
마지막까지 화이팅입니다 ! 🔥

2021-11-09 05:08 UTC, leeyohan93 commented on src/main/java/qna/domain/Question.java
> +    public void checkOwner(User writer) throws CannotDeleteException {
외부에서 사용하는 곳이 없는데 접근제어자를 변경해주면 어떨까요 ?

2021-11-09 05:08 UTC, leeyohan93 commented on src/main/java/qna/domain/Answers.java
> +        this.answers = answers;
Collection에서 제공하는 unmodifiableList를 활용해보는 건 어떨까요?
리스트에 대한 추가, 삭제를 막아주는 기능으로 일급 컬렉션도 좀 더 불변에 가까워질 수 있습니다 :)

2021-11-09 05:08 UTC, leeyohan93 commented on src/main/java/qna/service/QnaService.java
> +        List<Answer> answerList = answerRepository.findByQuestionIdAndDeletedFalse(questionId);
List에 의존한, 즉 타입에 의존하는 변수명은 타입변경 시 변수명도 함께 변경되어야 한다는 단점이 있습니다.
복수 형태의 변수명을 지어주는 것은 어떨까요? :)

2021-11-09 05:08 UTC, leeyohan93 commented on src/main/java/qna/service/QnaService.java
> +        List<Answer> answerList = answerRepository.findByQuestionIdAndDeletedFalse(questionId);
현재 Question 조회 하고 난 후 Answers를 조회하고 있는데요. 
양방향 연관 관계 설정을 통해 객체 그래프를 통해서 Answers를 조회해보는 것은 어떨까요 ?

양방항 연관관계를 만들 때는 @Embeddable을 사용해보시는 것도 좋을 것 같아요 :)
실무에서는 복잡해서 지양한다는 의견도 존재하지만 저희는 훈련을 하는 것이니 진행해보는 것이 좋을 것 같아요 😄 
https://wbluke.tistory.com/23
https://www.inflearn.com/questions/84874

2021-11-09 05:08 UTC, leeyohan93 commented on src/main/java/qna/domain/DeleteHistories.java
> +    private final Answers answers;
DeleteHistories가 꼭 Answers를 상태로 저장해야할까요? 🤔 
DeleteHistories 내부에 Answers를 가지고 있지 않고 Answers에게 메시지를 던져 DeleteHistories를 반환받는 방식은 어떨까요 ?

2021-11-09 05:08 UTC, leeyohan93 commented on src/main/java/qna/domain/Answers.java
> +            throw new CannotDeleteException("다른 사람이 쓴 답변이 있어 삭제할 수 없습니다.");
RuntimeException으로 변경해보는건 어떨까요 ? 😄

2021-11-09 05:08 UTC, leeyohan93 commented on src/main/java/qna/domain/Question.java
> +    public List<DeleteHistory> delete(Answers answers, User writer) throws CannotDeleteException {
사소하지만 일급 컬렉션을 반환해보는 건 어떨까요 ?
```suggestion
    public DeleteHistories delete(Answers answers, User writer) throws CannotDeleteException {
```

2021-11-09 14:22 UTC, bgpark82 commented on src/main/java/qna/domain/Question.java
> +    public void checkOwner(User writer) throws CannotDeleteException {
그러네요 private으로 변경하고 테스트도 지워야 겠습니다

2021-11-09 14:25 UTC, bgpark82 commented on src/main/java/qna/service/QnaService.java
> +        List<Answer> answerList = answerRepository.findByQuestionIdAndDeletedFalse(questionId);
그렇군요 변수명이 타입에 의존한다고 생각해본적은 없었던 것 같습니다 감사합니다!

2021-11-10 02:50 UTC, bgpark82 commented on src/main/java/qna/domain/DeleteHistories.java
> +    private final Answers answers;
delete 메소드의 파라미터를 줄이려고 생각하다 보니, 그 생각을 못했던 것 같네요. DeleteHistories가 Answers를 가지고 있는 건 좀 부자연스럽긴 한 것 같습니다

2021-11-10 03:06 UTC, bgpark82 commented on src/main/java/qna/service/QnaService.java
> +        List<Answer> answerList = answerRepository.findByQuestionIdAndDeletedFalse(questionId);
아 네 알고는 있었지만 보이질 않았네요ㅠ 좋은 지적 감사합니다!

2021-11-10 03:15 UTC, bgpark82 commented on src/main/java/qna/domain/Answers.java
> +            throw new CannotDeleteException("다른 사람이 쓴 답변이 있어 삭제할 수 없습니다.");
CannotDeleteException이 Checked Exception이였네요. 제가 미쳐 신경쓰지 못한 것 같습니다. 감사합니다 😄

2021-11-10 17:08 UTC, leeyohan93 requested changes
피드백을 잘 적용해주셨네요 👍 
미션을 종료하기 전에 조금 더 개선해보면 좋을 것 같은부분에 대한 몇가지 코멘트들을 남겨 놓았습니다.
확인 부탁드릴게요 :) 조금만 더 화이팅입니다 🔥

2021-11-10 17:08 UTC, leeyohan93 commented on src/test/java/qna/domain/QuestionRepositoryTest.java
> +        entityManager.clear();
테스트가 추가된다면 해당 로직이 반복될 수 있을 것 같은데요.
BeforeEach를 통해 수행하도록 해보는 건 어떨까요? :)

2021-11-10 17:08 UTC, leeyohan93 commented on src/test/java/qna/domain/QuestionRepositoryTest.java
> +        }
해당 테스트는 조회 결과가 null일 경우에도 통과할 수 있을 것 같습니다. 개선이 필요해보여요 🤔

2021-11-10 17:08 UTC, leeyohan93 commented on src/main/java/qna/domain/Question.java
> +        answers.checkIsOwner(writer);
답변을 삭제할 때 해야할 검증이, 질문을 삭제할 때 수행되어지고 있는 것 같아요.
질문을 삭제하라는 메시지를 구현한 메서드 안에서 검증하도록 하는 것은 어떨까요? :)

2021-11-10 17:08 UTC, leeyohan93 commented on src/main/java/qna/domain/Question.java
> +        checkOwner(writer);
메서드 첫 라인으로 이동하여 로직이 빠르게 실패하도록 개선할 수 있을 것 같아요 :)

2021-11-10 17:08 UTC, leeyohan93 commented on src/main/java/qna/domain/Question.java
> +        Answers answers = this.answers.getNotDeleted();
해당 부분 또한 질문을 삭제하라는 메세지를 구현한 메서드 안에서 처리하는 것이 더욱 적합해보여요 🤔 
+ 추가적인 질문으로 삭제함으로써 모든 답변을을 삭제하는데 따로 삭제되지 않은 답변을 가져오시는 이유가 있을까요 ?

2021-11-10 17:08 UTC, leeyohan93 commented on src/main/java/qna/domain/Question.java
> +        DeleteHistories histories = new DeleteHistories();
현재는 histories 내부의 빈 리스트를 생성해두고 추가하고 있는데요. 일급 컬레션을 불변 객체로 사용해보는건 어떨까요?

2021-11-10 17:08 UTC, leeyohan93 commented on src/main/java/qna/domain/Question.java
> +        return histories.delete(answers, DeleteHistory.question(id, writer));
삭제 기록들 객체에게 삭제하라는 책임은 조금 어색해보이기도 하는데요 🤔 
아래 처럼 같이 개선해볼 수도 있을 것 같아요. 참고만 해주세요 :)

```suggestion
        return DeleteHistories.of(answers.delete, DeleteHistory.question(id, writer));
```

2021-11-10 17:08 UTC, leeyohan93 commented on src/main/java/qna/domain/DeleteHistories.java
> +    }
일급 컬렉션을 불변 객체로 만들어보는건 어떨까요?

Collection에서 제공하는 unmodifiableList를 활용하면 리스트에 대한 추가, 삭제를 막아주는 기능으로 일급 컬렉션도 좀 더 불변에 가까워질 수 있습니다 :)

2021-11-10 17:08 UTC, leeyohan93 commented on src/main/java/qna/service/QnaService.java
>      private DeleteHistoryService deleteHistoryService;
final을 붙여주시면 좋을 것 같아요 :)

2021-11-11 11:53 UTC, peter-alethio commented on src/test/java/qna/domain/QuestionRepositoryTest.java
> +        entityManager.clear();
전체 테스트 메소드에서 한개의 메소드만 해당 로직이 사용되는데 테스트가 추가되고 BeforeEach로 옮겨도 되지 않을까요?

2021-11-11 11:53 UTC, peter-alethio commented on src/test/java/qna/domain/QuestionRepositoryTest.java
> +        }
그러네요 다시 고려해봐야 될 것 같습니다

2021-11-11 12:14 UTC, peter-alethio commented on src/main/java/qna/domain/Question.java
> +        Answers answers = this.answers.getNotDeleted();
그러네요 코드 그대로를 구현하도록 고민을 했던 것 같네요. 어짜피 다 지워질테니 말씀하신 것처럼 삭제 여부를 구하지 않아도 될 것 같습니다!

2021-11-11 14:23 UTC, bgpark82 commented on src/main/java/qna/domain/Question.java
> +        return histories.delete(answers, DeleteHistory.question(id, writer));
네 뭔가 도메인의 역할에 따라 작성되기 보다는 클래스의 변수에 위임하면서 만든게 아닌가 싶네요 감사합니다

2021-11-11 14:24 UTC, bgpark82 commented on src/main/java/qna/domain/Question.java
> +        answers.checkIsOwner(writer);
네 그러네요 수정하는게 좋을 것 같습니다!

2021-11-11 14:27 UTC, bgpark82 commented
꼼꼼한 리뷰 감사드립니다

뭔가 도메인의 역할에 따라 작성되었기 보다는 클래스의 변수에 책임을 위임하는 느낌이 강했던 것 같습니다
아직 확실하지 못한 부분이 있어서 피드백 주시면 감사하겠습니다 🙇‍♂️

2021-11-11 15:06 UTC, leeyohan93 commented on src/test/java/qna/domain/QuestionRepositoryTest.java
> +        entityManager.clear();
이전에 BeforeEach로 작성해주신 부분이 있어 드렸던 코멘트였습니다 🙏 
병길님 의견이 그러시다고 하면 현재 BeforeEach에서 setup 해주던 부분도 해당 테스트의 given절로 들어와야할 것 같아 보이는데 어떻게 생각하시나요 ? 🤔

2021-11-11 16:00 UTC, leeyohan93 requested changes
피드백 반영을 잘해주셨습니다 ! 👍 
마지막 단계를 종료하기 전에 조금 더 개선해볼만한 부분에
코멘트들을 남겨놓았으니 확인 부탁드려요 :)
마지막까지 파이팅입니다! 🔥

2021-11-11 16:00 UTC, leeyohan93 commented on src/main/java/qna/domain/Answers.java
> +    }
미사용 로직은 제거해주시면 좋을 것 같아요 :)

2021-11-11 16:00 UTC, leeyohan93 commented on src/main/java/qna/domain/Answers.java
> +    }
답변을 삭제할 때 필요한 검증의 책임을 Answer 클래스로 이전해보는 건 어떨까요?

2021-11-11 16:00 UTC, leeyohan93 commented on src/main/java/qna/domain/Answers.java
> +    public List<DeleteHistory> delete(User writer) {
반환 값으로 일급 컬렉션을 사용해보면 좋을 것 같아요 :)

추가적으로 질문이 지워질때, 답변이 함께 지워져야하므로 삭제 시간은 동일해야하지 않을까요?

```suggestion
    public DeleteHistories delete(User writer, LocalDateTime deletedAt) {
```

2021-11-11 16:00 UTC, leeyohan93 commented on src/main/java/qna/domain/DeleteHistories.java
> +    private final List<DeleteHistory> deleteHistories = new ArrayList<>();
미리 빈 배열로 내부 컬렉션을 초기화하게 되면 일급 컬렉션을 불변 객체로 만들 수 없게됩니다!
생성자를 통해서 초기화를 진행해보시면 좋을 것 같아요!
생성자로 초기화해주실 때 Collections.unmodifiableList()를 활용해보시면 좋을 것 같아요
    }/

```suggestion
    private final List<DeleteHistory> deleteHistories;
```

2021-11-11 16:00 UTC, leeyohan93 commented on src/main/java/qna/domain/DeleteHistories.java
> +        return Collections.unmodifiableList(deleteHistories);
생성자를 통해 Collections.unmodifiableList()를 사용해준다면 반복적인 로직이 될 수 있겠네요 🤔

2021-11-12 09:24 UTC, bgpark82 commented on src/main/java/qna/domain/DeleteHistories.java
> +    private final List<DeleteHistory> deleteHistories = new ArrayList<>();
아 그렇네요 이미 변경 가능하니까ㅠ 생성 시점에 `Collections.unmodifiableList()`하면 되는군요. 감사합니다!

2021-11-12 09:48 UTC, bgpark82 commented on src/main/java/qna/domain/Answers.java
> +    public List<DeleteHistory> delete(User writer) {
시간 상 거의 차이가 없을 거라고 생각했는데 말씀하신대로 삭제 시간을 동일하게 둬야 될 것 같네요
꼼꼼한 피드백 감사합니다!

2021-11-12 09:49 UTC, bgpark82 commented
덕분에 일급 컬렉션에 불변화에 대해 많이 배우게 되었습니다.
자세한 피드백 정말 감사합니다!

2021-11-12 15:18 UTC, leeyohan93 approved these changes
창섭님 마지막까지 빠르게 피드백을 반영하여 미션을 잘 마무리 해주셨네요 💯
피드백에 대해 많이 고민하고 생각하여 반영해주시는 것이 정말 좋았습니다 👍 
JPA 미션은 종료되었지만 앞으로도 궁금한점이나, 어려운점 있다면 편하게 연락주세요.
다음 미션도 좋은 모습으로 완주하시기라 믿습니다.🔥
감사합니다.

2021-11-12 15:18 UTC, merged