3단계 : 질문 삭제하기 리팩터링
next-step/jwp-qna pull request #216
Opened 2021-11-08 14:01 UTC by tyranotyrano

안녕하세요😊 2주차 JPA 미션 진행자 최영진입니다.
3단계 질문 삭제하기 리팩터링 미션 리뷰 요청 드리겠습니다!
3단계 진행 중 궁금한 내용은 아래에 정리하였습니다.

---
Q1. **(답변 완료)** 이번 리팩토링 미션을 진행하면서 한번에 모두 리팩토링 하지 않고 Question 삭제 -> Answer 삭제 -> DeleteHistory 생성 순으로 단계적으로 리팩토링을 진행하였습니다. 리팩토링 하는 과정에서 각 단계별로 비즈니스 로직 및 테스트 코드를 정삭적으로 돌아가게 하기위해 임시적으로 getter 메소드를 추가하였습니다. 그리고 모든 리팩토링 완료 후 불필요한 getter 를 삭제하였습니다. 리팩토링 과정에서 발생하는 임시 getter 메소드들은 모든 처리가 완료된 후 지운다는 전제하에 편의를 위해 추가해도 괜찮을까요? 아니면 리팩토링 과정 단계에서부터도 엄격하게 사용을 최소화 하는게 좋을까요?

Q2. **(답변 완료)** 처음엔 Cascade 나 orphanRemoval 옵션을 주어 Question 이 삭제되면 Answer 도 영속성 전이가 일어나 자동으로 삭제되도록 설계를 했었습니다. 하지만 이렇게 개발을 하니 Answer 의 삭제 조건을 통과하지 않고 그냥 Answer 를 삭제하는 문제가 발생하였습니다. 아직 Cascade 나 orphanRemoval 사용이 익숙치 않아서 이런 옵션들을 사용할 때 주의해야할 점이나 사용 시 팁같은 것들이 있다면 공유받고싶습니다.😃

--- 
3단계 피드백 반영 완료하였습니다. 다시 리뷰 부탁드리겠습니다.😁👍

2021-11-09 11:14 UTC, slamdunk7575 requested changes
질문 삭제하기 리팩토링 정말 잘해주셨네요.
질문에 대한 답변과 소소한 코멘트 몇가지 남겨드렸습니다.
미션 마무리까지 얼마남지 않으셨네요~ 💪

2021-11-09 11:14 UTC, slamdunk7575 commented on src/main/java/qna/service/QnaService.java
> +        deleteHistoryService.saveAll(deleteHistories.getValues());
깔끔하게 리팩토링 잘해주셨네요 👍

2021-11-09 11:14 UTC, slamdunk7575 commented on src/main/java/qna/domain/Answers.java
> +	private final List<Answer> answers;
일급 컬렉션 분리 좋습니다 💯

2021-11-09 11:14 UTC, slamdunk7575 commented on src/main/java/qna/domain/Answer.java
> +        if (isOwner(owner) && question.isSameWriter(writer)) {
`question.isSameWriter(writer)`

이부분은 `Question` 에서 검증이 되었으니 제거해도 되지 않을까요?

2021-11-09 11:14 UTC, slamdunk7575 commented on src/main/java/qna/domain/DeleteHistory.java
> +    }
정적 팩토리 메소드 잘 활용해주셨네요 👍

2021-11-09 11:14 UTC, slamdunk7575 commented on src/main/java/qna/domain/Question.java
> 모든 원시 값과 문자열을 포장한다.

`예: title` 을 객체로 포장하고 길이에 대한 검증을 해볼 수 있겠네요.
필요하다고 생각되는 부분에 적용해보시면 좋을 것 같아요.

2021-11-09 11:14 UTC, slamdunk7575 commented on src/test/java/qna/domain/QuestionTest.java
> +    }
현재 Repository와 Domain에 대한 테스트가 작성되어 있긴 하지만
리팩토링을 통해 비지니스 로직이 도메인으로 옮겨졌으니 
필요하다고 생각되는 `도메인에(예: Answers) 단위 테스트`를 해보면 좋을 것 같아요.
기존 테스트를 Repository와 Domain 테스트로 나눠보셔도 좋습니다 😄

2021-11-09 11:14 UTC, slamdunk7575 commented on src/test/java/qna/service/QnaServiceTest.java
> +                DeleteHistory.ofAnswer(answer.getId(), answer.getWriter())
> Q1. 이번 리팩토링 미션을 진행하면서 한번에 모두 리팩토링 하지 않고 Question 삭제 -> Answer 삭제 -> DeleteHistory 생성 순으로 단계적으로 리팩토링을 진행하였습니다. 리팩토링 하는 과정에서 각 단계별로 비즈니스 로직 및 테스트 코드를 정삭적으로 돌아가게 하기위해 임시적으로 getter 메소드를 추가하였습니다. 그리고 모든 리팩토링 완료 후 불필요한 getter 를 삭제하였습니다. 리팩토링 과정에서 발생하는 임시 getter 메소드들은 모든 처리가 완료된 후 지운다는 전제하에 편의를 위해 추가해도 괜찮을까요? 아니면 리팩토링 과정 단계에서부터도 엄격하게 사용을 최소화 하는게 좋을까요?

미션을 하시면서 느끼셨겠지만 보통 비지니스 로직을 처리할 때 객체의 상태를 외부로 가져오는 `getter()`를 사용하면서 코드가 복잡해지는데요. 이런 `getter()` 최대한 없애고 객체에게 메시지를 보내는 과정에서 발생하는 것이기 때문에 괜찮다고 생각합니다. 또한 연습하는 과정이니 결과를 출력하기 위해 (예: DTO 에서) 최대한 마지막에 `getter()`를 사용한다고 생각하고 해보시는 것도 좋겠네요 :)

2021-11-09 11:14 UTC, slamdunk7575 commented on src/main/java/qna/domain/Answers.java
> +	@OneToMany(mappedBy = "question")
> Q2. 처음엔 Cascade 나 orphanRemoval 옵션을 주어 Question 이 삭제되면 Answer 도 영속성 전이가 일어나 자동으로 삭제되도록 설계를 했었습니다. 하지만 이렇게 개발을 하니 Answer 의 삭제 조건을 통과하지 않고 그냥 Answer 를 삭제하는 문제가 발생하였습니다. 아직 Cascade 나 orphanRemoval 사용이 익숙치 않아서 이런 옵션들을 사용할 때 주의해야할 점이나 사용 시 팁같은 것들이 있다면 공유받고싶습니다.😃

객체의 생성과 소멸을 같이 하는 경우에 `Cascade` 설정을 고려해볼 수 있을것 같아요.
알고 계시겠지만 `Cascade` 옵션에는 다양한 값들이 있기 때문에 상황에 맞춰 설정을 해보면 좋을 것 같네요.

2021-11-09 16:05 UTC, tyranotyrano commented on src/main/java/qna/domain/Answer.java
> +        if (isOwner(owner) && question.isSameWriter(writer)) {
이부분이 제일 고민되는 부분이었는데, Question 을 삭제하는 전반적인 로직에 대해서 Question 에서 이미 유효성 체크를 하였으니 Answer 에서는 패스할 것인가? 아니면 Answer 는 Answer 그 자체로 독립적인 삭제 로직을 검증해야 하는가? 이 두 가지 상황에 대해서 생각을 해봤습니다. 리뷰어님 피드백 처럼 "삭제" 로직 자체가 Question 에서부터 시작하는 로직이고, Answer 를 개별로 삭제하는 요구사항이 없으니 Answer 삭제를 독립적으로 보기보다 Question 삭제 로직과 연결지어서 하나로 보는게 맞을 것 같습니다.😊 refactoring 후 다시 리뷰 요청드리겠습니다! 감사합니다!

2021-11-09 16:08 UTC, tyranotyrano commented on src/main/java/qna/domain/Question.java
JPA 에만 집중해서 개발하다보니 원시값, 문자열 포장을 놓친 것 같습니다😂
이부분도 같이 refactoring 하여 다시 리뷰요청 드리겠습니다!

2021-11-09 16:12 UTC, tyranotyrano commented on src/test/java/qna/service/QnaServiceTest.java
> +                DeleteHistory.ofAnswer(answer.getId(), answer.getWriter())
답변 감사합니다! getter/setter 를 극단적으로 안쓰려고 하다보니 오히려 리팩토링 하는 과정에서 문제가 많았고, 뭔가 getter 를 사용하면 심적으로 미션을 잘못된 방향으로 가져가는게 아닌가 걱정을 많이 했었습니다. 이번 미션진행하면서 그리고 리뷰어님의 피드백을  곰곰히 생각해보니 getter/setter 를 지양하는 것은 맞지만 꼭 필요한 경우에 제한적으로 getter 를 쓰고 최대한 도메인 객체에게 메시지를 보내어 처리할 수 있게 만드는게 좋다고 판단됩니다!😁

2021-11-09 16:15 UTC, tyranotyrano commented on src/main/java/qna/domain/Answers.java
> +	@OneToMany(mappedBy = "question")
Cascade 를 사용할 때 습관적으로 항상 Cascade.ALL 을 사용했었는데, 피드백 주신 것 처럼 하위 엔티티가 상위 엔티티 1군데 에서만 종속적이고 비즈니스 로직으로 상위 엔티티가 삭제되면 모든 하위 엔티티가 삭제된다는 요구사항이 있다면 Cascade 를 좀더 활용할 수 있을 것 같습니다. 2단계에서 공유해주신 내용 덕분에 Cascade, orphanRemoval 옵션에 대해 많은 공부가 되었습니다. 감사합니다!👍

2021-11-09 17:14 UTC, tyranotyrano commented on src/test/java/qna/domain/QuestionTest.java
> +    }
이 부분도 JPA 에만 집중하다보니 각 도메인 객체별 테스트 코드를 작성하지 못한 것 같습니다😂
테스트 코드 추가하여 다시 리뷰 요청드리겠습니다! 세심하게 봐주셔서 감사합니다!

2021-11-10 12:40 UTC, slamdunk7575 approved these changes
피드백 열심히 반영해주셨네요.
제가 드렸던 피드백들이 앞으로 영진님께 조금이라도 도움이 되었으면 좋겠네요.
그동안 고생 많으셨습니다. 감사합니다. 🙇
남은 미션도 꾸준히 진행하시고 끝까지 완주하시길 응원하겠습니다! 🎉

2021-11-10 12:40 UTC, slamdunk7575 commented on src/main/java/qna/domain/QuestionTitle.java
> +public class QuestionTitle {
원시값 포장 💯

2021-11-10 12:40 UTC, slamdunk7575 commented on src/main/java/qna/domain/Answer.java
>      }
피드백 반영 잘해주셨네요 👍

2021-11-10 12:40 UTC, slamdunk7575 commented on src/test/java/qna/domain/AnswersTest.java
> +	void deleteAll1() throws CannotDeleteException {
현재는 도메인에 비지니스 로직이 많지 않지만
남은 미션들에서는 순수 도메인에 대한 테스트를 별도로 만들어 보면 좋을 것 같아요 🙂

2021-11-10 12:40 UTC, merged