1단계 - 엔티티 매핑
next-step/jwp-qna pull request #218
Opened 2021-11-08 23:58 UTC by minseokLim

처음에 클론 받고 좀 당황했습니다;;
리팩토링해야할 부분도 너무 많아보이고 엔티티도 이상하고... 이걸 다 고쳐야하나 생각을 하다 그걸 2, 3단계에서 한다는 걸 알게되었습니다^^;;; 그래서 1단계에서는 가볍게 학습테스트만을 요구한다고 생각하고 다른 건 최대한 건드리지 않기 위해 노력했습니다.

잘 부탁드립니다! :)

2021-11-09 04:34 UTC, nokchax requested changes
안녕하세요, 민석님! 2주차 JPA 과제 리뷰어 김광현입니다. 🙇‍♂️

엔티티 매핑 과제 전반적으로 잘 진행해주셨어요!
다만 필드와 컬럼을 매핑할때 다양한 어노테이션을 사용하는데,
빠진 것들이 있어 요구사항에 적혀있는 ddl을 만족하지 못하고 있습니다.
확인후 재요청 부탁드립니다 :)

2021-11-09 04:34 UTC, nokchax commented on src/main/java/qna/Application.java
> +@EnableJpaAuditing
👍

2021-11-09 04:34 UTC, nokchax commented on src/main/java/qna/domain/Answer.java
> +    private LocalDateTime updatedAt;
createdAt, updatedAt은 여러 곳에서 재사용하는 코드인데요, 이런 반복적인 걸 해결할 수 없을까요?

2021-11-09 04:34 UTC, nokchax commented on src/main/java/qna/domain/Answer.java
> +    private Long writerId;
여기에 선언된 것 만으로 요구사항에 나와있는 ddl과 같은 ddl이 생성될까요?
다른 엔티티도 마찬가진데요, 테스트 하실때 출력되는 ddl을 확인해보세요 :)

2021-11-09 04:34 UTC, nokchax commented on src/main/java/qna/domain/DeleteHistory.java
> +    private ContentType contentType;
`@Enumerated`에 대해 한번 찾아보세요 :)

2021-11-09 04:34 UTC, nokchax commented on src/test/java/qna/domain/AnswerTest.java
> +    }
setup에 대해 한번 생각해보셨으면 해서 링크 공유드립니다!
https://jojoldu.tistory.com/611

2021-11-09 04:50 UTC, minseokLim commented on src/main/java/qna/domain/Answer.java
> +    private LocalDateTime updatedAt;
추상클래스를 만들어서 MappedSuperClass 어노테이션을 사용해서 상속받으면 된다는 걸 알고는 있는데, 앞서 말씀드렸듯이 클론 받고 많이 당황해서; 어디까지 뜯어고쳐야하고 어디까지 1단계에서 원하는 건지 범위를 알 수가 없어서 진행하지 않았습니다^^; 해야한다고 생각하시면 진행하도록 하겠습니다.

2021-11-09 04:51 UTC, minseokLim commented on src/main/java/qna/domain/Answer.java
> +    private Long writerId;
아이고 죄송합니다ㅠㅠ 출근 전 급하게 하는 바람에 정말 기본적인건데 체크하질 못했네요. 수정하도록 하겠습니다.

2021-11-09 04:52 UTC, minseokLim commented on src/main/java/qna/domain/DeleteHistory.java
> +    private ContentType contentType;
아.. 이것도 varchar인데 지금은 ordinal로 박히겠군요... 제 불찰입니다ㅠㅠ

2021-11-09 04:52 UTC, minseokLim commented on src/test/java/qna/domain/AnswerTest.java
> +    }
퇴근 후 확인해보도록 하겠습니다. 감사합니다! :)

2021-11-09 12:46 UTC, nokchax commented on src/main/java/qna/domain/Answer.java
> +    private LocalDateTime updatedAt;
객체간의 연관관계 매핑이 아닌 엔티티 매핑이기 때문에 진행하셔도 될 것 같습니다 :)

2021-11-09 12:48 UTC, nokchax commented on src/test/java/qna/domain/AnswerTest.java
> +    }
오늘 테스트에 관해 좋은글을 하나 발견해서 추가적으로 공유드려요 :)
https://blog.kingbbode.com/52

2021-11-11 10:33 UTC, nokchax approved these changes
안녕하세요, 민석님! 🙇‍♂️ 
피드백 잘 반영해 주셨습니다.
깔끔히 리팩토링 하셔서, 특별히 코멘트 드릴게 없네요 💯 
머지하겠습니다, 다음 단계 진행해주세요!

2021-11-11 10:33 UTC, nokchax commented on src/main/java/qna/domain/BaseTimeEntity.java
> +public abstract class BaseTimeEntity {
👍

2021-11-11 10:33 UTC, merged