1단계 - 엔티티 매핑
next-step/jwp-qna pull request #219
Opened 2021-11-09 02:06 UTC by jerry92k

안녕하세요!
JPA 1단계 미션 코드리뷰 요청드립니다.
잘 부탁드립니다🙂

2021-11-09 14:05 UTC, na-mul requested changes
안녕하세요! JPA 미션의 리뷰를 맡게된 노동환입니다!
올려주신 내용 잘 봤습니다! 고생 많으셨습니다. 🙇‍♂️
조금 더 살펴봤으면 하는 부분들을 코멘트로 남겨드렸어요.
확인해주셔서 다시 request 부탁드릴게요!

2021-11-09 14:05 UTC, na-mul commented on src/main/java/qna/domain/Answer.java
> +	private String contents;
`contents`를 그냥 String으로 만들면 요구사항이었던 clob을 충족시키지 못하게 됩니다.
- 수정을 부탁드릴께요

2021-11-09 14:05 UTC, na-mul commented on src/main/java/qna/domain/Answer.java
> +	private boolean deleted;
- not null 조건을 고려하여 작성 부탁드릴께요!

2021-11-09 14:05 UTC, na-mul commented on src/main/java/qna/domain/Answer.java
> +	}
- 기본적으로 존재했던 코드들, 특히 `setter` 메소드들은 정리를 부탁드릴께요!

2021-11-09 14:05 UTC, na-mul commented on src/main/java/qna/domain/BaseTimeEntity.java
> +@MappedSuperclass
Auditing 기능을 잘 활용해주셨습니다!👍
다만 이 기능이 실제로 동작하기 위해서는 
`public class Application`에 `@EnableJpaAuditing` 어노테이션을 포함시켜주셔야 할 것 같아요.
- 수정을 부탁드릴께요!

2021-11-09 14:05 UTC, na-mul commented on src/main/java/qna/domain/DeleteHistory.java
> +    private ContentType contentType;
`enum` 타입의 경우 역시 어노테이션을 붙여주어야 합니다.
- `@Enumerated(EnumType.STRING)` 어노테이션 사용을 검토 부탁드릴께요

2021-11-09 14:05 UTC, na-mul commented on src/main/java/qna/domain/DeleteHistory.java
>      }
- IDE가 기본으로 생성해준 `equals` 메소드라 할지라도 코드 컨벤션을 지켜주시는 방향으로 수정 부탁드릴께요!
- 그리고 비슷한 상황으로 보이는 `equals` 메소드들도 한번에 수정 부탁드릴께요

2021-11-09 14:05 UTC, na-mul commented on src/main/java/qna/domain/Question.java
> +	private boolean deleted;
- 모두 적절한 어노테이션을 붙여주시면 감사하겠습니다! 🙏

2021-11-09 14:05 UTC, na-mul commented on src/main/java/qna/repository/QuestionRepository.java
> +package qna.repository;
패키지 정리 감사합니다.
팀의 상황에 따라서 `repository`들이 `domain` 패키지 하위로 가기도 하니 그 점은 참고 부탁드릴께요!

2021-11-09 14:05 UTC, na-mul commented on src/test/java/qna/domain/AnswerTest.java
> +    }
JPQL을 잘 학습해주셨네요! 👍😄

2021-11-09 14:05 UTC, na-mul commented on src/test/java/qna/repository/AnswerRepositoryTest.java
> +	}
`assertThat` 구문이 올바르게 종료되지 않은 것 같아요! 
또한 `findByCreatedAtBetween` 테스트의 경우, 위 말씀드린 사유로 createdAt이 정상적으로 세팅되어있지 않아요.
- 전반적인 수정을 부탁드립니다

2021-11-10 04:21 UTC, jerry92k commented on src/test/java/qna/repository/AnswerRepositoryTest.java
> +	}
안녕하세요 동환님🙂
엔티티 요구사항을 꼼꼼히 반영하지 못했던 것 같습니다.
코멘트 주신 것 참고하여 부족한 부분들을 보완해보았습니다.
감사합니다😀

2021-11-10 15:23 UTC, na-mul approved these changes
안녕하세요 지희님, 요구사항에 맞게 잘 수정해주셨네요!
approve 하도록 하겠습니다!
참고하면 좋을 간단한 코멘트도 하나 달아두었으니 괜찮으시면 다음 단계 진행 하실 때 고려해주세요! 🙇‍♂️
다음 단계도 화이팅입니다. 😄

2021-11-10 15:23 UTC, na-mul commented on src/main/java/qna/domain/Answer.java
> +	}
앞서 코멘트를 하나 놓친 부분이 있네요!

entity의 equals 메소드를 오버라이딩할 때는 주로 비즈니스 키를 활용합니다. 
보통 중복되지 않고 거의 변하지 않는 필드들이 활용됩니다. DB로 치면 후보키들을 사용한다고 볼 수 있을 것 같아요.
따라서 contents나 updatedAt 등은 적절치 않습니다. 

그러나 만약에 값 타입 ( `@Embedded` ) 이라면 모든 필드를 equals 메소드로 비교하곤 하니 참고 부탁드려요!

2021-11-10 15:23 UTC, merged