Step2 - 연관 관계 매핑
next-step/jwp-qna pull request #248
Opened 2021-11-11 00:29 UTC by mnonm

안녕하세요 민호님! 2주차 과제 진행자 송성빈입니다.

이번 과제를 하면서 궁금한 점은 RepositoryTest (CRUD)를 실제 현업에서도 작성하는지 궁금합니다.

어떻게 보면 엔티티를 저장, 조회하는게 JPA가 맡아서 진행되는 일이니 당연한 일인거 같은데,

이 과정을 테스트하는 이유는 쿼리를 확인하기 위한 위한 과정으로 보면될까요?

2021-11-11 22:30 UTC, 5minho requested changes
안녕하세요 성빈님
2단계 미션하시느라 고생많으셨어요 👍
코멘트 몇개 드렸는데 확인부탁드립니다~

2021-11-11 22:30 UTC, 5minho commented on src/main/java/qna/domain/Answer.java
> +    @OneToOne
`OneToOne` 으로 매핑해주셨네요.
보통 QnA 게시판에서는 한명의 유저가 여러 질문과, 여러 답변을 할 수 있지 않나요?
`ManyToOne` 으로 해보는건 어떨까요?
다른 OneToOne 매핑도 확인 부탁드릴게요

2021-11-11 22:30 UTC, 5minho commented on src/main/java/qna/domain/Question.java
Question 과 Answer 는 양방향매핑을 시도해봤으면 좋겠어요!
양방향매핑을 하면서 주의해야 할 점 같은 것도 학습해보면 좋을거 같아요

2021-11-11 22:33 UTC, 5minho commented
> 안녕하세요 민호님! 2주차 과제 진행자 송성빈입니다.
> 
> 이번 과제를 하면서 궁금한 점은 RepositoryTest (CRUD)를 실제 현업에서도 작성하는지 궁금합니다.
> 
> 어떻게 보면 엔티티를 저장, 조회하는게 JPA가 맡아서 진행되는 일이니 당연한 일인거 같은데,
> 
> 이 과정을 테스트하는 이유는 쿼리를 확인하기 위한 위한 과정으로 보면될까요?

팀 마다 다를거 같은데요! 복잡한 조회쿼리가 아닌 단순한 CRUD Repository Test 는 하지 않는거 같아요~
성빈님께서 말씀하신대로 이번과정에서는 학습을 위해 진행하는거라고 생각하셔도 될거 같아요!

2021-11-12 08:18 UTC, mnonm commented on src/main/java/qna/domain/Question.java
양방향 매핑, 편의 메소드 관련해서 학습을 해봤습니다.
현재는 학습상 편의 메소드를 추가했는데,
현재 요구사항 같은 경우 질문과 답변을 변경은 불가능하고, 
질문이 있을 때만 답변을 달 수 있어서 답변 생성시에 질문이 필수라고 하면 생성자에서 처리를 하고,
편의 메소드를 만들지 않아도 되는지 궁금합니다.

2021-11-12 08:19 UTC, mnonm commented on src/main/java/qna/domain/Answer.java
> +    @OneToOne
Answer - User 다대일 변경
DeleteHistory - User 다대일 변경
Question - User 다대일 변경

위와 같이 연관관계 변경했습니다!

2021-11-13 11:10 UTC, 5minho commented on src/main/java/qna/domain/Question.java
네 성빈님 Answer 에 setQuestion 을 만드는 것보다 생성자에서 처리하는 것이 더 안전한 방법이라고 생각해요.
그리고 이번 미션에서는 학습차원에서 양방향 매핑을 시도해주셨으면 좋겠다고 가이드 했지만, 
개인적으로는 양방향 매핑을 될 수 있으면 안하는게 좋다고 생각해요. 
양방향 매핑을 하면 편의 메서드 처럼 고려해야할 부분도 있고 엔티티간에 의존성도 가지게 되어서요.

2021-11-13 11:15 UTC, 5minho approved these changes
안녕하세요 성빈님!
피드백 반영 잘해주셨고요 👍
다음 단계도 화이팅입니다!!!!

2021-11-13 11:15 UTC, 5minho commented on src/main/java/qna/domain/Question.java
> +    public void addAnswer(Answer answer) {
메서드 접근제한자가 public 일 필요가 없을때는 default 로 해주는 것도 좋을거 같아요~

2021-11-13 11:15 UTC, 5minho commented on src/main/java/qna/domain/Answer.java
> +    public void setWriter(User writer) {
다음 단계에서 불필요한 getter, setter, 안쓰는 메서드를 지워보아요~

2021-11-13 11:15 UTC, merged

2021-11-15 16:12 UTC, mnonm commented on src/main/java/qna/domain/Answer.java
> +    public void setWriter(User writer) {
미사용 코드 제거하도록 하겠습니다!

2021-11-15 16:14 UTC, mnonm commented on src/main/java/qna/domain/Question.java
> +    public void addAnswer(Answer answer) {
습관적으로 public을 먼저 치게 되는거 같습니다.
default로 사용하고 다른 곳에서도 필요하면 점차 확대해가는 식으로 사용하겠습니다!