2단계 - 연관 관계 매핑
next-step/jwp-qna pull request #261
Opened 2021-11-12 13:10 UTC by keepbang

안녕하세요! 2단계 연관 관계 매핑 진행했습니다.

진행하면서 궁금한점이 있어서 질문 남깁니다!!

1. Question에 User가 ManyToOne으로 들어가있는데 User객체를 사용해서 데이터를 꺼내는것이 좀 더 객체지향적인 방법이라 생각했습니다. 그래서 findByUser를 추가해봤는데요 이런 Object형태로 데이터를 찾는 방법을 많이 사용하는 편인가요? 아니면 jpql이나 queryDsl같은걸로 객체에서 값을 꺼내 비교하는 방법을 사용하시나요?

2. 엔티티를 보다가 id나 created_date, updated_date가 중복된다는 느낌이 들었습니다. 그래서 따로 클래스를 만들어서 상속후 사용할려고 하는데 이때 setter를 여는것보다는 생성자를 추가해서 하는 방법이 더 괜찮은 방법일까요?

2021-11-13 12:55 UTC, kang-hyungu commented
>     1. Question에 User가 ManyToOne으로 들어가있는데 User객체를 사용해서 데이터를 꺼내는것이 좀 더 객체지향적인 방법이라 생각했습니다. 그래서 findByUser를 추가해봤는데요 이런 Object형태로 데이터를 찾는 방법을 많이 사용하는 편인가요? 아니면 jpql이나 queryDsl같은걸로 객체에서 값을 꺼내 비교하는 방법을 사용하시나요?

Question에서 연관 관계 매핑 해주신 것처럼 객체지향적으로 코드를 작성하려고 jpa를 쓰는거죠
다른 도메인 객체도 관계 매핑을 해주세요.

>     2. 엔티티를 보다가 id나 created_date, updated_date가 중복된다는 느낌이 들었습니다. 그래서 따로 클래스를 만들어서 상속후 사용할려고 하는데 이때 setter를 여는것보다는 생성자를 추가해서 하는 방법이 더 괜찮은 방법일까요?

DateTimeEntity 추가하신 것을 말씀하시는 걸까요?
세 필드는 값을 직접 적용하지 않아도 jpa에서 자동으로 처리해주죠. AuditingEntityListener 라던지...
필요하다면 생성자에서 파라미터로 전달받아서 셋팅해주기도 합니다.

2021-11-13 13:06 UTC, kang-hyungu requested changes
기병님
몇 가지 피드백 남겼습니다.
피드백 적용해보시고 도메인 객체의 테스트 코드도 추가해보시기 바랍니다.

2021-11-13 13:06 UTC, kang-hyungu commented on src/main/java/qna/answer/Answer.java
> +    public void setDeleted(final boolean deleted) {
setter는 제거해주시고 삭제용 메서드를 추가해주세요.

2021-11-13 13:06 UTC, kang-hyungu commented on src/main/java/qna/question/Question.java
> +    public void setDeleted(final boolean deleted) {
setter는 제거해주세요

2021-11-13 13:06 UTC, kang-hyungu commented on src/main/java/qna/service/QnaService.java
> +    public void deleteQuestion(User loginUser, Question question) throws CannotDeleteException {
객체지향적으로 작성하려면 어떻게 해야 할까요?
이 메서드에서 repository를 쓰는 부분만 제외하고 나머지 내용은 도메인 객체로 옮겨보세요.

2021-11-13 13:06 UTC, kang-hyungu commented on src/test/java/qna/ApplicationTest.java
> +@DataJpaTest
DataJpaTest로 바꾼 이유가 있을까요?

2021-11-13 13:06 UTC, kang-hyungu commented on src/test/java/qna/domain/AnswerRepositoryTest.java
> +    private AnswerRepository answerRepository;
AnswerRepository 외에 다른 repository는 없어도 문제 없겠네요

2021-11-14 04:53 UTC, keepbang commented on src/test/java/qna/ApplicationTest.java
> +@DataJpaTest
해당 테스트에서 테이블 생성 쿼리를 볼려고 변경했습니다... 다시 바꿔놓겠습니다!

2021-11-15 13:00 UTC, kang-hyungu approved these changes
기병님 피드백 반영하신 내용 확인했습니다.
추가 피드백 남긴 내용은 다음 미션 진행하면서 적용해주세요
pr은 머지 처리하겠습니다. 수고하셨습니다

2021-11-15 13:00 UTC, kang-hyungu commented on src/main/java/qna/action/NullCheckAction.java
> +public interface NullCheckAction {
이미 구현된 Objects.requireNonNull() 를 사용해도 되지 않을까요?

2021-11-15 13:00 UTC, kang-hyungu commented on src/main/java/qna/answer/Answer.java
> +    public void deleteAnswer() {
```suggestion
    public void delete() {
```
Answer 객체이니 메서드명에 반복해서 표시하지 않아도 되겠네요

2021-11-15 13:00 UTC, kang-hyungu commented on src/main/java/qna/common/QnaConst.java
> +    public static final int MIN_TEXT_LENGTH = 1;
상수로 길이 제한을 두는 방식보다 문자열이 비었는지 체크해주는 util을 추가해보면 어떨까요?
지금 이 클래스와 상수는 의존하는 곳이 너무 많고 QnaConst라서 QnA 관련 로직에서만 써야 할 것 같은 이름이네요

2021-11-15 13:00 UTC, kang-hyungu commented on src/main/java/qna/deletehistory/DeleteHistories.java
> +        return new DeleteHistories(answers.stream()
일급컬렉션인 Answers 클래스를 활용해보면 좋겠네요.

2021-11-15 13:00 UTC, merged

2021-11-15 13:12 UTC, keepbang commented on src/main/java/qna/action/NullCheckAction.java
> +public interface NullCheckAction {
이미 구현된 메서드 였군요.. 감사합니다!

2021-11-15 13:22 UTC, keepbang commented on src/main/java/qna/common/QnaConst.java
> +    public static final int MIN_TEXT_LENGTH = 1;
String에 isEmpty()를 사용하면 될거같습니다

2021-11-15 13:48 UTC, keepbang commented on src/main/java/qna/deletehistory/DeleteHistories.java
> +        return new DeleteHistories(answers.stream()
의견 감사합니다!

2021-11-15 14:18 UTC, keepbang commented on src/main/java/qna/action/NullCheckAction.java
> +public interface NullCheckAction {
Objects.requireNonNull() 메서드 내부를 확인해보니 NullPointerException이 발생되어서 각 도메인 내부에 getOrElseThrow라는 메서드를 만들어서 null처리를 했습니다😅

현재 회사에서는 NullPointerException을 발생시키는 것을 회피하고 다른 Exception을 발생시키는 방향으로 개발을 진행하고 있는데 다른 회사에서는 어떤식으로 null에대한 Exception처리를 하는지 궁금합니다ㅎㅎㅎ