Step2
next-step/jwp-qna pull request #265
Opened 2021-11-12 15:17 UTC by don-key

안녕하세요~! 광현님

이번 미션은 인텔리제이에서 Run all Tests가 안돼서 좀 헤맸네요 😢 

2단계 리뷰 요청드립니다!

2021-11-13 06:05 UTC, nokchax requested changes
안녕하세요, 동현님
연관 관계 매핑 진행하느라 고생하셨습니다 👍 
몇몇 코멘트 드렸는데, 확인후 재요청 부탁드립니다 :)
주말에도 파이팅입니다 💪

2021-11-13 06:05 UTC, nokchax commented on src/main/java/qna/domain/Answer.java
> +    private Question question;
Question 과 Answer 간의 관계에 대해서 한번 생각해 봐야할 것 같아요.
지금은 다대일 단방향 관계로 설정해 주셨는데요, 이러면서 Question 에서 Answer를 다루기 힘들게 됐습니다.

QnA 서비스를 생각해볼게요, 하나의 Answer에서 Question을 참조할 일이 많을까요?
아니면 하나의 Question에서 여러 Answer를 가져다 사용할 일이 많을까요?

Question과 Answer간의 관계뿐만 아니라 다른 엔티티 간의 관계도 한번 되돌아 볼 필요가 있을거 같아요.
목요일에 진행했던 JPA 수업에서 소개된 여러 관계에 대해 깊이 생각해보시고, 이 도메인 사이의 적절한 관계를 찾아보세요 :)

2021-11-13 06:05 UTC, nokchax commented on src/test/java/qna/domain/AnswerTest.java
> +    }
setUp과 테스트에 대해서 읽을 거리 공유해드릴게요 한번 읽어보세요 :)
https://jojoldu.tistory.com/611
https://blog.kingbbode.com/52

2021-11-13 14:55 UTC, don-key commented on src/main/java/qna/domain/Answer.java
> +    private Question question;
넵 엔티티 간의 관계 고민해보겠습니다~!!

2021-11-13 14:55 UTC, don-key commented on src/test/java/qna/domain/AnswerTest.java
> +    }
감사합니다!

2021-11-14 14:07 UTC, don-key commented on src/main/java/qna/domain/Answer.java
> +    private Question question;
Question과 Answer의 관계는 질문을 통해서 답변을 하기때문에 양방향 관계 설정을 적용하였고, Question에서 질문을 등록할 수 있게 연관관계 편의 메서드를 만들었습니다.

2021-11-14 14:08 UTC, don-key commented
안녕하세요~! 광현님

픽스처는 블로그를 읽고 적용을 해봤는데 맞는지 잘 모르겠네요 😢 
그리고 픽스처 네이밍 하실때 보통 어떻게 하는편인가요? (저는 향로님 블로그 참조해서 TestXXXFactory라는 클래스명으로 적용하였습니다.)

2021-11-15 08:55 UTC, nokchax approved these changes
안녕하세요, 동현님! 피드백 반영 잘 해주셨습니다 👍
추가적인 피드백도 남기긴했는데, 다음 단계에서 한번 고민해 보세요 :)
그럼 머지하겠습니다. 다음 단계 진행해주세요~!

2021-11-15 08:55 UTC, nokchax commented on src/main/java/qna/domain/Question.java
> +    private List<Answer> answers = new ArrayList<>();
일급 켤렉션이네요 한번 래핑해보는건 어떨까요?

2021-11-15 08:55 UTC, nokchax commented on src/main/java/qna/domain/Question.java
> +        }
answer.toQeustion(this); 만 하고
toQuestion 내부에서 위의 로직을 수행하는 방식이 좀 더 객체지향스럽지 않을까요?

2021-11-15 08:55 UTC, nokchax commented on src/test/java/qna/domain/TestAnswerFactory.java
> +public class TestAnswerFactory {
테스트 객체 팩토리 👍
질문 남겨주셨는데, 이전에는 ~Helper 혹은 TestFixture 와 같은 이름을 썼다가
최근에 위와 같은 ~Factory 로 바꿔서 사용하고 있습니다.

2021-11-15 08:55 UTC, nokchax commented on src/main/java/qna/domain/Answer.java
> +    private Question question;
Question과 Answer 양방향 관계를 설정해주셨는데, 특별한 이유가 있을까요?
Answer에서 Question을 참조할 일이 없다면 없애는게 좋을거 같아요, 양방향 연관관계는 단방향에 비해 신경쓸게 많아지거든요

2021-11-15 08:56 UTC, merged

2021-11-15 14:44 UTC, don-key commented on src/main/java/qna/domain/Answer.java
> +    private Question question;
FK를 생성해줄때 연관 관계 주인쪽에 ManyToOne 설정을 해줘야 하는 줄 알고 만들었었는데,
방금 테스트해보니 Question쪽에만 관계를 잡아줘도 생성이 되네요 😢 
피드백 주신 것 생각해보고 다음 미션에 반영하겠습니다~!

2021-11-15 14:44 UTC, don-key commented on src/main/java/qna/domain/Question.java
> +    private List<Answer> answers = new ArrayList<>();
넵 래핑해보겠습니다~

2021-11-15 14:47 UTC, don-key commented on src/main/java/qna/domain/Question.java
> +        }
넵ㅠ 잘 못된 곳에서 체크를 했네요 😢

2021-11-15 14:47 UTC, don-key commented on src/test/java/qna/domain/TestAnswerFactory.java
> +public class TestAnswerFactory {
넵 감사합니다~! 👍