2주차 Step2 - 연관 관계 매핑
next-step/jwp-qna pull request #282
Opened 2021-11-13 17:17 UTC by devsigner9920

안녕하세요!

연관 관계 매핑 해보았습니다.

영한님 책 보며 하나하나 차근차근 해보았습니다!

한가지 질문 사항이 있습니다!

설정 관련해서 ddl create-auto 옵션을 주었는데 테스트 시에 외래키 제약조건이 생성되어 있질 않아 처음에 외래키 조건을 드롭하는 프로세스가 돌아갈 때 내부적으로 계속 오류를 내더라구요.. 테스트 케이스 수행에 문제는 안되지만 찝찝해서 계속 찾아봤는데 해결을 못했습니다 ㅠ

혹시 해결 방법을 찾을 수 있을까요..?!

매번 리뷰 감사드립니다! 잘부탁드립니다!

2021-11-14 08:52 UTC, nokchax commented
```
설정 관련해서 ddl create-auto 옵션을 주었는데 테스트 시에 외래키 제약조건이 생성되어 있질 않아 
처음에 외래키 조건을 드롭하는 프로세스가 돌아갈 때 내부적으로 계속 오류를 내더라구요..
```
create-auto 는 실행시에 drop을 먼저 실행하기 때문에 error는 어쩔수 없는것 같습니다. 에러가 보기 싫으시다면 update를 사용해보세요

라고 남기고 제가 테스트좀 해봤는데 오류가 많이 나네요ㅠ
일단 연관관계 설정에서 JoinColumn 때문에 매 테스트시에 sql에러가 납니다.
제가 수정했던 과정을 공유해 드릴게요

0. src/main/resources/data/schema.sql 삭제

1. Question 수정
```java
  @OneToMany(fetch = FetchType.LAZY, cascade = CascadeType.ALL, mappedBy = "question")
  private final List<Answer> answers = new ArrayList<>();
```

2. User 내의 JoinColumn 어노테이션 모두 삭제
여기서 생성된 외래키 때문에 에러가 나더라구요

3. id autoincrement 초기화
이후에도 전체 테스트를 돌리면 에러가 나는데요, update로 변경하면서 db가 완전히 초기화 되지 않기 때문에 발생하는 문제입니다.
테스트 전반적으로 id를 사용한 조회가 많은데요, dirtycontext를 사용하여 초기화를 하더라도 autoincrement는 초기화 되지 않기 때문에
매 테스트가 끝난 후 초기화 하는 식으로 하시면 됩니다. (사실 id 값에 영향받지 않도록 테스트 하는게 좋은 방법 같습니다..)
```
// usertest내에 추가
  @BeforeEach
  void reset() {
      entityManager.createNativeQuery("ALTER TABLE `user` ALTER COLUMN `id` RESTART WITH 1")
              .executeUpdate();
  }
// questiontest내에 추가
  @BeforeEach
  void reset() {
    entityManager.createNativeQuery("ALTER TABLE `question` ALTER COLUMN `id` RESTART WITH 1")
            .executeUpdate();
  }
```

![image](https://user-images.githubusercontent.com/32362748/141674185-3f3387df-9c15-46e2-a0b4-119331851a10.png)

2021-11-14 09:06 UTC, nokchax requested changes
안녕하세요, 원준님
연관 관계매핑 진행 고생많으셨습니다 👏👏
질문주신 것과 코멘트 남겼는데요, 확인 후 재요청 부탁드립니닫 :)

2021-11-14 09:06 UTC, nokchax commented on src/main/java/qna/domain/Answer.java
> +  @Lob
👍

2021-11-14 09:06 UTC, nokchax commented on src/main/java/qna/domain/Question.java
> +  private Long id;
indent 4로 통일해 주세요 ㅠ

2021-11-14 09:06 UTC, nokchax commented on src/main/java/qna/domain/Question.java
> +  private final List<Answer> answers = new ArrayList<>();
`@JoinColumn` 과 `mappedBy` 에 대해서 찾아보세요 :)

2021-11-14 09:06 UTC, nokchax commented on src/main/java/qna/domain/User.java
> +  private final List<DeleteHistory> deleteHistories = new ArrayList<>();
전반적으로 양방향 연관관계 설정을 하셨는데요, 단방향에 비해 양방향은 신경쓸 것이 많아 진답니다.
현재 요구사항에서 양방향이 꼭 필요할까요?

2021-11-14 09:06 UTC, nokchax commented on src/test/java/qna/domain/QuestionTest.java
> +    q2 = QuestionFactory.create("test q2", "contents q2");
setup과 테스트에 대해서 한번 생각해보셨으면 해서 공유드려요
https://jojoldu.tistory.com/611
https://blog.kingbbode.com/52

2021-11-14 12:40 UTC, devsigner9920 commented on src/main/java/qna/domain/Question.java
> +  private Long id;
@nokchax 죄송합니다 ㅠ 컴퓨터를 바꾸면서 프로젝트 인덴트가 설정해둔게 초기화 됐나봐요! 다음엔 확실하게 확인하겠습니다!!

2021-11-14 13:08 UTC, devsigner9920 commented on src/test/java/qna/domain/QuestionTest.java
> +    q2 = QuestionFactory.create("test q2", "contents q2");
아하... setup에서 선언하기 보다는 테스트 케이스 내부에서 하는게 좀 더 직관적이고 공유할 일이 없어지는 것 같네요!

좋은 내용 감사합니다!! 적용 해보겠습니다 ㅎㅎ

2021-11-14 13:39 UTC, devsigner9920 commented on src/main/java/qna/domain/Question.java
> +  private final List<Answer> answers = new ArrayList<>();
넵 찾아서 학습 해보았습니다!! 좋네요 ㅎㅎ 연관관계 매핑 좀 더 알아가는 것 같습니다 ㅎ

2021-11-14 13:42 UTC, devsigner9920 commented on src/main/java/qna/domain/User.java
> +  private final List<DeleteHistory> deleteHistories = new ArrayList<>();
@nokchax 처음에 단방향 연관관계를 설정해보았는데요! 단순히 생각했을 땐 양방향으로 하면 User쪽에서 객체를 조회하는게 쉽지 않을까? 하는 의문으로 해보았습니다.

그런데 찾아보니 양방향 관계일 시 관리에 조금 더 신경을 써야하고, 무한 루프에 빠지지 않도록 조심해야하는 등 현재 단계에서 제가 신경 쓰지 못하는 점들이 많아 보입니다!

영한님 책을 보면서 조금 더 확실히 학습한 후에 필요한 경우에만 쓰도록 하겠습니다 !

2021-11-14 14:24 UTC, devsigner9920 commented
@nokchax 아하.. 질문한 내용에 대한 세심한 답변 감사합니다!!
JPA랑 조금 더 친해져서 오류 없이 테스트를 할 수 있게끔 노력해보겠습니다!
정말 퀄리티 높은 답변을 해주셔서 감동이에요 ㅎㅎ
피드백 항상 감사드립니다!

2021-11-15 09:14 UTC, nokchax requested changes
안녕하세요, 원준님! 피드백 반영하느라 고생하셨습니다. 👏👏 
몇가지 추가적으로 피드백 드린 부분이 있는데, 확인후 재요청 부탁드립니다 💪

2021-11-15 09:14 UTC, nokchax commented on src/main/java/qna/domain/DeleteHistory.java
>    private User deletedById;
User 타입이므로 필드명 deletedById가 어울리지 않게 되었네요 :)

2021-11-15 09:14 UTC, nokchax commented on src/main/java/qna/domain/Question.java
> -
Question 과 Answer 간의 관계에 대해서 한번 생각해 봐야할 것 같아요.
지금은 다대일 단방향 관계로 설정해 주셨는데요, 이러면서 Question 에서 Answer를 다루기 힘들게 됐습니다.

QnA 서비스를 생각해볼게요, 하나의 Answer에서 Question을 참조할 일이 많을까요?
아니면 하나의 Question에서 여러 Answer를 가져다 사용할 일이 많을까요?

Question과 Answer간의 관계뿐만 아니라 다른 엔티티 간의 관계도 한 번 되돌아 볼 필요가 있을거 같아요.
지난주 목요일에 진행했던 JPA 수업에서 소개된 여러 관계에 대해 깊이 생각해보시고, 도메인 간의 적절한 관계를 찾아보세요 :)

2021-11-15 09:14 UTC, nokchax commented on src/test/java/qna/domain/QuestionTest.java
> +    Question q2 = QuestionFactory.create("test q2", "contents q2");
이전 코멘트에도 남기긴 했지만, 보다 좋은 방식은 id값에 의존하지 않는 테스트를 짜는 거라고 봐요.
예를 들어볼게요 findById() 의 경우에
```java
...
questionRepository.save(q1);

Question question = questionRepository.findById(1L).orElse(null);
...
```
처럼 `Question question = questionRepository.findById(1L).orElse(null);` 1L을 사용하셨는데, 대신에
```java
...
savedQuestion = questionRepository.save(q1);

Question question = questionRepository.findById(savedQuestion.getId()).orElse(null);
...
```
`savedQuestion.getId()` 처럼 테스트를 수정하면, 그러면 매번 id값을 1로 초기화 할 필요도 없어지겠죠 :)

2021-11-15 09:40 UTC, devsigner9920 commented on src/main/java/qna/domain/DeleteHistory.java
>    private User deletedById;
아하 넵 deletedByUser로 해주는게 더 알맞는 명명 규칙이군요! 세세한 디테일 신경 쓰겠습니다

2021-11-15 09:41 UTC, devsigner9920 commented on src/test/java/qna/domain/QuestionTest.java
> +    Question q2 = QuestionFactory.create("test q2", "contents q2");
앗 그래도 조금 더 확실하게 배워서 좋습니다!!! 감사합니다 테스트 케이스 그래도 한번 더 반영 해보겠습니다! ㅎㅎ

2021-11-15 09:44 UTC, devsigner9920 commented on src/main/java/qna/domain/Question.java
> -
아하 넵 알겠습니다 수업 다시 복습하고 완전히 슥듭하겠습니다! 그러네요.. 단순히 외래키 생성되는 곳을 주인격으로 생각하지 않고 조금 더 실 사용에서의 관계를 초점에 두고 해보겠습니다! 감사합니다 ㅎㅎ

2021-11-16 07:21 UTC, nokchax approved these changes
안녕하세요, 원준님 피드백 반영 고생하셨습니다. 👍 
머지할게요 다음 단계 진행해주세요 :)

2021-11-16 07:21 UTC, merged