Step3 - 질문 삭제하기 리팩터링
next-step/jwp-qna pull request #311
Opened 2021-11-15 15:58 UTC by tbvjdudfhr

안녕하세요 리뷰어님

리뷰 잘 부탁드려요~

2021-11-16 13:44 UTC, 5minho requested changes
안녕하세요 영록님
3단계 미션까지 진행하시느라 고생많으셨습니다
개선해보면 좋을거 같은 것들 코멘트로 남겼습니다.
확인해주시면 감사하겠습니다.

2021-11-16 13:44 UTC, 5minho commented on src/test/java/qna/service/QnaServiceTest.java
>          question.addAnswer(answer);
Answer 를 생성할때 이미 question 을 넘기는데 `question.addAnswer(answer)` 메서드를 또 호출해야 할까요?
Answer 의 생성자 내에서 연관관계를 모두 매핑후 addAnswer 같은 메서드는 외부로 노출 안하는게 좋지 않을까요?

2021-11-16 13:44 UTC, 5minho commented on src/test/java/qna/domain/AnswersTest.java
> +}
파일 끝은 새로운 라인으로 끝나게 해주세요.
https://minz.dev/19

2021-11-16 13:44 UTC, 5minho commented on src/main/java/qna/domain/Answers.java
> +            answer.setDeleted(true);
setter 를 사용하는 대신에 delete 같은 메서드를 만들어서 사용해보는건 어떨까요

2021-11-16 13:44 UTC, 5minho commented on src/main/java/qna/domain/Question.java
> +    public void delete(User user) {
질문 삭제시 삭제 히스토리가 남는다는 요구사항인데요.
제 생각엔 delete 메서드에서 삭제 히스토리를 반환해주면 질문 삭제 요구사항에 대한 더 안전한 코드를 작성할 수 있을거 같은데 어떻게 생각하시나요?

2021-11-16 13:44 UTC, 5minho commented on src/main/java/qna/domain/Question.java
> +        answers.delete();
Answer 의 writer 에 대한 권한 체크는 answer 의 삭제 시점에 하는게 좋지 않을까요?

2021-11-16 13:44 UTC, 5minho commented on src/main/java/qna/domain/User.java
> +        return Objects.equals(id, user.id) && Objects.equals(userId, user.userId) && Objects.equals(password, user.password) && Objects.equals(name, user.name) && Objects.equals(email, user.email);
엔티티의 모든 프로퍼티를 비교해야 할까요? 식별자만 비교해도 되지 않을까요?

2021-11-16 13:44 UTC, 5minho commented on src/test/java/qna/domain/AnswersTest.java
> +    @DisplayName("답변자와 삭제하는 유저가 다른 경우 테스트")
`답변자가 아닌 유저는 답변을 삭제할 수 없다`
이런 DisplayName 이면 테스트만 보고 요구사항을 더 잘 파악할 수 있지 않을까요?

2021-11-16 13:44 UTC, 5minho commented on src/test/java/qna/domain/QuestionTest.java
> +public class QuestionTest {
* 질문을 삭제할때 답변도 삭제해야 된다.
* 다른 사람이 쓴 답변이 있으면 삭제할 수 없다.
* 질문 삭제시 삭제 히스토리가 남아야 한다.
* 답변이 없는 경우 삭제 가능하다.
* 질문자와 답변의 모든 답변자가 같으면 삭제 가능하다.

이런 중요한 요구사항들을 단위테스트를 통해 테스트 해보셨으면 좋겠습니다.

2021-11-16 13:44 UTC, 5minho commented on src/main/java/qna/domain/Answers.java
> +    public Answers(List<Answer> answers) {
프로젝트 전체적으로 불필요한 getter / setter / 생성자 들을 삭제해주시면 좋을거 같습니다.
영록님이 이직하셔서 프로젝트 pull 을 받았는데 여기저기 안쓰는 메서드들이 있는 것보다는 사용하는 코드들만 있는게 더 좋겠죠?

2021-11-16 15:53 UTC, tbvjdudfhr commented
피드백 감사합니다. 

반영해서 다시 보냅니다~

2021-11-16 16:17 UTC, 5minho requested changes
영록님 피드백 반영을 빠르게 해주셨네요!
추가로 더 알아가셨으면 하는 부분이 있어서 코멘트 남겼어요.
한번 만 더 수정 부탁드립니다~

2021-11-16 16:17 UTC, 5minho commented on src/main/java/qna/domain/Answer.java
> +    }
public 으로 열려있어 아무나 삭제 가능하네요 권한 체크를 해줘야 하지 않을까요?
그리고 질문이 삭제되면 삭제내역이 생기는 것처럼 답변도 삭제되면 삭제내역이 생기는게 좋지 않을까요?

2021-11-16 16:17 UTC, 5minho commented on src/test/java/qna/domain/QuestionTest.java
> +
피드백 반영을 잘해주셨네요 👍

마지막으로 `질문을 삭제한 시각과 삭제내역에 남는 시각은 같아야 한다` 라는 요구사항의 테스트코드도 한번 작성 해주셨으면해요.
테스트 짜기쉬운 코드를 짜는 테크닉을 얻어가실 수 있을거에요!

2021-11-18 13:20 UTC, 5minho approved these changes
안녕하세요 영록님
JPA 미션하느라 고생 많으셨고요.
마지막까지 화이팅입니다!

2021-11-18 13:20 UTC, 5minho commented on src/main/java/qna/domain/User.java
> +        return Objects.hash(id, userId, password, name, email);
equals 메서드 수정시에 hashcode 메서드도 같이 수정해야 하지 않을까요?

2021-11-18 13:20 UTC, 5minho commented on src/main/java/qna/domain/Answer.java
> +    public void setQuestion(Question question) {
접근 제한자를 디폴트로 해서 패키지 내에서만 접근 가능하게 하면 더 안전할 거 같습니다

2021-11-18 13:20 UTC, 5minho commented on src/main/java/qna/domain/Answers.java
> +        validateAnswer(writer);
Answer 의 delete 에서 권한체크를 하고 있어서 이 라인은 필요 없을거 같네요

2021-11-18 13:20 UTC, merged