2단계 - 연관 관계 매핑
next-step/jwp-qna pull request #316
Opened 2021-11-16 02:39 UTC by smpark1020

안녕하세요 경준님😀
2단계 리뷰도 잘 부탁드립니다!
1단계 피드백 내용도 수정하였습니다!

```
refactor: isOwner 메서드 코드 수정
```
* 참고로 해당 커밋은 리팩토링 하는 과정에서 기존 코드가 변경 되어 다시 원상복구한 커밋입니다. 다음 미션에서 사용될 것 같은데 User 객체에 메시지를 전달하는 방법으로 개선할 필요가 있을 것 같아 체크해두겠습니다!

2021-11-16 11:42 UTC, slamdunk7575 requested changes
연관관계 매핑 잘해주셨네요.
몇가지 고민해보면 좋을 부분에 피드백 남겨드렸습니다.
확인해보시고 리뷰요청 부탁드려요~ 끝까지 화이팅 입니다! 💪

2021-11-16 11:42 UTC, slamdunk7575 commented on src/main/java/qna/domain/Answer.java
> +    private Question question;
JPA를 배제하고 서비스의 흐름으로 봤을때
일반적으로 `질문(Question)`이 먼저 생성되고 `답변(Answer)`이 생성되는 순서가 될 것 같은데요.
`Answer`가 cascade를 통해 `Question`의 라이프 사이클을 관리하는 부분은 제거하는게 좋을 것 같아요.

2021-11-16 11:42 UTC, slamdunk7575 commented on src/main/java/qna/domain/Answer.java
> +    private User writer;
`CascadeType.ALL`을 주면 Answer 삭제시 User가 삭제될 것 같은데요. 
다른 옵션 값에 대해서 고민해보시면 좋을 것 같아요.

`cascade` 설정은 부모 엔티티를 영속 상태로 만들때 연관된 자식 엔티티도 함께 영속 상태로 만들고 싶을때 사용합니다.
객체들의 라이프 사이클이 같이 움직이는지 고민해보시면 좋겠네요. 

[영속성 전이(CASCADE)와 고아 객체](https://sun-22.tistory.com/73)

2021-11-16 11:42 UTC, slamdunk7575 commented on src/main/java/qna/domain/Question.java
> +    private User writer;
`@OneToOne`으로 연관관계를 맺어주신 이유가 있으신가요?
`User` 한명이 여러개의 `Question`을 만들 수 있을 것 같은데요.

2021-11-16 11:42 UTC, slamdunk7575 commented on src/main/java/qna/domain/Answer.java
>          this.contents = contents;
`question의 answers` 에도 `answer` 를 추가해줘야 할 것 같은데요.
양방향 연관관계는 양쪽 객체 모두 신경써야하는 부분이 있습니다.

2021-11-16 11:42 UTC, slamdunk7575 commented on src/test/java/qna/domain/AnswerTest.java
> +    }
지난 피드백 잊지않고 반영해보셨네요 👍

2021-11-17 01:18 UTC, smpark1020 commented on src/main/java/qna/domain/Answer.java
> +    private Question question;
네 수정하겠습니다.

2021-11-17 01:19 UTC, smpark1020 commented on src/main/java/qna/domain/Answer.java
> +    private User writer;
영속성 전이(CASCADE)에 대해 제대로 이해하지 못한 상태였는데 피드백 덕분에 정확하게 이해하게 되었습니다.
내용 수정하겠습니다!

2021-11-17 01:19 UTC, smpark1020 commented on src/main/java/qna/domain/Question.java
> +    private User writer;
다른 연관관계도 다시 한번 검토 후 수정하겠습니다.

2021-11-17 01:20 UTC, smpark1020 commented on src/test/java/qna/domain/AnswerTest.java
> +    }
넵ㅎㅎ훨씬 가독성이 좋아진 것 같습니다ㅎㅎ

2021-11-17 01:26 UTC, smpark1020 commented
안녕하세요 경준님!
피드백 내용 수정했습니다.
연관 관계 매핑, 영속성 전이, 고아 객체에 대해 제대로 이해할 수 있었습니다.

그럼 리뷰 잘 부탁드립니다😀

2021-11-17 10:38 UTC, slamdunk7575 approved these changes
피드백 반영 잘해주셨네요.
소소한 코멘트 남겨드렸는데 다음 단계에서 확인해보시면 좋겠어요.
끝까지 화이팅 입니다~!

2021-11-17 10:38 UTC, slamdunk7575 commented on src/main/java/qna/domain/Question.java
>      }
객체의 상태를 외부에서 변경하도록 드러내는 `set-` 이라는 네이밍 보다는
`예:writerBy()` 라는 이름을 주어 객체에게 메시지를 보내 처리되도록 나타내면 좋겠네요.

2021-11-17 10:38 UTC, slamdunk7575 commented on src/test/java/qna/domain/QuestionTest.java
> +    void 주어진_ID에_해당하는_삭제되지_않은_질문을_리턴한다() {
다음 단계인 `질문 삭제하기 리팩토링`을 진행하다보면 Service 의 비지니스 로직들이 각 Domain 으로 이동을 하게 될텐데요.
예를들어, 현재 `QuestionTest`를 `QuestionRepositoryTest` 로 바꾸고 `Question 도메인에 대한 테스트`를 
별도로 만들어 보면 좋을 것 같습니다. 리팩토링 해보시면서 고민해보시면 좋겠어요.

크게 중요한 부분은 아니지만, 테스트에 대한 설명을 위해 주로 `@DisplayName` 을 사용하거나 `메소드명을 한글`로 작성하는데요.
메소드 명에 한글을 사용하면 아무래도 IDE 호환도 좋지 않고 해서 저는 주로 `@DisplayName`을 선호하고 있습니다.
`@DisplayName` 으로 설명을 작성했다면 메소드 명은 꼭 한글로 작성하지 않으셔도 좋습니다 😄

2021-11-17 10:38 UTC, merged

2021-11-18 00:20 UTC, smpark1020 commented on src/main/java/qna/domain/Question.java
>      }
네 수정하겠습니다!

2021-11-18 00:21 UTC, smpark1020 commented on src/test/java/qna/domain/QuestionTest.java
> +    void 주어진_ID에_해당하는_삭제되지_않은_질문을_리턴한다() {
넵 다음 미션에 적용하도로 하겠습니다!