[2주차 1단계]  엔티티 매핑
next-step/jwp-qna pull request #33
Opened 2021-05-29 07:30 UTC by AppleMango2021

리뷰어님 안녕하세요! 
우아한테크캠프 Pro 2기 수강생 이지선입니다.

현업에서 JPA를 사용하지 않아 테스트를 어떻게 작성해야 할지 고민이 많았습니다. 
보시다가 의아한 부분이 있으시면 언제든지 피드백 주시면 감사하겠습니다. 
그리고 테스트를 진행하다가 궁금한 부분은 코멘트 달았으니 코멘트도 확인부탁드리겠습니다!

2021-05-29 07:35 UTC, AppleMango2021 commented on src/main/java/qna/domain/Answer.java
> +
createdAt의 경우에는 객체 생성시 LocalDateTime.now()를 이용하여 값을 집어넣어줄 수 있는데, updateAt의 경우에는 현업에서 어떻게 처리하는지 궁금합니다. 
저는 테스트 코드에서  setContents()를 이용하여 updatedAt 필드가 채워지는지 확인하기 때문에, setContents() 메소드에만 아래 로직을 추가하였는데, 만약 객체에서 변경가능한 필드가 많다면 매번 setXXX() 메소드에 아래 로직을 추가하는 것이 비효율적으로 느껴집니다. 그리고 보통 setter의 사용을 권장하지도 않는 걸로 알고 있구요! 
```code
this.updatedAt = LocalDateTime.now();
```

2021-05-29 07:38 UTC, AppleMango2021 commented on src/test/java/qna/domain/AnswerRepositoryTest.java
> +    }
RepositoryTest의 범위가 어디까지인지가 궁금합니다. 예를 들어, 저장 후 id의 값이 채워지는지 여부는, 아무래도 Repository가 DB와의 소통(?)을 담당하기 때문에 RepositoryTest의 영역이 맞다고 생각합니다. 하지만 createdAt()나 updatedAt()는 도메인 클래스에서 로직을 넣어주기 때문에 이 부분까지도 RepositoryTest에서 수행하는 것이 맞나 궁금합니다.

2021-05-29 09:05 UTC, AppleMango2021 commented on src/test/java/qna/domain/UserRepositoryTest.java
> +        System.out.println("BEFORE EACH의 expected = "+expected.toString());
System.out.println 구문은 아래 질문 드리기 위해 추가한 코드입니다. 차후에 삭제할 예정입니다.

2021-05-29 09:06 UTC, AppleMango2021 commented on src/test/java/qna/domain/UserRepositoryTest.java
> +}
이해가 잘 안 되지만, 해당 테스트 코드가 살아있으면 제가 이상하다고 느낀 부분이 재현이 되지 않아 우선 주석처리 해 두었습니다.

2021-05-29 09:31 UTC, AppleMango2021 commented on src/test/java/qna/domain/UserRepositoryTest.java
> +//        assertThatThrownBy(() -> userRepository.save(newUser)).isInstanceOf(DataIntegrityViolationException.class);
해당 테스트 코드를 수행할 때 이해가 가지 않는 부분이 생겨 질문 드립니다 ㅠㅠ

1. UserRepositoryTest를 실행했을 때 (즉, 모든 테스트 메소드가 실행됨)

- 29번 라인에 System.out.println 구문을 추가하였기에, BeforeEach를 수행할 때마다 save()된 데이터의 정보가 출력이 됩니다. 모든 테스트 메소드를 실행하면 신기하게도 check_unique_constraints 메소드가 항상 3번째로 수행됩니다. (테스트 메소드 실행 순서는 랜덤이라고 알고 있었는데, 아닌가봅니다!) 
- 그래서인지 이때 expected 객체의 id는 3번입니다. UserTest.JAVAJIGI를 선언할 때 id값이 '1L'로 고정이 되어 있지만, 영속성 컨텍스트에서 DB로부터 auto incremented된 id값을 가져와서 반영하는 것 같습니다. (하지만 이 부분도 확실하지는 않아서 틀렸다면 코멘트 부탁드립니다! )
- 그런데 `newUser` 객체의 id를 '3L'로 주고 저장을 하였더니 exception이 발생하지 않고 문제 없이 수행되고 있습니다. 
![image](https://user-images.githubusercontent.com/29113357/120064759-e5f4da80-c0a8-11eb-9da2-6b95c1e49136.png)


2. 해당 메소드만 실행했을 때
- 캡처화면과 같이 @BeforeEach에서 출력된 `expected`의 id값은 1이고, 해당 테스트 메소드를 수행했을 때는 두 번쨰 캡쳐화면과 같은 에러 메세지가 발생합니다. 
![image](https://user-images.githubusercontent.com/29113357/120065286-6b798a00-c0ab-11eb-8cdf-d8e645e609a6.png)

![image](https://user-images.githubusercontent.com/29113357/120065304-906dfd00-c0ab-11eb-9a4f-3ef0d83326c6.png)




이런 상황이 발생하는 이유는,  save()메소드를 수행할 때 저장하려는 `newUser` 객체의 id가 영속성 컨텍스트에 있는 `expected`의 id와 동일한 경우에는  새로운 객체를 저장하지 않고 기존 데이터를 업데이트한다고 이해하면 되는 걸까요ㅠㅠ?

질문이 조금 길어졌는데 혹시 이해가 안가는 부분이 있으시다면 언제든지 코멘트나 DM 부탁드립니다!

2021-05-29 13:38 UTC, wheejuni requested changes
수고 많으셨습니다. 👍 💯 
코드상에 수정을 요하는 부분은 크게 보이지 않았습니다. 질문해주신 부분에 답변을 하나하나 남겨놓았는데요, 
답변을 보시면서 수정하시고 싶은 부분이 있을 것 같아 바로 머지하지 않고 한번 request change 하겠습니다.

추가 질문이 있다면 남겨주시고요. 감사합니다. 💯

2021-05-29 13:38 UTC, wheejuni commented on src/main/java/qna/domain/Answer.java
> +
@AppleMango2021 좋은 질문 주셨네요. 👍 
사실 현업에서도 부서마다 차이가 있고 여러 컨벤션이 있어서 딱 이렇다 라고 말씀드리기 어려운데요...
저같은 경우엔 [Auditing](https://www.baeldung.com/database-auditing-jpa) 이라는 기능을 선호합니다.

사실 이것은 JPA뿐만 아니라 종류를 불문하고 OR Mapper나 Query Template이라면 다 갖는 문제인데요, 성숙한 라이브러리라면 다 나름대로 해결책을 갖고 있습니다. iBATIS, MyBatis같은 경우엔 [Interceptor](https://fascinate-zsoo.tistory.com/12)를 사용하기도 합니다.

2021-05-29 13:38 UTC, wheejuni commented on src/test/java/qna/domain/AnswerRepositoryTest.java
> +    }
@AppleMango2021 말씀처럼 도메인 엔티티가 담고 있는 "상태" 에 관한 테스트는 이곳에서 수행하면 안된다는 생각이고요.
다만 지금 엔티티가 테스트하기 좋은 구조인지는 좀 다시 생각해봐야 할 필요가 있습니다. 메소드 안에서 `LocalDateTime.now()` 가 호출되어서 굉장히 테스트가 어려운 구조이기는 하고요, 이 부분에 대한 테스트는 어쩌면 JDK가 제공하는 클래스인 `LocalDateTime` 에 관한 테스트일 수 있어서 꼭 테스트가 이뤄져야 하는 영역인지도 확신이 잘 안 들기는 합니다.

2021-05-29 13:38 UTC, wheejuni commented on src/test/java/qna/domain/UserRepositoryTest.java
> +//        assertThatThrownBy(() -> userRepository.save(newUser)).isInstanceOf(DataIntegrityViolationException.class);
원인 파악을 잘 하신 것 같습니다. PKEY에 해당하는 필드에 임의로 값을 부여하시는 것은 그렇게 바람직한 방법은 아닙니다. 
테스트 케이스 상호간에 의존관계가 발생하면 안되는데요, https://junit.org/junit5/docs/5.0.1/api/org/junit/jupiter/api/AfterEach.html 이 링크 참고하셔서 테스트 컨텍스트를 매번 초기화하는 방법도 생각해볼만 합니다.

2021-05-29 15:50 UTC, AppleMango2021 commented on src/main/java/qna/domain/Answer.java
> +
링크 걸어주신 [Auditing](https://www.baeldung.com/database-auditing-jpa)을 바탕으로 PrePersist/PreUpdate 어노테이션을 이용하여서 로그를 남기는 작업을 할까 고민하다가, lifecycle callback method는 연관관계가 없는 entity에서만 호출하라는 권고를 보고 다른 방법을 찾았습니다. 

Auditing 키워드를 바탕으로 구글링해보니 말씀하신 것처럼 좋은 해결책이 있어 이 [링크](https://velog.io/@conatuseus/2019-12-06-2212-%EC%9E%91%EC%84%B1%EB%90%A8-1sk3u75zo9)를 참고하여 구현하였습니다.  감사합니다!

2021-05-29 15:58 UTC, AppleMango2021 commented on src/test/java/qna/domain/AnswerRepositoryTest.java
> +    }
일단은 JPA Auditing 기능을 사용하면서 Setter에서 직접 updatedAt 필드값을 설정하는 로직은 제거할 수 있게 되었습니다.  그리고 혹시

> 말씀처럼 도메인 엔티티가 담고 있는 "상태" 에 관한 테스트는 이곳에서 수행하면 안된다는 생각이고요.

이 말씀은 updatedAt의 값을 createdAt과 LocalDataTime.now()과 직접 비교하는 테스트는 지양하자는 뜻으로 이해하면 될까요? 현재는 JPA Auditing 기능을 통해 엔티티 필드 값이 업데이트될 경우에 자동으로 updatedAt 값을 넣어주고 있기 때문에, updatedAt이 NotNull인지 테스트하는 정도로 수정하였는데, 혹시 NotNull 여부 체크도 말씀하신 상태에 대한 테스트에 해당할지 궁금합니다!

2021-05-29 16:05 UTC, AppleMango2021 commented on src/test/java/qna/domain/UserRepositoryTest.java
> +//        assertThatThrownBy(() -> userRepository.save(newUser)).isInstanceOf(DataIntegrityViolationException.class);
넵 말씀하신 것처럼 PK에 해당하는 필드에 값을 직접적으로 부여하는 것은 바람직한 방법이 아니라 생각하여, `newUser`에서 키값을 제거하였습니다. 

 공유해주신 링크를 바탕으로 이런저런 테스트를 더 해보았는데, 결과적으로는 save() 메소드의 특성 때문에 제가 직접 '3L'이라는 [키값을 넣는 이상 어떻게 해도 save가 update처럼 작동](https://stackoverflow.com/a/52576978)하는 것 같습니다. 생각해보니 수업 시간에 제이슨 강사님께서 SimpleJpaRepository 클래스의 save 메소드 코드를 직접 보여주시까지 했는데 제가 제대로 이해 못하고 넘어갔었나 봅니다 ㅎㅎ

감사합니다!

2021-05-29 16:07 UTC, AppleMango2021 commented
휘준님 안녕하세요. 피드백 재요청드립니다!
코멘트에 남겨주신 여러 키워드 덕분에 영속성 컨텍스트의 개념에 대해서 조금 더 공부할 수 있는 기회가 되었습니다. 감사합니다.

2021-05-30 00:18 UTC, wheejuni commented on src/main/java/qna/domain/Answer.java
> +
@AppleMango2021 사실 auditing 적용이 이번 미션의 범위는 아닙니다만, 잘 찾아서 시도하셨습니다!

2021-05-30 00:20 UTC, wheejuni commented on src/test/java/qna/domain/AnswerRepositoryTest.java
> +    }
@AppleMango2021 Notnull 정도로 충분하다고 생각합니다. 타임스탬프성 필드와 같이 변동성이 객체 내부에 있고, 멱등성이 확보되지 않는 상태값들은 사실 테스트하기가 굉장히 어렵습니다. 그리고 많은 경우에 테스트하지 않아도 될 영역이기도 하고요.

Notnull 키워드를 활용해서 어느정도 회피하면서도 테스트의 목적을 달성한 시도가 좋아 보입니다.

2021-05-30 00:23 UTC, wheejuni approved these changes
질문에 대한 답변이 충분히 되셨는지 모르겠습니다. ㅎㅎ
2단계에서 해야 할 학습은 충분히 이뤄진 것 같아 머지하겠습니다.
3단계로 넘어가주세요~

2021-05-30 00:23 UTC, merged

2021-05-30 00:24 UTC, wheejuni commented
아...1단계를 2단계로 착각한 것이니 못본 척 해주세요 ㅋㅋ ㅠㅠ