Step3 - 질문삭제하기 리뷰 요청드립니다
next-step/jwp-qna pull request #335
Opened 2021-11-17 15:14 UTC by chaeyun17

안녕하세요! 수강생 이채윤입니다.

3단계 질문삭제하기 리뷰 요청드립니다.

감사합니다!

2021-11-19 09:47 UTC, jaeyeonling requested changes
질문 삭제하기 리팩터링을 잘 구현해주셨어요 👍 
코멘트 남겨두었으니 확인 부탁드릴게요!

2021-11-19 09:47 UTC, jaeyeonling commented on src/main/java/qna/domain/Answer.java
> +	public DeleteHistory delete() {
상대적으로 우선순위가 낮은 equals, hashcode를 맨 아래에 위치시켜주세요!

2021-11-19 09:47 UTC, jaeyeonling commented on src/main/java/qna/domain/Answers.java
> +	private final List<Answer> answerList;
List와 같은 자료형을 변수명으로 쓰면 어떠한 문제가 있을지 고민해보아요

2021-11-19 09:47 UTC, jaeyeonling commented on src/main/java/qna/domain/Answers.java
> +		this.answerList = new ArrayList<>();
```suggestion
		this(new ArrayList<>());
```

인스턴스 변수의 초기화는 주 생성자를 정하여 하나의 생성자에서 해주는 것이 좋은데, 왜 그럴지 고민해보아요 ㅎㅎ

2021-11-19 09:47 UTC, jaeyeonling commented on src/main/java/qna/domain/Answers.java
> +		return DeleteHistories.of(list);
```suggestion
                return answerList.stream()
                                .collect(collectingAndThen(toList(), DeleteHistories::of));
```

와 같은 마무리 연산자도 제공하니 활용해볼 수 있을 것 같아요!

2021-11-19 09:47 UTC, jaeyeonling commented on src/main/java/qna/domain/Deleted.java
> +public class Deleted {
해당 클래스는 객체로 분리하여 얻을 수 있는 이점이 보이지 않는데, 분리해주신 이유가 있을까요?

2021-11-19 09:47 UTC, jaeyeonling commented on src/main/java/qna/domain/Password.java
> +			throw new IllegalArgumentException("길이 20 이하여야 합니다");
```suggestion
			throw new IllegalArgumentException("길이 " + MAX_LENGTH  + " 이하여야 합니다");
```

예외처리 메시지에 상수를 사용한다면 조건이 변경 됐을 때 예외처리 메시지를 신경쓰지 않아도 될 것 같네요 ㅎㅎ

2021-11-19 09:47 UTC, jaeyeonling commented on src/main/java/qna/domain/Answers.java
> +	public boolean isAllSameWriter(User user) {
삭제와 검증에 대한 부분을 분리한다면 클라이언트에서 해당 검증을 하지 않으면 의도하지 않게 동작할 수 있을 것 같습니다!
삭제 시점에 해당 검증을 해보면 어떨까요?

2021-11-19 11:22 UTC, chaeyun17 commented on src/main/java/qna/domain/Answers.java
> +	private final List<Answer> answerList;
네 answers 클래스와 똑같으면 안될 것 같아서 list로 변수명을 했는데 데이터타입 명시대신 다른 변수를 생각해보야겠네요!

2021-11-19 11:24 UTC, chaeyun17 commented on src/main/java/qna/domain/Answers.java
> +		this.answerList = new ArrayList<>();
아하 네! 하나의 생성자에서 하는 것이 변경에 더 유연할 것 같네요. 한 곳만 변경하면 되니.

2021-11-19 11:24 UTC, chaeyun17 commented on src/main/java/qna/domain/Answers.java
> +		return DeleteHistories.of(list);
마무리 연산자도 제공하는군요! 감사합니다!

2021-11-19 11:26 UTC, chaeyun17 commented on src/main/java/qna/domain/Deleted.java
> +public class Deleted {
그러네요. 우선 미션에 primitive 타입을 최대한 감싸보기로 해서 기계적으로 리팩토링을 했네요. 다음엔 역할이 있는 지 먼저 생각하고 객체로 분리해보겠습니다!

2021-11-19 11:26 UTC, chaeyun17 commented on src/main/java/qna/domain/Password.java
> +			throw new IllegalArgumentException("길이 20 이하여야 합니다");
에러메시지도 잘 챙겨보겠습니다

2021-11-19 11:27 UTC, chaeyun17 commented on src/main/java/qna/domain/Answers.java
> +	public boolean isAllSameWriter(User user) {
아하.. 그러네요. 삭제하려면 검증을 무조건하도록 했어야 됬네요. 감사합니다.

2021-11-20 05:01 UTC, jaeyeonling approved these changes
마지막까지 미션 잘 진행해주셨습니다 👍 
수 많은 코멘트 반영하시느라 고생 많으셨어요 😄 
해당 요청은 머지하도록 하겠습니다 다음 미션도 화이팅입니다!!

2021-11-20 05:01 UTC, merged