Step3 : 질문 삭제하기 리팩터링
next-step/jwp-qna pull request #345
Opened 2021-11-19 19:10 UTC by codeleesh

안녕하세요 리뷰어님!

질문 삭제하기 리팩터링 리뷰 요청드립니다! 

3단계를 진행하면서 집중한 부분은 테스트 코드 작성을 하면서 픽스쳐를 활용하여서
가독성을 높여보려고 했는데, 중복코드가 많아진 느낌도 들었습니다.

그리고 한 가지 여쭤보고 싶은 부분이 있는데요, 소스상에서 객체의 null 체크를 위해서 nonNull을 사용하였는데요.

`if (Objects.nonNull(this.question)) `

`This method exists to be used as a java.util.function.Predicate, filter(Objects::nonNull)`

nonNull의 API 설명을 보면 지금 사용하고 있는 목적과는 좀 다른거 같아서요. 실제 현업에서 사용하실때는 어떤지 궁금합니다.

이번 리뷰도 잘 부탁드립니다. 감사합니다.

2021-11-20 13:15 UTC, 5minho requested changes
안녕하세요 상호님!
3단계 정말 잘해주셨네요!
코드 가독성도 좋고 테스트도 꼼꼼하게 해주셔서 좋았습니다!
개선했으면 좋겠는 부분 코멘트 달았는데요
확인해주시면 감사하겠습니다!

2021-11-20 13:15 UTC, 5minho commented on src/main/java/qna/domain/Answer.java
> +        this.setDeleted(true);
`setDeleted` 가 현재 public 으로 열려있네요.
private 로 바꾸어서 `Answer` 만 접근 가능하게 하는건 어떨까요?

2021-11-20 13:15 UTC, 5minho commented on src/main/java/qna/domain/Question.java
> +        if( this.getAnswers().existAnswer() ) {
Question.answers 가 null 인 가능성이 있을거 같아요.
생성시점에 answers 에 디폴트 값을 넣어줘서 Null 일 가능성을 없애는건 어떨까요?

2021-11-20 13:15 UTC, 5minho commented on src/main/java/qna/domain/Question.java
> +        this.setDeleted(true);
이 setter 도 접근제한자를 private 으로 바꾸는게 좋지 않을까요?

2021-11-20 13:15 UTC, 5minho commented on src/test/java/qna/domain/QuestionTest.java
> +        final Question question = 질문자_모든답변자_일치("questionWriter");
`질문자_모든답변자_일치("questionWriter")` 라는 테스트는 가독성을 위해 만드신 것인가요? 좋은시도라고 생각해요! 👍
하지만 코드를 읽는 입장에서 이 테스트를 위해 어떤 객체들이 연관되어 있는지 한눈에 파악이 어려웠어요.

개인적으로는 객체들의 팩토리 메서드만 사용해서 해당 테스트가 어떤 객체들을 사용하는지 given 단락에 명시하는게 테스트를 파악하는데 좋다고 생각해요. 
예를들면 이런식으로요.

```
@Test
@DisplayName("질문자가 질문 삭제 시 모든 답변자가 질문자와 같다면 삭제할 수 있다")
void deleteQuestion_정상_질문자_모든답변자_일치() {
    // given
    final User user = 사용자_생성("user");
    final Question question = 질문_생성(user);
    final Answer answerOne = 답변_생성(question, user);
    final Answer answerTwo = 답변_생성(question, user);

    // when
    final List<DeleteHistory> deleteHistories = 질문_삭제(question);

    // then
    assertAll(
            () -> assertThat(deleteHistories).hasSize(3),
            () -> assertThat(question.isDeleted()).isTrue(),
            () -> assertThat(answerOne.isDeleted()).isTrue(),
            () -> assertThat(answerTwo.isDeleted()).isTrue()
    );
}
```

위의 테스트 구조도 가독성을 크게 해치지 않는다고 생각하고, 테스트에 필요한 객체들이 어떻게 생성되는지 쉽게 파악이 가능해서 좋은거 같아요.

2021-11-20 13:15 UTC, 5minho commented on src/test/java/qna/domain/QuestionTest.java
> +    private Question 질문_생성(String writer) {
Questions 생성 메서드에서 User 의 이름을 받아 내부에서 User 를 생성하는 것보다, User 자체를 매개변수로 받아서 생성하는 걸 추천합니다. User 생성 방식이 달라져서 User 생성자에 인자가 추가됐다고 가정하면 User 생성 메서드만 수정해주면 좋겠죠?
```
private Question 질문_생성(User writer) {
    return new Question("title", "contents", writer);
}
```

테스트 전반적으로 확인 부탁드려요

2021-11-20 13:15 UTC, 5minho commented on src/test/java/qna/domain/QuestionRepositoryTest.java
> +class QuestionRepositoryTest {
테스트를 정말 꼼꼼하게 잘해주셨네요 👍
다만 도메인 테스트와 상당히 중복되는 부분이 있는거 같아요.
요구사항은 도메인 테스트를 통해 해주시고 repositoryTest 는 엔티티들의 CRUD 가 잘 되는지 정도 테스트 해주시면 된다고 생각해요.
테스트 코드도 우리가 관리해야할 코드들이고 너무 양이 많아지고 중복이 되면 유지보수가 어려워지기 때문이에요.

2021-11-20 13:15 UTC, 5minho commented on src/test/java/qna/service/QnaServiceTest.java
>  import static org.assertj.core.api.Assertions.assertThat;
QnaServiceTest 에 실패하는 테스트들이 있는데 성공하도록 수정해주시면 좋겠어요

2021-11-20 13:23 UTC, 5minho commented
> 안녕하세요 리뷰어님!
> 
> 질문 삭제하기 리팩터링 리뷰 요청드립니다!
> 
> 3단계를 진행하면서 집중한 부분은 테스트 코드 작성을 하면서 픽스쳐를 활용하여서 가독성을 높여보려고 했는데, 중복코드가 많아진 느낌도 들었습니다.
> 
> 그리고 한 가지 여쭤보고 싶은 부분이 있는데요, 소스상에서 객체의 null 체크를 위해서 nonNull을 사용하였는데요.
> 
> `if (Objects.nonNull(this.question)) `
> 
> `This method exists to be used as a java.util.function.Predicate, filter(Objects::nonNull)`
> 
> nonNull의 API 설명을 보면 지금 사용하고 있는 목적과는 좀 다른거 같아서요. 실제 현업에서 사용하실때는 어떤지 궁금합니다.
> 
> 이번 리뷰도 잘 부탁드립니다. 감사합니다.

아마 테스트 픽스쳐를 위해 엔티티 생성 메서드를 클래스 내부에 private 메서드로만 처리해서 중복코드가 많아지는 것 같아요.
클래스 외부에서 static 한팩토리 클래스를 만들어서 사용해보시는 것도 좋을거 같아요. 
관련 링크 남겨드릴게요. https://jojoldu.tistory.com/611 

nonNull 메서드와 관련해서 저런 설명이 있는지 저도 몰랐네요 😅 
저 같은 경우에는 Objects.isNull, Objects.nonNull 메서드는 단순 null 체크 null 이 아님을 체크 하기 위해 종종 쓰고 있습니다.

2021-11-20 14:44 UTC, 5minho commented on src/test/java/qna/domain/QuestionTest.java
> +class QuestionTest {
`질문을 삭제한 시간과 삭제내역이 생성된 시간은 같아야 한다` 라는 테스트도 작성해보시면 좋을거 같아요!

2021-11-21 04:27 UTC, codeleesh commented on src/main/java/qna/domain/Question.java
> +        if( this.getAnswers().existAnswer() ) {
생성자에서 default값을 넣어주고 있는데요, 혹시 다른 부분에서 처리를 해줘야 할까요?

2021-11-21 11:23 UTC, codeleesh commented on src/main/java/qna/domain/Answer.java
> +        this.setDeleted(true);
네 그렇게 하는 것이 맞을것 같습니다. 접근제한자가 아직 익숙하지 않네요..

2021-11-21 11:23 UTC, codeleesh commented on src/main/java/qna/domain/Question.java
> +        this.setDeleted(true);
네 접근제한자 변경하겠습니다!

2021-11-21 12:07 UTC, codeleesh commented on src/test/java/qna/domain/QuestionTest.java
> +        final Question question = 질문자_모든답변자_일치("questionWriter");
네 훨씬 깔끔해지고 파악도 가능한것 같습니다!

2021-11-21 12:08 UTC, codeleesh commented on src/test/java/qna/domain/QuestionTest.java
> +    private Question 질문_생성(String writer) {
네 그렇게 받아서 처리하니 훨씬 눈에 보기 좋아지고 불필요한 수정이 필요없어보입니다!

2021-11-21 12:09 UTC, codeleesh commented on src/test/java/qna/domain/QuestionRepositoryTest.java
> +class QuestionRepositoryTest {
네 이 부분이 걱정이 되었는데, 객체와 레파지토리의 대한 테스트 영역을 나누는 것이 중요하다고 생각이 들었습니다. 감사합니다.

2021-11-21 14:47 UTC, codeleesh commented on src/test/java/qna/domain/QuestionTest.java
> +class QuestionTest {
네 질문을 삭제를 수행한 시간과 실제 삭제 이력 테이블의 생성된 시간과 비교해보겠습니다.

2021-11-21 14:50 UTC, codeleesh commented
> > 안녕하세요 리뷰어님!
> > 질문 삭제하기 리팩터링 리뷰 요청드립니다!
> > 3단계를 진행하면서 집중한 부분은 테스트 코드 작성을 하면서 픽스쳐를 활용하여서 가독성을 높여보려고 했는데, 중복코드가 많아진 느낌도 들었습니다.
> > 그리고 한 가지 여쭤보고 싶은 부분이 있는데요, 소스상에서 객체의 null 체크를 위해서 nonNull을 사용하였는데요.
> > `if (Objects.nonNull(this.question)) `
> > `This method exists to be used as a java.util.function.Predicate, filter(Objects::nonNull)`
> > nonNull의 API 설명을 보면 지금 사용하고 있는 목적과는 좀 다른거 같아서요. 실제 현업에서 사용하실때는 어떤지 궁금합니다.
> > 이번 리뷰도 잘 부탁드립니다. 감사합니다.
> 
> 아마 테스트 픽스쳐를 위해 엔티티 생성 메서드를 클래스 내부에 private 메서드로만 처리해서 중복코드가 많아지는 것 같아요. 클래스 외부에서 static 한팩토리 클래스를 만들어서 사용해보시는 것도 좋을거 같아요. 관련 링크 남겨드릴게요. https://jojoldu.tistory.com/611
> 
> nonNull 메서드와 관련해서 저런 설명이 있는지 저도 몰랐네요 😅 저 같은 경우에는 Objects.isNull, Objects.nonNull 메서드는 단순 null 체크 null 이 아님을 체크 하기 위해 종종 쓰고 있습니다.

텍스트 픽스쳐 메소드 참고하여 추가해보았습니다. 감사합니다.

nonNull 관련해서도 의견주셔서 감사합니다!

2021-11-22 10:21 UTC, 5minho approved these changes
안녕하세요 상호님!
피드백 반영 잘해주셨고요~
JPA 미션 하시느라 고생 많으셨습니다.
마지막까지 화이팅입니다!!!!

2021-11-22 10:21 UTC, 5minho commented on src/main/java/qna/domain/Question.java
> +        if( this.getAnswers().existAnswer() ) {
```
public Question(String title, String contents, User writer) {
    this(null, title, contents, writer);
}
```
통해 질문을 생성하면 answers 가 null 일거 같아서요!
Answers 선언 할 때 초기화를 해주면 NPE 를 방지할 수 있을거 같습니다
```
@Embedded
private Answers answers = new Answers();
```

2021-11-22 10:21 UTC, merged