Step3 - 질문 삭제하기 리팩터링
next-step/jwp-qna pull request #346
Opened 2021-11-19 23:56 UTC by lsm7179

안녕하세요.~ 리뷰어님 2단계 리뷰사항 반영하고
3단계 리뷰 요청드립니다.
감사합니다.👍

2021-11-20 14:55 UTC, 5minho requested changes
안녕하세요 승민님!
JPA 마지막 미션 아주 잘해주셨습니다~
조금 더 개선했으면 좋겠는 부분을 코멘트로 달아봤습니다.
확인해주시면 감사하겠습니다!

2021-11-20 14:55 UTC, 5minho commented on src/main/java/qna/domain/Answers.java
> +    public static Answers of() {
빈 Answers 를 리턴한다는 의미로 `empty()` 라고 하는건 어떨까요?

2021-11-20 14:55 UTC, 5minho commented on src/main/java/qna/service/QnaService.java
> +        List<DeleteHistory> deleteHistories = question.delete(loginUser);
서비스레이어가 얇아졌네요 👍

2021-11-20 14:55 UTC, 5minho commented on src/test/java/qna/domain/AnswerTest.java
>      public static final Answer A2 = new Answer(UserTest.SANJIGI, QuestionTest.Q1, "Answers Contents2");
여러 테스트가 static 변수를 공유하고 있는데, 코드가 깔끔해지는 장점이 있지만 객체를 공유하면서 생기는 문제점들도 있습니다.
예를 들면 어떤 테스트 내에서 A1 을 수정하면 A1 을 공유하고 있는 다른 테스트들에 영향이 가게됩니다. 또 A1 을 사용하는 테스트내에서 A1 이 어떻게 생성되었는지 파악하기 어렵습니다. A1 을 생성하고 있는 클래스 파일로 가봐야 하죠.
비슷한 문제를 다루고 있는 블로그글 링크를 남기겠습니다. (https://jojoldu.tistory.com/611)
보시고 테스트픽스쳐를 static 변수가 아닌 테스트 내에서 생성하는 방식으로 바꿔보시는 경험을 하면서 서로 장단점을 경험해보셨으면 합니다.

2021-11-20 14:55 UTC, 5minho commented on src/test/java/qna/domain/QuestionTest.java
>  public class QuestionTest {
`질문을 삭제한 시간과 삭제내역이 생성된 시간은 같아야 한다` 라는 테스트도 작성해보셨으면 좋겠어요.

2021-11-21 08:31 UTC, lsm7179 commented on src/main/java/qna/domain/Answers.java
> +    public static Answers of() {
적절한 메소드명 사용 좋은거 같습니다.

2021-11-21 10:28 UTC, lsm7179 commented on src/test/java/qna/domain/AnswerTest.java
>      public static final Answer A2 = new Answer(UserTest.SANJIGI, QuestionTest.Q1, "Answers Contents2");
테스트메소드는 가독성이 중요하다라는 걸 알고 있었지만 중복코드를 생각해서 변수를 공유하는 형태로 만들었습니다.
그리고 말씀에 주신 테스트 내에서 변수를 생성하는 방식으로 바꿨을땐 가독성이 좋아지는 장점을 얻을 수 있었습니다.
다음에 사용 할때는 저도 테스트메소드의 가독성, 결합도를 고려하여 각 메소드에서 생성하는 방식으로 할 거 같습니다. 
감사합니다.

2021-11-22 03:02 UTC, 5minho approved these changes
안녕하세요 승민님! 피드백 반영해주시느라 고생하셨어요~
코멘트 단것은 앞으로 미션을 할때 도움이 될지도 모르니 한번 확인을 해주셨으면 좋겠습니다!
JPA 미션 진행하시느라 고생하셨고
마지막까지 화이팅입니다!!!!

2021-11-22 03:02 UTC, 5minho commented on src/test/java/qna/domain/DeleteHistoryRepositoryTest.java
> +    @DisplayName("질문 삭제 시간과 삭제내역 생성시간이 같아야함")
삭제 내역 생성시간에 질문, 답변의 수정시간을 넣어주셨군요 😂
이렇게 되면 어제 내용을 수정을 질문을 오늘 삭제 했을때 삭제 내역 생성시간에는 어제 날짜가 들어가지 않을까요?


테스트를 어렵게 하는 요소를 제거해 테스트하기 쉬운 코드짜는 법을 고민해보셨으면 좋으실거 같아서`질문 삭제 시간과 삭제내역 생성시간이 같아야한다` 라는 테스트를 작성해보라고 제안드렸어요.

제 생각에느 DeleteHistory 내에서 생성하는 createDate 가 테스트하기 어려운 요소인거 같고, createDate 를  삭제하는 측에서 주입해주면 해결할 수 있을거 같아요. 
프로덕트 코드에서는 Service 쪽에서 createDate 를 생성해 질문 삭제시 주입해주면 되겠죠?

```
@DisplayName("질문 삭제 시간과 삭제내역 생성시간이 같아야함")
@Test
void timeCompare() throws Exception{
    final User user = userRepository.save(UserTest.JAVAJIGI);
    final Question question =questionRepository.save( new Question("test","contents").writeBy(user));
    final Answer answer = answerRepository.save(new Answer(UserTest.JAVAJIGI, question, "Answers Contents1"));
    final LocalDateTime deleteAt = LocalDateTime.now();

    List<DeleteHistory> deleteHistories = question.delete(UserTest.JAVAJIGI, deleteAt);
    deleteHistoryRepository.saveAll(deleteHistories);

    assertThat(deleteHistories.get(0).getCreateDate()).isEqualTo(deleteAt);
    assertThat(deleteHistories.get(1).getCreateDate()).isEqualTo(deleteAt);
}
}
```

그리고 해당 테스트는 repository layer 테스트 보다 비즈니스 로직을 테스트 하는 domain layer 테스트에 있으면 더 좋을거 같습니다.

2021-11-22 03:03 UTC, merged

2021-11-22 11:15 UTC, lsm7179 commented on src/test/java/qna/domain/DeleteHistoryRepositoryTest.java
> +    @DisplayName("질문 삭제 시간과 삭제내역 생성시간이 같아야함")
> 삭제 내역 생성시간에 질문, 답변의 수정시간을 넣어주셨군요 😂 이렇게 되면 어제 내용을 수정을 질문을 오늘 삭제 했을때 삭제 내역 생성시간에는 어제 날짜가 들어가지 않을까요?
> 
> 테스트를 어렵게 하는 요소를 제거해 테스트하기 쉬운 코드짜는 법을 고민해보셨으면 좋으실거 같아서`질문 삭제 시간과 삭제내역 생성시간이 같아야한다` 라는 테스트를 작성해보라고 제안드렸어요.
> 
> 제 생각에느 DeleteHistory 내에서 생성하는 createDate 가 테스트하기 어려운 요소인거 같고, createDate 를 삭제하는 측에서 주입해주면 해결할 수 있을거 같아요. 프로덕트 코드에서는 Service 쪽에서 createDate 를 생성해 질문 삭제시 주입해주면 되겠죠?
> 
> ```
> @DisplayName("질문 삭제 시간과 삭제내역 생성시간이 같아야함")
> @Test
> void timeCompare() throws Exception{
>     final User user = userRepository.save(UserTest.JAVAJIGI);
>     final Question question =questionRepository.save( new Question("test","contents").writeBy(user));
>     final Answer answer = answerRepository.save(new Answer(UserTest.JAVAJIGI, question, "Answers Contents1"));
>     final LocalDateTime deleteAt = LocalDateTime.now();
> 
>     List<DeleteHistory> deleteHistories = question.delete(UserTest.JAVAJIGI, deleteAt);
>     deleteHistoryRepository.saveAll(deleteHistories);
> 
>     assertThat(deleteHistories.get(0).getCreateDate()).isEqualTo(deleteAt);
>     assertThat(deleteHistories.get(1).getCreateDate()).isEqualTo(deleteAt);
> }
> }
> ```
> 
> 그리고 해당 테스트는 repository layer 테스트 보다 비즈니스 로직을 테스트 하는 domain layer 테스트에 있으면 더 좋을거 같습니다.

처음에 jpa를 이용해서 만들어야 되나 라는 생각에 repository layer 쪽에 테스트 코드를 넣었습니다.
만들고 보니 도메인쪽이 맞는거같습니다. ㅜㅜ

jpa를 민호님과 함께 해서 좋은 경험이 었고 많은 인사이트를 얻어갑니다. 감사합니다.