2단계 - 연관 관계 매핑
next-step/jwp-qna pull request #348
Opened 2021-11-20 01:28 UTC by InmookJeong

안녕하세요. 우아한테크캠프 Pro 참여자 정인묵입니다.
2단계 연관 관계 매핑에 대한 코드리뷰를 부탁드립니다.
고속버스 안에서 코딩을 하다보니 약~간 부족한 부분이 있을 수도 있습니다.
혹, 그런 부분이 많은 경우 냉정한 리뷰 부탁드려요~^^

참고로 대부분 Product 코드가 아닌 Test 코드 위주로 작성하였습니다.

2021-11-20 19:08 UTC, jhhj424 requested changes
안녕하세요 인묵님~ 🙇🏻‍♂️
바쁘신 일정에서 미션 진행하시느라 고생하셨습니다 !
연관관계 매핑중 테스트가 깨지는 현상이 발생하였는데,
전체 테스트를 한번에 Run 해보시고 확인해주시면 좋을 것 같아요~
다시 한번 요청 드리겠습니다 🙏

2021-11-20 19:08 UTC, jhhj424 commented on README.md
> +## 기능 목록
기능 목록 작성 잘 해주셨네요 💯

2021-11-20 19:08 UTC, jhhj424 commented on README_BACK/README_1.0.0.md
> +> version : 1.0.0
개인적으로 git 을 통해 형상관리를 하고있기때문에 따로 버저닝이 필요하지 않을 것 같은데
README 를 버저닝하여 관리하시는 이유가 따로 있으실까요?

2021-11-20 19:08 UTC, jhhj424 commented on src/main/java/qna/Application.java
> +@EnableJpaAuditing
👍

2021-11-20 19:08 UTC, jhhj424 commented on src/main/java/qna/domain/Answer.java
> +        return this.writer.getId().equals(writer.getId());
id 를 꺼내서 비교하지 말고 객체비교로 진행해도 좋을 것 같아요 :)

2021-11-20 19:08 UTC, jhhj424 commented on src/main/java/qna/domain/Answer.java
> +                ", questionI/d=" + question.getId() +
```suggestion
                ", questionId=" + question.getId() +
```
오타인 것 같네요 :)

---

toString 에서 객체 자체를 보여줘도 괜찮겠네요, 물론 아시겠지만 연관관계상 순환참조가 발생하지 않도록 유의해주시면 좋을 것 같습니다.

2021-11-20 19:08 UTC, jhhj424 commented on src/main/java/qna/domain/BaseEntity.java
> +public abstract class BaseEntity {
`@MappedSuperclass` `abstract` 를 활용한 BaseEntity 💯

2021-11-20 19:08 UTC, jhhj424 commented on src/main/java/qna/domain/DeleteHistory.java
> +    @Enumerated(EnumType.STRING)
`@Enumerated(EnumType.STRING)` 👍 

잘 작성해주셨네요!
동작 차이를 확인해보셨을까요~:?

2021-11-20 19:08 UTC, jhhj424 commented on src/main/java/qna/domain/DeleteHistory.java
> +        this.deleteUser.setId(deletedById);
혹시 전체 테스트를 진행해보셨을까요~?

많은 곳에서 failed가 떨어지고 있는데 확인해보시면 좋을 것 같습니다 ~

2021-11-20 19:08 UTC, jhhj424 commented on src/main/java/qna/domain/User.java
> +    private List<DeleteHistory> deleteHistories = new ArrayList<DeleteHistory>();
현재 유저가 모든 엔티티와 직접적으로 연관관계를 맺고있는데, 앞으로 해당 애플리케이션이 확장된다면 또 User 에 엔티티들을 연관관계 매핑을 해줘야할까요?

어느정도에서 직접참조연관관계를 끊어내는게 좋을지도 고민해보면 좋을 것 같습니다 :)


현재의 코드를 바꾸라고 말씀드리는건 아니고, 앞으로도 여러 미션 진행하시면서 고민해보면 좋을 것 같아서 영상 하나 남겨볼께요~
https://www.youtube.com/watch?v=dJ5C4qRqAgA&t=1s

2021-11-20 19:08 UTC, jhhj424 commented on src/main/java/qna/domain/UserRepository.java
> +     * userId 조회를 통한 User 수 가져오기
명확하게 의도를 드러내는 메서드라고 생각이드는데
주석을 작성해주신 이유가 있을까요?

개인적으로, 정말 복잡한 로직이어서 한눈에 확인하기 힘든 구조일때 정도로 사용하는게 좋다고 생각하는데 혹시 어떻게 생각하시나요~?

추후에 코드가 발전되면서 코드는 수정되었는데 주석은 수정되지 않는 경우도 생기곤 하는 것 같아서 (인적리스크) 
주석 사용에 주의하는게 좋을 것 같더라구요 :)

2021-11-21 01:43 UTC, InmookJeong commented on README_BACK/README_1.0.0.md
> +> version : 1.0.0
보통은 Git 코드이력을 통해 이전 버전의 README를 보긴 하는데
이번에는 Github 접속 없이 IntelliJ에서 빠르게 확인하기 위해 그냥 Backup했습니다.^^

2021-11-21 01:50 UTC, InmookJeong commented on src/main/java/qna/domain/DeleteHistory.java
> +    @Enumerated(EnumType.STRING)
@Column은 DB Table의 컬럼과 Annotation의 속성을 매핑시켜주는 역할을 하고,
@Enumerated의 EnumbTyp.String은 객체 자체를 String으로 변환하여 데이터를 저장하는 역할을 하는 것으로
이해를 했는데 맞나요?^^

2021-11-21 01:53 UTC, InmookJeong commented on src/main/java/qna/domain/User.java
> +    private List<DeleteHistory> deleteHistories = new ArrayList<DeleteHistory>();
참고 영상을 알려주셔서 감사해요~ 😃

2021-11-21 02:01 UTC, InmookJeong commented on src/main/java/qna/domain/UserRepository.java
> +     * userId 조회를 통한 User 수 가져오기
의도가 명확하여도 JAVA Doc 주석을 작성하는 것은 일종의 습관인데요.

후배 직원들이 복잡한 Method를 만들었음에도 워낙 주석을 작성하지 않다 보니
간단한 Method라도 어떻게 주석을 달면 좋을지, 각 parameter는 어떤 역할을 하고
return은 어떤 기준으로 하는 것인지 직접 보여주면서 가르치다 생긴 버릇(?)이에요 ^^
간혹 급한 경우 저도 주석을 작성하지 않는 경우가 있는데, 일부로 더 작성하려다 보니
간단한 Method도 모두 주석을 달아버리고 있어요.^^

다만 코멘트 해주신대로 코드 수정 시 주석 내용 또한 변경되도록 많이 신경써야겠네요.😃

2021-11-22 10:56 UTC, jhhj424 requested changes
안녕하세요 인묵님~ 🙇🏻‍♂️
저번에 말씀드린 테스트 fail 관련해서 아직 수정이 더 필요해보이네요 :(
코멘트 남겼으니 확인 한번만 부탁드리겠습니다 🙏
모든 테스트 초록불 확인하시고 리뷰 한번만 다시 주세요 ~

2021-11-22 10:56 UTC, jhhj424 commented on src/main/java/qna/domain/Answer.java
> +                ", questionId=" + question.toString() +
```suggestion
                ", question=" + question +
```

이런식으로 사용하셔도 됩니당~

(양방향 순환 참조만 주의)

2021-11-22 10:56 UTC, jhhj424 commented on src/main/java/qna/domain/DeleteHistory.java
> +        this.deleteUser.setId(deletedById);
![image](https://user-images.githubusercontent.com/46177529/142848366-ba52123b-a7e4-436f-b38b-14ea4e9a77c5.png)


![image](https://user-images.githubusercontent.com/46177529/142848298-b1cb3b63-374e-4473-b1e2-628a8bea5acf.png)


아직도 fail 테스트들이 발생하네요 :(
그리고 전체 테스트를 실행할 때 마다 성공 or 실패가 보장하지 않는 테스트도 있어서 어쩔땐 2개실패하고 어쩔땐 3개 실패하고 그러네요,

테스트간의 격리가 잘 되어있는지도 체크가 필요할 것 같습니다 ~
왜 그런지 이유를 찾고 수정해보시면 좋을 것 같습니다 👍

2021-11-22 10:56 UTC, jhhj424 commented on src/test/java/qna/domain/AnswerTest.java
> +                () -> assertThat(answer1.isDeleted()).isEqualTo(false)
```suggestion
                () -> assertThat(answer1.isDeleted()).isFalse()
```

이렇게도 가능합니다~

2021-11-22 14:07 UTC, jhhj424 approved these changes
안녕하세요 인묵님~ 🙇🏻‍♂️
여러번 요청드려서 힘드셨을텐데 잘 작성해주셔서 감사합니다 :)
코멘트 몇개 남겼으니 다음 단계 진행하시면서 확인 부탁드리겠습니다~
고생하셨습니다, 다음 단계도 화이팅입니다 👊

2021-11-22 14:07 UTC, jhhj424 commented on src/main/java/qna/domain/Answer.java
> +@EntityListeners(AuditingEntityListener.class)
`@EntityListeners(AuditingEntityListener.class)` 가 어떤 역할때문에 선언하는지 확인해주시면 좋을 것 같습니다 :)

2021-11-22 14:07 UTC, jhhj424 commented on src/main/java/qna/domain/DeleteHistory.java
>          this.createDate = createDate;
현재 `Auditing` 기능을 사용하고 있기 때문에 없어도 될 것 같아요~

2021-11-22 14:08 UTC, merged