Step3
next-step/jwp-qna pull request #356
Opened 2021-11-21 06:24 UTC by lights93

2021-11-21 11:16 UTC, slamdunk7575 requested changes
질문 삭제하기 리팩토링 잘해주셨네요.
몇가지 코멘트 남겨드렸는데 확인 부탁드립니다.
조금만 더 힘내주세요~ 💪

2021-11-21 11:16 UTC, slamdunk7575 commented on src/main/java/qna/service/QnaService.java
> +        deleteHistoryService.saveAll(deleteHistories.getDeleteHistories());
깔끔하게 리팩토링 잘해주셨네요 👍

2021-11-21 11:16 UTC, slamdunk7575 commented on src/main/java/qna/domain/Question.java
> +            new DeleteHistory(new Content(this), LocalDateTime.now()));
아래와 같은 `정적 팩토리 메소드`를 만들어보면
인자수도 줄면서 코드의 가독성을 높여줄 수 있겠네요 :)

분리하신 `Content`도 좋고 Content 분리에 큰 이점이 없다고 생각된다면
`DeleteHistory` 내에 만들어 보셔도 좋습니다.

```java
    public static DeleteHistory ofQuestion(Long contentId, User deletedBy) {
        return new DeleteHistory(ContentType.QUESTION, contentId, deletedBy);
    }

    public static DeleteHistory ofAnswer(Long contentId, User deletedBy) {
        return new DeleteHistory(ContentType.ANSWER, contentId, deletedBy);
    }
```

2021-11-21 11:16 UTC, slamdunk7575 commented on src/main/java/qna/domain/Question.java
>      private String title;
> 모든 원시 값과 문자열을 포장한다.

`예: title` 을 객체로 포장하고 길이에 대한 검증을 해볼 수 있겠네요.
필요하다고 생각되는 부분에 적용해보시면 좋을 것 같아요.

2021-11-21 11:16 UTC, slamdunk7575 commented on src/main/java/qna/domain/Answers.java
> +    }
Question과 동일하게 `Answer 작성자`에 대한 검증은 Answer 내에서 삭제시 해보면 어떨까요?

2021-11-21 11:16 UTC, slamdunk7575 commented on src/main/java/qna/domain/Answer.java
>          return "Answer{" +
> 안 그래도 개발 중에 순환참조가 발생하여 수정을 했었는데요.
요구사항에 따라 다를 것 같긴 하지만, 보통 entitytoString() 시에는 아이디로만 해도 상관이 없을까요?

순환참조를 예방하는 다양한 방법이 있지만 실무에서는 주로 `DTO`를 넘기도록 사용합니다.

[요청과 응답으로 엔티티(Entity) 대신 DTO를 사용하자](https://tecoble.techcourse.co.kr/post/2020-08-31-dto-vs-entity/)
[JPA 양방향 Entity 무한재귀 문제해결](https://thxwelchs.github.io/JPA%20%EC%96%91%EB%B0%A9%ED%96%A5%20Entity%20%EB%AC%B4%ED%95%9C%20%EC%9E%AC%EA%B7%80%20%EB%AC%B8%EC%A0%9C%20%ED%95%B4%EA%B2%B0/)

2021-11-21 11:16 UTC, slamdunk7575 commented on src/test/java/qna/domain/AnswersTest.java
> +    }
도메인 테스트 잘해주셨네요 💯

2021-11-21 11:16 UTC, slamdunk7575 commented on src/test/java/qna/domain/AnswersTest.java
> +    }
검증 부분이 없네요. 해당 테스트는 불필요해 보이는데 제거해보면 어떨까요?

2021-11-23 11:57 UTC, lights93 commented on src/main/java/qna/domain/Answer.java
>          return "Answer{" +
DTO로 넘기는 것 외에도 참고할만 링크들 같이 주셔서 감사합니다!

2021-11-23 13:44 UTC, lights93 commented on src/main/java/qna/domain/Answer.java
>          return "Answer{" +
현재는 toString에서 한 쪽에서 id를 가져오도록 되어 있어 순환참조가 일어나지 않습니다.
jackson으로 파싱하게 된다면 위의 링크에서 나온 내용들을 이용하도록 하겠습니다.

감사합니다.

2021-11-23 13:48 UTC, lights93 commented on src/main/java/qna/domain/Question.java
> +            new DeleteHistory(new Content(this), LocalDateTime.now()));
`정적 팩토리 메서드`로 수정했습니다.

`Content` 분리의 이점에 대해 얘기해주셨는데, 이점이라는 것이 어떤 것이 있을까요??
제가 `Content`로 분리한 이유는 
1. 삭제되는 컨텐츠라는 의미를 클래스명을 통해 설명이 되는 것
2. `Content`를 이용하여 전보다 간단하게 생성할 수 있다고 생성했기 떄문입니다.

이러한 것들이 이점으로 볼 수 있을까요??
오히려 `Content`를 이용하여 복잡해져서 이점이 없는 것은 아닐지 고민이 되네요.

이점과 관련하여 리뷰어님의 생각이 궁금합니다.

감사합니다.

2021-11-23 13:49 UTC, lights93 commented on src/main/java/qna/domain/Question.java
>      private String title;
title과 이 외에 일부 값들 객체로 포장했습니다.

감사합니다.

2021-11-23 13:49 UTC, lights93 commented on src/main/java/qna/domain/Answers.java
> +    }
`Answer` 작성자에 대한 검증은 Answer 내에서 삭제시 하도록 수정했습니다.

감사합니다.

2021-11-23 13:51 UTC, lights93 commented on src/test/java/qna/domain/AnswersTest.java
> +    }
수정하여 푸시했습니다.

문의사항이 있는데, 에러가 나지 않음을 검증하기 위해서 이렇게 사용하는 경우는 없을까요??
혹은 다른 방법이 있는지 궁금합니다.

감사합니다.

2021-11-23 13:53 UTC, lights93 commented
추가적으로 질문이 있습니다.
객체 포장을 많이하다보니 domain 패키지 안에 많은 클래스가 생성되고 있는데요.
이럴 때는 보통 패키지 관리를 어떻게 하시는지 궁금합니다!

관련된 것끼리 다시 domain안에서 패키지로 묶는 걸까요??
ex. domain.user, domain.question

감사합니다.

2021-11-24 12:46 UTC, slamdunk7575 approved these changes
마지막까지 열심히 해주셔서 감사합니다. 그동안 고생 많으셨어요. 🙇
제가 드렸던 피드백들이 앞으로 민호님께 조금이라도 도움이 되었으면 좋겠네요.
남은 미션도 꾸준히 진행하시고 끝까지 완주하시길 응원하겠습니다! 🎉

2021-11-24 12:46 UTC, slamdunk7575 commented on src/main/java/qna/domain/Content.java
> +    }
피드백 반영 잘해주셨네요 💯

> Content 분리의 이점에 대해 얘기해주셨는데, 이점이라는 것이 어떤 것이 있을까요?? 제가 Content로 분리한 이유는
> 1. 삭제되는 컨텐츠라는 의미를 클래스명을 통해 설명이 되는 것
> 2. Content를 이용하여 전보다 간단하게 생성할 수 있다고 생성했기 떄문입니다.
이러한 것들이 이점으로 볼 수 있을까요??오히려 Content를 이용하여 복잡해져서 이점이 없는 것은 아닐지 고민이 되네요.
이점과 관련하여 리뷰어님의 생각이 궁금합니다.

분리했을때 이점은 객체 내에서 스스로 상태와 관련된 검증이나 로직을 처리할 수 있다는 점이 가장 클 것 같은데요.
이런 관점에서 볼때 현재 `Content`로 분리한 contentType, writer는 `DeleteHistory`에 있어도 될 것 같습니다.
하지만 좋은 시도라고 생각되고 미션을 진행하시면서 지금처럼 분리도 했다가 다시 합치기도 하면서 다양한 인사이트를 얻으셨으면 좋겠네요 :)

2021-11-24 12:46 UTC, slamdunk7575 commented on src/main/java/qna/domain/Email.java
> +public class Email {
피드백 반영 잘해주셨네요 👍
참고로 `Email 형식 검사`도 해볼 수 있겠네요.

2021-11-24 12:46 UTC, slamdunk7575 commented on src/main/java/qna/domain/Answer.java
>      }
지난 피드백 https://github.com/next-step/jwp-qna/pull/356#discussion_r753782460 을 드렸던 의도는 Question의 delete() 와 동일하게
`Answer`의 `delete()` 내에서 아래처럼 검증후 처리해보면 좋을 것 같아 드렸던 것이에요.

```java
public DeleteHistory delete(User loginUser) {
        validateOwner(loginUser);
        deleted = true;
        return DeleteHistory.ofContent(Content.ofAnswer(this));
}
```

2021-11-24 12:46 UTC, slamdunk7575 commented on src/test/java/qna/domain/AnswersTest.java
> +    void validateOwner_error() {
> 문의사항이 있는데, 에러가 나지 않음을 검증하기 위해서 이렇게 사용하는 경우는 없을까요??
혹은 다른 방법이 있는지 궁금합니다.

아래처럼 테스트할 수 있을듯 한데요.
`리턴이 없는 메소드`는 테스트 하기 힘들뿐더러 지금같은 경우 예외발생(일종의 리턴)에 대한 
테스트를 하는 것이 더 좋을듯 합니다 :)

`assertDoesNotThrow(() -> answer.validateOwner(UserTest.JAVAJIGI));`

2021-11-24 12:46 UTC, slamdunk7575 commented on src/main/java/qna/domain/Title.java
> +public class Title {
> 추가적으로 질문이 있습니다.
객체 포장을 많이하다보니 domain 패키지 안에 많은 클래스가 생성되고 있는데요.
이럴 때는 보통 패키지 관리를 어떻게 하시는지 궁금합니다!

> 관련된 것끼리 다시 domain안에서 패키지로 묶는 걸까요??
ex. domain.user, domain.question

> 정답은 없는 것 같지만 보통 어떻게 많이 하시는지 궁금합니다.
감사합니다.


저도 관련있는 엔티티끼리 패지키를 묶는게 좋을것 같아요 😄
나아가 시스템이 커진다면 도메인 별로 `예: question.domain, question.dao` 처럼 나눠볼 수도 있겠네요.

2021-11-24 12:48 UTC, merged