Step3 - 질문 삭제하기 리팩토링
next-step/jwp-qna pull request #360
Opened 2021-11-21 19:02 UTC by changjinpark

3단계 과제 제출합니다!

질문 삭제하기 리팩토링 과제를 하면서 테스트를 구현할 때 일급 콜렉션(Answers.java, DeleteHistories.java)의 인수가 데이터베이스에 의존을 받다보니까 일급 콜렉션(Answers.java, DeleteHistories.java)들에 대한 테스트를 구현하기 어려웠었습니다. 
결국 일급 콜렉션 테스트를 할 때, 테스트 클래스에 데이터베이스를 직접 만들어서 테스트를 하였지만, 데이터베이스를 의존 받는 클래스도 단위 테스트를 하는게 맞는걸까 하는 의구심이 들었습니다. 리뷰어님께서는 이럴 경우 단위 테스트에서 제외하시는지 아니면 단위테스트에 포함하시는지 궁금합니다.

2021-11-22 04:03 UTC, nokchax requested changes
안녕하세요, 창진님! 세번째 단계 고생하셨습니다 👏👏
코멘트 남겨드렸는데, 확인후 재요청 부탁드립니다 🙇‍♂️

2021-11-22 04:03 UTC, nokchax commented on src/main/java/qna/domain/User.java
> +
equals와 hashCode는 IDE의 자동 생성을 이용하신 건가요?

2021-11-22 04:03 UTC, nokchax commented on src/main/java/qna/domain/Answers.java
> +public class Answers {
`@Embeddable` 과 `@Embedded` 에 대해서 찾아보시고, 현재 Question과 Answer간의 관계에 사용해보세요 :)
질문 주신내용도 이 어노테이션을 공부하시고 나면 해결되시거나 질문이 바뀌실거 같네요

2021-11-22 04:03 UTC, nokchax commented on src/main/java/qna/domain/Answers.java
> +    private Answers(List<Answer> answers, User loginUser) throws CannotDeleteException {
CannotDeleteException 에서 Exception을 상속하도록 놔두신 이유가 있으실까요?
Exception과 RuntimeException의 차이에 대해 한번 찾아보세요 :)

2021-11-22 04:03 UTC, nokchax commented on src/main/java/qna/domain/DeleteHistories.java
> +            answer.setDeleted(true);
setDeleted(boolean) 은 setter나 다름없습니다.
answer.delete(), answer.restore() 처럼 객체지향적으로 짤수 있지 않을까요?
그리고 answer.delete() 결과물로 deletehistory 생성도 가능하겠네요

2021-11-22 04:03 UTC, nokchax commented on src/main/java/qna/service/QnaService.java
> +        DeleteHistories deleteHistories = DeleteHistories.createDeletedHistories(question, answers);
question따로, answers 따로 처리하셨는데 이러면 question에서 answers를 매핑한 의미가 전혀없는거 같아요.
question내의 answers를 활용해보세요 :)

2021-11-22 08:44 UTC, changjinpark commented on src/main/java/qna/domain/Answers.java
> +    private Answers(List<Answer> answers, User loginUser) throws CannotDeleteException {
네 힌트를 주셔서 감사합니다👍 

Exception과 RuntimeException의 차이를 찾아보니 Exception은 throws 혹은 try catch 구문을 같이 예외 처리하는 구문을 꼭 넣어야 컴파일이 가능하지만, RuntimeException은 이런 구문을 넣지 않아도 컴파일이 가능하군요. 

CannotDeleteException에서 Exception 대신 RuntimeException을 상속 받도록 변경했고, 도메인에서 사용했던 throws CannotDeleteException들을 모두 지웠습니다. : )

2021-11-22 09:12 UTC, changjinpark commented on src/main/java/qna/domain/DeleteHistories.java
> +            answer.setDeleted(true);
객체지향적으로 리팩토링 가능한 것 같네요👍 
answer에서 true 지정과 deletehistory 생성까지 같이 해주는 answer.deleteAnswerAndCreateDeleteHistory(answer)로 리팩토링했습니다.
3줄코드가 1줄로 줄어드는 효과가 있네요. 객체지향 프로그래밍이 참 유용하다고 느끼면서도 아직 더 배워야겠다는 생각을 하게 되네요. ㅎㅎ

2021-11-22 10:27 UTC, changjinpark commented on src/main/java/qna/service/QnaService.java
> +        DeleteHistories deleteHistories = DeleteHistories.createDeletedHistories(question, answers);
네 리팩토링했습니다.
question 내에 answer가 매핑되어있기 때문에 
DeleteHistories.createDeletedHistories(question, answers); 의 answer 인자를 빼고 리팩토링할 수 있네요👍

2021-11-22 10:43 UTC, changjinpark commented on src/main/java/qna/domain/User.java
> +
네 IDE 자동 생성을 이용했습니다.
추가로 공부하다보니까 엔티티의 equals()와 hashCode()를 구현할 때는 엔티티의 식별자만 있어도 충분하다는 것을 알게 되었습니다. id(PK)와 user_id(UK) 2개만 사용해서 equals()와 hashCode()를 구현했습니다.

2021-11-22 14:49 UTC, changjinpark commented on src/main/java/qna/domain/Answers.java
> +public class Answers {
Question과 Answers 간의 관계를 @Embedded와 @Embeddable 로 설정했습니다. 이전에 질문드렸던 데이터베이스 코드가 삭제되는 리팩토링 효과가 있었습니다. 이 두 개의 관계를 설정해주니 전보다 많은 부분이 더 간략하게 리팩토링이 되는 경험을 했습니다.

2021-11-23 04:09 UTC, nokchax approved these changes
안녕하세요 창진님 🙇‍♂️ 
마지막 단계까지 고생많으셨습니다. 이만 머지할게요 :) 
남아있는 과정을 통해서 많이 얻어가시길 바랄게요 🙏

2021-11-23 04:09 UTC, nokchax commented on src/main/java/qna/service/QnaService.java
> +        DeleteHistories deleteHistories = question.delete(loginUser);
👍  깔끔하네요

2021-11-23 04:09 UTC, merged