JPA 2단계 미션 진행
next-step/jwp-qna pull request #364
Opened 2021-11-22 19:53 UTC by devhak2

안녕하세요! 2단계 미션을 좀 늦게 진행하게 되었습니다!ㅠ 요번 미션에서는 Test 코드 작성을 위해서 Cascade를 쓰게 되었는데 이렇게 진행하는 것이 맞을지 모르겠네요! 리뷰 잘 부탁드리겠습니다

2021-11-23 10:23 UTC, slamdunk7575 requested changes
연관관계 매핑 잘해주셨네요.
몇가지 피드백 남겨드렸는데 고민해보시고 리뷰요청 주시면 좋을 것 같아요.
끝까지 화이팅 입니다~ 💪

2021-11-23 10:23 UTC, slamdunk7575 commented on src/main/java/qna/domain/Answer.java
> +	private Question question;
JPA를 배제하고 서비스의 흐름으로 봤을때
일반적으로 `질문(Question)`이 먼저 생성되고 `답변(Answer)`이 생성되는 순서가 될 것 같은데요.
`Answer`가 cascade를 통해 `Question`의 라이프 사이클을 관리하는 부분은 제거하는게 좋을 것 같아요.

Answer를 조회시 항상 `Question, Writer`를 같이 조회해야 하는 경우가 아니라면 `지연로딩` 속성을 주면 좋겠네요.
`@OneToMany`는 LAZY가 디폴트이지만 `@ManyToOne`는 아니기 때문입니다.

2021-11-23 10:23 UTC, slamdunk7575 commented on src/main/java/qna/domain/Answer.java
> +	private User writer;
`CascadeType.ALL`을 주면 Answer 삭제시 User가 삭제될 것 같은데요. 
다른 옵션값에 대해서 고민해보시면 좋을 것 같아요.

`cascade` 설정은 부모 엔티티를 영속 상태로 만들때 연관된 자식 엔티티도 함께 영속 상태로 만들고 싶을때 사용합니다.
객체들의 라이프 사이클이 같이 움직이는지 고민해보시면 좋겠네요.

[영속성 전이(CASCADE)와 고아 객체](https://sun-22.tistory.com/73)

2021-11-23 10:23 UTC, slamdunk7575 commented on src/main/java/qna/domain/Answer.java
> +		return Objects.equals(id, answer.id);
지난 피드백 잊지 않고 반영해보셨네요 👍

2021-11-23 10:23 UTC, slamdunk7575 commented on src/main/java/qna/domain/DeleteHistory.java
> +		// java.util.Arrays.ArrayList != java.util.ArrayLit, Arrays.ArrayList는 불변한 리스트를 리턴한다. add() 메소드 사용불가
사용하지 않는 코드는 제거하는게 좋겠네요 🙏

2021-11-23 10:23 UTC, slamdunk7575 commented on src/test/java/qna/domain/AnswerTest.java
> +	void findAnswerWithQuestion() {
전체 테스트를 돌리면 아래와 같은 에러가 발생합니다.
`org.hibernate.PersistentObjectException: detached entity passed to persist`

연관 엔티티가 DB에 이미 저장되어 있는 상태에서 다시 persist 하는 경우 발생하는 것인데
위의 `cascade` 관련 피드백을 고민하면서 설정을 제거해볼 수 있지만 또 다른 오류를 만나게 되실거에요.

근본적으로 테스트에 사용되고 있는 `static 변수들`이 여러 테스트에 걸쳐 영향을 끼치고 있기 때문인데요.
서로 고립된 테스트가 될 수 있게 static 변수를 공유하지 않도록 해보시면 좋을 것 같습니다.

아래 내용은 참고만해주세요 :)
[테스트 픽스처 올바르게 사용하기](https://jojoldu.tistory.com/611)

2021-11-23 10:27 UTC, slamdunk7575 commented on src/test/java/qna/domain/DeleteHistoryTest.java
> +		UserTest.JAVAJIGI);
전체 테스트를 돌리면 아래와 같은 에러가 발생합니다.
`org.hibernate.PersistentObjectException: detached entity passed to persist`

연관 엔티티가 DB에 이미 저장되어 있는 상태에서 다시 persist 하는 경우 발생하는 것인데
위의 `cascade` 관련 피드백을 고민하면서 설정을 제거해볼 수 있지만 또 다른 오류를 만나게 되실거에요.

근본적으로 테스트에 사용되고 있는 `static 변수들`이 여러 테스트에 걸쳐 영향을 끼치고 있기 때문인데요.
서로 고립된 테스트가 될 수 있게 static 변수를 공유하지 않도록 해보시면 좋을 것 같습니다.

아래 내용은 참고만해주세요 :)
[테스트 픽스처 올바르게 사용하기](https://jojoldu.tistory.com/611)

2021-11-25 17:55 UTC, devhak2 commented on src/main/java/qna/domain/Answer.java
> +	private Question question;
Answer가 Question을 관리하는 것은 말씀주신대로 이상해 보입니다! cascade는 제거 해놓도록 하겠습니다! 말씀 주신대로 @ManyToOne은 지연 로딩으로 바꿔놓도록 하겠습니다!

2021-11-25 17:56 UTC, devhak2 commented on src/main/java/qna/domain/Answer.java
> +	private User writer;
cascade를 쓸때 주의해서 써야겠군요..! 해당 cascade는 제거하도록 하겠습니다

2021-11-25 18:02 UTC, devhak2 commented on src/test/java/qna/domain/DeleteHistoryTest.java
> +		UserTest.JAVAJIGI);
말씀 주신 피드백 부분중 cascade 제거와 함께 static 변수를 전부 제거 했습니다. 링크해주신 테스트 픽스처에 대해서도 읽어 보았는데 이렇게 하다보니 DeleteHistoryTest의 경우 집중해야할 DeleteHistory 객체를 위해서 User, Question, Answer를 전부 생성하고 저장한 뒤에 DeleteHistory 객체를 생성할 수 있어서 반복적인 코드가 나타나게 되는 것 같습니다. 마찬가지로 AnswerTest에서도 Answer 객체를 생성하기 위해 User, Question을 차례대로 생성하고 저장을 해야 하는데 이를 어떻게 해결할 수 있을까요? 또한 각 테스트 메소드에서 이 모든 생성 코드를 넣기가 버거워 결국 BeforeEach를 이용한 setUp 메소드를 만들게 되었는데요. 주신 링크에 보면 이런 패턴은 피해야 하는 것으로 나와 있습니다. 이를 위해 정적 팩토리 메소드를 만들기를 시도해 보았는데 해당 클래스에서는 repository를 사용할 수 없다보니 결국 DB에 저장하기 위해 setUp메소드에서 각 repository에 정적 팩토리 메소드에서 생성한 객체를 저장하는 코드가 다시 등장하게 되는 것 같습니다. 혹시 이런 것들을 어떻게 해결할 수 있을지 조언을 얻고 싶습니다!

2021-11-26 15:45 UTC, slamdunk7575 requested changes
피드백 반영 잘해주셨네요 👍 
QnaService 내의 로직들을 리팩토링 해볼 수 있을것 같은데요.
관련하여 피드백 남겨드렸습니다. 조금만 더 힘내주세요~!

2021-11-26 15:45 UTC, slamdunk7575 commented on src/main/java/qna/service/QnaService.java
> +	}
이번 미션의 핵심인 QnaService의 `delete() 메소드` 내의 비지니스 로직을 좀 더 간결하게 리팩토링 해보면 좋을 것 같습니다.
최종적으로 아래와 같이 되도록 각 도메인과 관련된 로직은 `도메인 내에서 수행`하도록 옮겨보면 좋겠네요.

   ```java
    @Transactional
    public void deleteQuestion(User loginUser, Long questionId) throws CannotDeleteException {
        Question question = findQuestionById(questionId);
        DeleteHistories deleteHistories = question.delete(loginUser);
        deleteHistoryService.saveAll(deleteHistories.getDeleteHistories());
    }
```

2021-11-26 15:45 UTC, slamdunk7575 commented on src/main/java/qna/service/QnaService.java
> +				new DeleteHistory(ContentType.ANSWER, answer.getId(), answer.getWriter(), LocalDateTime.now()));
`DeleteHistory` 내에 아래와 같이 `정적 팩토리 메소드`로 만들어 보면 좀 더 가독성을 높여줄 수 있겠네요 :)

```java
    public static DeleteHistory ofQuestion(Long contentId, User deletedBy) {
        return new DeleteHistory(ContentType.QUESTION, contentId, deletedBy);
    }

    public static DeleteHistory ofAnswer(Long contentId, User deletedBy) {
        return new DeleteHistory(ContentType.ANSWER, contentId, deletedBy);
    }
```

2021-11-26 15:45 UTC, slamdunk7575 commented on src/main/java/qna/domain/Question.java
>  	private String title;
> 모든 원시 값과 문자열을 포장한다.

`예: title` 을 객체로 포장하고 길이에 대한 검증을 해볼 수 있겠네요.
필요하다고 생각되는 부분에 적용해보시면 좋을 것 같아요.

2021-11-26 15:45 UTC, slamdunk7575 commented on src/test/java/qna/domain/QuestionTest.java
>  public class QuestionTest {
위의 리팩토링을 진행하다보면 Service 의 비지니스 로직들이 각 `Domain` 으로 이동을 하게 될텐데요.
예를들어, 현재 `QuestionTest`를 `QuestionRepositoryTest` 로 바꾸고 `Question 도메인에 대한 테스트`를 
별도로 만들어 보면 좋을 것 같습니다. 리팩토링 하면서 고민해보시면 좋겠어요 :)

2021-11-26 15:45 UTC, slamdunk7575 commented on src/test/java/qna/domain/DeleteHistoryTest.java
> +	}
> 말씀 주신 피드백 부분중 cascade 제거와 함께 static 변수를 전부 제거 했습니다. 링크해주신 테스트 픽스처에 대해서도 읽어 보았는데 이렇게 하다보니 DeleteHistoryTest의 경우 집중해야할 DeleteHistory 객체를 위해서 User, Question, Answer를 전부 생성하고 저장한 뒤에 DeleteHistory 객체를 생성할 수 있어서 반복적인 코드가 나타나게 되는 것 같습니다. 마찬가지로 AnswerTest에서도 Answer 객체를 생성하기 위해 User, Question을 차례대로 생성하고 저장을 해야 하는데 이를 어떻게 해결할 수 있을까요? 또한 각 테스트 메소드에서 이 모든 생성 코드를 넣기가 버거워 결국 BeforeEach를 이용한 setUp 메소드를 만들게 되었는데요. 주신 링크에 보면 이런 패턴은 피해야 하는 것으로 나와 있습니다. 이를 위해 정적 팩토리 메소드를 만들기를 시도해 보았는데 해당 클래스에서는 repository를 사용할 수 없다보니 결국 DB에 저장하기 위해 setUp메소드에서 각 repository에 정적 팩토리 메소드에서 생성한 객체를 저장하는 코드가 다시 등장하게 되는 것 같습니다. 혹시 이런 것들을 어떻게 해결할 수 있을지 조언을 얻고 싶습니다!

먼저 여러 테스트에서 사용되던 static 변수들을 잘 제거해주셨네요 💯 

각 테스트에서만 사용하는 조건들은 테스트 메소드 내에 작성하면 파악하기도 좋고 격리된 테스트가 됩니다.
테스트의 setup 에는 주로 테스트를 위한 환경을 셋팅하는 것이 좋습니다.

지금 같은 경우는 테스트내에서 조건을 바꿔가며 테스트 하는 것이 아니기 때문에 (영학님 말씀대로 중복이 발생하기 때문에)
`@BeforeEach`를 활용하여 잘 해주셨다고 생각합니다.

정답이 있는 것이 아니니 영학님이 미션 진행하시면서 좋은 테스트에 대해 고민해보시면 좋겠네요 😄

2021-11-27 17:34 UTC, devhak2 commented on src/main/java/qna/service/QnaService.java
> +	}
말씀 주신대로 리팩토링 진행 하였습니다! 다만 위와 같이 줄이게 되면서 Question 클래스 내에 인스턴스 멤버인 Answers(Answer 일급컬렉션)에 delete를 위임하게 되었는데요. Question <-> Answer간 연관 관계가 단순히 question_id에 의해 이루어지다 보니 Answers 내에서 deleted 된 Answer를 필터링 하는 로직이 생기게 되고 answerRepository.findByQuestionIdAndDeletedFalse 메소드를 사용하지 못하게 되었습니다. deleted의 cardinality가 2이기 때문에 인덱스가 있을 것 같진 않지만 (question_id, deleted) 인덱스가 존재한다면 성능적으로 손해를 보고 있는 로직이 될 것 같은데 혹시 좋은 방법이 있을까요?

2021-11-27 17:41 UTC, devhak2 commented on src/main/java/qna/service/QnaService.java
> +				new DeleteHistory(ContentType.ANSWER, answer.getId(), answer.getWriter(), LocalDateTime.now()));
말씀하신대로 정적 팩토리 메소드를 통해 가독성을 높여보았습니다!

2021-11-27 17:49 UTC, devhak2 commented on src/test/java/qna/domain/QuestionTest.java
>  public class QuestionTest {
말씀하신대로 기존의 QuestionTest는 Respository test가 되는 것 같아, Test 클래스 명을 바꾸어 보았습니다. 리팩토링을 진행하면서 생긴 Question의 delete메소드와 Answers의 delete 메소드를 위해 각각 테스트를 만들어 보았습니다!

2021-11-27 17:51 UTC, devhak2 commented on src/test/java/qna/domain/DeleteHistoryTest.java
> +	}
그렇군요! 조언 감사드립니다!

2021-11-27 17:58 UTC, devhak2 commented on src/main/java/qna/domain/Question.java
>  	private String title;
말씀주신 것처럼 DB가 아닌 애플리케이션 내에서 검증하기 위한 작업들을 위한 프로퍼티들로 Question의 title, User의 userId, password, name, email를 전부 포장해서 검증해볼 수 있을 것 같습니다. 다만 이렇게 되면 너무 많은 값들이 클래스로 포장되어 많은 수의 클래스가 생성되게 될 것 같습니다. 이 정도의 검증은 JSR 스펙중에 하나인 bean validation을 통해 클래스를 따로 만들지 않고 검증을 해볼 수 있을 것 같은데요. 어떤게 더 좋은 방법일까요? bean validation은 Java가 가진 스펙이지 객체지향의 스펙이 아니다 보니 다른 객체지향 언어에서는 이런 것이 안될 것 같기도 하고 단순 객체지향 관점에서 보자면 모든 단순 원시 값을 포장해서 검증하는 것이 맞는건지 의문이 듭니다. 혹시 이 부분에 대해서 조언을 들을 수 있을까요?

2021-11-28 08:45 UTC, slamdunk7575 approved these changes
리팩토링 깔끔하게 잘해주셨어요 👍
제가 단계를 착각하여 피드백을 먼저 드렸네요. 죄송합니다. 🙇
다음 단계는 코멘트만 확인해보시고 바로 리뷰요청 주셔도 좋을 것 같아요~!

2021-11-28 08:45 UTC, slamdunk7575 commented on src/main/java/qna/domain/Question.java
>  	}
깔끔하게 리팩토링 잘해주셨네요 👍

비교적 중요도가 낮은 `equals(), hashCode()` 메소드는 아래쪽에 배치하면 코드를 파악하는데 더 좋겠네요 😄
불필요한 `set-` 들도 전체적으로 정리를 한번 해보시면 좋을 것 같습니다.

(참고)
> 메서드들은 범위나 접근성을 기준으로 나누기 보다는 기능성에 의해서 구성되어야 한다. 
예를 들어, private 클래스 메서드가 두 개의 public 메서드들 사이에 존재할 수도 있다. 
이렇게 하는 목적은 코드가 더 쉽게 읽히고, 더 쉽게 이해되도록 돕기 위해서이다.

3.1.3 Class와 Interface 선언
[자바 코딩 규칙(Java Code Conventions)](https://myeonguni.tistory.com/1596)

2021-11-28 08:45 UTC, slamdunk7575 commented on src/main/java/qna/domain/Answers.java
> +	}
> 말씀 주신대로 리팩토링 진행 하였습니다! 다만 위와 같이 줄이게 되면서 Question 클래스 내에 인스턴스 멤버인 Answers(Answer 일급컬렉션)에 delete를 위임하게 되었는데요. Question <-> Answer간 연관 관계가 단순히 question_id에 의해 이루어지다 보니 Answers 내에서 deleted 된 Answer를 필터링 하는 로직이 생기게 되고 answerRepository.findByQuestionIdAndDeletedFalse 메소드를 사용하지 못하게 되었습니다. deleted의 cardinality가 2이기 때문에 인덱스가 있을 것 같진 않지만 (question_id, deleted) 인덱스가 존재한다면 성능적으로 손해를 보고 있는 로직이 될 것 같은데 혹시 좋은 방법이 있을까요?

좋은 질문을 해주셨네요 🥇

`@Where`를 활용하면 Question을 통해 삭제되지 않은 Answer를 가지고 올 수도 있습니다.
`@Where(clause = "deleted = false")`

2021-11-28 08:45 UTC, slamdunk7575 commented on src/main/java/qna/domain/User.java
> 말씀주신 것처럼 DB가 아닌 애플리케이션 내에서 검증하기 위한 작업들을 위한 프로퍼티들로 Question의 title, User의 userId, password, name, email를 전부 포장해서 검증해볼 수 있을 것 같습니다. 다만 이렇게 되면 너무 많은 값들이 클래스로 포장되어 많은 수의 클래스가 생성되게 될 것 같습니다. 이 정도의 검증은 JSR 스펙중에 하나인 bean validation을 통해 클래스를 따로 만들지 않고 검증을 해볼 수 있을 것 같은데요. 어떤게 더 좋은 방법일까요? bean validation은 Java가 가진 스펙이지 객체지향의 스펙이 아니다 보니 다른 객체지향 언어에서는 이런 것이 안될 것 같기도 하고 단순 객체지향 관점에서 보자면 모든 단순 원시 값을 포장해서 검증하는 것이 맞는건지 의문이 듭니다. 혹시 이 부분에 대해서 조언을 들을 수 있을까요?

`검증`을 위해 클래스를 분리해야 한다면 분리하지 않으셔도 괜찮습니다.
연습하는 과정이니 영학님이 필요하다고 생각되시는 부분을 객체로 만들어 보시면 좋을 것 같아요.

예를들어 `Email` 같은 경우는 객체로 포장하면 나중에 형식체크 같은 것도 해볼 수 있을 것 같아요.
형식 체크를 반영해야 하는 의미는 아닙니다 😄

2021-11-28 08:45 UTC, slamdunk7575 commented on src/main/java/qna/domain/Answers.java
> +
추가한 `Answers`에 대한 테스트도 해보면 좋을것 같아요.

2021-11-28 08:47 UTC, merged

2021-11-29 19:39 UTC, devhak2 commented on src/main/java/qna/domain/Question.java
>  	}
불필요한 메소드나 중요도가 낮은 메소드는 제거 및 위치를 바꾸어서 정리해보겠습니다~!

2021-11-29 19:44 UTC, devhak2 commented on src/main/java/qna/domain/Answers.java
> +	}
이런게 있었군요! 또 하나 배워가네요 감사합니다!

2021-11-29 21:08 UTC, devhak2 commented on src/main/java/qna/domain/User.java
넵!! 조언 감사드립니다.

2021-11-29 21:08 UTC, devhak2 commented on src/main/java/qna/domain/Answers.java
> +
Answers도 추가해보도록 하겠습니다!!