🚀 3단계 - 질문 삭제하기 리팩터링
next-step/jwp-qna pull request #368
Opened 2021-11-27 17:45 UTC by daehyun0

안녕하세요 동환님!
3단계 리뷰 요청 드립니다.
리뷰 자체도 많은 도움이 되고, 리뷰에도 정말 능숙하신것 같으셔서 멋지다는 생각이 드네요.
거의 혼자 일해왔다 보니, 리뷰에 익숙하진 않은데, 말씀해주시는 것들에 제 의지와 지식에 많은 도움이 되고 있습니다. 감사합니다 🙇

2021-11-28 14:54 UTC, na-mul requested changes
안녕하세요 대현님!
이번 미션의 마지막인 3단계도 잘 진행해주셨습니다! 👍
이번 과제는 본 과정에서도 특히 중요하다고 생각합니다.
코멘트 남겨드린 내용 검토해보시고, 다시 request 부탁드릴께요! 🙇‍♂️

2021-11-28 14:54 UTC, na-mul commented on src/main/java/qna/service/QnaService.java
>      }
좀 더 적극적으로 서비스 레이어의 로직을 도메인으로 옮겨보면 어떨까요?
극단적으로 말하면 서비스 레이어에 넣어도 괜찮은 로직은 repository를 사용하는 부분 뿐입니다.
`findQuestionById(questionId)`, `findAnswersByQuestionId(questionId)`, `deleteHistoryService.saveAll()` 이렇게 세개 뿐이라고 볼 수도 있습니다.

add하고 delete하는 부분은 도메인 안쪽으로 전부 옮겨주세요!

그리고 다른 곳에 코멘트로 언급해드리겠지만, `findAnswersByQuestionId(questionId)`의 호출도 서비스레이어에서 제거할 수 있는 방법이 있습니다.

2021-11-28 14:54 UTC, na-mul commented on src/main/java/qna/domain/Question.java
> +	private User writer;
음, 이 부분은 2단계에서 짚어드리면 더 좋았을 것 같다는 생각이 드네요.
이전 단계까지는 단순히 연관관계를 정의해보는 것이었죠.
이번 단계에서는 그렇게 정의한 연관관계를 이용해 어플리케이션을 더 객체지향적으로 짜보는 연습을 하게 됩니다.

`Question`도메인에서 `@OneToMany`를 이용해 Answer를 찾을 수 있게 수정해주세요!
기본적으로 연관관계는 `Answer` → `Question`으로 `@ManyToOne`만 설정해도 충분하고, 
`@OneToMany`는 그다지 권장되지 않는 것도 사실입니다.
그러나 `@OneToMany`를 사용할 떄 더욱 객체지향적으로 JPA를 사용할 수 있게 되지요.
`@OneToMany`를 사용하면, `QnaService`의 `deleteQuestion`메소드에서 굳이 `findAnswersByQuestionId(questionId)`를 호출하지 않아도, 
자동으로 로딩하게 됩니다. 그리고 역시 영속성 컨텍스트에서 관리되기에, 객체 수정 시 update도 문제없이 일어나게 됩니다.

그리고 하나 첨언하자면,
`List<Answer>`를 바로 `@OneToMany`하는 것 보다는 이왕 만들어주신 `Answers` 일급 콜렉션을 사용하는 방법이 좋을 것 같습니다.
`@Embedded`를 한번 찾아보셔도 좋을 것 같아요!

2021-11-28 14:54 UTC, na-mul commented on src/main/java/qna/domain/Answer.java
>  	}
equals 메소드에서 불필요한 필드에 대한 비교를 제외해주신 것은 좋지만,
그럴 경우 아래와 같이 두 객체가 있을 때, equals가 true가 되어버립니다.
왜냐하면 둘 다 id가 null이어서 equals가 true가 되어버리지요.

```
	public static final Answer A1 = new Answer(UserTest.JAVAJIGI, QuestionTest.Q1, "Answers Contents1");
	public static final Answer A2 = new Answer(UserTest.SANJIGI, QuestionTest.Q1, "Answers Contents2");
```

비즈니스 키를 equals에 포함하기 위해서는 어떤 것을 선택해야할 지 고민이 물론 저도 되네요 😭
사실 이번 과제에서는 기획문서가 있는 것도 아니고, 정답은 없습니다.
다만 위의 케이스 덕분에 id만 비교하는 것에 대해서는 수정을 부탁드립니다!

2021-11-28 14:54 UTC, na-mul commented on src/main/java/qna/domain/Answer.java
> +	}
이 로직을 Answer 안으로 옮겨주신 것은 정말 잘 해주셨습니다 👍

2021-11-29 18:58 UTC, daehyun0 commented on src/main/java/qna/domain/Answer.java
>  	}
이것저것 생각해보고 의견을 구하고 싶습니다!

Entity가 데이터베이스와 매핑되는 용도로 사용되는 경우와
데이터베이스에 저장되지는 않았지만 임시 자료형으로 사용되는 경우 두가지의 경우가 있을 것 같은데요..

이미 데이터베이스에 저장된 두개의 엔티티끼리의 비교를 위해서는 데이터베이스의 키를 사용하는게 반드시 필요할 것 같고,
임시 자료형끼리 사용되는 경우의 동일성을 비교하기 위해 사용하는 것을 비즈니스 키라고 생각했습니다.

그래서 가장 이상적인 조합은 Primary Key와 Unique Key를 equals의 키로 사용하는게 best라고 생각하는데 Answer 같은 경우는 unique key가 없어서 거의 모든 키를 사용하는게 맞지 않나 생각 했스빈다.

동환님은 이 경우 어떤 키를 사용하실지 궁금합니다!

2021-11-29 19:01 UTC, daehyun0 commented
QuestionTest의 119번 라인에서
> assertThat(answers.get()).isEqualTo(actual.getAnswers().get());
해당 코드를 아래와 같이 바꾸면 테스트에 실패합니다.
> assertThat(actual.getAnswers().get()).isEqualTo(answers.get());

혹시 어떤 이유일지 아시는게 있으면 힌트를 주실 수 있을까요?
일반적으로 assertThat(actual).isEqualTo(expected) 식으로 사용을 해와서 actual의 위치를 유지시키고 싶은데, 어떤 문제로 저런일이 일어나는지 몰라서 찾아 볼 수 있을 키워드 질문 드립니다!

2021-11-30 14:12 UTC, na-mul commented on src/main/java/qna/domain/Answer.java
>  	}
요구사항의 정의에 따라 다를 것 같아요. 
`답변의 내용을 수정할 수 없다`, `한 질문에는 한번만 답변을 달 수 있다` 이런 요구사항이 들어오냐에 마느냐에 따라서 equals의 필드가 달라질 수 있겠지요.

다만 이 경우에는 id만 비교하게되면 A1과 A2가 같다고 나와버리는 오류를 고치는 차원에서 한번 말씀드리게 되었습니다. 사실 그래서 저는 entity 자체를 equals로 비교하는 일을 아에 하지 않습니다. 내부에 비교가 필요한 영역만 묶어서 값 객체로 따로 두고, 그 값 객체를 비교하곤 합니다.

2021-11-30 15:06 UTC, na-mul commented
> QuestionTest의 119번 라인에서
> 
> assertThat(answers.get()).isEqualTo(actual.getAnswers().get());
> 해당 코드를 아래와 같이 바꾸면 테스트에 실패합니다.
> assertThat(actual.getAnswers().get()).isEqualTo(answers.get());
> 
> 혹시 어떤 이유일지 아시는게 있으면 힌트를 주실 수 있을까요?
> 일반적으로 assertThat(actual).isEqualTo(expected) 식으로 사용을 해와서 actual의 위치를 유지시키고 싶은데, 어떤 문제로 저런일이 일어나는지 몰라서 찾아 볼 수 있을 키워드 질문 드립니다!

내부구현은 알기 어렵지만, `actual.getAnswers().get()`을 얻으면 사실 저희는 List를 받았을 것으로 추측하지만, JPA 내부적으로는 `PersistentBag`라는 자체적인 일급 컬렉션으로 관리하는 모양입니다. 그렇기에 일반적인 ArrayList와 equals를 수행했을 때 예기치 못한 결과가 나오는 것 같아요. 

추측하건데 PersistentBag가 내부적으로 List를 포함하는 관계고 그 역은 성립하지 않기에,
`assertThat(List).isEqualTo(PersistentBag); `와 `assertThat(PersistentBag).isEqualTo(List); ` 중 하나만 만족하는 모양입니다.

결국 이럴 때는 테스트를 아래와 같이 수정하는 편이 낫습니다.
`assertThat(actual.getAnswers().get()).contains(answer);`

참고 부탁드릴께요!

2021-11-30 15:09 UTC, na-mul approved these changes
안녕하세요 대현님. 
깊은 고민을 담아 수정해주신 덕분에 미션을 마무리하기에 충분한 좋은 코드가 나왔네요.
고생이 많으셨습니다.
벌써 12월이네요. 이제 과정도 반환점을 돌았습니다.
남은 한달 마저 힘내셔서 많은 것을 얻어가실 수 있기를 바랄께요~  🙇‍♂️🙇‍♂️
추가적인 질문이 있다면 언제든 환영입니다!

2021-11-30 15:09 UTC, na-mul commented on src/main/java/qna/domain/Answers.java
>  	}
일급 콜렉션에서 내부 콜렉션을 get으로 어쩔 수 없이 내보낼 때는 불변 리스트로 바꿔 넘겨주시는 편이 좋습니다.
```suggestion
	public List<Answer> get() {
		return Collections.unmodifiableList(answers);
	}
```
요런 방법도 가능하니 참고 부탁드릴께요!

2021-11-30 15:09 UTC, merged