Step3
next-step/jwp-qna pull request #38
Opened 2021-05-29 14:58 UTC by yjs2952

포비님 영상처럼 3줄만 남기게 하려면 Question 과 Answer 와의 일대 다 관계를 활용한다면 가능할 것 같긴 한데
영상과는 다르게 answer 목록을 DB에서 가져오시길래 일단은 따로 리팩토링을 했습니다.
저 개인적으로도 일 대 다 관계를 사용하는 건 n+1 문제나 영속성 전이 과정에서 문제가 발생하는 등의 위험이 
동반될 것 같아 우선은 관계 매핑 없이 따로 리팩토링을 했습니다.
일대다 관계를 사용함에 있어 위험할 수 있는 상황과 안전한 상황 같은 것을 판단할 수 있는 기준같은 것이 있을까요?

2021-05-30 11:42 UTC, hhlyn0328 requested changes
서비스 로직을 도메인 로직으로 잘 리팩토링 해주셨네요 :+1:
몇 가지 코멘트 남겼으니 확인 부탁드려요 !

2021-05-30 11:42 UTC, hhlyn0328 commented on src/main/java/qna/domain/Answer.java
> +        if (!this.writer.equals(loginUser)) {
null 체크를 포함하는 Objects.equals 를 사용해보면 어떨까요?

2021-05-30 11:42 UTC, hhlyn0328 commented on src/main/java/qna/domain/Answer.java
> +        return new DeleteHistory(ContentType.ANSWER, id, writer);
ContentType 별 팩토리 메서드를 활용해보면 더 좋을 것 같아요

2021-05-30 11:42 UTC, hhlyn0328 commented on src/main/java/qna/domain/Answers.java
> +    }
같은 사이즈의 다른 형태로 매핑되는 것이니, stream 을 활용해보면 좋을 것 같아요 !

2021-05-30 11:42 UTC, hhlyn0328 commented on src/main/java/qna/service/QnAService.java
>      public void deleteQuestion(User loginUser, Long questionId) throws CannotDeleteException {
JPA가 없는, DB와 연동되지 않는 프로젝트였어도 
Question이 List<Answer> 를 가지지 않았을까 생각해보면 좋을 거 같습니다 
만약에 가졌을 것 같다면 그 이유는 무엇일까요? 
제 개인적은 생각은 탐색의 방향이  질문 -> 답변 으로 가는게 자연스럽기 때문에 그렇게 설계할 것 같아요 


일대다 연관관계를 주고, 3줄로 화끈하게 리팩터링 해볼까요? :fire: :fire:


JPA는 객체지향 패러다임과 관계형 DB 패러다임의 불일치를 해소시켜주는 역할을 하기 때문에
기술적인 이슈보다는, 객체간의 관계와 책임, 탐색에 대해서 우선 생각해보면 좋을 거 같아요 

그렇게 일단 필요한 관계를 맺은 다음 
그 구조에서 생길 수 있는 문제가 있는지 살펴보고 해결방법을 찾는것은 그 다음 순서인 것 같아요 
N+1 이 이슈가 될 것 같다면 아래와 같은 방법들을 고민해보겠죠? 

1. fetchJoin을 사용할 수 없는가? 
2. 패치타입 EAGER로 변경할 수는 없는가?
3. 배치사이즈 적용해볼 수 있는가?
4. 설계가 잘못된 것은 아닌가?   
등등등

2021-05-30 11:42 UTC, hhlyn0328 commented on src/main/java/qna/service/QnAService.java
> +        Answers answers = new Answers(findAnswers);
일대다 관계를 추가해보신다면, @Embeddable 어노테이션을 통해 일급컬렉션을 사용할 수 있습니다

2021-05-30 11:42 UTC, hhlyn0328 commented on src/test/java/qna/service/QnaServiceTest.java
> +        when(answerRepository.findByQuestionIdAndDeletedFalse(question.getId())).thenReturn((Collections.singletonList(answer)));
도메인으로 옮겨간 로직들에 대한 테스트도 작성해보시면 좋을 거 같습니다 :)

2021-05-31 01:06 UTC, yjs2952 commented on src/main/java/qna/domain/Answer.java
> +        if (!this.writer.equals(loginUser)) {
이런 방법이 있었네요. 미처 생각을 못했습니다. 감사합니다~ ㅎㅎ

2021-05-31 02:17 UTC, yjs2952 commented on src/main/java/qna/domain/Answer.java
> +        return new DeleteHistory(ContentType.ANSWER, id, writer);
좋은 방법인 것 같습니다. 그런데 네이밍이 어렵네요. 
이펙티브 자바에서 팩토리 메소드 네이밍 컨벤션이 있던데 조합이 어렵네요...

2021-05-31 02:25 UTC, yjs2952 commented on src/main/java/qna/domain/Answers.java
> +    }
시도를 했었는데 예외처리를 강제로 해야 되서 try - catch  문을 넣어야 하는데 너무 지저분해 보여서 for - each 문으로 처리 했습니다.
혹시 이 try - catch 를 안보이게 하는 방법이 있을까요? 
아니면 어쩔 수 없이 감싸야 할까요?

2021-05-31 15:49 UTC, hhlyn0328 approved these changes
피드백 반영을 잘해주셨네요 👍 
도메인 테스트코드도 잘 작성해주셔서 머지하겠습니다!! 

jpa 미션은 이로써 완료되었습니다!
끝까지 완주하시길 응원하겠습니다 :)

2021-05-31 15:49 UTC, hhlyn0328 commented on src/main/java/qna/domain/Answers.java
> +
try-catch가 필요했던 이유는 `CannotDeleteException` 을 checked exception으로 생성하셨기 떄문인데요 
결국 이 exception을 catch해서 runtimeException을 던진다면, CannotDeleteException 을 runtimeException을 상속하도록 하는 것은 어떨까요?

transaction rollback이 되려면 runtimeException이 발생해야하기 때문에 
수정이나 삭제등의 작업에서 발생하는 exception 은 rollback 도 고려해서 선언하시면 좋을 거 같아요 :)

2021-05-31 15:50 UTC, merged