Step1 - 엔티티 매핑
next-step/jwp-qna pull request #391
Opened 2022-05-17 10:44 UTC by tasklet1579

안녕하세요
Step1 엔티티 매핑 완료했습니다
Step1 풀 리퀘스트 하신 분들 보면 궁금한 점도 많으시고 진행 도중에 자기 생각을 잘 정리해서 전달하시던데 저는 그런 부분에서 어려움을 느낍니다..
특히 JPA는 사용해본 적이 없어서 일단 결과가 나오도록 수정은 했는데 아직 JPA에 대해서 체감되는 부분은 없습니다
기초 개념부터 공부를 해야할 것 같은데 이번 과정은 어떻게 접근하면 좋을까요..?

2022-05-18 04:28 UTC, seok-2-o requested changes
안녕하세요 😄 두번째 미션 리뷰어를 맡은 이재석입니다.

첫번째 미션 잘진행해주셨어요 👍 
JPA에 아직 익숙하지 않더라도 천천히 과정을 따라가면 큰 무리는 없을 것이라 생각해요.

익숙하지 않은 부분이 있다는것은 배울부분이 많다고 생각해도 괜찮지 않을까요?
일단 수업 들으신 이후에 어려우시다면 함께 어떻게 헤처 나갈지 고민해보아요 🔥 

앞으로 과정 진행하면서 저와 의견이 다르거나 궁금한점 있으면 
편하게 코멘트 또는 DM 남겨주세요.

성우님과 함께 할 수 있게 되어 무척 기쁜 마음입니다. :)
모쪼록 다음 코드 기대하며 기다리고 있을게요. 🙇

2022-05-18 04:28 UTC, seok-2-o commented on src/main/java/qna/domain/Answer.java
>      private boolean deleted = false;
```suggestion
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private Long writerId;
    private Long questionId;
    @Lob
    private String contents;
    private boolean deleted = false;
    @Column(nullable = false)
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;
```

2022-05-18 04:28 UTC, seok-2-o commented on src/main/java/qna/domain/Answer.java
>      private boolean deleted = false;
비지니스와 연관도가 낮은 필드를 아래로 위치시켜 가독성을 키울 수 있어요.

2022-05-18 04:28 UTC, seok-2-o commented on src/main/java/qna/domain/Answer.java
>      private boolean deleted = false;
또한 공통적으로 도메인들이 가지고 있는 필드나 컬럼들을 상속하고 자동으로 값이 입력되면 편리할텐데
이를 지원 하는 [JPA Auditing](https://webcoding-start.tistory.com/53) 기능이 있어요.
참고하여 리펙토링해보면 좋을 것 같아요.

2022-05-18 04:28 UTC, seok-2-o commented on src/test/java/qna/domain/StationRepositoryTest.java
> +@TestPropertySource(locations = "classpath:application-test.properties")
👍

2022-05-19 08:57 UTC, tasklet1579 commented on src/main/java/qna/domain/Answer.java
>      private boolean deleted = false;
안녕하세요
엔티티에서 순서를 변경해도 테이블 컬럼은 알파벳 순서대로 생성되네요
등록일자, 수정일자는 거의 모든 테이블에 들어가는 내용인데 유용하게 사용할 수 있을 것 같습니다

2022-05-20 00:17 UTC, seok-2-o approved these changes
피드백 반영 잘해주셨네요 👍 
이어서 다음미션 진행해주세요.

2022-05-20 00:17 UTC, merged