1단계 - 엔티티 매핑 리뷰 요청
next-step/jwp-qna pull request #401
Opened 2022-05-18 13:52 UTC by Su-hub9

안녕하세요! 리뷰어님😄 드디어 JPA 미션도 시작 됐네요ㅎㅎ
1단계 엔티티 매핑 과제 리뷰 요청 드립니다.

JPA는 경험이 많지 않아 과제 진행 전에 사전 공부도 좀 필요 했고 부족한 부분이 많았네요..
이번 단계에서는 엔티티 매핑이 메인이어서 관련된 리포지토리 테스트에 좀 더 신경을 썼고
도메인 로직에 대한 구현이나 테스트는 별도로 수정하지 않았습니다.

중복되는 속성을 사용하는 도메인이 많아 BaseEntity 클래스로 최소화 시켜 봤는데
그로 인해 요구사항에서 제시한 DDL 과 일부 다른 점이 있어 괜찮은 건지 고민이 좀 됐습니다..😭
(create_at 이나 update_at 컬럼이 전체 도메인에 다 추가가 되네요;;)

부족한 코드라 리뷰 하실 부분이 많을텐데 가감 없이 지적 해주시면 열심히 수정 해보겠습니다!!
감사합니다~

2022-05-19 14:23 UTC, parkeeseul requested changes
안녕하세요 수지님! JPA 미션을 함께 하게 된 박이슬 입니다! 😄 
1 단계 미션 잘 진행해 주셨네요! 👍  
몇 가지 코멘트 남겨두었으니 확인 부탁드립니다!
함께 이번 미션 잘 풀어나가 보아요! 화이팅 입니다 🔥

2022-05-19 14:23 UTC, parkeeseul commented on src/main/java/qna/domain/BaseEntity.java
> +public abstract class BaseEntity {
> Q. 중복되는 속성을 사용하는 도메인이 많아 BaseEntity 클래스로 최소화 시켜 봤는데
> 그로 인해 요구사항에서 제시한 DDL 과 일부 다른 점이 있어 괜찮은 건지 고민이 좀 됐습니다..😭
> (create_at 이나 update_at 컬럼이 전체 도메인에 다 추가가 되네요;;)

-> A. 요구 사항에 보시면 일부 entity 에서는 updateAt 컬럼을 가지고 있지 않는데요,
모든 entity 에서 baseEntity 를 상속받아 updateAt 컬럼이 생성되네요.
요구사항에 맞춰 해결해 보면 좋을 것 같아요 😄

2022-05-19 14:23 UTC, parkeeseul commented on src/main/java/qna/domain/BaseEntity.java
> +    protected LocalDateTime createdAt = LocalDateTime.now();
@CreatedDate 을 사용하면 Entity가 생성되어 DB에 insert 할때 시간이 자동으로 저장됩니다 😄

2022-05-19 14:23 UTC, parkeeseul commented on src/test/java/qna/domain/AnswerRepositoryTest.java
> +        answerRepository.flush();
flush 를 하시는 이유가 있으신가요? 😄

2022-05-19 15:08 UTC, Su-hub9 commented on src/main/java/qna/domain/BaseEntity.java
> +public abstract class BaseEntity {
하나만 다른데 그냥 써도 되지 않을까 했던 안일함이 이런 부분을 만들게 된 거 같네요ㅜㅜ 다시 한 번 반성하게 됩니다! 꼭 기억하고 요구사항은 맞출 수 있도록 노력 하겠습니다~

2022-05-19 15:09 UTC, Su-hub9 commented on src/main/java/qna/domain/BaseEntity.java
> +    protected LocalDateTime createdAt = LocalDateTime.now();
그렇군요! 초기화를 같이 사용하면서 중복 코드가 발생하게 됐네요😭
어노테이션에 대해서 좀 더 깊이 공부하고 사용 했어야 했네요..ㅜㅜ

2022-05-19 15:09 UTC, Su-hub9 commented on src/test/java/qna/domain/AnswerRepositoryTest.java
> +        answerRepository.flush();
확실히 commit 이 되는 시점을 명시적으로 표현하고 싶었습니다! 혹시 사용함으로 인해 단점이 있다면 소중한 의견 부탁 드립니다~ 리뷰 주신 의견 참고하여 수정 했습니다! 😄

2022-05-19 15:13 UTC, Su-hub9 commented
리뷰 주신 의견 최대한 반영하여 코드 수정 해보았습니다! 바쁜 시간 내서 정성껏 리뷰 해주셔서 감사합니다~! 😄

2022-05-20 10:03 UTC, parkeeseul approved these changes
피드백 잘 반영해 주셨네요! 👍 
질문 주신 사항에 코멘트 남겨두었으니 확인 부탁드립니다 😄 
다음 단계 진행해 주세요! 🔥

2022-05-20 10:03 UTC, parkeeseul commented on src/test/java/qna/domain/AnswerRepositoryTest.java
> +        answerRepository.flush();
단점이 있다기 보다는 flush를 사용하시는 목적이 따로 있으신지 궁금해서 질문을 드렸습니다.
트랜잭션이 종료되기 전에 직접 flush 를 호출하면 어떤 차이가 있을까요? 😄

2022-05-20 10:03 UTC, merged