Step1 - 엔티티 매핑
next-step/jwp-qna pull request #404
Opened 2022-05-18 15:00 UTC by yulmucha

반갑습니다.
리뷰 요청드립니다.
감사합니다.

2022-05-18 23:58 UTC, chae-yh requested changes
전율님 안녕하세요! jpa 리뷰를 맡은 채영훈이라고 합니다 : )
전체적으로 코드 잘 작성해주셨네요 👍 하지만 조금 더 수정해보면 좋을 만한 부분이 있어 코멘트 남겨드렸는데 확인 부탁드립니다

감사합니다 : )

2022-05-18 23:58 UTC, chae-yh commented on src/main/java/qna/domain/Answer.java
>      private String contents;
answer 테이블의 해당 필드의 타입은 clob인데 해당 내용을 표현할 좋은 자료형이 있지 않을까요...?

2022-05-18 23:58 UTC, chae-yh commented on src/main/java/qna/domain/DeleteHistory.java
> +    @Enumerated(EnumType.STRING)
적당한 자료형으로 표현한 부분 좋습니다 👍

2022-05-18 23:58 UTC, chae-yh commented on src/main/java/qna/domain/User.java
> +    private LocalDateTime updatedAt = LocalDateTime.now();
createdAt, updatedAt 이 반복적으로 나오네요! 공통으로 분리해줘도 좋을 것 같습니다 : )

2022-05-18 23:58 UTC, chae-yh commented on src/main/resources/application.yml
> +spring:
혹시 properties가 아니라 yml로 형식 변경한 이유가 있으신가요...?

2022-05-18 23:58 UTC, chae-yh commented on src/test/java/qna/domain/AnswerRepositoryTest.java
> +    @Test
@DisplayName을 써서 어떤 내용의 테스트인지 구체적으로 작성해줘도 좋을 것 같습니다 : )

2022-05-18 23:58 UTC, chae-yh commented on src/test/java/qna/domain/DeleteHistoryRepositoryTest.java
> +    void save() {
단순 save 테스트 만이 아니라 db에서 가져온 데이터가 동일한 객체인지를 검증하는 등의 테스트를 추가해도 좋지 않을까요...?

2022-05-18 23:58 UTC, chae-yh commented on src/main/java/qna/domain/Answer.java
>  public class Answer {
setId(Long id) 메소드는 혹시 어디에서 사용할까요..?

2022-05-18 23:58 UTC, chae-yh commented on src/main/java/qna/domain/User.java
>      private String userId;
user id는 unique constraint가 있는 것 같습니다!

2022-05-19 00:42 UTC, yulmucha commented on src/main/resources/application.yml
> +spring:
저만 그렇게 느끼는 걸 수도 있겠지만, 가독성 측면에서 더 좋다고 생각했습니다. 그리고 스프링 말고 다른 데서도 쓰이는 더 범용적인 형식으로 알고 있어서 변경했습니다.

2022-05-19 10:32 UTC, yulmucha commented on src/main/java/qna/domain/Answer.java
>  public class Answer {
사용하는 곳 없어요. 기존 코드가 꽤 많길래 요구 사항에 꼭 필요한 부분만 고치는 방향으로 가다가 미처 지우지 못했네요.

2022-05-20 03:41 UTC, chae-yh approved these changes
율님 안녕하세요 피드백 잘 반영해주셨습니다 👍 merge 진행하겠습니다!
코드 중에 조금 생각해보면 좋을만한 부분은 코멘트로 남겨두었는데 확인부탁드립니다

감사합니다 : )

2022-05-20 03:41 UTC, chae-yh commented on src/test/java/qna/domain/UserTest.java
>  public class UserTest {
UserTest면 User에 대한 도메인 테스트로 생각되는데, 실제로는 객체를 만들어주는 역할 밖에 하지 않네요. 해당 객체들을 UserRepositoryTest로 옮겨도 좋지 않을까요...?

2022-05-20 03:41 UTC, chae-yh commented on src/test/java/qna/service/QnaServiceTest.java
>      public void delete_답변_중_다른_사람이_쓴_글() throws Exception {
메소드명은 영문으로, @DisplayName은 한글로 통일해서 써도 좋지 않을까요...?

2022-05-20 03:41 UTC, chae-yh commented on src/main/java/qna/domain/BaseEntity.java
> +public abstract class BaseEntity {
abstract class 로 잘 분리해주셨습니다! @MappedSuperclass 클래스 사용도 좋네요 👍

2022-05-20 03:41 UTC, chae-yh commented on src/main/java/qna/domain/BaseEntity.java
> +    private LocalDateTime createdAt = LocalDateTime.now();
이런 부분은 JPA auditing 기능으로 값을 넣어줄 수도 있습니다 참고만 부탁드립니다 : )

2022-05-20 03:41 UTC, chae-yh commented on src/main/java/qna/domain/BaseEntity.java
> +    private Long id;
id를 base entity로 분리한 부분은 조금 생각할 필요가 있을 것 같습니다! 성격적으로 봐도 도메인에 속해있다고 생각이 들고, entity마다 id를 만드는 전략이 다를 수 있을 것 같아요
관련하여 율님은 어떻게 생각하시나요...?

2022-05-20 03:41 UTC, chae-yh commented on src/main/java/qna/domain/DeleteHistoryRepository.java
> +    Optional<DeleteHistory> findById(Long id);
findById는 jpa에서 자동으로 만들어줄텐데 혹시 새롭게 정의하신 이유가 있으신가요..?

2022-05-20 03:41 UTC, chae-yh commented on src/test/java/qna/service/QnaServiceTest.java
해당 테스트가 실패하네요 다음 미션 때 확인 부탁드립니다!

2022-05-20 03:41 UTC, merged

2022-05-20 13:30 UTC, yulmucha commented on src/main/java/qna/domain/DeleteHistoryRepository.java
> +    Optional<DeleteHistory> findById(Long id);
아 자동으로 만들어주는군요! 착각했습니다.

2022-05-20 13:49 UTC, yulmucha commented on src/main/java/qna/domain/BaseEntity.java
> +    private Long id;
물론 엔티티마다 전략이 다른 게 일반적인 상황이라면 `id`를 포함시킨 `BaseEntity`의 효용성이 많이 떨어지겠지만, 일부 특수한 경우 외에 대부분 전략이 같다면 반복 제거 측면에서는 포함시키는 게 낫지 않을까 싶습니다. 하지만, 사용 목적이 `createdAt`이나 `updatedAt` 등과 같이 잊기 쉬운 것들을 실수로 빠뜨리는 걸 방지하기 위함이라면 `id`를 빠뜨릴 일은 없으니 `BaseEntity`에 포함시키지 않는 것이 맞을 것 같습니다.

2022-05-20 13:59 UTC, yulmucha commented on src/test/java/qna/domain/UserTest.java
>  public class UserTest {
동의합니다. 참고로, 실습 저장소를 처음 클론했을 때부터 이미 코드들이 꽤 작성돼 있었고 요구 사항에도 언급된 게 없어서 어디까지 손을 대야 할지 가늠이 되지 않아 일단 그냥 두었던 거에요. 아래 영문_한글로 된 테스트도요.