Step1 - 리뷰 요청 드립니다.
next-step/jwp-qna pull request #418
Opened 2022-05-19 17:00 UTC by jiyeonghwang

안녕하세요. 황지영 입니다.😊
엔티티 매핑 PR 요청 드립니다!
잘 부탁드리겠습니다!

2022-05-20 02:19 UTC, jhhj424 requested changes
안녕하세요 지영님 🙇🏻‍♂️
JPA 미션을 함께 진행하게 된 신지호 입니다 :)
1단계 미션 잘 작성해주셨네요, 소소한 변경사항을 이번 단계에서 적용하면 좋을 것 같아서 RC 한번 드리겠습니다. 확인 한번 부탁드립니다 🙏
앞으로 궁금하신 점 있으시면 언제든 코멘트&DM 환영합니다 ~ 😊

2022-05-20 02:19 UTC, jhhj424 commented on src/main/java/qna/Application.java
> +@EnableJpaAuditing
`@EnableJpaAuditing` 잘 활용해주셨네요 :)

2022-05-20 02:19 UTC, jhhj424 commented on src/main/java/qna/domain/Answer.java
> +    protected Answer() {
엔티티의 접근제어자를 방어적으로 잘 변경 해주셨네요 👍

2022-05-20 02:19 UTC, jhhj424 commented on src/main/java/qna/domain/Answer.java
> +    private LocalDateTime createdAt;
여러 엔티티에서 공통으로 사용하고 있는 필드들이 있는데, 중복을 제거할 수 없을까요?
이번 엔티티 설정 단계에서 진행해주시면 좋을 것 같아요 :)

참고 키워드: `@MappedSuperclass`

2022-05-20 02:19 UTC, jhhj424 commented on src/main/java/qna/domain/Question.java
> +    @Column(name = "title", nullable = false)
```sql
create table question
(
    id         bigint generated by default as identity,
    contents   clob,
    created_at timestamp    not null,
    deleted    boolean      not null,
    title      varchar(100) not null,
    updated_at timestamp,
    writer_id  bigint,
    primary key (id)
)

```

조금 다른 부분이 있는데, 확인 부탁드릴게요 :)

2022-05-20 02:19 UTC, jhhj424 commented on src/main/java/qna/domain/User.java
> +    private LocalDateTime updatedAt;
```sql
create table user
(
    id         bigint generated by default as identity,
    created_at timestamp   not null,
    email      varchar(50),
    name       varchar(20) not null,
    password   varchar(20) not null,
    updated_at timestamp,
    user_id    varchar(20) not null,
    primary key (id)
)

alter table user
    add constraint UK_a3imlf41l37utmxiquukk8ajc unique (user_id)

```

여기도 다시 확인해주시면 좋을 것 같습니다 ~

2022-05-20 02:19 UTC, jhhj424 commented on src/main/java/qna/domain/Question.java
> +    @Lob
`@Lob` 을 잘 활용해주셨네요 !

그리고 전체적으로 `@Column` 어노테이션을 사용해주셨는데, 저는 보통 해당 필드(컬럼)에 특정 속성이 필요한 경우만 사용하곤 하는데, 취향차이인 것 같긴합니다 :)

2022-05-20 02:19 UTC, jhhj424 commented on src/test/java/qna/repository/AnswerRepositoryTest.java
> +public class AnswerRepositoryTest {
모든 엔티티에 대한 테스트 잘 작성해주셨네요 💯

2022-05-22 05:35 UTC, jiyeonghwang commented on src/main/java/qna/domain/User.java
> +    private LocalDateTime updatedAt;
공통으로 사용할 `BaseTimeEntity`를 사용하여 개선하였습니다!

2022-05-22 05:35 UTC, jiyeonghwang commented on src/main/java/qna/domain/Question.java
> +    @Column(name = "title", nullable = false)
앗.. 길이제한 추가하였습니다!

2022-05-22 05:36 UTC, jiyeonghwang commented on src/main/java/qna/domain/Answer.java
> +    private LocalDateTime createdAt;
`BaseTimeEntity`를 생성하여 상속받도록 개선하였습니다!

2022-05-22 05:39 UTC, jiyeonghwang commented
자세한 피드백 감사드립니다! 😀
수정 필요한 부분 개선하였습니다! 확인 부탁드리겠습니다.

2022-05-23 03:49 UTC, jhhj424 approved these changes
안녕하세요 지영님~🙇🏻‍♂️
JPA 1단계 피드백 반영 잘 해주셨네요 💯 
바로 머지 하겠습니다, 다음 단계도 화이팅입니다 👊

2022-05-23 03:49 UTC, jhhj424 commented on src/main/java/qna/domain/BaseTimeEntity.java
> +public abstract class BaseTimeEntity {
`@MappedSuperclass` 를 활용해서 중복을 잘 제거해주셨네요, 해당 엔티티는 단독으로 구현되어 사용되지 않으니 `abstract` 추상클래스로도 잘 작성해주셨습니다 💯

2022-05-23 03:49 UTC, jhhj424 commented on src/main/java/qna/domain/Question.java
> +    @Column(name = "title", nullable = false, length = 100)
👍

2022-05-23 03:49 UTC, merged