2단계 - 연관 관계 매핑
next-step/jwp-qna pull request #430
Opened 2022-05-20 17:34 UTC by tyakamyz

안녕하세요 리뷰어님
2단계 - 연관 관계 매핑 PR 드립니다 :)

요구사항에 양방향/단방향에 대한 언급이 따로 없어서 기본적으로는 단방향으로 작성했고,
학습을 위해 'fk_answer_to_question' 부분만 양방향으로 작성해보았습니다

이번 리뷰도 잘부탁드리겠습니다!
감사합니다

2022-05-21 02:46 UTC, seokhongkim requested changes
시현님, JPA 2단계 미션 잘 진행해주셨습니다. 👍 
1단계에서 드린 피드백 반영도 잘 해주셨네요.

피드백과 함께 고민해보시면 좋을 것 같은 질문을 남겼습니다.
제가 처음 JPA를 사용했을 때 잘 몰랐던 부분이라 한 번 질문으로 남겨봤습니다. 😀

2022-05-21 02:46 UTC, seokhongkim commented on src/main/java/qna/domain/DeleteHistory.java
>      public boolean equals(Object o) {
`equals` 가 `DeleteHistory` 엔티티 에 대해서만 오버라이드 되어 있네요.

1. 엔티티의 `equals` 는 어떤 기준으로 구현하면 좋을까요?
2. 다른 엔티티 `equals` 구현이 필요할까요? `DeleteHistory` 에서도 제거해야 할까요?

2022-05-21 02:46 UTC, seokhongkim commented on src/main/java/qna/domain/Answer.java
> +    @ManyToOne(fetch = FetchType.LAZY)
`FetchType.LAZY` 로 사용하신 이유가 있을까요?
모든 연관관계마다 특정 타입으로 설정하신 이유가 있을 것 같아요!

2022-05-21 02:46 UTC, seokhongkim commented on src/main/java/qna/domain/Answer.java
> +                ", question=" + question +
`FetchType.LAZY` 로 설정된 대상 객체를 `toString` 에서 출력할 때 유의해야 할 점은 어떤 게 있을까요?
`toString` 구현을 변경해야 할까요? `FetchType` 을 변경하는 게 필요할까요?

2022-05-21 02:46 UTC, seokhongkim commented on src/main/java/qna/service/QnaService.java
>          for (Answer answer : answers) {
`answers` 를 꺼내올 때 `Question` 에 연관된 관계에서 가져오신 것이 아닌 것 같아요.
`Question` 과 연관관계가 생성되었으니, 이제 `Question` 에게 삭제해야 할 `answers` 를 달라고 요청할 수 있지 않을까요?

2022-05-21 02:46 UTC, seokhongkim commented on src/main/java/qna/domain/Question.java
> +        this.answers.add(answer);
`answer.toQuestion` 구현을 보니, 이 메소드를 호출할 때 `answers` 에 `add` 가 2번 될 것으로 보여요.
어떻게 수정하면 좋을까요?

2022-05-21 02:46 UTC, seokhongkim commented on src/test/java/qna/domain/DeleteHistoryRepositoryTest.java
> +        DeleteHistory findDeleteHistory = deleteHistoryRepository.findById(deleteHistory.getId()).get();
JPA를 처음 사용하셨다고 하여 한 번 생각해볼 수 있는 질문을 드려봅니다!

1. 여기서 가져온 `findDeleteHistory` 는 DB에서 조회한 값일까요?
2. 그렇다면, `getDeleteBy` 에서 가져온 `Writer` 객체도 새로 만들어진 객체일까요? 그게 아니라면 아래 `assert` 문은 어떻게 성공했을까요? 🤔 

바로 답이 생각나신다면 학습을 충분히 하신거라고 생각됩니다. 💯 
고민되신다면, `persistence context`, `persistence context cache`, `entity lifecycle` 등의 키워드를 학습해보시면 좋을 것 같아요!

2022-05-21 07:24 UTC, tyakamyz commented on src/main/java/qna/domain/DeleteHistory.java
>      public boolean equals(Object o) {
equals 사용에 대한 답변을 생각하기 위해 영속성 컨텍스트와 프록시에 대해 많은 공부를 하게 되네요
우선 질문해주신 내용에 답변은
1. 영속성 컨텍스트와 프록시 객체, 비영속성 또는 준영속성 상태 상태처럼
동일성이 아닌 동등성으로 비교해야할 경우
그리고 복합키를 사용하는 경우에 구현해야 한다고 생각하였습니다
2. 항상 동일성이 보장되는 것이 아니기 때문에 모두 구현하는 것이 맞는 것 같습니다


구현한 코드가 올바른지 잘 모르겠어서 확인 한번만 부탁 드리겠습니다ㅜ
- 프록시 타입 비교는 == 비교 대신 instanceof를 사용
- 접근자 메소드(get)를 사용

두가지를 이용한 구현을 시도하였는데

`       User writer = em.persist(UserTest.JAVAJIGI);
        Question question = em.persist(new Question("title1", "contents1").writeBy(writer));

        Answer answer = new Answer(writer, question, "Answers Contents1");
        em.persist(answer);
        em.flush();
        em.clear();

        Answer findAnswer = em.find(Answer.class, answer.getId());
        assertEquals(answer, findAnswer);`

위 코드처럼 구현할 경우
findAnswer 에서 question을 비교할 때 getAnswers() 를 실행 할 때 
프록시 객체를 가져오게 되면서 answer의 question에는 answer와 조인되기 이전에 시점이라 getAnswers()값이 null 이기 때문에 이부분이 문제가 되네요
고민끝에 id값이 null이 아닐 때 id값을 기준으로 비교하도록 구현하였는데 이렇게 해결해도 괜찮은건지 궁금합니다

2022-05-21 07:27 UTC, tyakamyz commented on src/main/java/qna/domain/Answer.java
> +    @ManyToOne(fetch = FetchType.LAZY)
즉시로딩의 경우 예상치 못한 쿼리가 실행되는 등의 문제가 있어서 (ex: N+1 문제) 즉시로딩으로 설정해주는 것이 좋다고 학습하였습니다!

2022-05-21 07:39 UTC, tyakamyz commented on src/main/java/qna/domain/Answer.java
> +                ", question=" + question +
무한 루프가 발생할 수 있는 문제가 있네요!
LAZY 타입을 변경하기 보다는 
연관 관계 매핑되는 경우 @ToString(exclude = "question") 등의 방법을 사용해야할 것 같습니다

2022-05-21 07:48 UTC, tyakamyz commented on src/test/java/qna/domain/DeleteHistoryRepositoryTest.java
> +        DeleteHistory findDeleteHistory = deleteHistoryRepository.findById(deleteHistory.getId()).get();
1. 영속성 1차 캐시에서 가져온 값이라 DB에서 조회된 값이 아니네요! ㅜ
2. writer 역시 writer 1차 캐시값이라 동일성이 보장되어 성공한 케이스였네요!

clear()를 통해 준영속성 상태로 다시 테스트 진행하겠습니다

2022-05-21 09:48 UTC, tyakamyz commented
피드백 모두 반영하여 수정 완료하였습니다!

개념적인 부분을 모르는 게 많아서 학습하는데 굉장히 오랜 시간이 걸렸네요ㅜ
아직 많이 부족한 느낌이라 꾸준히 학습해야 할 것 같습니다
중요한 부분들 짚어주셔서 너무 감사드립니다!

수정한 부분들 확인 부탁드리겠습니다 :)

2022-05-21 09:50 UTC, tyakamyz commented
피드백 모두 반영하여 수정 완료하였습니다!

개념적인 부분을 모르는 게 많아서 꾸준히 학습해야 할 것 같습니다ㅜ
중요한 부분들 짚어주셔서 너무 감사드립니다!

수정한 부분들 확인 부탁드리겠습니다 :)

2022-05-21 13:55 UTC, seokhongkim commented on src/main/java/qna/domain/Answer.java
> +    @ManyToOne(fetch = FetchType.LAZY)
N+1 문제를 해결하는 다른 방법도 같이 학습해보시면 도움이 될 것 같네요!
`LAZY` 로 사용하는 경우 트랜잭션 외부에서 접근할 때 문제가 발생할 수 있으므로, `EAGER` 와 `LAZY` 를 사용하는 기준도 같이 고민해보시면 좋겠습니다. 😀

2022-05-21 13:56 UTC, seokhongkim commented on src/main/java/qna/domain/Answer.java
> +                ", question=" + question +
말씀하신 무한 루프 이슈도 있습니다.
이 부분은 `toString` 구현의 이슈이고, `FetchType` 과 관련된 이슈는 `toString` 에서는 `FetchType.LAZY` 연관관계인 객체를 사용하는데, `toString` 이 트랜잭션 외부에서 처리된다는 보장은 어려울 것 같네요.

2022-05-21 14:18 UTC, seokhongkim requested changes
시현님, 피드백 드린 내용에 대해 충분히 학습하고 고민하고 반영해주신 것 같아요. 💯 
주말에도 미션 진행을 열심히 하시는 모습이 좋습니다. 👍 

간단한 피드백 조금 남겼으니, 확인 부탁드립니다!

2022-05-21 14:18 UTC, seokhongkim commented on src/main/java/qna/service/QnaService.java
> -        List<Answer> answers = answerRepository.findByQuestionIdAndDeletedFalse(questionId);
이제 사용하지 않게 된 메소드는 제거해도 괜찮겠네요!

2022-05-21 14:18 UTC, seokhongkim commented on src/main/java/qna/service/QnaService.java
> +        List<Answer> answers = question.getAnswers();
기존에는 `deleted = false` 조건도 있었는데, 현재는 모든 답변을 다 가져오는 것 같네요.
현재 구현상 답변만 삭제하는 기능이 없어서 이슈는 아니겠으나, 기존 로직과 달라진 부분이라 고민해보시면 좋겠습니다. 😀

2022-05-21 14:18 UTC, seokhongkim commented on src/test/java/qna/service/QnaServiceTest.java
> +        //when(answerRepository.findByQuestionIdAndDeletedFalse(question.getId())).thenReturn(Arrays.asList(answer));
사용하지 않는 코드는 주석 처리하지 말고, 삭제하셔도 괜찮을 것 같아요!

2022-05-21 14:18 UTC, seokhongkim commented on src/main/java/qna/domain/DeleteHistory.java
>      public boolean equals(Object o) {
엔티티의 `equals` 구현에 대해서는 너무 다양한 의견이 있기에, 다양한 구현의 장단점을 알아보시고 적당한 기준을 선택하시면 될 것 같습니다.

먼저, 구현하신 부분에 대해서는 제 생각에는 괜찮을 것 같습니다. 😀 
프록시에 대한 고민도 하시며 많은 공부를 하신 것 같아 좋습니다. 👍 

이번에 구현하신 방법 외에도 PK, UK(Business Key 인 경우)만 비교하는 경우도 있습니다.
엔티티가 영속성 컨텍스트에서 관리되는 상황에서 주로 비교할 것이라는 가정이 포함되어 있겠죠.

`hibernate entity equals` 와 같은 키워드로 검색해보시면 더 다양한 방법이 나올 수 있으니, 이 내용도 참고해보시면 좋을 것 같습니다!

2022-05-21 14:18 UTC, seokhongkim commented on src/main/java/qna/domain/Answer.java
>      public void toQuestion(Question question) {
`toQuestion` 은 `Answer` 가 `setQuestion` 이상의 역할을 수행하기 위해 제공해주는 메소드로 보이네요.
`Question`, `Answer` 모두 답변을 달았을 때 연관관계를 맺어주기 위한 메소드를 제공하고 있는데, 두 곳에서 모두 제공할 필요가 있을까요?
`setter` 를 제외하고, `Question` 에서만 `Answer` 를 추가할 수 있는 메소드를 제공해주거나, `Answer` 에서만 `Question` 과 연관관계를 맺을 수 있는 메소드를 제공한다면 문제가 있을까요?

두 곳에서 연관관계를 잘 맺어주기 위한 코드가 관리되며 복잡도가 올라간 것 같은데, 엔티티가 아닌 일반 객체라면 질문/답변에 모두 서로 연결해주기 위한 메소드가 필요할까요?

2022-05-21 14:46 UTC, tyakamyz commented on src/main/java/qna/domain/DeleteHistory.java
>      public boolean equals(Object o) {
hibernate entity equals 에 대해서도 공부해보겠습니다!
감사합니다

2022-05-21 14:47 UTC, tyakamyz commented on src/main/java/qna/domain/Answer.java
> +                ", question=" + question +
트랜잭션에 대해서는 생각해보지 못했네요
그 부분도 같이 학습하겠습니다!
좋은 리뷰 감사드립니다 :)

2022-05-21 14:59 UTC, tyakamyz commented on src/main/java/qna/domain/Answer.java
>      public void toQuestion(Question question) {
연관 관계를 이어준다는 포인트만 생각한 것 같네요
List를 가지고 있는 Question 객체에서 처리하도록 수정하겠습니다!

2022-05-21 15:49 UTC, tyakamyz commented
피드백 반영하였습니다!
확인 부탁드리겠습니다

꼼꼼한 리뷰 감사드립니다 :)

2022-05-22 03:01 UTC, seokhongkim approved these changes
시현님, JPA 2단계 미션 잘 진행해주셨어요! 👍 

2단계 PR은 머지하도록 하겠습니다.
코멘트 하나 남긴 것은 다음 단계에서 반영하셔도 괜찮을 것 같습니다.

그럼 3단계에서 뵙겠습니다! 😀

2022-05-22 03:01 UTC, seokhongkim commented on src/main/java/qna/domain/Question.java
> -        answer.toQuestion(this);
`answer` 에도 연관관계 설정은 필요하므로 `answer.setQuestion` 은 필요할 것 같아요! 😀

2022-05-22 03:02 UTC, merged