Step2 - 연관 관계 매핑
next-step/jwp-qna pull request #470
Opened 2022-05-22 14:57 UTC by kmmin78

안녕하세요, 리뷰어님! 🙇‍♂️

Step2 - 연관 관계 매핑 PR 드립니다.

아직 양방향의 필요성을 느끼진 못해서 단방향 매핑을 우선으로 진행하였습니다.

이번 리뷰도 잘부탁드립니다! 🙂

2022-05-22 15:37 UTC, joojimin requested changes
안녕하세요~ 민성님!
피드백이라고 하기에는 쪼금 성격이다르지만 같이 논의해보면 좋을 내용이있어서 RC드렷습니다!
간단하게 확인후 생각해보시고 리뷰재요청 부탁드려요~ㅎㅎ

2022-05-22 15:37 UTC, joojimin commented on src/main/java/qna/docs/README.md
> +    - [x] user 단방향 매핑
요구사항 정리 👍 👍

2022-05-22 15:37 UTC, joojimin commented on src/main/java/qna/domain/Answer.java
> +    @ManyToOne(fetch = FetchType.LAZY)
지연로딩 👍 👍

2022-05-22 15:37 UTC, joojimin commented on src/main/java/qna/domain/AnswerRepository.java
> +    List<Answer> findByQuestionAndDeletedFalse(Question question);
흠.. 이부분이 저도 리뷰하기가 제일 고민되는 부분인데요!
아직 양방향의 필요성을 느끼진 못해서 단방향 매핑을 우선으로 진행하였습니다. << 라고하셔서 비슷한 생각을 하지않았나 싶기도한데 
저도 실제 실무에서는 양방향 매핑을 최대한 지양하려고 하고있습니다! ( 관리가 어렵고, 자칫 성능저하를 일으키는 실수가 생길수있어서 ) 

하지만 저희 미션이 객체지향적으로 생각하고 JPA를 공부하는 방향이다보니 해당부분을 Answer과 Question의 양방향매핑으로 해결해보면 어떨까요~?

2022-05-22 17:23 UTC, kmmin78 commented on src/main/java/qna/domain/AnswerRepository.java
> +    List<Answer> findByQuestionAndDeletedFalse(Question question);
넵! 양방향 매핑으로 Question에서 역방향으로 조회하도록 구현하겠습니다!

2022-05-23 03:32 UTC, joojimin approved these changes
안녕하세요~ 민성님!!
JPA 2단계 미션도 고민많이해주시고 잘 작성해주신것같습니다!! 💯 
다음미션도 화이팅입니다!

2022-05-23 03:32 UTC, merged