3단계 - 질문 삭제하기 PR입니다.
next-step/jwp-qna pull request #493
Opened 2022-05-23 15:20 UTC by tj3828

안녕하세요!
3단계 질문 삭제하기 입니다!

1단계에서 질문드렸던 repository와 entity 테스트 분리에 관해서 분리하니 정말 테스트가 편하고 정확해지는 걸 느꼈습니다 ㅎㅎ

2022-05-24 16:02 UTC, parkeeseul requested changes
3 단계 잘 진행해 주셨네요! 👍 
소소한 코멘트 남겨두었으니 확인 부탁드립니다 😄 
즐거운 수요일 되세요! 🔥

2022-05-24 16:02 UTC, parkeeseul commented on src/main/java/qna/service/QnaService.java
>          deleteHistoryService.saveAll(deleteHistories);
리팩토링 잘 진행해 주셨네요! 👍

2022-05-24 16:02 UTC, parkeeseul commented on src/main/java/qna/domain/Question.java
> +
Question 가 Answer 를 참조하게 되었네요! 👍 

Answer 에서 Question 를 참조해야 할 이유는 있을까요? 
어떻게 생각하시나요? 😄

2022-05-25 12:42 UTC, tj3828 commented on src/main/java/qna/domain/Question.java
> +
음.. 당연히 아시겠지만..!
@OneToMany 단방향(Question에서 Answer 참조)이라면 update 쿼리나 관리상 문제가 있어 개인적으로 양방향을 선호합니다.

물론,, 객체입장에서는 양방향이 필요없는데 수정될 수 있는 루트가 오픈되어 있어 아닐 수도 있지만,
테이블과 연관지어 엔티티를 바라봤을 때는 훨씬 가독성(?)이 좋고, 의도하지 않은 update쿼리 방지용으로  
이번 미션에서도 @ManyToOne (Answer에서 Question 참조)를 굳이 제거하진 않았습니다!

혹시 비지니스 역할에 맞게  단방향으로 관리하는게 더 좋을까요??

2022-05-26 08:34 UTC, parkeeseul commented on src/main/java/qna/domain/Question.java
> +
비즈니스 적으로는 Answer 에서 Question 알 필요가 없기 때문에 
객체의 관점 보다는 좀 더 디비에 맞춰 설계가 되는데요. 정답이 있기 보다는 트레이드 오프의 영역인 것 같아요 😄 
탁종님의 의견이 궁금해서 여쭤보았는데 잘 설명해 주셨네요! 👍

2022-05-26 08:36 UTC, parkeeseul approved these changes
의견 주신 부분에 추가적인 의견 남겨두었으니 확인 부탁드립니다!
이만 머지하도록 하겠습니다! 😄 

피드백 반영해 주시느라 고생 많으셨고
남은 미션도 꼭 완주하셔서 많은 인사이트 얻어가시길 바라요! 😄 
오늘 수업도 재밌게 들으시고 앞으로도 화이팅 입니다 🔥

2022-05-26 08:36 UTC, merged