Step3 - 질문 삭제하기 리팩터링
next-step/jwp-qna pull request #494
Opened 2022-05-23 15:22 UTC by june2

안녕하세요 리뷰어님~ 

미션 3단계 완료하여 pr드리오니 리뷰 부탁드려요~~

감사합니다.!

2022-05-24 07:58 UTC, joojimin requested changes
안녕하세요~ 준영님!!
3단계 미션도 정말고생하셧습니다!
몇가지 피드백 드렸으니 확인후 리뷰재요청 부탁드려요~!!

2022-05-24 07:58 UTC, joojimin commented on README.md
> +- [x] 질문과 답변 삭제 이력에 대한 정보를 DeleteHistory를 활용해 남긴다.
요구사항 정리 👍 👍 👍

2022-05-24 07:58 UTC, joojimin commented on src/main/java/qna/domain/Answer.java
> +        return new DeleteHistory(ContentType.ANSWER, id, writer);
`new DeleteHistory(ContentType.ANSWER, id, writer)`
`new DeleteHistory(ContentType.Question, id, writer)`
두가지의 생성타입이 있는거같아요! Enum을 파라미터로 받아서 생성하게되면 자칫 잘못된 Enum 케이스를 넣을 수도 있고 사용자가 명확하게 인지못할거같습니다!

팩토리 메서드를 이용하여 객체 생성을 해보면 어떨까요~?

2022-05-24 07:58 UTC, joojimin commented on src/main/java/qna/domain/Answers.java
> +public class Answers {
Embedded 활용!! 👍 👍 👍

2022-05-24 07:58 UTC, joojimin commented on src/main/java/qna/domain/Question.java
> +        List<DeleteHistory> histories = new ArrayList<>();
DeleteHistory 리스트를 만드는 책임을 분리하여 일급컬렉션으로 만들어보면어떨까요~?

2022-05-25 05:50 UTC, june2 commented on src/main/java/qna/domain/Answer.java
> +        return new DeleteHistory(ContentType.ANSWER, id, writer);
네~ 팩토리 메서드로 타입별로 생성할수있게 추가했습니다!

2022-05-25 05:51 UTC, june2 commented on src/main/java/qna/domain/Question.java
> +        List<DeleteHistory> histories = new ArrayList<>();
네  Answers 처럼, DeleteHistorise라는 일급 컬렉션을 생성했습니다.~~


https://github.com/next-step/jwp-qna/pull/494/commits/abb71e1be97203c8663647bfb3f54964b5ec3d5e

2022-05-25 16:02 UTC, joojimin approved these changes
안녕하세요! 준영님~
다소 빡빡한 피드백을 드렸는데 고민해보시고 잘 반영해주신거같아요!!!
이번 미션은 여기서 마무리하겠습니다!!
고생하셧습니다~

2022-05-25 16:02 UTC, merged

2022-05-26 05:29 UTC, june2 commented
리뷰 감사합니다~~~!!