Step2 : 연관 관계 매핑
next-step/jwp-qna pull request #498
Opened 2022-05-23 17:21 UTC by mannue

### 데이터 베이스 정의
- 질문은  많은 답변은 가진다.
- 답변은 질문 정보를 알수 있다.
- 다대일 양방향 이며 Answer Entity 가 FK 주인 이다.

- 질문은 사용자를 참조한다.
- 다대일 단방향 이며 Question Entity 가 FK 주인 이다.

- 답변은 사용자를 참조한다.
- 다대일 단방향 이며 Answer Entity 가 FK 주인 이다.

- 삭제된 정보는 사용자 정보를 가지고 있다.
- 다대일 단방향 이며 DeleteHistory Entity 가 FK 주인 이다.

위 문서를 기반으로 연관 관계 매핑작업을 하였습니다.
리뷰 해주셔서 감사합니다 ^^

2022-05-24 10:40 UTC, seokhongkim requested changes
은남님, JPA 2단계 미션 잘 진행해주셨어요. 👍 

피드백을 조금 남겼으니 확인 부탁드립니다. 🙏 
보시고 궁금하신 점이나 고민되는 부분 있다면 깃헙 코멘트나 슬랙 DM 으로 편하게 말씀해주세요!

2022-05-24 10:40 UTC, seokhongkim commented on src/main/java/qna/domain/Answer.java
> +    @ManyToOne
`ManyToOne` 관계일 때 `FetchType` 은 무엇일까요?
디폴트 값을 사용하도록 결정하신 이유가 있을까요?

2022-05-24 10:40 UTC, seokhongkim commented on src/main/java/qna/domain/Answer.java
> +                ", question=" + question +
연관관계가 설정된 데이터를 `toString` 에서 출력할 때 주의해야 할 점은 어떤 게 있을까요?

2022-05-24 10:40 UTC, seokhongkim commented on src/main/java/qna/domain/Answer.java
> +        if (Objects.nonNull(question)) {
여기서도 `Question` 에서 `Answer` 에게 맵핑을 요청했는데, `Answer` 가 다시 `Question` 의 데이터를 접근하는 순환 참조가 발생한 것 같네요!

2022-05-24 10:40 UTC, seokhongkim commented on src/main/java/qna/domain/Answer.java
> +        if (Objects.nonNull(this.question)) {
`Answer` 를 다른 `Question` 으로 맵핑하는 로직을 구현해주신 것 같은데, 맞을까요?

맞다면, 데이터를 옮기는 작업을 `Answer` 에서 하는 게 맞을까요?
그리고 `Question` 과 `Answer` 의 비즈니스 로직에서 순환 참조가 발생하는 것 같아요. 어떻게 개선하면 좋을까요?

2022-05-24 10:40 UTC, seokhongkim commented on src/main/java/qna/service/QnaService.java
>          for (Answer answer : answers) {
`Question` 과 `Answer` 가 연관관계를 맺었지만, 삭제해야 할 답변은 `AnswerRepository` 를 이용해서 가져오네요.
`Question` 에게 삭제 대상인 `Answer` 를 요청해서 가져올 수 있지 않을까요?

2022-05-24 10:58 UTC, mannue commented on src/main/java/qna/domain/Answer.java
> +                ", question=" + question +
이번에 양반향 매핑으로 작업하다가 보니 무한 루프에 빠지는 경우가 있었습니다. 
자세히 보니 toString 에서 서로가 서로를 계속 호출하는 case 였습니다 
음 그래서 저는 FK 쪽 만 정보 출력하고 Read 쪽은 해당 정보를 제외 하였습니다  😄

2022-05-24 11:02 UTC, mannue commented on src/main/java/qna/domain/Answer.java
> +    @ManyToOne
연결관계 매핑에 집중하다보니 이부분을 놓쳤네요 조언 감사합니다 👍 
From the [JPA 2.0 spec](http://download.oracle.com/otndocs/jcp/persistence-2.0-fr-oth-JSpec/), the defaults are:

OneToMany: LAZY
ManyToOne: EAGER
ManyToMany: LAZY
OneToOne: EAGER

위 처럼 매핑관계에 따른 default 값이 다르네요 lazy 로 선언하도록 하겠습니다.
감사합니다 💯

2022-05-24 11:10 UTC, mannue commented on src/main/java/qna/domain/Answer.java
> +        if (Objects.nonNull(question)) {
해당 코드는 기존에 질문 이 있다면 질문 의 답변 리스트에서 현재 답변을 삭제한 후에 변경된 질문 리스트에 현 답변을 추가하는 식으로
기존 정보를 제거 하기 위해서 작성했는데요
리스트에 접근해서 문제는 없는것 같은데요 혹시 자세히 설명 부탁드립니다 ^^;

2022-05-24 11:17 UTC, mannue commented on src/main/java/qna/domain/Answer.java
> +        if (Objects.nonNull(this.question)) {
Answer 를 다른 Question 으로 맵핑하는 로직을 구현해주신 것 같은데, 맞을까요?
-> 네 맞습니다. 기존 답변이 다른 질문으로 변경될수 있다고 생각하여 구현하였습니다.
     답변을 삭제한다고 예로 기존 질문에서 답변을 삭제해야지 기존 질문에서 답변을 검색할때 해당 답변이 사라지지 않을까요? 
    편의 메소드로 만들었는데 음... 어떤 식으로 해야 될지 조언 부탁드립니다 😄

2022-05-24 11:18 UTC, mannue commented on src/main/java/qna/service/QnaService.java
>          for (Answer answer : answers) {
이 코드는 default 코드 인데요 이부분도 제가 수정 해도 되나요? 된다고 하면 이부분도 수정해 보겠습니다 👍 
조언 감사합니다 ^^

2022-05-24 11:22 UTC, mannue commented
바쁘신 가운데 좋은 리뷰 감사합니다.
질문에 대한 부분 답변과 (fetch = FetchType.LAZY) 부분을 명시적으로 수정 해서 반영하였습니다.
감사합니다 👍

2022-05-25 04:23 UTC, seokhongkim requested changes
은남님, 피드백에 코멘트 남겨주신 내용 확인했습니다.
질문주신 내용에 답변과 피드백 함께 남겼으니 확인 부탁드립니다. 🙏

2022-05-25 04:23 UTC, seokhongkim commented on src/main/java/qna/service/QnaService.java
>          for (Answer answer : answers) {
2단계 미션 힌트를 보시면 아래 코드가 나와 있네요! 😀 

```
Question question = findQuestionById(questionId);
List<Answer> answers = question.getAnswers();
```

2022-05-25 04:23 UTC, seokhongkim commented on src/main/java/qna/domain/Answer.java
> +        if (Objects.nonNull(this.question)) {
3단계 미션 내용이긴 하지만 코드 변경을 요청드리기 위해 설명이 필요할 것 같아서 2단계에서 말씀 드려요.

질문을 삭제할 때는 질문에 달린 답변도 모두 삭제되며, 질문과 답변을 작성한 사용자가 모두 동일한 경우에만 삭제가 가능합니다.
따라서 답변을 다른 질문에 맵핑할 일은 없을 것 같아요!

2022-05-25 04:23 UTC, seokhongkim commented on src/main/java/qna/domain/Answer.java
> +        if (Objects.nonNull(question)) {
질문에 답변이 달릴 때 `Question` 에게 `Answer` 를 연결하라고 요청한다면,
`Question` 에서 `Answer` 와 연관관계를 맺고(`answers.add(answer)`), 이후 `Answer` 에게는 `Question` 에 대한 연관관계를 설정하라고만 요청해도 되지 않을까요?

순환 참조라고 말씀드린 것은, `Question` -> `Answer` 를 향한 로직상의 의존관계를 가지고 있는데, `Answer` -> `Question` 을 사용한 로직(`question.getAnswers().add(this)`)이 추가되어서 좋지 않다고 생각했습니다.
엔티티가 아닌 일반 객체라고 생각한다면 어떻게 구현할 지 고민해보셔도 좋을 것 같아요!

2022-05-25 04:23 UTC, seokhongkim commented on src/main/java/qna/domain/Answer.java
> +                ", question=" + question +
말씀하신 것처럼 무한 루프에 빠지는 경우가 발생할 수 있습니다.
이외에도 `FetchType.LAZY` 으로 맵핑되어 있는데, 트랜잭션 내부에서 데이터를 가져오지 않은 상황에서 트랜잭션 밖에서 `toString` 이 호출되는 경우 `LazyInitializationException` 이 발생할 수도 있습니다.
이런 점을 고려하여, `toString` 이 사용되는 곳을 제한할 수 없다면 예외가 발생하지 않도록 구현할 필요가 있을 것 같아요. 😀

2022-05-25 06:59 UTC, mannue commented on src/main/java/qna/domain/Answer.java
> +        if (Objects.nonNull(this.question)) {
아.. 그렇군요 전 답변은 다른질문으로 변경될수 있다라고 생각했는데 
그럼 이부분을 심플하게 this.question = question 이랑 question.getAnswers().add(this) 라고 변경해야 겠네요 3단계에서 삭제하는 부분을 그때 수정하도록 하겠습니다. 감사합니다 👍

2022-05-25 13:43 UTC, mannue reviewed
바쁘신 가운데 리뷰 해주셔서 감사합니다 😄 
다시 한번 부탁드립니다.

2022-05-25 13:43 UTC, mannue commented on src/main/java/qna/domain/Answer.java
> +        if (Objects.nonNull(question)) {
아 말씀 감사합니다. 
저는 일대다 양방향으로 생각해서 위코드를 넣었는데요 
cascade 와 orphanRemoval 가 설정되지 않는 경우에는 양반향이기 때문에 한쪽만 입력하고 다른 쪽에 입력하지 않으면 이부분도 문제가 되지 않을까요?

우선 학습하는 입장이라서 서적에는 일대다 양반향일경우 서로에 정보를 넣어주도록 가이드 주더라구요 

order 와 member 간의 일대다 양반향일때 
```java
public void setMember(Member member) {
    // 기존 관계 제거 
   if(this.member != null) {
        this.member.getOrders().remove(this);
   }
   this.member = member;
   this.member.getOrders().add(this);
}
```

위 처럼 되어있어서 저도 이부분을 참고해서 작성했네요 ^^;;

2022-05-25 13:43 UTC, mannue commented on src/main/java/qna/domain/Answer.java
> +                ", question=" + question +
네 맞는 말씀입니다. 그냥 무심코 toString 시에 서로간의 참조로 인해서 문제가 발생해서 저도 발생후에 인지하게 되었습니다 ㅠㅠ

2022-05-25 13:43 UTC, mannue commented on src/main/java/qna/service/QnaService.java
>          for (Answer answer : answers) {
조언 감사합니다 ^^ 
학습하는 목적으로 Question 과 Answer 관계에서  cascade = CascadeType.PERSIST 도 사용하였습니다.
 cascade = CascadeType.PERSIST 는 서로 연관관계 를 설정 후에 Answer 를 엔티티로 등록하지 않아도 Question 이 엔티티 등록될때 같이 등록 되는 기능이라고 학습을 통해서 배웠습니다 ^^

바쁘신 가운데 리뷰 감사합니다. 👍 💯

2022-05-25 14:51 UTC, seokhongkim requested changes
은남님, 코멘트 작성해주신 부분에 대해 추가 코멘트 남겼습니다. 😀 
확인 부탁드립니다!

2022-05-25 14:51 UTC, seokhongkim commented on src/main/java/qna/domain/Answer.java
> +        if (Objects.nonNull(question)) {
`Question` 의 코드를 보면 답변을 추가했을 때 로직이 아래와 같네요.
맵핑된 `answers`에 새로운 `answer` 를 추가하고, `answer.toQuestion` 을 통해 답변에 질문을 맵핑해주네요.
```java
public void addAnswer(Answer answer) {
    if (!this.answers.contains(answer)) {
        this.answers.add(answer);
        answer.toQuestion(this);
    }
}
```

그런데, 현재 `Answer` 에 질문을 추가해주는 부분을 보면 로직이 이와 같습니다.
```java
public void toQuestion(Question question) {
    if (Objects.nonNull(question)) {
        question.getAnswers().add(this);
    }
    this.question = question;
}
```
따라서 답변을 추가했을 때 `question.answers` 에 `answer` 를 `add` 하는 로직이 두번 실행될 것 같고, 이 부분은 확인 부탁드려요!

말씀하신 코드를 봤을 때 제가 이해한 바로는, `order` 에서 `member` 의 데이터에만 접근하고, `member` 에서는 `order` 에 직접 접근해서 맵핑하는 로직이 없는 것 같습니다.
`order` 에서 `member` 와 연관관계를 맺는 모든 책임(`this.member = member, this.member.getOrders().add(this)`)을 가지고 있는 것으로 보입니다.

현재 작성하신 코드는 `Question` 에서 `Answer` 를 관리하면서(`this.answers.add(answer)`), `Answer` 에게도 `Question` 과 연관관계 맺는 일을 요청하고 있는데(`answer.toQuestion`), `Answer` 는 내부적으로 또 `Question` 의 데이터를 접근하는 것(`question.getAnswers().add(this)`) 같아요.

은남님께서 말씀해주신 내용을 제가 잘못 이해하고 답변 드렸을까 우려스러운데, 혹시 제가 잘못 이해한 내용이 있다면 편하게 말씀해주세요! 🙏

2022-05-25 19:09 UTC, mannue commented on src/main/java/qna/domain/Answer.java
> +        if (Objects.nonNull(question)) {
맞는 말씀 같습니다. 음 책에는 위와 같이 있어서 따라 해봤는데 그냥 내부체크하도록 수정하였습니다 ㅎㅎ
늦은 시간까지 감사합니다

 if (Objects.nonNull(question) && !question.getAnswers().contains(this)) {
            question.getAnswers().add(this);
        }
        this.question = question;

이렇게 수정하였습니다 ^^

2022-05-25 19:11 UTC, mannue reviewed
말씀해주신 부분이 양쪽으로 넣는것 같습니다 ㅠㅠ
그래서 내부 검사해서 삽입하도록 수정하였습니다.
조언감사합니다 💯

2022-05-26 00:25 UTC, seokhongkim approved these changes
은남님, JPA 2단계 미션 마무리 잘 해주셨습니다. 👍 
PR은 여기서 머지하도록 하겠습니다.

짧은 의견을 코멘트로 남겼는데, 이 내용은 한 번 생각만 해보시고 반영은 안 하셔도 괜찮을 것 같습니다.
3단계에서 뵙겠습니다. 🙏

2022-05-26 00:25 UTC, seokhongkim commented on src/main/java/qna/domain/Answer.java
> +        this.question = question;
저는 개인적으로 `toQuestion` 에서 `this.question = question` 부분만 남기거나, `Question` 에서 `Answer`의 `setQuestion` 을 사용하도록 변경해도 되지 않을까 싶었습니다. 😀 
`setter` 를 사용하는 것이 안 좋으나, 이건 비즈니스 로직을 객체의 협력으로 푸는 목적이 아니라 DB에서 데이터를 관리하기 위해 연관관계를 맺어주는 목적이라고 생각했어요.
정답은 없기 때문에 은남님께서 구현하신 방법도 괜찮을 것 같네요!

2022-05-26 00:25 UTC, merged

2022-05-26 01:22 UTC, mannue commented on src/main/java/qna/domain/Answer.java
> +        this.question = question;
리뷰 잘 해주셔서 감사합니다. ㅠㅠ
@seokhongkim 님이 제안해주신 부분에 대해서 좋은것 같습니다 :+1: 
다만 저는 사용자가 실수해서 어느 한쪽만 입력하면 문제가 있을것 같아서 양쪽에 서로 넣을수 있도록 하였습니다 ㅠㅠ
Answer 에서 Question 을 넣든지 Question 에서 Answer 를 넣든지 신경 쓰지 않도록 하기 위함이였습니다.
다만 이렇다 보니 잘 생각해서 구현해야 되는것 같습니다 ㅠㅠ
바쁘신 가운데 감사합니다 :+1:  :100:  :hand: