Step3: 질문 삭제하기 리팩터링
next-step/jwp-qna pull request #505
Opened 2022-05-24 15:29 UTC by lakey001

선흠 리뷰어님, 안녕하세요!
JPA 미션 Step 3 질문 삭제하기 리팩터링 PR 요청 드립니다.
기존 코드의 Service Layer 로직을 Domain 내부로 리팩토링 진행하였고, 
Step2(#472) 에서 피드백주신 내용도 함께 반영해보았습니다.

항상 친절한 조언 감사드리며, 마지막 미션도 시간 되실 때 확인 부탁드리겠습니다!!
감사합니다 😄

2022-05-24 16:57 UTC, shared-moon requested changes
수연님 안녕하세요!
3단계 미션도 잘 진행해 주셨네요 :)
코멘트 몇 개 남겨 놓았는데, 확인 후 리뷰 재 요청 부탁드릴게요!
화이팅 하세요! 🔥

2022-05-24 16:57 UTC, shared-moon commented on src/main/java/qna/domain/Answer.java
> +    public void delete(User loginUser) throws CannotDeleteException {
Custom Exception은 RuntimeException을 상속받는 걸 추천드려요! 그럼 이렇게 throw 안하셔도 돼요!

2022-05-24 16:57 UTC, shared-moon commented on src/main/java/qna/domain/Answer.java
> +        if (!isOwner(loginUser)) {
메서드에서 부정형을 리턴하고 이름을 isNotOwner로 바꾸는 건 어떻게 생각하세요 ?

2022-05-24 16:57 UTC, shared-moon commented on src/main/java/qna/domain/Answers.java
> +@Embeddable
👍

2022-05-24 16:57 UTC, shared-moon commented on src/main/java/qna/domain/Answers.java
> +        answers = new ArrayList<>();
요런건 선언부에서 그냥 해줘도 될 것 같아요!

2022-05-24 16:57 UTC, shared-moon commented on src/main/java/qna/domain/Answers.java
> +    public List<Answer> getUnmodifiableAnswers(){
Unmodifiable은 굳이 드러내지 않아도 될 것 같아요! (개인의견)

2022-05-24 16:57 UTC, shared-moon commented on src/main/java/qna/domain/DeleteHistory.java
> +        return new DeleteHistory(ContentType.ANSWER, answer.getId(), loginUser, LocalDateTime.now());
now도 매개변수로 받는 게 좋을 것 같아요!
호출때마다 생성하면 같이 묶여야 하는 히스토리가 시간이 다르게 기록 될 수 있어요 :)

2022-05-24 16:57 UTC, shared-moon commented on src/main/java/qna/domain/DeleteHistories.java
> +            deleteHistories.add(DeleteHistory.of(answer, loginUser));
만약 question이 동일한데, 예전에 이미 답변만 달렸다가 삭제 된 경우가 있다면 이 부분에서 이력이 정상적으로 남을 수 있을까요 ?

2022-05-24 16:57 UTC, shared-moon commented on src/main/java/qna/service/QnaService.java
> +        deleteHistoryService.saveAll(DeleteHistories.of(question, loginUser).getUnmodifiableDeleteHistories());
여기는 로컬 변수로 한번 빼 주시면 더 읽기 좋을 것 같아요!

2022-05-24 16:57 UTC, shared-moon commented on src/test/java/qna/domain/AnswerRepositoryTest.java
> +    @CsvSource(value = {"true:false", "false:true"}, delimiter = ':')
요건 약간 사족인데, ParameterizedTest시에는 MethodSource가 제일 깔끔한것같아요!

2022-05-24 16:57 UTC, shared-moon commented on src/test/java/qna/domain/AnswerTest.java
> +        assertThatThrownBy(() -> {
`assertThrows(NotFoundException.class, () -> {})`
이런식으로도 쓸 수 있어요 !

2022-05-25 14:37 UTC, lakey001 commented on src/main/java/qna/domain/Answer.java
> +    public void delete(User loginUser) throws CannotDeleteException {
앗 좋은 조언 감사드립니다 :)

2022-05-25 14:38 UTC, lakey001 commented on src/main/java/qna/domain/Answer.java
> +        if (!isOwner(loginUser)) {
조건문에 부정형이 있으면 가독성이 떨어져서 바꾸는게 좋을 것 같습니다 :) 
메서드명을 mismatchOwner로 바꿔보았습니다!

2022-05-25 14:39 UTC, lakey001 commented on src/main/java/qna/domain/DeleteHistory.java
> +        return new DeleteHistory(ContentType.ANSWER, answer.getId(), loginUser, LocalDateTime.now());
시간도 매개변수로 받는 것이 시간에 통일성이 부여되고 좋을 것 같습니다! 해당 내용 반영하였습니다 😄

2022-05-25 14:42 UTC, lakey001 commented on src/main/java/qna/domain/DeleteHistories.java
> +            deleteHistories.add(DeleteHistory.of(answer, loginUser));
앗 구현하면서 해당 Case를 미처 고려하지 못했었네요..
Question 도메인에서 delete 수행 시, 기존에 이미 삭제되었던 것을 제외하고 신규로 삭제된 Answers 결과를 반환하도록 구현하여 해결해보았습니다.
좋은 지적 감사합니다 ^^

2022-05-25 14:43 UTC, lakey001 commented on src/test/java/qna/domain/AnswerRepositoryTest.java
> +    @CsvSource(value = {"true:false", "false:true"}, delimiter = ':')
새롭게 배웠습니다! 감사합니다 👍

2022-05-26 13:38 UTC, shared-moon approved these changes
수연님 안녕하세요!
피드백 반영 잘 해 주셨네요 :)
소소한 코멘트 몇 개 남겨 두었으니 다음 미션 진행 전에 확인 부탁드려요!

이번 미션은 이만 머지 하도록 하겠습니다. 남은 미션도 화이팅 하세요 🔥 
정말 고생 많으셨습니다 :)

2022-05-26 13:38 UTC, shared-moon commented on src/main/java/qna/UnAuthenticationException.java
> +public class UnAuthenticationException extends RuntimeException {
👍

2022-05-26 13:38 UTC, shared-moon commented on src/main/java/qna/domain/Answers.java
> +        List<Answer> undeletedAnswers = answers.stream().filter(answer -> !answer.isDeleted())
지금처럼 애초에 Answer가 deleted = false 인 애들만 필요한 경우에는 @Where 도 고려 해 볼 수 있을 것 같아요 :)

2022-05-26 13:38 UTC, shared-moon commented on src/main/java/qna/domain/DeleteHistory.java
> +    public static DeleteHistory of(Answer answer, User user, LocalDateTime time) {
👍

2022-05-26 13:38 UTC, shared-moon commented on src/test/java/qna/domain/AnswerTest.java
> +        try {
테스트 메서드는 전제조건 등을 완전히 제어할 수 있는 상태기 때문에 try-catch 문으로 감싸는 처리는 필요가 없을 것 같아요!

2022-05-26 13:39 UTC, merged