Step1 - 엔티티 매핑
next-step/jwp-qna pull request #511
Opened 2022-05-24 21:07 UTC by bgc8214

안녕하세요 :)

1단계 미션인 엔티티 매핑 완료하여 리뷰 요청드립니다!

잘부탁드립니다. 🙇

2022-05-24 21:09 UTC, bgc8214 commented on src/test/java/qna/domain/UserRepositoryTest.java
> +        assertThat(actual.equalsNameAndEmail(expected));
다른 엔티티는 객체를 비교해도 정상으로 테스트 통과하는데, 유저 엔티티만 안되어서 다른 방식으로 체크를 했어요.
왜 이것만 그런지 잘 모르겠어서 여쭤봐요

2022-05-25 01:17 UTC, seok-2-o requested changes
안녕하세요 😄 JPA 리뷰어를 맡은 이재석입니다.

엔티티 매핑 미션 잘진행해주셨네요 👍 
질문 남겨주신부분에 답변 남겨놓았어요. 해당부분 수정하고 넘어가는게 좋을것 같아요


앞으로 과정 진행하면서 저와 의견이 다르거나 궁금한점 있으면 편하게 코멘트 또는 DM 남겨주세요.

규철님과 함께 할 수 있게 되어 무척 기쁜 마음입니다. :)
모쪼록 다음 코드 기대하며 기다리고 있을게요. 🙇

2022-05-25 01:17 UTC, seok-2-o commented on src/main/java/qna/domain/BaseEntity.java
> +public abstract class BaseEntity {
Auditing 👍 
abstract class 💯

2022-05-25 01:17 UTC, seok-2-o commented on src/main/java/qna/domain/DeleteHistory.java
> +    protected DeleteHistory() {
protected 👍

2022-05-25 01:17 UTC, seok-2-o commented on src/main/resources/data.sql
> +/*INSERT INTO line (id, name)
불필요한 파일은 주석으로 남겨놓기보다 삭제하는게 좋을 것 같아요.

2022-05-25 01:17 UTC, seok-2-o commented on src/test/java/qna/domain/UserRepositoryTest.java
> +        assertThat(actual.equalsNameAndEmail(expected));
SANJIGI 의 ID는 2인데, 새로 저장되어 자동으로 생성되는 SANJIGI의 ID는 1이여서 차이가 발생하는것 같아요.

2022-05-25 12:34 UTC, bgc8214 commented on src/main/resources/data.sql
> +/*INSERT INTO line (id, name)
넵 삭제했습니다 !

2022-05-25 12:59 UTC, bgc8214 commented on src/test/java/qna/domain/UserRepositoryTest.java
> +        assertThat(actual.equalsNameAndEmail(expected));
JAVAJIGI 로 해도 동일하게 실패를 합니다 ㅠ
![image](https://user-images.githubusercontent.com/14211629/170263166-184d9c6c-ab4d-48b6-a216-0967107af5dc.png)
UserTest.JAVAJIGI 에서 생성자로 id 값을 1L 로 직접 받는 경우에는 실제로 내부 값이 같더라도 동등하지 않다고 에러가 발생하네요..!
이걸 id를 넣지 않는 생성자로 id 값을 NULL로 하여 저장을 하면, NULL에 GenerationType.IDENTITY로 생성된 Id 값이 들어가서 정상으로 테스트가 동작합니다.

테스트를 해보니, 저장전에 id값이 이미 있으면 저장 후에 해당 객체에 id값을 Set 하지는 않는 것으로 보이네요...! 1L의 경우 Wrapper 클래스여서 같은 값이여도 동등성 비교에서는 실패하는 것으로 보이구요. ( equals, hashCodes 메소드를 만들면 정상 동작 ) 

JPA의 EntityManager persist  구현체에서 id 가 null 인 객체가 들어오면, GenerationType 으로 생성한 id를 set 하고 들어온 객체를 그대로 넘겨주고, id 값이 있으면 객체를 복사해서 id값을 set하고 넘겨주는 방식이지 않을까.... 라고 혼자생각은 하는데, 구현체에서 따로 코드는 못찾았습니다 😢

2022-05-26 03:54 UTC, seok-2-o commented on src/test/java/qna/domain/UserRepositoryTest.java
> +        assertThat(actual.equalsNameAndEmail(expected));
equals 메소드를 구현해주지 않으셨네요.

equals 메소드를 구현하고 테스트를 실행하면 테스트가 통과하는 것을 호가인할 수 있어요.

2022-05-26 03:56 UTC, seok-2-o approved these changes
피드백이 늦어져 죄송합니다. 
추가 답변 남겨놓았으니 확인 부탁드릴께요.

이어서 다음 미션 진행해주세요.

2022-05-26 03:58 UTC, seok-2-o commented on src/test/java/qna/domain/UserRepositoryTest.java
> +        assertThat(actual.equalsNameAndEmail(expected));
Wrapper 로 ID를 지정할 경우 equals를 구현하지 않아도 되는것으로 알고 있기는한데, 저도 한번 더 확인해보고 말씀드릴 수 있도록 할게요.

2022-05-26 04:07 UTC, seok-2-o commented on src/test/java/qna/domain/UserRepositoryTest.java
> +        assertThat(actual.equalsNameAndEmail(expected));
아이디를 지정하고 save() 메소드를 호출할 경우
```java

		if (entityInformation.isNew(entity)) {
			em.persist(entity);
			return entity;
		} else {
			return em.merge(entity);
		}
```

2022-05-26 04:19 UTC, seok-2-o commented on src/test/java/qna/domain/UserRepositoryTest.java
> +        assertThat(actual.equalsNameAndEmail(expected));
```
merge는 파라미터로 넘어온 엔티티의 식별자로 영속성 컨텍스트를 조회하고 없을 경우 DB를 조회한다. 
만약 DB에도 존재하지 않는다면 새로운 엔티티를 생성해서 병합을 하게 된다.
```

2022-05-26 04:20 UTC, merged

2022-05-26 11:19 UTC, bgc8214 commented on src/test/java/qna/domain/UserRepositoryTest.java
> +        assertThat(actual.equalsNameAndEmail(expected));
@seok-2-o 아하... merge 의 동작이 어떻게 되는지를 몰랐네요! 
상세한 답변 정말 감사합니다 🙇