Step2 - 연관관계 매핑
next-step/jwp-qna pull request #522
Opened 2022-05-26 15:48 UTC by bgc8214

안녕하세요 :) 연관관계 매핑 구현해서 리뷰 부탁드립니다!

감사합니다.

2022-05-27 05:10 UTC, seok-2-o requested changes
연관관계 매핑도 잘진행해주셨네요. 다만 요구사항에서 추가적으로 진행해주셨으면 하는 부분이 있어
코멘트로 남겨드렸어요. 확인부탁드릴게요.

2022-05-27 05:10 UTC, seok-2-o commented on src/main/java/qna/domain/Answer.java
>      }
기존에 구현되어 있는 코드이긴 하지만 이번 과정들에서는 getter,setter는 지양하고 있어요

왜 get,set을 지양하는지 고민해보면 좋을것 같네요.

2022-05-27 05:10 UTC, seok-2-o commented on src/main/java/qna/domain/Question.java
>  public class Question extends BaseEntity {
보통 Question -> Answer 조회하는 일이 있을 것 같은데, 해당 부분을 연습해보는것은 어떤가요?

2022-05-27 05:10 UTC, seok-2-o commented on src/main/java/qna/service/QnaService.java
> +            deleteHistories.add(new DeleteHistory(ContentType.ANSWER, answer.getId(), answer.getWriter(), LocalDateTime.now()));
DeleteHistory 를 정적 팩토리로 생성하면 어떤 장점이 있을까요?

2022-05-27 05:10 UTC, seok-2-o commented on src/main/java/qna/domain/Question.java
>  public class Question extends BaseEntity {
테이블의 외래 키를 객체에 그대로 가져온 부분이 문제다. 왜냐하면 관계형 데이터베이스는 연관된 객체를 찾을 때 외래 키를 사용해서 조인하면 되지만 객체에는 조인이라는 기능이 없다. 객체는 연관된 객체를 찾을 때 참조를 사용해야 한다.
```java
Question question = findQuestionById(questionId);
List<Answer> answers = question.getAnswers();

2022-05-28 06:53 UTC, bgc8214 commented on src/main/java/qna/service/QnaService.java
> +            deleteHistories.add(new DeleteHistory(ContentType.ANSWER, answer.getId(), answer.getWriter(), LocalDateTime.now()));
정적 팩토리 메소드를 사용해서 생성할 수 있도록 변경했는데, 네이밍을 통해서 어떤 객체를 만들고자 하는지 명시적으로 더 알 수 있게 되는 것 같습니다.
사용자가 내부적인 구현을 더 알필요도 없어지는 거 같아요

2022-05-28 07:01 UTC, bgc8214 commented on src/main/java/qna/domain/Answer.java
>      }
넵 필요없는 getter, setter 들은 삭제했습니다. 1주차 강의에서 떠올려보면 getter를 통해서 값을 가져간다는 것은 외부에서 해당 로직을 처리한다는 것을 의미하는 것이기 때문에 객체지향적이지 않다고 생각됩니다. 내부에 메시지를 보내서 처리할 수 있도록 하는게 맞는 방향이겠네요
setter 는 사용하면 외부에서 값을 맘대로 바꿀 수 있어서, 객체가 정상동작 하지 않을 가능성도 커질 거라 생각됩니다

2022-05-28 07:24 UTC, bgc8214 commented on src/main/java/qna/domain/Question.java
>  public class Question extends BaseEntity {
넵 양방향 연관관계를 매핑하고, Answer 클래스에 아래와 같이 양방향 편의메소드를 작성했습니다. 여기서 하나 궁금증이 있는데요.

```java
  public void toQuestion(Question question) {
        if (this.question != null) {
            question.getAnswers().remove(this);
        }
        this.question = question;
        question.getAnswers().add(this);
    }
```
공부를 하다보니까, 양방향 편의 메소드는 순수 객체 일때도 양뱡향 관계를 만들어주기 위한 것이라고 확인을 했습니다. 
연관관계의 주인에게 관계를 세팅하고 저장하면 문제없이 잘 들어간다고 봐서, 이 내용을 한번 테스트 해보려고 했어요. ( [참고한 곳](https://velog.io/@neity16/3-JPA-%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%B0%8D-6-%EC%97%B0%EA%B4%80%EA%B4%80%EA%B3%84-%EB%A7%A4%ED%95%91-1-%EB%8B%A8%EB%B0%A9%ED%96%A5%EC%96%91%EB%B0%A9%ED%96%A5-%EC%97%B0%EA%B4%80%EA%B4%80%EA%B3%84-%EC%97%B0%EA%B4%80%EA%B4%80%EA%B3%84-%EC%A3%BC%EC%9D%B8-mappedBy#%EC%97%B0%EA%B4%80%EA%B4%80%EA%B3%84-%ED%8E%B8%EC%9D%98-%EB%A9%94%EC%86%8C%EB%93%9C-) ) 

```java
 @Test
    public void findQuestionAnswer() {
        //given
        Question question = questionRepository.save(new Question("title3", "contents3"));
        User user = userRepository.save(new User("boss", "pw", "back", "boss@slipp.net"));
        Answer expectedAnswer = answerRepository.save(new Answer(user, question, "content"));
        //expectedAnswer.toQuestion(question); 연관 관계 편의 메소드 사용하지 않음
        
        //flush 를 해야 값이 들어갈 것으로 보여 모두 다 flush
        questionRepository.flush();
        userRepository.flush();
        answerRepository.flush();
        //when
        //id로 찾으면 엔티티 메니져에서 캐싱된 내용을 찾을 수 있어, 타이틀로 찾음
        Question actual = questionRepository.findByTitle("title3");
        //then
        assertThat(actual.getAnswers()).contains(expectedAnswer);
    }
```
위와 같이 테스트를 하면, 객체간의 연관 관계는 설정하지 않았지만, DB에는 FK 가 저장되었을 것이라고 생각을 했고, 다시 findByTitle을 했을 때, Answer의 값이 있지 않을까? 싶었는데... 그렇지 않더라구요.

JPA에 대해서 아직 잘 모르는 부분이 많아 어떤게 잘못되었을까 잘 모르겠어서 질문드립니다 😭

2022-05-29 02:24 UTC, seok-2-o commented on src/main/java/qna/domain/Question.java
>  public class Question extends BaseEntity {
@Transactional(propagation = Propagation.NOT_SUPPORTED) 옵션을 통해 해결할 수 있어요.
https://stackoverflow.com/questions/57767530/join-fetch-query-not-fetching-lazy-collection-in-spring-datajpatest

2022-05-29 02:24 UTC, seok-2-o approved these changes
피드백반영 잘해주셨네요 👍 
이어서 다음 미션 진행해주세요.

2022-05-29 02:25 UTC, merged