Step1 엔티티 매핑
next-step/jwp-qna pull request #54
Opened 2021-05-30 09:38 UTC by SGKIM94

안녕하세요 리뷰어님! 🙇 

Step1 JPA 엔티티 매핑 과제에 대한 피드백 요청입니다.

잘부탁드리겠습니다.
감사합니다.!🙆‍♂️

2021-05-31 13:58 UTC, tearight requested changes
안녕하세요.
이번 jwp-qna 미션을 함께 진행하게 될 리뷰어 한수빈입니다.
이번 단계에서 2단계 요구사항까지 일부 진행하셔서 2단계에 대한 피드백도 같이 포함해서 드리는데요.
원하신다면 1단계에 대한 요구사항만 수정하셔도 될 것 같아요.
그럼 코멘트 확인 부탁드릴게요.

2021-05-31 13:58 UTC, tearight commented on src/main/java/qna/Application.java
> +@EnableJpaAuditing
Auditing 추가 좋네요. 👍

2021-05-31 13:58 UTC, tearight commented on src/main/java/qna/domain/AbstractEntity.java
> +@MappedSuperclass
MappedSuperClass 를 통하여 코드의 재사용성이 증가하였네요. 👍

2021-05-31 13:58 UTC, tearight commented on src/main/java/qna/domain/Answer.java
> +    @ManyToOne(fetch = FetchType.LAZY)
2단계 요구사항인 연관관계 매핑까지 같이 진행하신걸로 보이네요.
여기서 FetchType 을 Lazy 로 지정하셨는데 원래 디폴트 값은 EAGER 이지요.
Lazy로 하신 의도가 있을까요?
또한 앞으로 LAZY 로 ManyToOne 으로 객체 탐색을 할 때 리스크나 제한사항이 있는지도 궁금합니다.

2021-05-31 13:58 UTC, tearight commented on src/main/java/qna/domain/Answer.java
> +    @Column
ddl 에서는 contents 가 clob 인걸로 보이는데요,
String에 @Column 을 붙일경우 hibernate 에서 table 생성시 clob 으로 정의될 수 있을까요 ?

2021-05-31 13:58 UTC, tearight commented on src/main/java/qna/domain/Answer.java
> +    @ManyToOne(fetch = FetchType.LAZY)
원래 2단계에서 드려야 피드백 드려야 할 사항이지만
미션 요구사항에서 FK 제약조건이 nullable 인걸로 보이진 않아요.
따라서 객체 매핑이 nullable 이 false 로 설정되어야 하지 않을까요 ?
다른 객체 매핑도 확인 부탁드릴게요.

2021-05-31 13:58 UTC, tearight commented on src/main/java/qna/domain/Answer.java
> +    @Column
ddl 에서 not null 으로 기재되어 있으니 nullable 이 false 로 명시적으로 적혀있어야 할 것 같아요.

2021-05-31 13:58 UTC, tearight commented on src/main/java/qna/domain/Answer.java
> +        return this.writer == writer;
같은 Id 를 가진 writer 라 하더라도 동일한 트랜잭션에서 영속화되지 않으면 동일성이 보장되지 않아요.
이는 영속성 컨텍스트가 가진 특징인데요.
이러한 특징을 참고하셔서 수정을 하셔야 할 것 같아요.

도움이 될 만한 글에 대해 링크를 남길게요.
https://ultrakain.gitbooks.io/jpa/content/chapter3/chapter3.4.html

2021-05-31 13:58 UTC, tearight commented on src/main/java/qna/domain/DeleteHistory.java
>      private ContentType contentType;
@Enumerated 어노테이션을 붙일 필요가 보입니다.
왜 붙여야 할까요 ?

2021-05-31 13:58 UTC, tearight commented on src/main/java/qna/domain/Question.java
> +    @Column
ddl 에서는 not null 로 정의되어 있네요.
nullable=false 추가가 필요해보입니다.

2021-05-31 13:58 UTC, tearight commented on src/main/java/qna/domain/User.java
>      private String email;
여기서도 not null 컬럼에 대해서 확인 부탁드릴게요.

2021-05-31 13:58 UTC, tearight commented on src/main/java/qna/service/QnaService.java
> +        List<Answer> answers = answerRepository.findByQuestionIdAndDeletedFalse(question.getId());
이 부분도 사실 2단계 요구사항인데요,
다음 단계 진행하면서 객체를 통해 Answer 를 탐색할 수 있도록 수정되어야 할 것 같아요.

2021-06-02 15:12 UTC, SGKIM94 commented on src/main/java/qna/domain/Answer.java
> +    @ManyToOne(fetch = FetchType.LAZY)
앗..!! 😢  의도한건 아니지만 컬럼을 매핑하다보니 추가를 하게되었습니다..

Lazy로 지정한 이유는 EAGER인 경우에는 만약 Answer를 조회한 경우 Question을 사용하지 않아도 항상 조회를 하게됩니다.
따라서 만약 Question을 사용하지 않는다면 불필요하게 객체를 가지고 있을 수 있는데요.
하지만, LAZY를 사용하게되면 우선 프록시 객체로 초기화한 상태에서 실제 객체를 사용하는 경우(해당 index의 값을 조회하는 경우)에 해당 객체를 조회하는 쿼리를 실행시켜 동작하는 것으로 알고 있습니다.

하지만 이러한 경우에 리스크나 제한사항은 만약 1만개의 객체를 반복하면서 LAZY된 객체를 가져오게되는 경우에는 쿼리가 해당 개수만큼 실행되는 문제가 발생할 수 있습니다.(N + 1 문제)
이러한 경우에는 별도의 Fetch Join 이나 @EntityGraph 등의 방법으로 상황에 맞게 해결할 수 있는 것으로 알고 있습니다.
(참고한 사이트 : https://jojoldu.tistory.com/165?category=637935)

만약 제가 잘못 알고 있는 부분이나 부족한 부분이 있는 경우 피드백 부탁드리겠습니다. 🙇 
감사합니다.

2021-06-02 15:15 UTC, SGKIM94 commented on src/main/java/qna/domain/Answer.java
> +    @Column
앗.. 생각을 못했었네요..! 😢 
`@Lob` 추가하여 피드백 반영하였습니다. 감사합니다.!

2021-06-02 15:15 UTC, SGKIM94 commented on src/main/java/qna/domain/Answer.java
> +    @Column
nullable 전부 추가하였습니다. 피드백 감사합니다.! 주의하도록 하겠습니다.

2021-06-02 15:19 UTC, SGKIM94 commented on src/main/java/qna/domain/Answer.java
> +        return this.writer == writer;
아.. 제가 착각을 하고 있었습니다.. . 🤭   isOwner가 항상 영속화되어있는 상태에서 실행된다는 보장이 없겠네요..
감사합니다.! 피드백 반영하였습니다

2021-06-02 15:24 UTC, SGKIM94 commented on src/main/java/qna/domain/DeleteHistory.java
>      private ContentType contentType;
`@Enumerated` 를 붙이지 않으면 순서 값인 ORDINAL한 값이 저장되는 것으로 알고 있습니다.
따라서 추후에 중간 값이 생기거나 변경이 발생하면 DB의 중간 값을 추가하기 매우 어려운 상황이 발생하므로 상수 값인 STRING으로 저장하기 위해 @Enumerated(EnumType.STRING) 으로 설정해야하는 것이 좋은 것으로 알고 있습니다.

..! `@Enumerated(EnumType.STRING)` 추가하여 피드백 반영하였습니다. 🙇

2021-06-02 15:24 UTC, SGKIM94 commented on src/main/java/qna/domain/Question.java
> +    @Column
피드백 반영하였습니다. 감사합니다.!

2021-06-02 15:24 UTC, SGKIM94 commented on src/main/java/qna/domain/User.java
>      private String email;
피드백 반영하였습니다. 감사합니다.!

2021-06-02 15:27 UTC, SGKIM94 commented on src/main/java/qna/service/QnaService.java
> +        List<Answer> answers = answerRepository.findByQuestionIdAndDeletedFalse(question.getId());
말씀해주신 부분에 대해서 Answers를 탐색을 통해 가져오기 위해 OneToMany 형태의 읽기전용 컬럼인 Answers 를 추가하여 피드백 반영하였습니다. 

확인 부탁드리겠습니다. 🙇

2021-06-03 11:18 UTC, tearight commented on src/main/java/qna/domain/Answer.java
> +    @ManyToOne(fetch = FetchType.LAZY)
넵 알고계신게 맞습니다.🙂
여기서 보충설명을 조금 더 드릴게요. FetchType이 Lazy 인 속성은 fetch join 을 통해서 미리 fetch 된 것이 아니라면
@Transactional 내부에서만 조회할 수 있습니다. 그 이외에는 LazyInitializationException 이 발생하게 됩니다.

때문에 실무에서는 Entity 를 참조하는 것을 Transactional 내부에서만 진행하고 바깥에서는 dto 객체를 따로 만들어 전달하고 있습니다.
(사실 이거 외에도 dirty checking 등 여러 의도하지 않은 사이드 이펙트가 나오는걸 방지하기 위해 엔티티를 제한적으로 사용하고 있습니다.)

2021-06-03 11:21 UTC, tearight commented on src/main/java/qna/domain/Answer.java
>      private boolean deleted = false;
@Column 은 왠만하면 적어주시는게 좋아요.
보통 @column 과 함께 컬럼명을 함께 적어주지요.
이것도 이유를 알아보시면 앞으로 JPA 프로젝트를 운영하시면서 큰 도움이 될 거 같아요.

2021-06-03 11:22 UTC, tearight approved these changes
코멘트 반영해주신 코드 잘 확인했습니다. 
추가적으로 남긴 코멘트가 있는데 다음 단계 진행하면서 확인 부탁드립니다.

2021-06-03 11:23 UTC, merged