Step3 - 질문 삭제하기 리팩터링
next-step/jwp-qna pull request #544
Opened 2022-05-29 16:56 UTC by jaesungahn91

영훈님 JPA 마지막단계입니다!

과제를 진행하는동안 좋은 코드리뷰 감사합니다. 해당 미션에서 정말 많은것들을 얻어가고싶습니다.

사견도 좋으니 많은 코멘트 부탁드립니다! 감사합니다!

2022-05-30 22:39 UTC, chae-yh requested changes
재성님 안녕하세요! 이제 jpa 마지막 미션입니다!
전체적으로 코드 잘 작성해주셨고, 리팩토링도 잘 된 것 같습니다 👍 
다만 조금 더 고민해보시면 좋을 만한 부분과 질문들을 코멘트 드렸으니 확인 부탁드립니다!

마지막까지 파이팅입니다 : )

2022-05-30 22:39 UTC, chae-yh commented on README.md
> +#### QnA 서비스를 만들어가면서 JPA로 실제 도메인 모델을 어떻게 구성하고 객체와 테이블을 어떻게 매핑해야 하는지 알아본다.
역시 기능 구현 목록 잘 작성해주셨습니다 👍

2022-05-30 22:39 UTC, chae-yh commented on src/main/java/qna/domain/Answer.java
> +    public boolean equals(Object o) {
equals / hashCode 구현 좋습니다 👍

2022-05-30 22:39 UTC, chae-yh commented on src/main/java/qna/domain/Answers.java
> +public class Answers {
1급 컬렉션 만드신 것 좋습니다 👍 
해당 클래스의 테스트 클래스가 없는데 추가되어도 좋을 것 같습니다!

2022-05-30 22:39 UTC, chae-yh commented on src/main/java/qna/domain/Answers.java
> +            cascade = {CascadeType.PERSIST, CascadeType.REMOVE})
Cascacse 는 PERSIST만 주신다고 하셨던 것 같은데 혹시 REMOVE가 추가된 사유를 여쭤봐도 될까요...?

2022-05-30 22:39 UTC, chae-yh commented on src/main/java/qna/service/QnaService.java
>          deleteHistoryService.saveAll(deleteHistories);
service layer에 있던 로직이 domain으로 옮겨지면서 상당히 얇아졌네요 👍

2022-05-30 22:39 UTC, chae-yh commented on src/main/java/qna/service/QnaService.java
>      public void deleteQuestion(User loginUser, Long questionId) throws CannotDeleteException {
CannotDeleteException 은 runtime exception으로 바꾸셨는데, 다시 throw를 해주시는 사유를 여쭤보고 싶습니다!

2022-05-30 22:39 UTC, chae-yh commented on src/main/java/qna/CannotDeleteException.java
> +public class CannotDeleteException extends RuntimeException {
여기를 unchecked exception으로 바꾸신 이유를 여쭤보고 싶습니다!

2022-05-30 22:39 UTC, chae-yh commented on src/main/java/qna/domain/Question.java
> +        List<DeleteHistory> deleteHistories = new ArrayList<>();
deleteHistories 도 1급 컬렉션으로 추출할 수 있지 않을까요....?

2022-05-31 10:18 UTC, jaesungahn91 commented on src/main/java/qna/domain/Answers.java
> +            cascade = {CascadeType.PERSIST, CascadeType.REMOVE})
앗 답변하면서 수정했던거라 다시 수정하겠습니다!

2022-06-01 03:59 UTC, jaesungahn91 commented on src/main/java/qna/service/QnaService.java
>      public void deleteQuestion(User loginUser, Long questionId) throws CannotDeleteException {
아래 코멘트랑 이어지는데, exception 던지지않기 위해서 변경했는데 throws CannotDeleteException 지우는 작업을 깜빡한거 같습니다!

2022-06-01 04:24 UTC, jaesungahn91 commented on src/main/java/qna/service/QnaService.java
>      public void deleteQuestion(User loginUser, Long questionId) throws CannotDeleteException {
`throws CannotDeleteException` 해당 코드를 삭제하는걸 깜빡했습니다ㅜㅜ!

2022-06-01 04:24 UTC, jaesungahn91 commented on src/main/java/qna/CannotDeleteException.java
> +public class CannotDeleteException extends RuntimeException {
에러처리를 강제하지 않기 위해서 사용했습니다!

2022-06-01 05:53 UTC, chae-yh approved these changes
재성님 안녕하세요! 피드백 잘 반영해주셨습니다 👍 
몇가지 추가로 확인해보면 좋을만한 내용은 코멘트 드렸으나, 미션의 완료와는 관계가 없다고 생각되기에 이만 merge 하도록 하겠습니다!

jpa 미션 마지막까지 피드백 잘 반영해주셔서 감사하고, 지금의 페이스로 모든 미션 완주하시길 빌겠습니다 ㅎㅎ 해당 미션은 여기서 종료되므로, 제 리뷰는 여기까지 드리겠지만 다른 미션에서 저 보다 훌륭하신 리뷰어님들과 소통하며 더 많은 성장하실 것이라고 생각합니다!

그 동안 고생많으셨습니다! 감사합니다 : )

2022-06-01 05:53 UTC, chae-yh commented on src/main/java/qna/domain/DeleteHistories.java
> +public class DeleteHistories {
일급 컬렉션으로 잘 분리해주셨습니다 👍

2022-06-01 05:53 UTC, chae-yh commented on src/main/java/qna/domain/DeleteHistories.java
> +    List<DeleteHistory> deleteHistories = new ArrayList<>();
private 접근 제한자를 추가해줘도 좋지 않을까요...?

2022-06-01 05:53 UTC, merged