[Step3]질문 삭제하기 리팩터링 PR 요청 드립니다.
next-step/jwp-qna pull request #565
Opened 2022-06-15 09:44 UTC by choi-ys

안녕하세요 :) 교육생 최용석입니다.

3단계 질문 삭제하기 리팩터링 미션 구현이 완료되어, 코드 리뷰 요청드립니다.

이번 미션 역시 미흡한 부분이 있다면 피드백 부탁드립니다 :)

--- 

이번 PR에도 step2에서 피드백 주셨던 내용에 대한 TC를 아래 커밋에 작성하였습니다.

- [FetchType.LAZY VS FetchType.EAGER 동작 비교](https://github.com/next-step/jwp-qna/commit/89df5204a78d3ba00ac02ddf15a06bb4d04a9def)
- [JPQL의 Join VS Fetch Join 동작 비교](https://github.com/next-step/jwp-qna/commit/f68a2b12b319d8fdfc23727a0341bd142b633e61)
- [Fetch Join VS@EntityGraph 동작 비교(inner join vs left join)](https://github.com/next-step/jwp-qna/commit/b84da39009c093e1768903744d06bbaee72eba1c)
- [N+1이 문제와 N+1에 대한 해결 방안](https://github.com/next-step/jwp-qna/commit/141c200d4b0f59f5fb549e1b33c9537d9b4dd0b4)
- [트랜잭션에서 밖에서 프록시 객체 초기화 시 발생하는 LazyInitializationException 검증](https://github.com/next-step/jwp-qna/commit/0dfe63e43f4f3bef1eb03b3338cd7b4d3273129b)

한번 더 생각할 수 있도록 리뷰 해주신 덕분에, 이번 미션을 진행하는 동안 전반적으로 JPA에 대해 돌아보는 계기가 되었습니다 :) 
길지 않은 기간 이었지만 리뷰 해주시느라 고생 많으셨습니다. 감사합니다!

2022-06-15 13:18 UTC, seokhongkim requested changes
용석님, JPA 3단계 미션도 잘 진행해주셨습니다.

2단계 미션에서 드린 피드백에 대해 학습 테스트를 모두 작성하며, 자세히 학습하신 것 같네요!
이번 단계 미션도 꼼꼼한 테스트와 함께 작은 커밋을 유지하며 잘 진행해주셨습니다. 👍 

코멘트를 조금 남겼으니 확인 부탁드립니다. 🙏

2022-06-15 13:18 UTC, seokhongkim commented on docs/step2-README.md
> +- Fetch Join을 이용하여 연관관계를 가지는 Entity를 함께 조회
피드백 드린 내용을 꼼꼼하게 잘 학습해주셔서 피드백 드린 보람이 더 크게 느껴지네요! 감사합니다. :)

fetch join 을 사용할 때 limit 쿼리와 함께 사용하면 어떤 일이 발생하는지도 같이 보셔도 도움이 될 것 같습니다.

예를 들면, 질문 5개와 거기에 달린 답변을 모두 조회하고 싶을 때 fetch join + distinct + limit 5 를 사용하면 어떻게 동작할까요? distinct 없이 사용하는 경우에는 어떻게 동작할까요?

2022-06-15 13:18 UTC, seokhongkim commented on src/main/java/qna/domain/Answer.java
> +    public void delete() {
`Answer` 라는 도메인의 입장에서 봤을 때, 질문은 그대로 남아있고 답변만 삭제하는 경우 `delete` 는 어떻게 동작해야 할까요?

hint: 답변을 작성한 사람만 삭제할 수 있어야 한다는 제약조건은 어느 도메인에서 담당해야 할 역할일까요?

2022-06-15 13:18 UTC, seokhongkim commented on src/main/java/qna/domain/Answers.java
> +            throw new CannotDeleteException("다른 사람이 쓴 답변이 있어 삭제할 수 없습니다.");
질문을 삭제할 때 발생할 수 있는 예외 내용으로 보이네요!
답변을 관리하는 컬렉션에서 질문 도메인에 대해 자세히 알고 있는 것은 아닐까요?

2022-06-15 13:18 UTC, seokhongkim commented on src/main/java/qna/repository/AnswerRepository.java
>      Optional<Answer> findByIdAndDeletedFalse(Long id);
이 메소드를 사용하는 곳이 남아 있을까요?

2022-06-15 13:18 UTC, seokhongkim commented on src/main/java/qna/service/QnaService.java
> +        DeleteHistories deleteHistories = DeleteHistories.of(question);
삭제를 한 후 `DeleteHistory` 를 만들어줘야 한다는 것을 서비스에서 관리하고 있네요!
`Question`, `Answer` 도메인에서 데이터가 삭제되는 경우 삭제 이력을 반환하도록 만들어 보는 것은 어떨까요?

2022-06-15 13:18 UTC, seokhongkim commented on src/test/java/qna/feedback/Ex02_Lazy_Type_And_Eager_Type_Test.java
> +public class Ex02_Lazy_Type_And_Eager_Type_Test {
학습 테스트 좋습니다! 👍

2022-06-17 06:50 UTC, choi-ys commented on src/main/java/qna/domain/Answer.java
> +    public void delete() {
질문과 답변을 모두 삭제하는 경우만 고려하여 작성자에 대한 유효성 검사를 답변 일급 컬렉션에 작성하게 되었습니다.
답변만 삭제하는 경우를 고려하여, 작성자에 대한 유효성 검사부의 위치를 수정하겠습니다!

2022-06-17 06:56 UTC, choi-ys commented on docs/step2-README.md
> +- Fetch Join을 이용하여 연관관계를 가지는 Entity를 함께 조회
말씀하셨던 내용에 대한 학습테스트를 아래 커밋에 작성하였습니다!

[test: 1:N 연관관계의 fetch join 사용 시, 주의 사항 및 해결 방안에 대한 학습 테스트](https://github.com/next-step/jwp-qna/pull/565/commits/7d0fdf566716757c630b693f8844d25a7b2bee07)

다만  distinct 유무에 따른 아래 두가지 학습 테스트를 작성 하였지만, 큰 차이점을 발견하지 못했습니다. 
- fetch join + distinct + limit 5 
- fetch join + limit 5 

distinct 유무에 따라 중복 제거에 대한 부분에 차이가 있을 것이라고 예상 하였지만, distinct를 명시하지 않은 페이징 쿼리의 결과에 중복이 제거되어 있어서 이 부분에 대해 제가 추가로 알아야 할 사항이 있다면 한번더 피드백 부탁드리겠습니다.

2022-06-17 09:08 UTC, choi-ys commented on src/main/java/qna/domain/Answers.java
> +            throw new CannotDeleteException("다른 사람이 쓴 답변이 있어 삭제할 수 없습니다.");
이 부분도 연관도가 높은 각 도메인으로 묶일 수 있도록 위치를 수정하겠습니다!

2022-06-17 09:09 UTC, re-mora commented on src/main/java/qna/service/QnaService.java
> +        DeleteHistories deleteHistories = DeleteHistories.of(question);
Question/Answer 도메인의 반환형을 다른 도메인으로 구성하는 것이 어색하여 따로 분리하게 되었습니다.
말씀하신 것처럼 삭제 로직 수행 결과로 삭제 이력을 반환할 수 있도록 구성 하겠습니다!

2022-06-17 09:25 UTC, seokhongkim commented on docs/step2-README.md
> +- Fetch Join을 이용하여 연관관계를 가지는 Entity를 함께 조회
데이터 개수에 따라서 테스트 결과가 달라질 수 있는데, 이 부분을 제가 말씀드리지 않았네요. 😓 
[블로그](https://tecoble.techcourse.co.kr/post/2020-10-21-jpa-fetch-join-paging/)에 올라온 내용을 읽어보시고, 테스트에 참고하시면 도움이 될 것 같습니다. :)

2022-06-17 09:31 UTC, seokhongkim requested changes
용석님, 피드백 잘 반영해주셨습니다! 👍 

질문주신 내용에 대한 답변도 남겼습니다.
간단한 코멘트 조금 남겼으니 확인 부탁드립니다. 🙏

2022-06-17 09:31 UTC, seokhongkim commented on src/main/java/qna/repository/AnswerRepository.java
> +//    Optional<Answer> findByIdAndDeletedFalse(Long id);
사용하지 않는 코드는 주석 처리보다는 삭제하시는 것을 권장합니다.
나중에 필요하시면 commit log 를 보시면 어떤 코드인지 찾을 수 있어요!

2022-06-17 09:31 UTC, seokhongkim commented on src/main/java/qna/repository/QuestionRepository.java
> +//글로벌서비스 개발팀이 현재 운영하고 있는 서비스가 있는지
코드와 상관 없는 내용이 붙여넣기 된 것 같습니다. :)

2022-06-17 09:31 UTC, seokhongkim commented on src/main/java/qna/domain/Question.java
> +        List<DeleteHistory> deleteHistories = new ArrayList<>();
본인이 작성하지 않은 답변이 있는 경우 발생했던 `CannotDeleteException("다른 사람이 쓴 답변이 있어 삭제할 수 없습니다.")` 예외 처리 코드가 사라진 것 같습니다.

2022-06-17 09:38 UTC, choi-ys commented on src/main/java/qna/repository/QuestionRepository.java
> +//글로벌서비스 개발팀이 현재 운영하고 있는 서비스가 있는지
헉.. 삭제하도록 하겠습니다.. 😭

2022-06-17 10:15 UTC, choi-ys commented on src/main/java/qna/domain/Question.java
> +        List<DeleteHistory> deleteHistories = new ArrayList<>();
기존 답변 컬렉션 객체에 구현 했던 코드를 삭제 하면서 누락된 것 같습니다 😭 
질문 삭제 시, 본인이 작성하지 않은 답변이 포함되는 경우에 대한 예외 처리를 아래 커밋에 추가하였습니다.

[refactor: 본인이 작성하지 않은 답변이 포함되는 경우 예외 누락 추가](https://github.com/next-step/jwp-qna/pull/565/commits/a7b4666d503aa32237f675a9e2af9b545e15be2e)

2022-06-17 10:57 UTC, seokhongkim approved these changes
용석님, 3단계 미션 잘 마무리해주셨습니다. 👍 

미션을 진행하시며 피드백으로 말씀드린 내용에 대해서도 열심히 학습하신 것 같습니다.
학습하신 내용이 앞으로 JPA 사용하실 때 도움이 되셨으면 좋겠네요!

남은 과정도 많이 학습하시고 성장하실 수 있기를 응원하겠습니다. 💪 
JPA 미션 진행하느라 수고하셨습니다! 👏

2022-06-17 10:57 UTC, merged