2단계 - 연관 관계 매핑
next-step/jwp-qna pull request #588
Opened 2022-11-02 16:56 UTC by snh15978

안녕하세요!

2단계 - 연관 관계 매핑 PR입니다.

확인부탁드려요~!

2022-11-03 11:55 UTC, dhmin5693 requested changes
남현님 안녕하세요!

JPA 미션 강의가 오늘인데 벌써 두 번째 미션을 해주시다니...
정말 좋은 열정입니다.

몇 가지 확인해야 할 부분이 있어서 피드백을 남겨두었습니다.
확인 후 다시 요청 부탁드립니다 🙇‍♂️

2022-11-03 11:55 UTC, dhmin5693 commented on src/test/java/qna/domain/AnswerRepositoryTest.java
> +    private User answerWriter;
리뷰 화면에 sameEntity 테스트가 안잡혀서 여기다 남깁니다.
전체 테스트를 한 번에 돌리면 sameEntity 테스트가 실패합니다.

상수로 선언된 `AnswerTest.A2` 가 여기저기서 저장되고 하다보면 이렇게 오류가 발생하기 때문에 가급적 별도의 인스턴스를 생성해서 독립적으로 테스트를 수행하는게 좋습니다.

2022-11-03 11:55 UTC, dhmin5693 commented on src/main/java/qna/domain/Answer.java
>      }
이번 미션에서 setter는 사용하지 않는게 좋겠습니다. 전부 제거해주세요.
setter를 많이 사용할수록 객체지향에서 멀어지게 됩니다.

2022-11-03 11:55 UTC, dhmin5693 commented on src/main/java/qna/domain/Answer.java
> +    private User writeBy;
`Answer`의 `User` 필드는 `DeleteHistory` 생성 시에만 넣어주고 있는데요,
여기서 굳이 연관관계를 맺을 필요는 없다고 생각해요.

다른 곳에 연관관계를 생성해보는건 어떤가요?

2022-11-03 17:22 UTC, snh15978 commented on src/test/java/qna/domain/AnswerRepositoryTest.java
> +    private User answerWriter;
수정완료!

2022-11-03 17:23 UTC, snh15978 commented on src/main/java/qna/domain/Answer.java
>      }
수정완료!

2022-11-03 17:26 UTC, snh15978 commented on src/main/java/qna/domain/Answer.java
> +    private User writeBy;
말씀하신 부분이 `Question`과 `Answer`를 양방향 연관관계 매핑을 하고 `Question`을 통해서 `Answer`를 제거로 변경하는걸로 이해하는게 맞을까요?

2022-11-04 11:59 UTC, dhmin5693 approved these changes
피드백 잘 반영해주셨네요 :)
사실 워낙 잘 해주셔서 크게 남겨드릴만한게 없었어요.

몇개 더 남겨는 두었는데요, 이번 미션은 충분한 공부가 된 것 같아서 마무리할까 합니다.
다음 미션 시작 전에 살짝 확인 부탁드릴게요.

그럼 다음 미션에서 또 뵈어요 👋

2022-11-04 11:59 UTC, dhmin5693 commented on src/main/java/qna/domain/Answer.java
> +    private User writeBy;
맞습니다.
사실 양방향은 서로가 서로를 의존하는 사이클이 생기기 때문에 좋지 못한 구조입니다만
JPA에서는 편의를 위해 사용하고 있어서 약간 예외를 두고 있습니다.

무엇보다 이 미션은 JPA에 친숙해지는게 목표니까 이것 저것 잘 써보는게 좋아요 😁

그럼에도 `User`의 연관성을 제거해달라고 한 이유는 이번 미션의 코드가 `User` 연관관계를 사용할만큼 필요해보이진 않았거든요.
이 부분은 선택사항이니 고민 후 결정해주세요.

2022-11-04 11:59 UTC, dhmin5693 commented on src/main/java/qna/domain/Answer.java
> +        return this.writeBy.equals(writer);
equals를 사용했는데 `User` 에 equals가 구현되어 있지 않아요.
이 구문에서 버그가 발생할 수 있겠네요.

2022-11-04 11:59 UTC, dhmin5693 commented on src/main/java/qna/domain/Answer.java
>      }
다른 setter 는 다 제거하셨는데 여긴 아직 그대로에요.
메소드 내용을 보면 납득은 됩니다.
단순 setter가 아니니까요.

메소드명을 `updateQuestion` 으로 바꿔주는게 어떨까요?

2022-11-04 12:00 UTC, merged