Step1 엔티티 매핑 PR 리뷰 요청 드립니다.
next-step/jwp-qna pull request #597
Opened 2022-11-03 16:56 UTC by giraffelim

안녕하세요 석홍님! 이번에 우테캠 pro 5기 수강생으로 공부하게 된 임태양이라고 합니다.
1단계 엔티티 매핑에 대한 리뷰 요청드립니다!
감사합니다.

2022-11-04 10:17 UTC, seokhongkim requested changes
태양님 안녕하세요!
JPA 미션을 함께 할 리뷰어 김석홍입니다. 만나서 반갑습니다. 😀 

1단계 엔티티 매핑 미션 잘 진행해주셨습니다. 👍 
작은 단위로 나눠서 작업하시고, 커밋도 작게 나눠서 해주셨네요.

코드를 보고 궁금한 점과 고민해보시면 도움이 될 것 같은 내용을 코멘트로 남겼습니다.
코멘트 확인 부탁드립니다. 🙏

2022-11-04 10:17 UTC, seokhongkim commented on README.md
> +## 1단계 엔티티 매핑 기능 구현 목록
기능 구현 목록 정리 좋습니다. 👍 
진행할 내용이 많아지면 마크다운의 체크리스트 문법(`- [ ]`, `- [x]`)을 사용하여 진행한 것과 진행중인 내용을 구분해보셔도 도움이 될 것 같습니다. :)

2022-11-04 10:17 UTC, seokhongkim commented on src/main/java/qna/domain/BaseEntity.java
> +@MappedSuperclass
`MappedSuperclass` 적용하신 것 좋습니다. 👍

2022-11-04 10:17 UTC, seokhongkim commented on src/main/java/qna/domain/BaseEntity.java
> +@EntityListeners(AuditingEntityListener.class)
Audit 기능을 사용했을 때 `CreatedDate` 와 `LastModifiedDate` 가 어떤 식으로 값이 설정되는지도 학습해보시면 좋을 것 같습니다.
하나의 트랜잭션 내에서 다른 엔티티 여러개를 생성하거나 수정할 때 각 엔티티의 생성일시, 수정일시가 어떻게 저장되는지도 보시면 좋을 것 같아요.
이 부분을 학습, 테스트 해보시면 언제 Audit 기능을 사용하고, 사용하지 않는 게 좋을지 결정하시는 데 도움이 되리라 생각합니다.

2022-11-04 10:17 UTC, seokhongkim commented on src/main/java/qna/domain/Answer.java
> +@SQLDelete(sql = "update answer set deleted = true where id = ?")
`SQLDelete` 를 사용하여 hard delete 를 방지하신 것 좋습니다. :)
실제 `delete` 구현은 별도의 로직으로 처리되어야 하므로, repository 의 delete method 는 예외를 던지는 형태로 구현해서 의도하지 않은 동작을 방지해봐도 좋을 것 같습니다.

2022-11-04 10:17 UTC, seokhongkim commented on src/main/java/qna/domain/DeleteHistory.java
>  public class DeleteHistory {
`DeleteHistory` 에만 `equals` 가 오버라이드 되어 있네요.
JPA Entity 의 equals, hashcode 는 어떻게 구현하는 게 좋을까요? 여러 방법이 있으니 `JPA Entity equals` 와 같은 키워드로 학습해보시면 좋을 것 같습니다!

2022-11-04 10:17 UTC, seokhongkim commented on src/main/java/qna/domain/DeleteHistory.java
> +    @Enumerated(EnumType.STRING)
enum 맵핑하실 때 `EnumType.STRING` 으로 지정해주신 것 좋습니다. :)

2022-11-04 10:17 UTC, seokhongkim commented on src/main/java/qna/domain/User.java
> +    @Column(nullable = false, length = 20, unique = true)
필드에 unique 설정 잘 챙겨주셨네요!

2022-11-04 10:17 UTC, seokhongkim commented on src/main/resources/application.properties
> +spring.jpa.show-sql=true
파일 마지막에 newline 이 없다고 깃헙에서 경고를 띄워주네요.
파일 마지막의 newline 은 무슨 역할을 할까요? 학습해보셨다면 IDE 설정을 통해 휴먼 에러를 방지해보셔도 좋겠습니다. :)

2022-11-04 10:17 UTC, seokhongkim commented on src/test/java/qna/domain/AnswerRepositoryTest.java
> +    void 영속성_컨텍스트_내_동일성_비교() {
영속성 컨텍스트의 동작을 테스트하신 이유가 궁금합니다.

2022-11-04 10:17 UTC, seokhongkim commented on src/test/java/qna/domain/AnswerRepositoryTest.java
> +        assertThat(actual == answer).isFalse();
현재 equals, hashcode 구현이 안 되어 있으므로 영속성 컨텍스트의 동작에 따라 검증 결과가 false 가 나오는 것은 맞습니다.
다만, 객체의 관점에서 동일한 id 를 가진 엔티티가 다른 객체로 처리되는 것이 맞을까요? 태양님께서 어떻게 생각하시는지 궁금합니다.

2022-11-04 10:17 UTC, seokhongkim commented on src/test/java/qna/domain/AnswerRepositoryTest.java
> +@DataJpaTest
꼼꼼한 테스트 좋습니다. 👍

2022-11-05 06:40 UTC, giraffelim commented on README.md
> +## 1단계 엔티티 매핑 기능 구현 목록
@seokhongkim 
다음 단계부터 제안해주신 체크리스트 문법을 사용해서 기능 구현 목록을 작성해보도록 하겠습니다. 👍

2022-11-05 07:26 UTC, giraffelim commented on src/main/java/qna/domain/BaseEntity.java
> +@EntityListeners(AuditingEntityListener.class)
@seokhongkim 
말씀해주신대로 Spring Data JPA의 Auditing 기능이 어떠한 동작원리로 생성일과 수정일에 대한 값을 생성 및 수정 시 지정해주는지에 대해 학습하였습니다. 그로 인해 알게된 내용은 다음과 같습니다.
1. spring data common 프로젝트에서 CreateBy, CreatedDate, LastModifiedBy, LastModifiedDate와 같은 어노테이션을 지원
2. 흔히들 사용하는 AuditingEntityListener는 Spring Data JPA에서 구현한 EntityListener로 @PrePersist, @PreUpdate 설정을 통해 엔티티가 영속화 되기 이전에 AuditingHandler를 통해 생성일, 수정일과 같은 정보를 찾아 설정
3. 본 과제에서 설정한 @CreateDate, @LastModifiedDate는 DateTimeProvider로 부터 추출되는데, 따로 지정하지 않을 경우 CurrentDateTimeProvider로 부터 추출
4. CurrentDateTime은 LocalDateTime을 사용, 따라서 ZonedDateTime을 사용할 경우 에러를 발생
5. ZonedDateTime을 사용하고 싶은 경우 아래와 같이 AuditingEntityListener의 기능을 사용하지 않고 구현
```
@EntityListeners(value = {AuditingEntityListener.class})
public abstract class BaseEntity {
    
    private ZonedDateTime createdAt;

    private ZonedDateTime updatedAt;

    @PrePersist
    public void onPrePersist() {
        this.createdAt = ZonedDateTime.now(ZoneOffset.UTC);
        this.updatedAt = this.createdAt;
    }

    @PreUpdate
    public void onPreUpdate() {
        this.updatedAt = ZonedDateTime.now(ZoneOffset.UTC);
    }
}
```

https://gist.github.com/dlxotn216/94c34a2debf848396cf82a7f21a32abe

2022-11-05 08:22 UTC, giraffelim commented on src/main/java/qna/domain/Answer.java
> +@SQLDelete(sql = "update answer set deleted = true where id = ?")
@seokhongkim 
`@SQLDelete` 어노테이션을 사용한 이유는, Repository에서 제공하는 `delete` Method를 사용할 경우 `hard delete` 방식이 아닌 어노테이션에 value로 전달한 `sql`이 실행되어 `soft delete` 방식이 되도록 하기 위해 사용했는데, 이 경우에는 delete 메소드를 예외처리 하면 안되지 않나요??..

2022-11-05 08:24 UTC, giraffelim commented on src/main/resources/application.properties
> +spring.jpa.show-sql=true
@seokhongkim 
아래 커밋에서 EOL 반영했습니다. 관습처럼 end-of-line을 붙이곤 했었는데 이번 기회덕분에 POSIX 명세를 지키기 위해 붙여야 한다는 것을 알게 되었습니다 👍 
[2758eaa](https://github.com/next-step/jwp-qna/pull/597/commits/2758eaa536fa0ae85b9fdcaf47873079199b5d6f)

2022-11-05 08:38 UTC, giraffelim commented on src/test/java/qna/domain/AnswerRepositoryTest.java
> +    void 영속성_컨텍스트_내_동일성_비교() {
@seokhongkim 
영속성 컨텍스트 내에서는 다른 객체라 하더라도, ID가 같다면 동일하다는 것을 보장해준다는 특징이 존재해 테스트 해보았습니다.

2022-11-05 10:18 UTC, giraffelim commented on src/main/java/qna/domain/DeleteHistory.java
>  public class DeleteHistory {
@seokhongkim 
DeleteHistory 내 equals 오버라이딩은 기본적으로 되어있기에 따로 건들지는 않았습니다!
하지만 이번 기회에 JPA Entity equals와 hashcode에 대해 알아보게 되었습니다. 알게된 내용은 간략하게 다음과 같습니다.

1. equals와 hashCode를 재정의하는 이유는 엔티티(객체)는 데이터베이스 테이블의 레코드를 나타내는 객체에 가깝기 때문에 이 엔티티의 필드(ID ...)등이 동일하다면 같은 레코드, 즉 같은 객체라고 판단해야 하기 때문에 재정의한다.
2. equals와 hashCode를 재정의하는 방법으로는 기본 키를 활용하는 방법, 모든 필드를 활용하는 방법, 비즈니스 키를 활용하는 방법이 존재한다. 하지만 기본키만 hashCode를 활용하도록 하는 경우, 서로 다른 테이블의 엔티티가 같은 해시값을 가져 hashCode를 활용하는 HashMap등에서는 덮어 씌워지거나 할 수 있다. 따라서 상황에 맞게 적절한 방법을 활용해야 한다.

혹시 제가 잘못 알게 된 부분이나, 추가적으로 확인해보면 좋은 것들이 있다면 코멘트 남겨주시면 감사하겠습니다.

2022-11-05 12:01 UTC, giraffelim commented on src/test/java/qna/domain/AnswerRepositoryTest.java
> +        assertThat(actual == answer).isFalse();
@seokhongkim 
위에 남겨주신 코멘트를 통해 equals와 hashCode를 알아보며 ID가 동일한 엔티티의 경우 같은 객체로 처리되도록 하는 것이 맞을 것 같아, 동일한 객체인지 확인하도록 테스트를 수정하였습니다.
[85d9edc](https://github.com/next-step/jwp-qna/pull/597/commits/85d9edc80688c300bc831c2f042c1e417ad585af)
[34ce6a5](https://github.com/next-step/jwp-qna/pull/597/commits/34ce6a576e6f4fbcab5ee63d669b9b3f43118538)

2022-11-05 12:04 UTC, giraffelim commented on src/main/java/qna/domain/DeleteHistory.java
>  public class DeleteHistory {
현재는 엔티티의 PK, FK만을 통해서 각 객체의 동등성을 비교할 수 있을 것 같다는 생각이 들어 해당 키값들만 사용하도록 재정의 해두었습니다!..

2022-11-05 13:17 UTC, seokhongkim commented on src/main/java/qna/domain/BaseEntity.java
> +@EntityListeners(AuditingEntityListener.class)
태양님 구현에 대해 자세히 찾아보시고 고민하신 것 같아요!

1. 이미 잘 아시겠지만, `@CreatedDate` 와 같이 `@` 가 들어가는 코드를 코멘트에 남기실 때는 백틱(\`)으로 감싸주셔야 멘션이 되지 않습니다. `@Createdate` 라는 계정이 멘션된 것으로 보여 말씀드려요~
2. 찾아보신 것처럼 자바 `LocalDateTime.now` 와 같은 값을 생성해서 `set` 해주는 형태로 구현되기에, 여러 엔티티를 저장하거나 수정하는 경우 한 트랜잭션 안에서 발생한 작업의 생성/수정 일시가 다르게 저장될 수 있습니다. :)

2022-11-05 13:19 UTC, seokhongkim commented on src/main/java/qna/domain/Answer.java
> +@SQLDelete(sql = "update answer set deleted = true where id = ?")
의도하신 것처럼 `delete` 메소드가 soft delete 로 처리되도록 하신 것은 좋습니다. 다만, `Answer` 의 `delete` 메소드를 통한 삭제가 아니라 레포지토리의 `delete` 메소드를 통한 삭제가 가능하면 안 될 것 같아서 말씀드렸습니다.
즉, `delete` 가 쿼리를 이용해서 처리되면 안되고, 비즈니스 밸리데이션을 거쳐야 하므로 레포지토리의 `delete` 메소드를 오버라이드해서 예외를 던지도록 해도 좋을 것 같아요.

2022-11-05 13:21 UTC, seokhongkim commented on src/test/java/qna/domain/AnswerRepositoryTest.java
> +    void 영속성_컨텍스트_내_동일성_비교() {
영속성 컨텍스트의 특징을 학습하기 위한 목적으로 테스트 하셨군요!
레포지토리 테스트에 있어서 레포지토리의 동작을 테스트하시는 의도도 있는지 궁금해서 여쭤봤습니다 :)

2022-11-05 13:23 UTC, seokhongkim commented on src/main/java/qna/domain/DeleteHistory.java
>  public class DeleteHistory {
이 부분은 잘 구현해주셨는데, 저는 PK만 사용해서 구현하셔도 좋을 것 같아요.
PK의 정의상 PK가 같다면 FK가 다른 엔티티가 존재하면 안 될 것 같네요.

2022-11-05 13:24 UTC, seokhongkim approved these changes
태양님, 1단계 미션 코멘트 잘 반영해주셨습니다. 💯 
1단계 PR은 이만 머지하도록 하겠습니다.

2단계 미션에서 뵙겠습니다. 😀

2022-11-05 13:24 UTC, merged