[Step1] 엔티티 매핑 리뷰 요청드려요
next-step/jwp-qna pull request #613
Opened 2022-11-05 08:09 UTC by meeingjae

2단계 미션을 진행하게 된 김민재(밍블) 입니다. 😄
날씨가 쌀쌀하니 감기 조심하시고 좋은 주말 되세요
앞으로 잘 부탁드립니다 🙇🏻‍♂️

2022-11-05 14:42 UTC, minzzang requested changes
안녕하세요 민재님~!
JPA 1단계 미션 잘 수행해주셨습니다! :+1:

수정하면 좋을 부분이 있어 코멘트 남겼는데 확인 부탁드립니다. 🙏 
그럼 남은 주말도 화이팅하세요!! :muscle:

2022-11-05 14:42 UTC, minzzang commented on src/main/java/qna/domain/Answer.java
> +@EntityListeners(AuditingEntityListener.class)
여러 도메인에서 Auditing 기능을 사용하는데 분리해보면 좋을 것 같아요!

2022-11-05 14:42 UTC, minzzang commented on src/main/java/qna/domain/Answer.java
> +    public boolean equals(Object o) {
equals에서 모든 변수를 비교한 이유가 있을까요?

2022-11-05 14:42 UTC, minzzang commented on src/main/java/qna/domain/AnswerRepository.java
> +@Repository
참고해보면 좋을 것 같아요~
[Repository 어노테이션](https://velog.io/@dltkdgns3435/SpringBoot-spring-data-jpa-%EC%82%AC%EC%9A%A9%EC%8B%9C-Repository-%EC%96%B4%EB%85%B8%ED%85%8C%EC%9D%B4%EC%85%98%EC%9D%80-%EA%BC%AD-%ED%95%84%EC%9A%94%ED%95%9C%EA%B0%80)

2022-11-05 14:42 UTC, minzzang commented on src/main/java/qna/domain/DeleteHistory.java
> +    @Column(name = "content_type", length = 255)
Enum타입 매핑은 어떻게 처리하면 좋을까요~?

2022-11-05 14:42 UTC, minzzang commented on src/test/java/qna/domain/AnswerTest.java
> +        assertThatNoException().isThrownBy(() -> answerRepository.save(A1));
저장된 객체의 id값으로도 확인할 수 있지 않을까요~?

2022-11-05 14:42 UTC, minzzang commented on src/test/java/qna/domain/UserTest.java
> +    @DisplayName("userId 가 null 인 엔티티 저장")
저장을 확인하는 테스트를 여러 개 만드셨는데 ParameterizedTest를 활용해보는 건 어떨까요~?

2022-11-05 14:42 UTC, minzzang commented on src/test/java/qna/domain/DeleteHistoryTest.java
> +public class DeleteHistoryTest {
요구사항에 @DataJpaTest를 사용하여 학습 테스트를 해 본다. 라고 나와 있는데 CRUD 모두 학습해 보는건 어떨까요~?

2022-11-05 14:42 UTC, minzzang commented on src/main/java/qna/Application.java
>  public class Application {
요구사항 정리가 빠져있는 거 같아요!

2022-11-05 23:32 UTC, meeingjae commented on src/main/java/qna/domain/Answer.java
> +@EntityListeners(AuditingEntityListener.class)
생성 일자, 수정 일자 컬럼을 갖고 있는 엔티티의 createdAt, updatedAt 필드를 추상 클래스로 분리하였습니다.
피드백 감사합니다 !

2022-11-05 23:38 UTC, meeingjae commented on src/main/java/qna/domain/Answer.java
> +    public boolean equals(Object o) {
처음 의도는 객체 자체를 비교하기 위함이었는데요
곰곰히 생각해보니 ```id``` 값만 비교해도 충분할 것 같아 ```id``` 값만 비교하는 것으로 수정하였습니다 !

2022-11-05 23:51 UTC, meeingjae commented on src/main/java/qna/domain/AnswerRepository.java
> +@Repository
Springboot 에선 ```JpaRepositoriesAutoConfiguration``` 에서 ```JpaRepository``` 레포지토리 타입을 활성화 시켜주고 있었네요.
```@Repository``` 어노테이션 삭제하였습니다 !
피드백 감사합니다 👍👍

2022-11-05 23:58 UTC, meeingjae commented on src/main/java/qna/domain/DeleteHistory.java
> +    @Column(name = "content_type", length = 255)
```@Enumerated``` 어노테이션 사용하여 Enum 타입 매핑했습니다 ! 
현재 ```content_type``` 필드는 varchar 타입의 컬럼 구조를 갖고 있어 ```Enumtype.String``` 으로 매핑했습니다
피드백 감사합니다 !

2022-11-06 00:01 UTC, meeingjae commented on src/test/java/qna/domain/AnswerTest.java
> +        assertThatNoException().isThrownBy(() -> answerRepository.save(A1));
```Answer``` 클래스의 ```equals``` 메서드를 ```id``` 값 비교로 수정 진행하면서
해당 테스트케이스도 객체 비교로 대체하였습니다
피드백 감사합니다 !

2022-11-06 00:12 UTC, meeingjae commented on src/test/java/qna/domain/UserTest.java
> +    @DisplayName("userId 가 null 인 엔티티 저장")
동일한 타입의 input에 동일한 타입의 output을 기대하는 테스트가 여러개 있었네요 !
충분히 ```Parameterized``` 테스트로 대체 가능할 것 같습니다
피드백 감사합니다 !

2022-11-06 00:48 UTC, meeingjae commented on src/test/java/qna/domain/DeleteHistoryTest.java
> +public class DeleteHistoryTest {
피드백 반영하여 ```Update```, ```Delete``` 테스트도 추가하였습니다 ! 👍

2022-11-06 01:01 UTC, meeingjae commented on src/main/java/qna/Application.java
>  public class Application {
요구사항 정리 문서 포함해서 커밋 올렸습니다 ! 🙇🏻‍♂️

2022-11-06 04:59 UTC, minzzang approved these changes
안녕하세요 민재님~!

피드백 반영 잘 해주셨네요~! :+1:

그럼 다음 미션도 화이팅입니다! :muscle:

2022-11-06 04:59 UTC, merged