3단계 - 질문 삭제하기 리팩터링 PR 요청드립니다.
next-step/jwp-qna pull request #614
Opened 2022-11-05 09:30 UTC by earth-h

안녕하세요, 민수님 :) 

3단계 - 질문 삭제하기 리팩터링 PR 피드백 요청드립니다.

먼저, 리팩터링 시 중점적으로 생각했던 부분은 아래와 같습니다 :) 
- 객체에 메시지를 보내어 로직 수행하도록 진행
- Answers 일급컬렉션 생성 -> 임베디드 타입 지정
  - 일급컬렉션 사용 시, list 내부가 외부요인에 의해 변경되지 않도록 관리
    - 생성자를 통해 list를 넣을 때 복사해서 넣도록 하여 외부에 의해 의도치 않은 변경 막고자 함
    - getAnswers()와 같은 list를 반환하는 메소드 대신, list를 조회해서 하려고 하는 행위(예: size() 반환 등) 자체를 메소드로 뽑아 사용
- DeleteHistories 일급컬렉션 생성
  - Answers와 달리, DeleteHistories는 list가 조회되어야 레포지토리에 넣을 수 있어, unmodifiedList()로 반환하여 저장할 수 있도록 함
  - 생성자를 통해 list 넣을 때 복사하여 넣도록 하여 외부에 의한 의도치 않은 변경 막고자 함
- 양방향 연관관계인 Answer와 Question 사이에 연관관계 편의 메소드는 Answer에만 생성
  - 기본적으로, 질문이 생성된 후 답변이 생성되어 질문과 연결되기 때문에 Answer에 의해서만 toQuestion() 통해서 연관관계가 맺어지도록 함

리팩토링 이후에도 고민되는 포인트는 아래와 같습니다...! 
- Answers에 생성한, removeAnswer()와 addAnswer()가 question에서 호출하기 때문에 public으로 열려있는데, 이렇게 열어도 될지 고민입니다. 외부 요인에 의해 잘못된 add나 remove를 막으려면 private이어야 할 것 같은데, 이를 내부적으로 수행할 방안을 찾지 못하였습니다..😭
- Answer 각각의 validation 체크를 Answers에서도 진행한 부분
  - Answer에서만 validateSameUser() 체크를 진행하고 싶었으나, 각각 Answer의 validate 후 바로 삭제여부를 변경하게 되면, 아래와 같은 상황일 때 잘못된 결과 발생하여서 중복된 validation체크가 된 것 같아 고민이 됩니다.
  - ```text
    상황) 질문A에 대한 답변1, 답변2가 존재할 때 답변2의 작성자가 질문과 상이하다.
    이때, answer 내에서만 validateSameUser() 체크 시, 답변1은 validation 통과 후 삭제여부가 true가 되고, 이후 답변2는 validation에서 걸려 exception이 터진다. 
    => 답변1의 삭제여부가 다시 false로 변경되지 않는 문제 발생
    ``` 

매번 좋은 피드백 감사드립니다 ! ㅎㅎ

2022-11-06 09:36 UTC, mskangg requested changes
3단계 미션도 잘 수행해주셨습니다 👍 
미션을 수행하면서 항상 중점적인 부분들 PR 로 설명해주셔서 보기간편했어요 🤩
몇가지 피드백 드렸으니 적용 부탁드려요 🙇‍♂️

> Answers에 생성한, removeAnswer()와 addAnswer()가 question에서 호출하기 때문에 public으로 열려있는데, 이렇게 열어도 될지 고민입니다. 외부 요인에 의해 잘못된 add나 remove를 막으려면 private이어야 할 것 같은데, 이를 내부적으로 수행할 방안을 찾지 못하였습니다..😭

사실 코드레벨에서 `외부 요인에 의해 잘못된 add나 remove`를 완전히 막을 순 없습니다.
add나 remove의 전제조건이 있다면 validation 정도 처리하는 것으로도 충분해 보여요 👍 

> Answer 각각의 validation 체크를 Answers에서도 진행한 부분

이 부분은 피드백 드렸습니당 😁

2022-11-06 09:36 UTC, mskangg commented on src/main/java/qna/domain/Answer.java
> +        return DeleteHistory.createDeleteHistory(ContentType.ANSWER, this.id, this.writer);
삭제 히스토리를 각각 `DeleteHistory.ofAnswer(id, writer) 와 ofQuestion` 으로 네이밍해서 만든다면 더욱 좋을 것 같아요 😃

2022-11-06 09:36 UTC, mskangg commented on src/main/java/qna/domain/Answers.java
> +        return new DeleteHistories(deleteHistories);
```java
    public DeleteHistories deleteAll(User user) {
        return answers.stream()
                .map(answer -> answer.delete(user))
                .collect(Collectors.collectingAndThen(Collectors.toList(), DeleteHistories::new));
    }
```
stream을 활용해보시는건 어떠신가요??

2022-11-06 09:36 UTC, mskangg commented on src/main/java/qna/domain/Answers.java
> +    }
> 상황) 질문A에 대한 답변1, 답변2가 존재할 때 답변2의 작성자가 질문과 상이하다.
이때, answer 내에서만 validateSameUser() 체크 시, 답변1은 validation 통과 후 삭제여부가 true가 되고, 이후 답변2는 validation에서 걸려 exception이 터진다. 
=> 답변1의 삭제여부가 다시 false로 변경되지 않는 문제 발생

이 부분은 서비스레이어에서 `@Transactional` 로 관리되어 있기 때문에 all pass / all fail 을 보장합니다.
그렇기 때문에 위 상황의 경우 답변1의 삭제여부가 다시 false 로 롤백되어집니다.

2022-11-06 09:36 UTC, mskangg commented on src/main/java/qna/domain/DeleteHistories.java
> +    }
equals를 오버라이딩하신 이유가 있으신가요??
컬렉션이기 때문에 element 의 순서가 바뀐다면 다른 컬렉션으로 인식합니다.

2022-11-06 09:48 UTC, mskangg commented on src/test/java/qna/domain/AnswerTest.java
> +    }
질문이_존재하지_않음 에 대한 예외 테스트케이스도 추가해보아요 😃

2022-11-06 09:57 UTC, earth-h commented on src/main/java/qna/domain/Answers.java
> +    }
@Transactional에 의해서 롤백되어질 것을 기대하고 하기와 같이 테스트코드를 작성해서 진행했었는데요!
제가 원하는 결과가 나오지 않는 것 같아 validation을 중복으로 처리하였습니다 ㅠ
혹시 테스트할 때에 @Tranactional을 통해 롤백되었는지까지 테스트할 방법이 있을까요..? 

**[ QnaServiceTest.java ]**
```java
    @Test
    void 질문자와_답변자_달라_예외_발생하면_질문_삭제여부는_거짓() {
        //given
        User writer = TestUserFactory.create("sanjigi");
        User fakeWriter = TestUserFactory.create("javajigi");
        Question question = TestQuestionFactory.create(writer);
        Answer answer1 = TestAnswerFactory.create(writer, question);
        Answer answer2 = TestAnswerFactory.create(fakeWriter, question);
        questionRepository.save(question);

        //when
        when(questionRepository.findByIdAndDeletedFalse(question.getId())).thenReturn(Optional.of(question));
        assertThat(question.isDeleted()).isFalse();
        assertThat(question.answersCount()).isEqualTo(2);
        assertThatThrownBy(() -> qnaService.deleteQuestion(writer, question.getId()))
                .isInstanceOf(CannotDeleteException.class);

        //then
        assertThat(question.isDeleted()).isFalse();
        assertThat(answer1.isDeleted()).isFalse();
    }
```

**[ Answers.java ]**
```java
    public DeleteHistories delete(User user) {
        List<DeleteHistory> deleteHistories = new ArrayList<>();
        validateSameUser(user); // 이 부분을 주석처리하면 위 테스트코드 성공하지 않음
        for(Answer answer: this.answers) {
            deleteHistories.add(answer.delete(user));
        }
        return new DeleteHistories(deleteHistories);
    }

2022-11-06 10:39 UTC, earth-h commented on src/main/java/qna/domain/DeleteHistories.java
> +    }
기본적으로 제공되는 테스트코드와 제가 구현한 테스트코드 일부에서 DeleteHistories를 비교해야 하는 부분이 있어 구현하였습니다.

말씀해주신 컬렉션 순서에 따른 equals() 참/거짓이 달라질 수 있는 부분은 제가 고려하지 못했던 부분이라 해당 부분 추가하여서 equals() 오버라이딩 하도록 하겠습니다.

감사합니다 :)

2022-11-06 11:05 UTC, earth-h commented on src/main/java/qna/domain/Answers.java
> +        return new DeleteHistories(deleteHistories);
오..! collectingAndThen()은 한 번도 안 써봤는데 감사합니다! 👍🏻 

answers를 stream()으로 만든 뒤, map()을 통해 delete()를 연산하고 그 결과를 다시 한 변 변환할 수 있게 하는 역할을 하는 거 같네요..!
그 후에 DeleteHistories를 생성할 수 있군요!!

감사합니다 ㅎㅎ 덕분에 새로운거 알게되었습니다 :)

2022-11-06 12:22 UTC, mskangg commented on src/main/java/qna/domain/Answers.java
> +    }
`@Transactional`은 도메인의 영역이 아닙니다.
이 부분은 QnaService에서 테스트하시면 될 것 같아요!

2022-11-06 12:26 UTC, earth-h commented on src/main/java/qna/domain/Answers.java
> +    }
넵, 테스트는 QnaServiceTest에서 진행했습니다..! 

질문자와_답변자_달라_예외_발생하면_질문_삭제여부는_거짓()
요 테스트를 통해서 진행해보고자 한 것인데, assertThatThrownBy()를 통해 에러 발생하는 것은 확인하였는데,
그 이후 롤백여부가 assertThat()을 통해서 isFalse()에서 느껴지길 바랐는데 그게 느껴지지 않아서요..!

2022-11-06 12:42 UTC, mskangg commented on src/main/java/qna/domain/Answers.java
> +    }
> [ QnaServiceTest.java ]

여기서 테스트했다고 작성하셨군요. 못봤네요 😅
그럼에도 발생안하는 이유는 @Transactional 자체가 spring aop로 동작하는데, 현재 모킹하여 테스트하기 때문에 동작하지 않는게 당연합니다.
해당 부분이 테스트가 필요하다면 @SpringBootTest 로 빈을 구동하면 동작할 것입니다.

2022-11-06 13:24 UTC, earth-h commented
안녕하세요, 민수님!

주신 피드백 바탕으로 수정하여서 재 피드백 요청드립니다~!

> 그리고 요구사항 중 하나인 모든 원시 값과 문자열을 포장한다 를 만족하지 못하는것 같습니다!
contents, name, email 등... 많이 포장할 수 있을 것 같네요 🤔

✏︎ 원시값과 문자열인데 원시값만이라고 보고 넘어가버렸네요 ㅠㅠ 이 부분 추가하였습니다 !

> 삭제 히스토리를 각각 DeleteHistory.ofAnswer(id, writer) 와 ofQuestion 으로 네이밍해서 만든다면 더욱 좋을 것 같아요 😃

✏︎ 각각 질문용/답변용으로 생성하여서 넘겨야할 파라미터도 줄고, 명확한 이름을 통해 DeleteHistory를 만들 수 있었습니다.

> stream을 활용해보시는건 어떠신가요??

✏︎ 덕분에 collectingAndThen()을 알게되었습니다 ! 감사합니다 👍🏻 

> 이 부분은 서비스레이어에서 @Transactional 로 관리되어 있기 때문에 all pass / all fail 을 보장합니다.
그렇기 때문에 위 상황의 경우 답변1의 삭제여부가 다시 false 로 롤백되어집니다.

✏︎ mock 하는 부분을 단순하게 특정 행위 결과를 강제해주는 느낌으로 인지하고 있었는데, 모킹으로 인해 @Transactional이 동작하지 않는 다는 점은 처음 알게 되었습니다..! Spring AOP와 mock을 얘기해주셔서, 두 키워드로 검색을 해봤는데 아직 정확한 정보는 찾지 못했네용.. ㅎㅎ.. 이 부분은 좀 더 공부해보겠습니다 :) 

> equals를 오버라이딩하신 이유가 있으신가요??
컬렉션이기 때문에 element 의 순서가 바뀐다면 다른 컬렉션으로 인식합니다.

✏︎ DeleteHistories에 equals()를 오버라이딩한 이유는, DeleteHistories의 saveAll() 메소드의 인자로 List<DeleteHistory>가 아닌 랩핑된 일급컬렉션 객체를 넘기기 위함이었습니다 ! 순서가 바뀔 수 있는 부분에 대해서는, equals()에서 비교할 때의 로직을 변경해두었습니다 ! 피드백 감사합니다 👍🏻 

추가적으로, 문자열 포장 및 말씀해주신 테스트코드 추가 필요한 부분에 대해서는 추가하였습니다 !

감사합니다 :)

2022-11-06 13:24 UTC, earth-h commented on src/main/java/qna/domain/Answers.java
> +    }
오.. 넵넵! 확인해서 테스트해봤습니다 ㅠㅠ 모킹하면 @Transactional이 동작하지 않는 다는 사실을 인지하지 못했네요!! 
감사합니다 !!!

2022-11-07 01:32 UTC, mskangg approved these changes
모든 요구사항을 만족시킨 100점 짜리 코드군요~! 💯 
깐깐한 리뷰 받아주셔서 감사합니다 🙇‍♂️
우테캠은 `일이 아닌 학습이기에` 자칫 오버엔지니어링이 될 수도 있는 경험을 해보는 것도 이 과정에서 느낄 수 있을거라 `모든 원시 값과 문자열을 포장한다`가 요구사항에 포함되어 있다고 생각합니다.
앞으로 미션 진행함에 있어서 `일이 아닌 학습으로` 생각하고 임해주신다면, 많은 것을 얻을 수 있으실거에요!

그럼 이만 머지해드리고 다음 미션 화이팅입니다! 🚀

2022-11-07 01:32 UTC, merged