Step3 리뷰 요청드립니다
next-step/jwp-qna pull request #635
Opened 2022-11-06 10:18 UTC by happy-dev-travel

대박이네요! Step2 진행하면서 나름대로 deleteQuestion함수를 리팩토링 한다고 했었는데 아주 우스운 수준이었습니다ㅎㅎ
박재성님 강의 듣고 큰 깨달음을 얻었네요ㅎㅎ Thin Service Layer를 유지하고 domain에 로직을 작성하는건 얼른 현업에서도 적용해 보고 싶은 프랙티스였습니다 :)

그리고 리뷰 주셨던 Cascade.Persist는 제가 무의식적으로 테스트 환경을 편리하게 셋팅하려고 붙인 것이더라고요. 다시 보니 ManyToOne에서 cascadeType.Persist는 객체간의 비즈니스 관계와 맞지가 않더라고요.. 리뷰 감사합니다 :)

그리고 궁금한 점은..
domain에 비즈니스 로직을 추가한다는 의미는, 예를 들면

2022-11-06 13:50 UTC, limwoobin requested changes
안녕하세요 동길님
3단계 미션도 잘 수행해주셨습니다!
획기적인 리팩토링도 보이고 많이 고민하신 흔적들이 보이네요 ㅎㅎ

몇가지 코멘트를 남겨드렸으니 확인하시고 다시 요청부탁드립니다!

2022-11-06 13:50 UTC, limwoobin commented on src/main/java/qna/domain/Question.java
> +        //answer.toQuestion(this);
의미없는 주석이라면 지워주심이 좋겠네요 ㅎㅎ

2022-11-06 13:50 UTC, limwoobin commented on src/main/java/qna/domain/Question.java
> +    }
이 메소드는 해당 클래스내부, 테스트코드에서만 사용되는걸로 보이네요
private으로 접근제어자를 변경해보시는건 어떨까요?

2022-11-06 13:50 UTC, limwoobin commented on src/main/java/qna/domain/Question.java
> +    private List<Answer> answers = new ArrayList<>();
`@Embedded` 를 이용해 List<Answer> 를 일급컬렉션으로 래핑해보시는건 어떨까요??
그렇다면 answers의 기능을 일급컬렉션 내에서 처리해서 보다 객체지향적인 설계를 해볼 수 있을것같습니다!

2022-11-06 13:50 UTC, limwoobin commented on src/main/java/qna/domain/DeleteCheckRule.java
> +public interface DeleteCheckRule {
interface를 이용해 질문삭제의 validation에 대해 추상화해주셨군요 
좋은방법이네요 ㅎㅎ
삭제에 대해 validate 동작을 수행하는데 `QuestionDeleteValidator` 와 같은 이름은 어떨까요?

2022-11-06 13:50 UTC, limwoobin commented on src/main/java/qna/domain/DeleteCheckRule.java
> +        return !(Objects.isNull(loginUser) || loginUser.isGuestUser() || Objects.isNull(answers));
`loginUser.isGuestUser()` 는 어떤 역할을 하는걸까요??

2022-11-06 13:50 UTC, limwoobin commented on src/main/java/qna/domain/Question.java
> +        this.markDeleted(true);
`markDeleted` 도 접근제어자의 변경에 대해 확인부탁드려요! ㅎㅎ

2022-11-06 13:50 UTC, limwoobin commented on src/main/java/qna/service/QnaService.java
> +        deleteHistoryService.saveAll(deleteHistories);
서비스레이어의 코드 라인이 획기적으로 줄어들었군요
추가로 해당 service에서는 더 이상 answerRepository는 사용되지 않는걸로 보이네요! ㅎㅎ
미사용 import 도 한번 체크해주세요~

2022-11-06 13:50 UTC, limwoobin commented on src/main/java/qna/domain/Question.java
> +    }
질문이 이미 삭제가 된 상태라면 어떻게동작할까요??

2022-11-06 13:56 UTC, limwoobin commented
질문에 대한 답변은 여기서 드리겠습니다.

해당 도메인이 하는 역할에 대해서는 도메인 내에서 로직을 수행하는게 맞습니다!
작성하신것처럼 만약 Question에 대한 비즈니스 로직을 수행한다면 Question 내에서 수행하는게 미션의 요구사항이 맞다고 보셔도 됩니다.
다만 로직이 과해져서 해당도메인의 핵심로직을 오염시킨다거나 하면 QuestionValidator와 같이 도메인을 분리해
Question으로 의존성을 주입하는 방법도 고려할 수 있습니다.
즉, 해당 도메인의 역할이어도 경우에 따라 클래스 분리를 통해 객체의 역할분리를 해보시는것도 좋은방법입니다!

답변이 되었을진 모르겠지만 혹시라도 추가로 의견나누고싶으시다면 dm주셔도 좋습니다 ㅎㅎ

2022-11-06 15:22 UTC, happy-dev-travel commented on src/main/java/qna/domain/DeleteCheckRule.java
> +public interface DeleteCheckRule {
말씀하신 naming이 관련 도메인, 역할이 더 잘 드러나네요ㅎㅎ 의견 감사합니다 :)

2022-11-06 15:22 UTC, happy-dev-travel commented on src/main/java/qna/domain/DeleteCheckRule.java
> +        return !(Objects.isNull(loginUser) || loginUser.isGuestUser() || Objects.isNull(answers));
초기 미션 코드에 저 메소드가 포함되어 있었습니다 :)

2022-11-06 15:22 UTC, happy-dev-travel commented on src/main/java/qna/domain/Question.java
> +    private List<Answer> answers = new ArrayList<>();
헛.. 넘 좋은데요?!

2022-11-06 15:22 UTC, happy-dev-travel commented on src/main/java/qna/domain/Question.java
> +        //answer.toQuestion(this);
네 알겠습니다!

2022-11-06 15:22 UTC, happy-dev-travel commented on src/main/java/qna/domain/Question.java
> +    }
질문을 잘 이해를 못했습니다 지금 delete함수는 Question 객체에 있는 것이니.. 질문이 이미 삭제되어 있다면 이 함수를 아예 실행하지 못 할 것이라서요

2022-11-06 15:22 UTC, happy-dev-travel commented on src/main/java/qna/domain/Question.java
> +        this.markDeleted(true);
네 알겠습니다!

2022-11-06 15:22 UTC, happy-dev-travel commented on src/main/java/qna/domain/Question.java
> +    }
네 알겠습니다!!

2022-11-07 15:21 UTC, happy-dev-travel commented on src/main/java/qna/domain/Question.java
> +    }
코드를 보니 질문이 삭제된 상태라면 NotFound Exception이 발생합니다 :)

2022-11-07 15:22 UTC, happy-dev-travel commented on src/main/java/qna/service/QnaService.java
> +        deleteHistoryService.saveAll(deleteHistories);
삭제하였습니다 :)

2022-11-07 16:14 UTC, limwoobin commented on src/main/java/qna/domain/Question.java
> +    private void checkOwnerOrThrow(User loginUser) throws CannotDeleteException {
validateOwner... 와 같은 이름은어떨까요??
일반적으로 예외처리에 대해서는 validate... 와 같은 네이밍을 많이 사용하기도 합니다!

2022-11-07 16:14 UTC, limwoobin commented on src/main/java/qna/domain/QuestionAnswers.java
> +    private List<Answer> answers = new ArrayList<>();
보다 깔끔해진것같네요!
이미 알고계신내용일수도 있지만 `@OneToMany`의 default fetch type은 LAZY여서 생략하셔도 무방합니다.
다만 지연로딩전략을 명확히 나타낸다는 장점도 있기에 있어도 좋다는 생각이 드네요 ㅎㅎ

2022-11-07 16:14 UTC, limwoobin commented on src/main/java/qna/domain/Question.java
> +    }
다른부분에 남기려던코멘트였는데 위치가 잘못되었네요 
혼선을 드려 죄송합니다.
해당 코멘트는 무시해주세요!

2022-11-07 16:35 UTC, limwoobin requested changes
동길님 3단계 피드백반영 정말 잘해주셨습니다
꼼꼼한 테스트도 인상적이고 `@Embedded`로 객체분리도 성공적으로 잘 해내주셨네요! 👍 

다만 마지막으로 고민해보면 정말 좋은 부분이 있어 request changes 드렸습니다.
코멘트 내용보시고 이해가안되거나 의견나누고싶으면 편히 dm주세요! 
조금만 더 화이팅입니다!

2022-11-07 16:35 UTC, limwoobin commented on src/main/java/qna/domain/QuestionAnswers.java
> +    }
`answer.delete`에서 CannotDeleteException을 던지고있는데
여기서 RuntimeException으로 다시 캐치하신 이유가 있을까요??

2022-11-07 16:35 UTC, limwoobin commented on src/main/java/qna/domain/QuestionAnswers.java
> +    }
해당 answers의 값은`OneToMany` 의 지연로딩전략으로 불려와지고 있습니다
Question은 `QuestionRepository`에 선언한 `findByIdAndDeletedFalse` 로 삭제되지 않은 질문에 대해서만 값을 가져오게되네요
그렇다면 answers는 연관관계가 맺어진 모든 답변을 가져오게 될것같습니다.
이때 모든 답변에 대해 삭제히스토리를 담는다면 이미 삭제된 답변도 중복으로 삭제히스토리로 들어가지 않을까요??
성능도 고려해서 한번 풀어보도록 고민해보시면 좋을것같아요!

2022-11-07 16:35 UTC, limwoobin commented on src/test/java/qna/domain/QuestionAnswersTest.java
> +class QuestionAnswersTest {
추가되는 도메인에 대한 단위테스트도 정말 꼼꼼하게 작성해주셨네요 👍👍👍

2022-11-07 16:35 UTC, limwoobin commented on src/test/java/qna/domain/QuestionTest.java
> +    }
여긴 `DisplayName`이 빠져있네요 ㅎㅎ

2022-11-07 22:43 UTC, happy-dev-travel commented on src/main/java/qna/domain/QuestionAnswers.java
> +    }
아.. 맞습니다 history가 중복으로 남겠네요ㅠㅠ 라뷰 갑사합니다!!

2022-11-08 15:04 UTC, limwoobin approved these changes
동길님 피드백 드린 내용 잘 반영해주셨습니다!
그동안 고생많으셨습니다 ㅎㅎ
도움이 될만한 코멘트를 하나 남겨드렸으니 확인부탁드립니다.

저와의 미션은 여기까지이지만 이후 미션을 진행하며 궁금한점이나
논의하고 싶은점이 있으면 언제든 편하게 dm주셔도 좋습니다.
다음미션도 화이팅입니다! 👍

2022-11-08 15:04 UTC, limwoobin commented on src/main/java/qna/domain/QuestionAnswers.java
> +    }
stream으로 삭제되지 않은 답변만 걸러내셨군요 ㅎㅎ 
추가로 jpa의 service에서 fetch join을 이용해서 삭제되지 않은 질문을 한번에 가져오게되면
보다 성능적 이점을 챙겨가실수도 있습니다!

2022-11-08 15:04 UTC, limwoobin commented on src/test/java/qna/domain/QuestionTest.java
> +    }
피드백드린 내용에 대해 테스트코드도 잘 작성해주셨네요! ㅎㅎ

2022-11-08 15:04 UTC, merged