Step2
next-step/jwp-qna pull request #636
Opened 2022-11-06 10:22 UTC by diqksrk

개발을 하면서, Mybatis에 비교 jpa는 확실히 객체지향적이다 라는 느낌을 많이 받았습니다 ㅎㅎ
이번에도 잘 부탁드립니다.

2022-11-06 12:42 UTC, ohtaeg requested changes
2단계 미션도 구현을 잘해주셨어요 👍 
같이 고민해보면 좋을 포인트가 존재하여 Request changes 하였습니다!
몇 개의 코멘트를 드렸는데 확인 부탁드립니다 🙏 
남은 주말 잘 보내시길 바라겠습니다 😄

2022-11-06 12:42 UTC, ohtaeg commented on src/main/java/qna/domain/entity/Answer.java
> +    private Question question;
서비스의 흐름으로 봤을때일반적으로 `질문(Question)`이 먼저 생성되고 `답변(Answer)`이 생성되는 순서가 될 것 같아요.
이부분에서 `Answer`가 Cascade를 통해 `Question`의 라이프 사이클을 관리하는 부분은 제거하는게 좋을 것 같은데
민준님 생각은 어떠신가요? 😄

2022-11-06 12:42 UTC, ohtaeg commented on src/main/java/qna/domain/entity/Answer.java
> +    @ManyToOne(cascade = CascadeType.PERSIST)
`@ManyToOne`의 기본 fetch 전략은 즉시 로딩인데요!
즉시 로딩으로 해주신 의도가 있을까요 😄 ?
즉시 로딩으로 하게 되면 어떤 문제점이 있을까요 :) ?

2022-11-06 12:42 UTC, ohtaeg commented on src/main/java/qna/domain/entity/Answer.java
> +                ", question=" + question+
현재는 즉시 로딩이지만 만약 FetchType.LAZY 로 설정된 대상 객체를
toString 에서 출력할 때 유의해야 할 점은 어떤 게 있을까요 :) ?

2022-11-06 14:04 UTC, diqksrk commented on src/main/java/qna/domain/entity/Answer.java
> +    private Question question;
음... Answer이 Question까지 생성할수 있으니. 영문을 알수 없는 Question이 생길수도 있고.
사이드 이펙트가 발생할수가 있겠네요. 삭제하겠습니다 !

2022-11-06 14:09 UTC, diqksrk commented on src/main/java/qna/domain/entity/Answer.java
> +    @ManyToOne(cascade = CascadeType.PERSIST)
기본전략이니 건들지 않고 사용한 감이 있었습니다.
고려해볼때, findAll()이나 리스트로 해당 엔티티를 가져온다면 리스트만큼 Question을 돌겠네요.
예상치 못한 서버에 부하를 줄수 있을것 같다는 생각을 했습니다. 수정하겠습니다 !

2022-11-06 14:15 UTC, diqksrk commented on src/main/java/qna/domain/entity/Answer.java
> +    @ManyToOne(cascade = CascadeType.PERSIST)
음.. 또 생각해보니 join 쿼리로 가져와도 사용하지 않을 불필요한 데이터를 가져올 우려가 있겠네요.

2022-11-06 14:19 UTC, diqksrk commented on src/main/java/qna/domain/entity/Answer.java
> +                ", question=" + question+
음.. 가져온 데이터가 없으니 일단 user를 가져오려고 할때, 에러가 발생하겠군요.
또, 만약 양방향 맵핑이여서 answer쪽도 user쪽을 호출하는 로직이 존재한다면 순환참조가 발생할수 있겠고요.

프로그래밍에 답은 없다고 생각합니다만, 지금은 객체지향이니 user쪽의 정보를 확인하는 작업인 toString은 user쪽에 주는것이 맞다고 생각합니다.

2022-11-07 05:46 UTC, ohtaeg approved these changes
리뷰가 늦어서 죄송합니다 🙏 
전체적으로 피드백 반영을 잘해주셨습니다 👍 
마지막 남은 미션도 화이팅입니다 :) 🔥

2022-11-07 05:46 UTC, ohtaeg commented on src/main/java/qna/domain/entity/Answer.java
> +    @ManyToOne(fetch = FetchType.LAZY)
피드백 반영 👍

2022-11-07 05:46 UTC, ohtaeg commented on src/test/java/qna/domain/repository/QuestionRepositoryTest.java
> +    @DisplayName("toString 테스트")
toString() 테스트까지..! 👍

2022-11-07 05:46 UTC, merged