Step1 - 리뷰요청 드립니다.
next-step/jwp-qna pull request #661
Opened 2022-11-07 18:23 UTC by aksgudwns

안녕하세요
Step1 엔티티매핑 리뷰요청 드립니다.
잘 부탁드리겠습니다!

2022-11-08 08:19 UTC, joojimin requested changes
안녕하세요~! 형준님
미션진행 고생하셨습니다!
간단히 확인해보고 넘어가면 좋을 코멘트 드렸는데요!
확인해보시고 리뷰 재요청 부탁드려요!!

2022-11-08 08:19 UTC, joojimin commented on README.md
> +- [ ] UserTest 구현 (저장 후 찾기 테스트, 저장 후 수정 테스트)
요구사항 정리 👍

2022-11-08 08:19 UTC, joojimin commented on src/main/java/qna/Application.java
> +@EnableJpaAuditing
Auditing 활용! 💯

2022-11-08 08:19 UTC, joojimin commented on src/main/java/qna/domain/Answer.java
> +@EntityListeners(AuditingEntityListener.class)
모든 Entity 클래스에 `@EntityListeners(AuditingEntityListener.class)`을 다는건 중복된 코드가 많이 나올 것 같아요!
공통적으로 정의되는 속성들을 따로 추출해보면 어떨까요~?

2022-11-08 16:16 UTC, aksgudwns commented
말씀주신 내용 반영해 보았습니다!
BaseTimeEntity를 상속받아 구현하니, 중복코드가 제거되어 깔끔한 느낌이 듭니다
리뷰부탁드리며 잘못된 부분이 있다면 말씀주세요!

감사합니다.

2022-11-08 16:17 UTC, aksgudwns commented on src/main/java/qna/domain/Answer.java
> +@EntityListeners(AuditingEntityListener.class)
시간속성관련하여 중복된 코드가 많네요..
부모클래스를 하나 작성하여 중복코드 제거해보겠습니다..!

2022-11-09 01:58 UTC, joojimin approved these changes
엔티티의 공통속성을 따로 추출해서 정의하니 중복코드도 없어지고 훨씬좋아진 것 같아요!
미션진행 고생하셨습니다~!!

2022-11-09 01:58 UTC, joojimin commented on src/main/java/qna/domain/BaseTimeEntity.java
> +@EntityListeners(AuditingEntityListener.class)
공통속성 정의 👍

2022-11-09 01:58 UTC, merged