Step3 질문삭제 리팩터링 PR요청드립니다
next-step/jwp-qna pull request #666
Opened 2022-11-08 02:54 UTC by chunhodong

2022-11-08 15:55 UTC, geunhwanlee requested changes
3단계 미션 잘해주셨어요! 👍🏻

몇가지 아쉬운 부분이 있어서 코멘트 드렸습니다.

확인해보시고 재 리뷰요청 주세요! 🙏

JPA미션도 거의 끝나가네요.
마지막까지 화이팅입니다! 🔥

2022-11-08 15:55 UTC, geunhwanlee commented on src/main/java/qna/domain/Answer.java
> +    }
`삭제하는 기능`과 `DeleteHistory를 만드는 기능`을 분리하신 이유가 있을까요?
두 기능은 서로 독립적으로 동작해야할까요? 🤔

2022-11-08 15:55 UTC, geunhwanlee commented on src/main/java/qna/domain/Answers.java
> +public class Answers {
일급컬렉션 👍🏻

2022-11-08 15:55 UTC, geunhwanlee commented on src/main/java/qna/domain/Answers.java
> +    }
기본 생성자에서 `answers`를 초기화하게되면
다른 생성자에서 `this();`로 기본생성자를 호출할때 의도치 않은 초기화가 발생할수 있을것 같아요!🤔

이 케이스에서는 `answers`의 디폴트값을 정의하는것이 아니라 NPE를 방지하려는 목적이 크기때문에 필드에서 초기화를 해줘도 무관할것같아요! 😀

2022-11-08 15:55 UTC, geunhwanlee commented on src/main/java/qna/domain/Answers.java
> +        boolean isAllSameWriter = answers.stream().allMatch(answer -> answer.isOwner(writer));
객체지향 생활 체조 원칙에 따르면 한줄에는 점을 하나씩 찍는것을 원칙으로 하고있어요!

[객체지향 생활 체조 원칙](https://blogshine.tistory.com/241)

2022-11-08 15:55 UTC, geunhwanlee commented on src/main/java/qna/domain/Question.java
> +    private Answers answers;
👍🏻

2022-11-08 15:55 UTC, geunhwanlee commented on src/main/java/qna/domain/Question.java
> +        this.answers = new Answers();
생성자에서 초기화하기보단 필드에서 초기화하는게 나을것같아요!

2022-11-08 15:55 UTC, geunhwanlee commented on src/main/java/qna/domain/Question.java
> +    public void delete(User writer) throws CannotDeleteException {
`CannotDeleteException`을 throws한다는것은

> 1. `CannotDeleteException`은 반드시 처리해야하는 예외이다.
> 2. 예외처리를 하지않고 상위 호출자에게 넘겼다

라는 의미로 볼수 있을것 같아요.
`CannotDeleteException`은 `Exception`을 상속하고있기 때문이에요.

예외처리를 하지않고 프로그램을 종료시키거나 선택적으로 예외처리를 할거라면
`RuntimeException`을 사용하는건 어떨까요? 🤔

[RuntimeException란 무엇인가?](https://nhj12311.tistory.com/204)

2022-11-08 15:55 UTC, geunhwanlee commented on src/main/java/qna/domain/Question.java
> +        return deleteHistories;
delete 메서드와 getDeleteHistories 메서드를 분리한 이유가 무엇일까요? 🤔

2022-11-08 15:55 UTC, geunhwanlee commented on src/main/java/qna/service/QnaService.java
> +        question.delete(loginUser);
👍🏻

2022-11-09 01:33 UTC, chunhodong commented on src/main/java/qna/domain/Answers.java
> +    }
필드초기화를 왠지모를 선입견으로 안좋게봤는데 NPE를 방지하기위한 필드초기화 배워갑니다! 감사합니다 :)

2022-11-09 02:02 UTC, chunhodong commented on src/main/java/qna/domain/Answer.java
> +    }
고민을 해봤는데 제 생각에 기능적인면만 봤을때는 독립적으로 동작해야하는게 맞다고 생각했습니다.
삭제와 히스토리 생성이라는 두가지 책임을 각각 분리해야된다고 생각했습니다

그런데 써주신 리뷰보고 생각을 해봤는데.. 만약 독립적으로 동작해야한다면 getDeleteHistory메소드에서 
`  
if (!this.deleted) {
            throw new IllegalStateException(ONLY_DELETED_STATE);
        }
`
이 부분을 추가할 필요가 없다고 생각이 듭니다ㅎㅎㅎ 지금 제 코드는 코드상으로는 삭제와 히스토리 생성을 분리해놨지만 로직상으로보면 히스토리 생성이 삭제여부상태에 의존하게 되는 상황인거같습니다

그래서 그럴바에는 아예 삭제와 히스토리 생성이 같은 메소드에 존재하는게 맞는거같습니다.
제가 생각한 방향이 맞는걸까요...?

2022-11-09 02:03 UTC, chunhodong commented on src/main/java/qna/domain/Question.java
> +    public void delete(User writer) throws CannotDeleteException {
Runtime으로 수정해봤는데, 반복적인 예외처리 코드가 줄어들었습니다 감사합니다 :)

2022-11-10 02:40 UTC, geunhwanlee approved these changes
리뷰사항 반영 잘해주셨어요! 👍🏻

충분히 잘해주셔서 머지하도록 할게요.

JPA 미션이 끝났네요! 👏
그럼 앞으로의 미션도 화이팅하시고 많은걸 얻어가셨으면 좋겠습니다. 🙏

2022-11-10 02:40 UTC, geunhwanlee commented on src/main/java/qna/domain/Answer.java
> +            throw new RuntimeException(NONE_AUTH_DELETE);
`CannotDeleteException`이 `RuntimeException`을 상속하도록 변경하라는 의도로 코멘트를 드렸는데
제가 조금 모호하게 말했었네요.. 😂

`RuntimeException`을 직접 던지는것보다 `RuntimeException`을 상속하고있는 구체적인 예외를 던지는게 더 명확할것같아요. 😀

2022-11-10 02:40 UTC, merged

2022-11-10 04:19 UTC, geunhwanlee commented on src/main/java/qna/domain/Answer.java
> +    }
그렇게 생각할수도 있겠네요! 😀

저는 히스토리 생성은 삭제의 결과로 만들어지는것이고
히스토리 생성을 독립적으로 할 케이스는 없을것이라 생각해서 코멘트를 드렸어요. 😊
결과적으로 동기님이 생각하신 방향이랑 같네요! 👍🏻