Step3 질문 삭제하기 리팩터링 PR 리뷰 요청 드립니다.
next-step/jwp-qna pull request #672
Opened 2022-11-08 15:13 UTC by giraffelim

안녕하세요 석홍님! 3단계 미션 리뷰 요청 드립니다.
벌써 마지막이라니 아쉽네요 😢😢😢

이번 미션을 진행하면서 고민이 되는 부분이 있어 질문을 드립니다.
1. Answers의 deleteAll은 stream을 이용하지만 삭제 되지 않은 답변을 찾고 삭제하는 역할을 하고 있습니다. 어떻게보면 두 가지 역할을 하고 있는거 같은데 삭제되지 않은 질문 목록을 찾아오는 메소드는 따로 생성하는 것이 맞을까요?
```
public List<DeleteHistory> deleteAll(final User user) {
        return this.answerList.stream()
                .filter(answer -> !answer.isDeleted())
                .map(answer -> answer.delete(user))
                .collect(Collectors.toList());
    }
```
2. DeleteHistory를 위한 일급 컬렉션을 생성할까 고민했지만, 현재 요구사항 내 별다른 비즈니스 로직이 존재하지 않기에 생성 한다 하더라도 히스토리를 추가하는 add와 엔티티 저장을 위한 getter만 구현이 될 것 같아 일급 컬렉션을 구현하지 않았습니다. 저는 아직 실무에서 JPA를 사용할 때 일급 컬렉션을 사용해 본 적이 없는데요. 실무에서 JPA에서 일급 컬렉션을 사용하신다면 어떠한 기준에 의해 사용하시는지 궁금합니다..!

미션을 진행하는 동안 꼼꼼하게 리뷰를 진행해주셔서 정말 감사합니다!! 💯 
찾아 볼만한 내용에 대해서도 코멘트에 같이 달아주셔서 한 단계 성장 할 수 있었던 것 같습니다! 정말 감사합니다 👍 👍 👍

2022-11-09 10:40 UTC, seokhongkim requested changes
태양님, 3단계 미션도 빠르게 구현해주셨네요. 👍 

먼저 질문 주신 부분에 대해 제 생각 말씀 드립니다.
> Answers의 deleteAll은 stream을 이용하지만 삭제 되지 않은 답변을 찾고 삭제하는 역할을 하고 있습니다. 어떻게보면 두 가지 역할을 하고 있는거 같은데 삭제되지 않은 질문 목록을 찾아오는 메소드는 따로 생성하는 것이 맞을까요?

해당 메서드에 코멘트로 의견을 남겼습니다. :) 확인 부탁드려요.

> DeleteHistory를 위한 일급 컬렉션을 생성할까 고민했지만, 현재 요구사항 내 별다른 비즈니스 로직이 존재하지 않기에 생성 한다 하더라도 히스토리를 추가하는 add와 엔티티 저장을 위한 getter만 구현이 될 것 같아 일급 컬렉션을 구현하지 않았습니다. 저는 아직 실무에서 JPA를 사용할 때 일급 컬렉션을 사용해 본 적이 없는데요. 실무에서 JPA에서 일급 컬렉션을 사용하신다면 어떠한 기준에 의해 사용하시는지 궁금합니다..!

일급 컬렉션의 사용 기준을 생각할 때, JPA에 대해서는 생각하지 않았습니다. JPA를 위해 일급 컬렉션을 사용하거나, JPA로 인해 일급 컬렉션 사용이 제한되는 것은 아니라고 생각합니다.
일급 컬렉션으로 관리하면서 도메인의 규칙이나 비즈니스 로직을 관리할 수 있을 때 일급 컬렉션을 사용하고, 그렇지 않다면 자바의 컬렉션을 이용했습니다.

---

이외에 코드를 보며 궁금한 점과 학습해보시면 도움이 될 것 같은 내용을 코멘트로 남겼습니다.
코멘트 확인 부탁드립니다. 🙏

2022-11-09 10:40 UTC, seokhongkim commented on src/main/java/qna/domain/Answer.java
> +            throw new CannotDeleteException("다른 사람이 쓴 답변이 있어 삭제할 수 없습니다.");
현재 요구사항은 없지만, 요구사항의 내용으로 유추했을 때 `Answer` 만 먼저 삭제할 수도 있을 것 같아요.
그렇다면 예외 메세지가 적절하지 않을 것 같네요.

위 요구사항이 없더라도, 예외 메세지가 `Question` 이 삭제되는 상황을 전제로 작성되어 있어서, 눈에 보이지는 않으나 `Answer` 가 `Question` 에 대해 알고 있는 것처럼 보이기도 합니다. :)
`Answer` 는 `Answer` 를 기준으로 예외 메세지를 정하고, 필요하면 `Question` 에서 예외 메세지를 바꿔서 전달하는 게 어떨까요?

2022-11-09 10:40 UTC, seokhongkim commented on src/main/java/qna/domain/Answers.java
> +    public List<DeleteHistory> deleteAll(final User user) {
질문 남겨주셔서 제 생각을 코멘트로 말씀드려요!

저는 `deleteAll` 에서 `.filter(!answer.isDeleted())` 로직을 가지고 있어도 괜찮다고 생각합니다.
이는 삭제를 위해 필요한 데이터를 거르는 과정이므로 두 가지 기능을 한다고 생각하지는 않아요.
만약 `삭제되지 않은 답변`만 글 목록에서 보여준다면, `삭제되지 않은 답변`만 가지고 오는 기능이 `getAnswers()` 대신 있을 것 같고, 그렇다면 그 메서드를 재사용할 수는 있다고 생각합니다. 하지만, 지금 메서드의 기능이 많아서 나눠야 할 정도는 아니라고 생각합니다.

이것과 다른 방향으로는 `answer.delete(user)`를 호출했을 때, 답변이 이미 삭제된 상태라면 아무것도 하지 않거나 예외를 발생시키는 방법도 있을 것 같아요.
또는 `answerList` 를 조회하는 시점에 `@Where` 를 사용해서 삭제되지 않은 답변만 조회할 수도 있을 것 같습니다. 이 경우 `삭제되지 않은 답변`만 보여주는 것이 기본 동작이 되어야 할 것 같네요.

2022-11-09 10:40 UTC, seokhongkim commented on src/main/java/qna/domain/Answers.java
> +    private final List<Answer> answerList = new ArrayList<>();
변수명에 컬렉션의 타입을 노출하면 추후 타입이 변경될 때 변수명도 챙겨야해서 변경 비용이 더 커지는 것 같아요.
`answers` 또는 `values` 와 같은 이름을 사용해보면 어떨까요?

2022-11-09 10:40 UTC, seokhongkim commented on src/main/java/qna/domain/Question.java
> +    public DeleteHistory delete(User user) {
`질문을 삭제할 때 답변 또한 삭제해야 하며, 답변의 삭제 또한 삭제 상태(deleted)를 변경한다.`는 요구사항이 있으므로 이 메서드는 private 으로 변경해보면 어떨까요?

2022-11-09 10:40 UTC, seokhongkim commented on src/test/java/qna/domain/AnswerRepositoryTest.java
> +    void 다른_사람이_작성한_답변은_삭제할_수_없다() {
이 테스트와 아래의 테스트는 `AnswerRepository` 를 사용하지 않아도 `Answer` 객체만을 이용해서 단위 테스트로 진행하면 더 좋을 것 같아요. 단위 테스트로 진행할 수 있는 부분과 통합 테스트(DB연결 포함)로 진행할 수 있는 테스트의 기준, 장단점도 함께 생각해보시면 학습에 더 도움이 될 것 같습니다.

2022-11-09 10:40 UTC, seokhongkim commented on src/test/java/qna/domain/AnswersTest.java
> +@DataJpaTest
이 테스트는 `@DataJpaTest` 가 필요 없을 것 같네요!

2022-11-09 10:40 UTC, seokhongkim commented on src/test/java/qna/domain/QuestionRepositoryTest.java
> +    @Test
테스트 꼼꼼하게 작성해주셨네요. 👍 
`Question` 에 대한 삭제 테스트도 단위 테스트로 작성해보시면 좋을 것 같아요.

2022-11-09 12:53 UTC, giraffelim commented on src/main/java/qna/domain/Answers.java
> +    private final List<Answer> answerList = new ArrayList<>();
@seokhongkim 
충분히 타입이 변경될 가능성이 열려있는데 타입으로 변수명을 작성하는건 올바르지 않다는걸 느낄 수 있었습니다!
말씀해주신대로, values로 이름을 변경하였습니다.
[3ea9596](https://github.com/next-step/jwp-qna/pull/672/commits/3ea95967adac6a04701b07b7868fa36b0c3b697f)

2022-11-09 13:16 UTC, giraffelim commented on src/test/java/qna/domain/AnswersTest.java
> +@DataJpaTest
@seokhongkim 
이번 JPA 과제를 진행하면서 습관적으로 해당 어노테이션을 붙인 것 같습니다. 😢 
아래 커밋에서 수정하였습니다!
[a1cca74](https://github.com/next-step/jwp-qna/pull/672/commits/a1cca74ea08bcb89ffe6641635c4f11c29f0d56d)

2022-11-09 13:31 UTC, giraffelim commented on src/test/java/qna/domain/AnswerRepositoryTest.java
> +    void 다른_사람이_작성한_답변은_삭제할_수_없다() {
@seokhongkim 
말씀해주신 것 처럼 기존 AnswerRepositoryTest에서는 통합 테스트(DB 연결)를 통해 실제로 데이터의 저장 및 변화에 대해 검증하도록 하고, AnswerTest를 통해 도메인 객체 단위 테스트(비즈니스 로직)을 테스트 하도록 분리하였습니다.
이렇게 분리함으로써 기준이 뚜렷해지고 검증하고자 하는 내용이 명확해진 것 같다는 느낌을 받을 수 있었습니다. 👍 
[9c5be0f](https://github.com/next-step/jwp-qna/pull/672/commits/9c5be0fcec3d9da135b86644023d252d640f5f6d)

2022-11-09 13:40 UTC, giraffelim commented on src/main/java/qna/domain/Answer.java
> +            throw new CannotDeleteException("다른 사람이 쓴 답변이 있어 삭제할 수 없습니다.");
@seokhongkim 
말씀해주신 것 처럼, Answer는 Answer 기준으로 예외 메시지를 응답하도록 변경하였고 Answers에 deleteAnswer 메소드를 생성해 현재 요구사항 조건인 "다른 사람이 쓴 답변이 있어 삭제할 수 없습니다."가 응답될 수 있도록 변경하였습니다!
[9ed95b3](https://github.com/next-step/jwp-qna/pull/672/commits/9ed95b359e2296a9854dc86d5a4e48e166c53649)
[852356e](https://github.com/next-step/jwp-qna/pull/672/commits/852356e24074a8aa1aadec97d82e20640c391cf9)

2022-11-09 13:49 UTC, giraffelim commented on src/test/java/qna/domain/QuestionRepositoryTest.java
> +    @Test
@seokhongkim 
넵 위에서 말씀해주신대로 통합 테스트(DB 연결)과 도메인 단위 테스트를 분리해서 작성하였습니다!
[b5ec166](https://github.com/next-step/jwp-qna/pull/672/commits/b5ec1660675e43657b655644ab75f1a32a6476e9)

2022-11-09 13:51 UTC, giraffelim commented on src/main/java/qna/domain/Question.java
> +    public DeleteHistory delete(User user) {
@seokhongkim 
현재 Question 내에서, Question 단독 삭제는 `delete(User user)`, Question과 Answers를 함께 삭제하는 기능은 `deleteWithAnswers(User user)`로 분리해둔 상태인데, 해당 delete(User user) 메서드를 private로 변경하면 테스트를 deleteWithAnswers를 통해 같이 진행이 되어야 하기에 기능에 맞게 두 개를 분리해둔 상태인데 하나로 통합하는게 좋을까요?

2022-11-10 08:59 UTC, seokhongkim commented on src/main/java/qna/domain/Question.java
> +    public DeleteHistory delete(User user) {
네, 저는 `delete` 를 private 으로 열어 놓으면 다른 개발자가 실수를 할 여지를 줄 수 있기에 위험하다고 생각합니다. :)
요구사항, 도메인에 대한 이해가 없을 때 `delete` 와 `deleteWithAnswers` 메서드를 보면 어떤 메서드를 사용할지 고민이 필요하고 실수로 `delete` 를 사용할 수도 있다고 생각합니다. 실수할 여지를 남겨 놓는 것보다 접근을 제한해서 실수를 방지하는 것이 더 좋다고 생각합니다.

테스트를 위해 접근 제어자를 변경한다면, 이는 코드의 구조 측면에서 고민이 필요할 수도 있다고 생각합니다.
지금 코드의 경우 가독성을 위해 메서드를 분리한 것으로 생각되어, 구조상의 문제는 아닌 것으로 보이며, 이 경우에는 public method(`deleteWithAnswers`) 를 통해 private method(`delete`) 의 로직도 함께 테스트하는 것이 더 좋을 것 같습니다!

2022-11-10 09:09 UTC, seokhongkim approved these changes
태양님 3단계 미션 코멘트 잘 반영해주셨습니다! 💯 
3단계 PR도 이만 머지하도록 하겠습니다.
태양님과 리뷰 코멘트 주고받으며 저도 배우고 고민할 수 있는 기회가 되었는데, 금방 미션이 지나간 것 같아 저도 아쉽네요.

남은 학습 기간에도 힘내셔서 목표하신 성장과 성취 모두 이루시길 응원하겠습니다. 💪 
JPA 미션 수고 많으셨습니다! 👍

2022-11-10 09:09 UTC, seokhongkim commented on src/main/java/qna/domain/Answer.java
> +        return new DeleteHistory(ContentType.ANSWER, id, user, LocalDateTime.now());
기능적인 부분과 구현에 대해서는 코멘트 드릴 내용이 없어서 데이터 측면에서 한 번 고민해보시면 도움이 될 것 같은 내용을 남겨봅니다. :)

현재 질문을 삭제할 때 답변도 함께 삭제하며, 삭제 이력(`DeleteHistory`)을 저장하고 있습니다.
질문, 답변의 변경 일시는 Audit 을 통해 관리되며, 삭제 이력은 `LocalDateTime.now()` 를 통해 생성되는데요. (Audit 또는 일시 생성 중 하나의 방법으로 통일하면 좋으나, 이건 논외로 하겠습니다!)
이렇게 구현하는 경우 한 트랜잭션을 통해 발생하는 데이터의 변경(질문, 답변 삭제 및 삭제이력 저장)이 모두 다른 생성/수정일시 값을 가질 수 있습니다. 데이터 동기화, 복제(e.g., 분석을 위한 데이터 웨어하우스 등)가 시간 기반으로 진행되는 경우가 있고, 데이터 규모가 커질 때 파티셔닝도 시간을 기준으로 진행하는 경우가 있는데요. 이처럼 데이터의 생성/수정이 한 트랜잭션에 이뤄지나 시간이 다른 경우 관리에 어려움이 있을 수 있습니다. 이러한 점을 고려하여 데이터의 생성/수정 일시를 어떻게 관리하는 것이 좋을지 고민해보시면 도움이 될 것 같습니다. :)

2022-11-10 09:09 UTC, merged