[yeojiin(임정연)] - 3단계 질문 삭제하기 리팩터링
next-step/jwp-qna pull request #681
Opened 2022-11-09 02:15 UTC by yeojiin

안녕하세요 휘준님~
깃충돌이 일어나는 바람에 rebase후 다시 작업해서 PR요청을 드리는 바람에 closede된 PR이 몇개 생겨버렸내요.😂

3단계 진행하면서 2단계에서 코멘트 해주신 부분들은 공부하고, 고민해봤습니다!
완벽히 이해한 것은 아니지만 영속성의 개념과 JPA는 객체로 저장된다는 개념을 이해한 거 같아요~
어떤 걸 공부해야할지 가이드 주셔서 정말 감사합니다!🙏

이번 미션에서는 원시값 래핑과 일급콜렉션 부분을 끝까지 고민했던 거 같습니다.
원시값으로 래핑하니 DB에 저장되는 값도 변수 타입에 의존하지 않고 원시값을 래핑한 객체 자체로 저장이 된다는 점이 이해하는 데 어려웠던 거 같습니다.
또한, 원시값을 어느 단위까지 나눠야하는 지에 대한 고민도 있었던 거 같아요.
이 개념에서 확장된 게 일급 콜랙션을 어디까지 처리하는게 좋을까 였습니다.
결국, DeleteHistories까지 일급콜렉션으로 만들었는데 이 부분은 일급콜렉션 처리하지 않고, DeleteHistory로 가는게 좋았을지 궁금합니다!🤔

언제나 양질의 코멘트 주셔서 감사합니다! 마지막 미션까지 잘 부탁드려요~

2022-11-09 03:07 UTC, wheejuni requested changes
수고하셨습니다. 💯 몇가지 개선 의견 드려요

2022-11-09 03:07 UTC, wheejuni commented on src/main/java/qna/domain/answer/Answers.java
> +public class Answers implements Iterable<Answer> {
`Iterable` 을 구현하는 방법을 택하신 것에는 다소 부정적인데요, 굳이? 라는 느낌이 듭니다.
일급 컬렉션 객체가 `Iterable` 의 스펙을 수행해야 하는지도 잘 모르겠고요. 그렇게 설계되면 오히려 데메테르의 법칙을 어기기 쉽다고 봐서요.

2022-11-09 03:07 UTC, wheejuni commented on src/main/java/qna/domain/answer/Answers.java
> +    }
이게 필요하다면 값을 물어보지 않고 꺼내 쓰고 있는 쪽이 있단 건데요, 거기서 리팩터링 포인트를 잡아야 할 것으로 보여요

2022-11-09 03:07 UTC, wheejuni commented on src/main/java/qna/domain/answer/Answers.java
> +        }
stream API로 개선은 가능할 듯 싶습니다.

2022-11-09 03:07 UTC, wheejuni commented on src/main/java/qna/domain/content/Contents.java
> +public class Contents {
복수형 접미사 괜찮을지요? `Content` 는 어떨까요?

2022-11-09 03:07 UTC, wheejuni commented on src/main/java/qna/domain/deleteHistory/DeleteHistory.java
> +    }
바뀌는 건 `ContentType` 파라메터밖에 없네요. 조금 과한 분리 같다는 생각도 들고요
하나의 스태틱 팩토리 메소드를 다르게 호출하는 로직이 `Question`, `Answer` 에 각각 있으면 어떨지 생각도 듭니다.

2022-11-09 03:07 UTC, wheejuni commented on src/main/java/qna/domain/user/Email.java
> +        String emailRegex = "^[0-9a-zA-Z]([-_.]?[0-9a-zA-Z])*@[0-9a-zA-Z]([-_.]?[0-9a-zA-Z])*.[a-zA-Z]{2,3}$";
로직상 자주 사용될 거라면 `Pattern.compile()` 을 스태틱 변수로 미리 해두는 것도 좋습니다.
CPU 소모가 비교적 큰 로직이라서요

2022-11-09 23:22 UTC, yeojiin commented on src/main/java/qna/domain/answer/Answers.java
> +public class Answers implements Iterable<Answer> {
콜렉션 객체를 하나하나 꺼내서 쓸 수도 있단 생각에 Iterable을 구현했던 건데 디미터 법칙에 위반될 수도 있겠네요.🤔
습관적으로 사용한 부분이 있는 거 같아 반성하게 됩니다! 피드백 해주신대로 제거하는게 더 좋은 방식 같습니다!

2022-11-09 23:23 UTC, yeojiin commented on src/main/java/qna/domain/answer/Answers.java
> +    }
물어보지 않고, 꺼내쓰고 있다는 표현이 맞는 거 같습니다! 헤당 부분 역시 불필요하다고 판단되어 삭제했습니다!

2022-11-09 23:29 UTC, yeojiin commented on src/main/java/qna/domain/answer/Answers.java
> +        }
넵! 해당 부분은 stream으로 수정했습니다~😀

2022-11-09 23:29 UTC, yeojiin commented on src/main/java/qna/domain/content/Contents.java
> +public class Contents {
원시값이니 복수형보다는 단수형이 훨씬 좋을 거 같습니다! 꼼꼼한 리뷰 감사해요!

2022-11-09 23:40 UTC, yeojiin commented on src/main/java/qna/domain/user/Email.java
> +        String emailRegex = "^[0-9a-zA-Z]([-_.]?[0-9a-zA-Z])*@[0-9a-zA-Z]([-_.]?[0-9a-zA-Z])*.[a-zA-Z]{2,3}$";
해당 부분은 Email 내부에서 변수로 선언하는게 좋을까요 아니면 Constant 클래스를 만들어 따로 뺴서 사용하는게 좋을까요? 이메일 정규식 같은 경우는 다른데서 사용될 일이 없을 거 같아 Email 클래스 내부에서 선언하는 방향으로 수정했습니다~

2022-11-10 00:30 UTC, yeojiin commented on src/main/java/qna/domain/answer/Answers.java
> +        }
한가지 궁금한 사항 있어 코멘트 남깁니다~

해당 부분을 forEach로 감싸면 `CannotDeleteException` 가 checkAnswerWriter 메소드에서 작동해 try-catch를 걸지 않으면 에러가 발생합니다.

```
public void validateDeleteAnswer(User loginUser) throws CannotDeleteException {
        answers.stream().forEach(answer -> {
            try {
                checkAnswerWriter(answer, loginUser);
            } catch (CannotDeleteException e) {
                e.printStackTrace();
            }
        });
    }
```
try-catch를 걸 경우 테스트 케이스를 돌릴 때 `CannotDeleteException`이 발생한 것을 감지하지 못해 실패로 처리됩니다.
하지만, 아래와 같이 
```
 public void validateDeleteAnswer(User loginUser) throws CannotDeleteException {

        for(Answer answer : answers) {
            checkAnswerWriter(answer,loginUser);
        }
    }
```
for문으로 처리하면 exception을 정상적으로 날려 테스트 케이스도 통과하게 됩니다. 그래서 이번 코드 수정에서는 for문은 유지했습니다.
참고로  Exception을 확인해 보니  커스텀이라 위와 같은 현상이 발생하는 거 같습니다. 
만약 `RuntimeException`을 걸 경우에는 foreach도 정상적으로 에러를 던지는 거 같습니다. 

위 상황에서 다른 해결방법이 있을까요? 아니면 그냥 for로 유지하는게 나을까요🤔

2022-11-10 00:33 UTC, yeojiin commented on src/main/java/qna/domain/deleteHistory/DeleteHistory.java
> +    }
이 부분은 `Question`과 `Answer`에 `DeleteHistory` 생성자를 통해 리턴받을 수 있는 메소드를 추가하는 방식으로 변경했습니다~
제가 피드백을 제대로 이해하고 수행한 건지 고민이 되네요.
혹시 다른 피드백이 있다면 편하게 코멘트 달아주새요! 감사합니다~🙏

2022-11-11 01:05 UTC, wheejuni commented on src/main/java/qna/domain/answer/Answers.java
> +        }
`CannotDeleteException` 을 `RuntimeException` 으로 개선하는 것이 좋아 보이기는 합니다.
이것은 다음 단계에서 고민해주세요!

2022-11-11 01:05 UTC, wheejuni commented on src/main/java/qna/domain/answer/Answers.java
> +        }
아 다음 단계가 없죠;; 죄송합니다. `RuntimeException` 을 적극적으로 활용하는 방식을 항상 고민해 주시면 됩니다.

2022-11-11 01:05 UTC, wheejuni commented on src/main/java/qna/domain/user/Email.java
> +        String emailRegex = "^[0-9a-zA-Z]([-_.]?[0-9a-zA-Z])*@[0-9a-zA-Z]([-_.]?[0-9a-zA-Z])*.[a-zA-Z]{2,3}$";
`Email` 내부에서의 선언이 좋습니다!

2022-11-11 01:06 UTC, wheejuni approved these changes
수고하셨습니다 💯

2022-11-11 01:06 UTC, wheejuni commented on src/main/java/qna/domain/user/Email.java
> +    private final static Pattern emailRegex = Pattern.compile("^[0-9a-zA-Z]([-_.]?[0-9a-zA-Z])*@[0-9a-zA-Z]([-_.]?[0-9a-zA-Z])*.[a-zA-Z]{2,3}$");
👍

2022-11-11 01:06 UTC, merged

2022-11-12 06:44 UTC, yeojiin commented on src/main/java/qna/domain/answer/Answers.java
> +        }
넵! `RuntimeException` 으로 활용하는 방식으로 고민해보겠습니다! 
jpa미션 리뷰해주셔서 감사합니다~