[Step3] 질문삭제하기 리팩터링
next-step/jwp-qna pull request #689
Opened 2022-11-09 14:51 UTC by sawooook

2022-11-10 13:40 UTC, wooobo requested changes
3단계 잘진행해주셨네요 :+1: 

코멘트 남겨 드렸는데 확인 후 재요청 부탁드려요~^^
화이팅입니다!

2022-11-10 13:40 UTC, wooobo commented on src/main/java/qna/domain/Answer.java
>          this.writer = writer;
`toQuestion` 처럼 더 이상 사용하지 않는 메서드는 제거 해주세요~

2022-11-10 13:40 UTC, wooobo commented on src/main/java/qna/domain/Answer.java
>      public int hashCode() {
`setDeleted`보다는 

```
public void deleted() {
    this.deleted = true;
}

public void release() {
    this.deleted = false;
}
```

이런식으로 객체에게 메시지를 좀 더 명확하게 주는 부분에 대해서 고민해볼 수 있겠네요 :thinking:

2022-11-10 13:40 UTC, wooobo commented on src/main/java/qna/domain/DeleteHistory.java
> +    public static DeleteHistory of(ContentType type, Question question) {
```
public static DeleteHistory ofAnswer(Long contentId, User deletedBy) {
    return new DeleteHistory(ContentType.ANSWER, contentId, deletedBy);
}
```
```
  public DeleteHistory deleteIfDifferentUserAnswerEmpty(User loginUser) {
        ...
        return DeleteHistory.ofAnswer(id, writer);
    }
```

`getter`를 지양하기 위해서 데이터를 가진 객체에게 시켜보는 패턴을 고민해보면 좋을것같아요 :thinking:

2022-11-10 13:40 UTC, wooobo commented on src/main/java/qna/domain/Question.java
> +    public List<DeleteHistory> delete(User loginUser) {
```
class A {
    상수(static final) 또는 클래스 변수
    인스턴스 변수
    생성자
    팩토리 메소드
    메소드
    기본 메소드 (equals, hashCode, toString)
}
```

고민해봐주세요~

2022-11-10 13:40 UTC, wooobo commented on src/main/java/qna/exception/CannotDeleteException.java
> +public class CannotDeleteException extends RuntimeException {
`RuntimeException` 으로 변경하신 이유가 있으실까요?

2022-11-12 06:57 UTC, sawooook commented on src/main/java/qna/exception/CannotDeleteException.java
> +public class CannotDeleteException extends RuntimeException {
Exception은 컴파일 과정에서 예외가 발생하는지 확인하는것으로 알고 있습니다...!!

근데 CannotDeleteException 이라는 예외는 제가 주로 데이터를 조회해와서 삭제가 가능한지 체크를 하고 삭제가 불가능하면 예외를 터트리는 로직에 주로 사용하기 때문에 exception 보다는 실행중에 발생하는runTimeException이 더 적합하다고 생각하여 바꿨습니다..!!

2022-11-12 06:59 UTC, sawooook commented on src/main/java/qna/domain/Question.java
> +    public List<DeleteHistory> delete(User loginUser) {
말씀해주신것처럼 순서 컨벤션에 맞춰서 하면 코드 보기가 더 보기좋을것같습니다!! 감사합니다 🙇

2022-11-12 07:00 UTC, sawooook commented on src/main/java/qna/domain/DeleteHistory.java
> +    public static DeleteHistory of(ContentType type, Question question) {
감사합니다..! 말씀해주신것처럼 바꾸니 코드도 깔끔해지고 훨씬 좋은것 같습니다 🙇

2022-11-12 07:00 UTC, sawooook commented on src/main/java/qna/domain/Answer.java
>          this.writer = writer;
헛... 제거를 안했네요 ..ㅜㅜ 제거 했습니다~!

2022-11-12 11:58 UTC, wooobo approved these changes
사욱님 JPA 미션 진행하느라 수고많으셨습니다 ^^

몇가지 코멘트 남겨드렸는데 확인 부탁드려요! :pray: 

미션 마무리 하도록 하겠습니다!
남은 미션도 응원하겠습니다 화이팅입니다~

2022-11-12 11:58 UTC, wooobo commented on src/main/java/qna/domain/Answer.java
> +                ", question=" + question +
[양방향 맵핑시 주의할점](https://logical-code.tistory.com/136#%EC%--%--%EB%B-%A-%ED%--%A-%--%EB%A-%A-%ED%--%--%--%EC%-B%-C%--%EC%A-%BC%EC%-D%--%ED%--%A-%--%EC%A-%--)

참고해주세요~

2022-11-12 11:58 UTC, wooobo commented on src/main/java/qna/domain/Question.java
> +    }
```suggestion
    private List<DeleteHistory> deleteAnswers(User loginUser) {
        List<DeleteHistory> deleteHistorie = answers.delete(loginUser);
        DeleteHistory questionDeleteHistory = this.toDeleteHistory();
        return makeCombineHistories(deleteHistorie,questionDeleteHistory);
    }
```

이렇게 해볼수도 있겠네요~

2022-11-12 11:58 UTC, wooobo commented on src/main/java/qna/exception/CannotDeleteException.java
```
    public CannotDeleteException(QuestionExceptionType message) {
        ...
    }
```

커스텀 exception을 만든만큼, 다양한 생성자를 만들어 볼 수 있겠네요!

[Implementing Custom Exceptions in Java](https://dzone.com/articles/implementing-custom-exceptions-in-java?fromrel=true)

2022-11-12 11:58 UTC, merged

2022-11-16 12:39 UTC, sawooook commented on src/main/java/qna/domain/Question.java
> +    }
와 이렇게도 할 수 있군요! 이렇게 하면 getter를 안쓰고 할 수도 있고 정말 좋은것 같습니다 ...! 

감사합니다 🙇

2022-11-16 12:42 UTC, sawooook commented on src/main/java/qna/domain/Answer.java
> +                ", question=" + question +
좋은글 링크 주셔서 감사합니다!  🙇 참고하겠습니다~!

2022-11-16 12:42 UTC, sawooook commented on src/main/java/qna/exception/CannotDeleteException.java
좋은글 감사합니다 🙇