Step1 리뷰 요청
next-step/jwp-qna pull request #7
Opened 2021-05-25 13:28 UTC by DoLiLu

안녕하세요 

Step1 엔티티 매핑 구현

리뷰 요청합니다.

엔티티 매핑 자체가 미션인거 같아 매핑 및 저장 기능 테스트 진행 하였습니다.

앞으로 JPA 미션 리뷰 잘 부탁드립니다!

2021-05-25 14:13 UTC, ssosso requested changes
정수님, 안녕하세요~ 리뷰어 쏘쏘(소현)입니다. (어느 것이든 편하게 불러주세요)
피드백 남기오니 확인 부탁드립니다~
잘 부탁드립니다:)

2021-05-25 14:13 UTC, ssosso commented on src/main/java/qna/domain/Answer.java
> +        return deleted == answer.deleted && Objects.equals(id, answer.id) && Objects.equals(contents, answer.contents) && Objects.equals(writerId, answer.writerId) && Objects.equals(questionId, answe
created_at, updated_at은 포함되지 않아도 될까요~?

2021-05-25 14:13 UTC, ssosso commented on src/test/java/qna/domain/AnswerTest.java
> +                () -> assertThat(saveAnswer.isDeleted()).isFalse()
db에 저장이 되었는가의 여부는 확인하지 않아도 될까요~?

2021-05-25 14:13 UTC, ssosso commented on src/main/java/qna/domain/DeleteHistory.java
> +
DeleteHistory에 대한 테스트는 없어도 될까요~?

2021-05-25 23:03 UTC, DoLiLu commented on src/test/java/qna/domain/AnswerTest.java
> +                () -> assertThat(saveAnswer.isDeleted()).isFalse()
select 추가 하였습니다.

saveAnswer의 getId가 null이 아닌거 만으로는 db에 저장되었다고 판단되기 어려울까요?

2021-05-25 23:03 UTC, DoLiLu commented on src/main/java/qna/domain/DeleteHistory.java
> +
테스트 작성 진행하였습니다.

2021-05-25 23:08 UTC, DoLiLu commented on src/main/java/qna/domain/Answer.java
> +        return deleted == answer.deleted && Objects.equals(id, answer.id) && Objects.equals(contents, answer.contents) && Objects.equals(writerId, answer.writerId) && Objects.equals(questionId, answe
created_at, updated_at 을 상속받는 구조로 구현되어 있는데 관련 부분 equals에 추가하기 위해서는
protected로 변경이 되어야 할 것 같습니다.

protected로 변경 후 equals 재정의 하는게 맞을까요? 

변경 로직에 대한 장점을 정확하게 판단을 내리기가 어려워 다시 질문합니다.

2021-05-26 02:53 UTC, ssosso approved these changes
정수님, 수정해주신 부분 확인하였습니다!
댓글도 달았으니 확인 부탁드려요~
1단계는 충분한거 같아 merge하겠습니다~

2021-05-26 02:53 UTC, ssosso commented on src/test/java/qna/domain/AnswerTest.java
> +                () -> assertThat(saveAnswer.isDeleted()).isFalse()
네네 정상동작하면 저장되었다고 판단할 수 있습니다!
명확한 확인을 위해 포함하면 좋지 않을까 정도의 피드백이었습니다:)

2021-05-26 02:53 UTC, merged

2021-07-11 15:13 UTC, ssosso commented on src/main/java/qna/domain/Answer.java
> +        return deleted == answer.deleted && Objects.equals(id, answer.id) && Objects.equals(contents, answer.contents) && Objects.equals(writerId, answer.writerId) && Objects.equals(questionId, answe
@DoLiLu
제가 이 부분에 답글을 남기지 않았었네요ㅠ 죄송합니다ㅠ
값 동등성 비교가 필요없다면 굳이 넣지 않아도 될 거 같습니다:)