2주차 JPA Step2 PR 드립니다.
next-step/jwp-qna pull request #701
Opened 2022-11-10 18:41 UTC by develo-pyo

2주차 step2 엔티티 연관관계 매핑 PR 요청드립니다.

질문 몇가지 드립니다. 😊 
1. domain 테스트코드 내에서 레파지토리 테스트코드를 작성한게 좀 이상하게 느껴져 전부 제거 후 도메인 관련 테스트만 작성했습니다.
도메인 테스트, 레파지토리 테스트를 이런식으로 분리하여 작성하는게 맞을까요?
2. UserRepositoryTest 에서 유니크 체크제약에 대한 테스트를 수행하던 도중 영속성컨텍스트 관련하여 좀 어렵다고 느껴지는 부분이 있었는데요..
- new 키워드로 인스턴스 생성시 준영속 상태이므로 save 호출시 persist 가 호출되고, 원래 flush 및 transaction commit 을 통해 insert 쿼리가 execute 되어야 하지만, User 도메인에서 @GeneratedValue로 DB에 id(pk)생성을 부여했기 때문에 persist 시점에서도 insert 쿼리가 나가게 되는게 맞나요..?
- 그리고 위와 같은 이유로 save를 2번째 호출할 때, flush 를 하지 않았음에도 insert 쿼리가 두번 수행되어 유니크 제약 위반에 따른 예외가 발생하는게 맞을까요?  

그럼 리뷰 및 답변 부탁드립니다 🙏  
행복한 금요일 보내세요 🔥 
감사합니다!

2022-11-12 03:40 UTC, seokhongkim requested changes
정표님, 2단계 미션 잘 진행해주셨습니다. 👍 

질문주신 부분에 대해 제 생각 먼저 답변 드립니다.
> domain 테스트코드 내에서 레파지토리 테스트코드를 작성한게 좀 이상하게 느껴져 전부 제거 후 도메인 관련 테스트만 작성했습니다.
도메인 테스트, 레파지토리 테스트를 이런식으로 분리하여 작성하는게 맞을까요?

이상하게 느껴지신 이유가 있을 것 같아요. 이 부분을 우선 정리해보시면 도움이 될 것 같습니다.
저는 도메인에 대한 테스트는 단위 테스트로 테스트하고, 레포지토리에 대한 테스트는 통합 테스트로 분리하신 것 같아서 좋습니다. 저는 기본적으로 단위 테스트로 만드는 것을 선호하고, 실제 DB 연결을 포함한 검증이 필요한 경우에 통합 테스트를 사용합니다. 단위 테스트가 실행 속도가 빠르고, 작성하고 이해하는 것이 쉽고, 테스트 격리도 수월해서 가능하면 단위 테스트를 이용합니다.

> UserRepositoryTest 에서 유니크 체크제약에 대한 테스트를 수행하던 도중 영속성컨텍스트 관련하여 좀 어렵다고 느껴지는 부분이 있었는데요..
new 키워드로 인스턴스 생성시 준영속 상태이므로 save 호출시 persist 가 호출되고, 원래 flush 및 transaction commit 을 통해 insert 쿼리가 execute 되어야 하지만, User 도메인에서 @GeneratedValue로 DB에 id(pk)생성을 부여했기 때문에 persist 시점에서도 insert 쿼리가 나가게 되는게 맞나요..?

이에 대해서는 `hibernate GenerationType.IDENTITY persist strategy` 키워드로 검색했을 때 나온 [블로그](https://gmlwjd9405.github.io/2019/08/12/primary-key-mapping.html)에 잘 정리되어 있어서 이 내용을 참고해보시면 도움이 될 것 같습니다. :)

이외에 코드에 코멘트를 조금 남겼으니 확인 부탁드립니다. 🙏 
정표님도 즐거운 주말 되세요!

2022-11-12 03:40 UTC, seokhongkim commented on src/main/java/qna/domain/Answer.java
> +    @ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.PERSIST)
연관관계를 설정하실 때 fetchType 을 `FetchType.LAZY` 로 설정하신 이유가 있을까요?

2022-11-12 03:40 UTC, seokhongkim commented on src/main/java/qna/domain/Answer.java
> +    @JoinColumn(name = "question_id", foreignKey = @ForeignKey(name = "fk_answer_to_question"))
명시적인 FK 설정 좋습니다! 👍

2022-11-12 03:40 UTC, seokhongkim commented on src/main/java/qna/domain/Answer.java
>      public String toString() {
연관관계가 설정된 엔티티의 `toString` 을 구현할 때 주의 또는 고려해야 할 점은 무엇이 있을까요?

2022-11-12 03:40 UTC, seokhongkim commented on src/main/java/qna/domain/DeleteHistory.java
> +    private User deletedById;
필드명도 변경이 필요할 것 같습니다. :)

2022-11-12 03:40 UTC, seokhongkim commented on src/main/java/qna/domain/DeleteHistory.java
>      private LocalDateTime createDate = LocalDateTime.now();
이 값도 audit 기능을 이용해서 관리해보면 어떨까요?

2022-11-12 03:40 UTC, seokhongkim commented on src/main/java/qna/domain/Question.java
>      public void addAnswer(Answer answer) {
`answers` 에도 추가해서 관리해줘야 할 것 같아요. :)
`setAnswers` 는 제공해주지 않아도 될 것 같은데, 정표님께서는 어떻게 생각하시나요?

2022-11-12 03:40 UTC, seokhongkim commented on src/main/java/qna/service/QnaService.java
>          for (Answer answer : answers) {
`Question` 과 `Answer` 의 연관관계를 설정했으니, `answerRepository` 를 통해 객체를 가져오지 말고 `Question` 을 통해 객체를 가져오는 건 어떨까요?

> https://edu.nextstep.camp/s/urD8knTu/ls/0G2Prpps 중 힌트 부분을 참고해주세요.
```java
Question question = findQuestionById(questionId);
List<Answer> answers = question.getAnswers();
```

2022-11-12 03:40 UTC, seokhongkim commented on src/test/java/qna/domain/AnswerTest.java
>  @DataJpaTest
`Repository` 에 대한 테스트를 분리하셨으니, `@DataJpaTest` 도 레포지토리와 관련된 테스트에서만 사용하셔도 될 것 같아요.

2022-11-12 03:40 UTC, seokhongkim commented on src/test/java/qna/domain/AnswerTest.java
> +    public void isOwnerTest() {
꼼꼼한 테스트 좋습니다. 👍

2022-11-12 11:58 UTC, develo-pyo commented on src/main/java/qna/domain/Answer.java
> +    @ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.PERSIST)
fetchType EAGER 는 N+1 문제로 특별한 경우가 아닌이상 몸에 베인것 처럼 LAZY 로 선언하라고 김영한님의 JPA 강좌 및 도서에서 봤기 때문에 깊이 생각 하지 않고 LAZY 로 선언하였습니다. Answer 와 Question 이 N : 1 구조라 EAGER 로 선언해도 크게 무방해보이긴 하네요..

2022-11-12 12:02 UTC, develo-pyo commented on src/test/java/qna/domain/AnswerTest.java
>  @DataJpaTest
앗 넵 수정하겠습니다

2022-11-12 12:38 UTC, develo-pyo commented on src/main/java/qna/domain/Answer.java
>      public String toString() {
순환참조로 인한 stackoverflow 가 발생할 수 있으므로 한쪽에서 참조관계에 놓인 필드에 대한 출력을 제거해주어야 함을 확인했습니다!

2022-11-12 12:57 UTC, develo-pyo commented on src/main/java/qna/domain/DeleteHistory.java
> +    private User deletedById;
아 필드명이 어색하다고 느끼긴했는데.. 수정하겠습니다!

2022-11-12 12:59 UTC, develo-pyo commented on src/main/java/qna/domain/DeleteHistory.java
>      private LocalDateTime createDate = LocalDateTime.now();
넵! 수정하겠습니다!

2022-11-12 16:15 UTC, develo-pyo commented on src/main/java/qna/domain/Question.java
>      public void addAnswer(Answer answer) {
질문하신 의도를 이해했습니다. 관련하여 answer 와 question 도메인을 수정했습니다. 감사합니다! 👍

2022-11-13 03:57 UTC, seokhongkim approved these changes
정표님, 2단계 미션 코멘트도 잘 반영해주셨습니다. 👍 
2단계 PR도 머지하도록 하겠습니다.

남긴 코멘트는 다음 단계 미션을 진행하실 때 함께 고민해보셔도 좋겠습니다.
3단계 미션에서 뵙겠습니다. 😀

2022-11-13 03:57 UTC, seokhongkim commented on src/main/java/qna/service/QnaService.java
> +        List<Answer> answers = question.getAnswers();
기존에는 삭제되지 않은 답변만 조회했는데, 이제는 삭제된 답변도 함께 조회해올 것으로 보이네요!

2022-11-13 03:57 UTC, seokhongkim commented on src/main/java/qna/service/QnaService.java
> -        List<Answer> answers = answerRepository.findByQuestionIdAndDeletedFalse(questionId);
`AnswerRepository` 에 있는 메서드는 이제 사용처가 없으니 삭제하고, 테스트 코드도 함께 삭제해도 될 것 같아요.

2022-11-13 03:57 UTC, seokhongkim commented on src/test/java/qna/service/QnaServiceTest.java
> +        Mockito.lenient().when(questionRepository.findByIdAndDeletedFalse(question.getId())).thenReturn(Optional.of(question));
사용하지 않는 코드에 대한 mocking 인 경우 설정하지 않는 것이 좋아 보입니다.
`answerRepository` 에 대해서는 프로덕션 코드에서도 의존성이 사라졌으므로 테스트 코드에서도 의존성을 제거하고, 행위에 대한 mocking 코드도 삭제하는 것이 좋을 것 같아요.

2022-11-13 03:57 UTC, seokhongkim commented on src/main/java/qna/domain/Answer.java
> +    @ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.PERSIST)
N+1 쿼리를 방지하기 위한 설정이라면 좋습니다. :)
관련하여 N+1 쿼리를 방지할 수 있는 다른 방법도 학습해보시면 좋겠습니다. `@BatchSize`, fetch join, entity graph 등의 키워드로 찾아보시면 학습에 도움이 될 것 같습니다. fetch join 과 페이징 처리를 함께 사용하면 발생할 수 있는 문제도 찾아보시면 도움이 될 것 같습니다.

2022-11-13 03:57 UTC, seokhongkim commented on src/main/java/qna/domain/Answer.java
>      public String toString() {
말씀하신 stack overflow 외에 트랜잭션 범위 밖에서 `toString` 을 호출하면 `LAZY` 설정된 엔티티에 접근하면서 `LazyInitializationException` 이 발생할 수 있는 점도 알고 계시면 구현할 때 도움이 될 것 같습니다. :)

2022-11-13 03:57 UTC, merged