Step2 연관 관계 매핑
next-step/jwp-qna pull request #702
Opened 2022-11-11 05:58 UTC by chosundeveloper

Step2 연관 관계 매핑 리뷰 부탁드립니다. 감사합니다~

2022-11-11 14:33 UTC, wooobo requested changes
2단계도 잘 진행해주셨습니다!

몇가지 코멘트 남겨드렸는데
확인 후 재요청 부탁드려요~!

2022-11-11 14:33 UTC, wooobo commented on src/main/java/qna/domain/Answer.java
> +    @ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
```
아래의 DDL을 보고 유추한다.

H2
alter table answer
    add constraint fk_answer_to_question
        foreign key (question_id)
            references question

alter table answer
    add constraint fk_answer_writer
        foreign key (writer_id)
            references user

alter table delete_history
    add constraint fk_delete_history_to_user
        foreign key (deleted_by_id)
            references user

alter table question
    add constraint fk_question_writer
        foreign key (writer_id)
            references user
```

` foreignkey` 이름을 부여해보아요~

2022-11-11 14:33 UTC, wooobo commented on src/main/java/qna/domain/Answer.java
> +        return this.writer.getId().equals(writer.getId());
`Question` 도메인 처럼 일관성있게 객체 비교형태면 좋겠네요!
`this.writer.equals(writer)` 

혹은, `equlas` 가 아니더라도 `isSame` 이라는 메시지를 던져볼수도 있겠네요!

2022-11-11 14:33 UTC, wooobo commented on src/main/java/qna/service/QnaService.java
```
Question question = findQuestionById(questionId);
List<Answer> answers = question.getAnswers();
```

객체 탐색을 좀 더 고민해보아요~!

2022-11-11 14:33 UTC, wooobo commented on src/main/java/qna/domain/DeleteHistory.java
> +    public DeleteHistory(ContentType contentType, Long contentId, User deletedBy, LocalDateTime createDate) {
정적 팩토리 메소드를 활용해보면 어떨까요? :thinking:

2022-11-11 14:33 UTC, wooobo commented on src/test/java/qna/repository/RepositoryTest.java
> +        javajigi = userRepository.save(new User("javajigi", "password", "name", "javajigi@slipp.net"));
[테스트 픽스처 올바르게 사용하기](https://jojoldu.tistory.com/611)

도움 될 수 있을것 같아 공유합니다~

2022-11-12 02:03 UTC, chosundeveloper commented on src/test/java/qna/repository/RepositoryTest.java
> +        javajigi = userRepository.save(new User("javajigi", "password", "name", "javajigi@slipp.net"));
오히려 결합도를 높일 수 있는 단점이 있다는 내용이군요. 하나의 테스트 기준에서는 사용하지도 않을 것을 로드하는 느낌이군요 클래스 내부 private 메서드 사용으로 변경했습니다.

2022-11-12 11:22 UTC, wooobo approved these changes
2단계 잘 마무리 해주셨습니다!

`merge` 진행하겠습니다!
3단계 진행해주세요!

2022-11-12 11:22 UTC, wooobo commented on src/main/java/qna/domain/DeleteHistory.java
> +    public static DeleteHistory of(ContentType contentType, Long contentId, User deletedBy, LocalDateTime createDate) {
`정적 팩토리 메소드`를 활용해보셨네요!

이렇게 해볼수 도 있겠네요! 

```
public static DeleteHistory ofQuestion(Long contentId, User deletedBy, LocalDateTime createDate) {
  return new DeleteHistory(ContentType.Question, ...);
```

2022-11-12 11:22 UTC, wooobo commented on src/main/java/qna/domain/Answer.java
> +    public User getWriter() {
3단계 진행시에는 `getter`,`setter`를 지양하는 패턴으로 진행해보시면 좋을것 같아요!

2022-11-12 11:22 UTC, merged

2022-11-13 11:12 UTC, chosundeveloper commented on src/main/java/qna/domain/Answer.java
> +    public User getWriter() {
setter는 전부 삭제했고 getter의 경우는 최소한으로 사용했다고 생각하는데 피드백 주시면 수정해나가겠습니다.