Step2 - JPA (연관관계매핑) 리뷰 요청드립니다.
next-step/jwp-qna pull request #71
Opened 2021-05-31 01:05 UTC by jhh992000

1단계에 이어서 바로 연관관계 매핑을 해보았습니다.
매핑을 하면서 fk 매핑 속성에 대해서 알게 되었고, fk로 지정되는 속성은 insertable과 updatable을 false로 주어야 한다는 점도 알게되었습니다.
일부 테스트코드가 깨지는 부분이 생겨서 깨지는부분만 수정했습니다.
3단계부터 Q&A 서비스를 만들어갈것 같아서 테스트코드는 일단 jpa 학습용 코드로 남겨두었습니다.
다음단계부터 도메인과 관련된 테스트코드를 작성해볼수 있도록 하겠습니다.
그럼 리뷰 부탁드립니다.

2021-05-31 18:37 UTC, jhh992000 commented
아직 리뷰전이시라서 테스트코드 조금 추가했습니다.
연관관계 매핑한 테스트코드가 빠져서요.

2021-06-01 01:49 UTC, kang-hyungu requested changes
훈희님 구현하신 코드 확인했습니다
연관 관계 매핑 관련하여 피드백 남겼습니다
확인해보시고 궁금한 점 생기면 dm 주시거나 코멘트 남겨주세요

2021-06-01 01:49 UTC, kang-hyungu commented on src/main/java/qna/domain/Answer.java
>      private Long writerId;
writer 인스턴스 변수를 추가했는데 writerId를 남겨둘 필요가 있을까요?

2021-06-01 01:49 UTC, kang-hyungu commented on src/main/java/qna/domain/Answer.java
>      private Long questionId;
question도 객체 관계를 매핑했으니 questionId는 필요 없겠네요

2021-06-01 01:49 UTC, kang-hyungu commented on src/main/java/qna/domain/Answer.java
> +    public void setQuestion(Question question) {
객체지향 생활체조
규칙 9: 게터/세터/프로퍼티를 쓰지 않는다.

필요한 getter를 제외하고 나머지 메서드는 삭제하는게 좋겠네요
모든 도메인 객체를 점검해보아요

2021-06-01 01:49 UTC, kang-hyungu commented on src/main/java/qna/domain/DeleteHistory.java
>      private Long deletedById;
deleteUser를 추가했으니 불필요한 인스턴스 변수는 삭제해주세요

2021-06-01 01:49 UTC, kang-hyungu commented on src/main/java/qna/domain/Question.java
>      private Long writerId;
이 필드도 이제 필요 없겠네요

2021-06-01 01:49 UTC, kang-hyungu commented on src/test/java/qna/repository/AnswerRepositoryTest.java
> +    EntityManager entityManager;
entityManager를 사용하지 않아도 테스트 가능합니다.
relation_question 메서드에 남긴 피드백 참고하세요

2021-06-01 01:49 UTC, kang-hyungu commented on src/test/java/qna/repository/AnswerRepositoryTest.java
> +@TestInstance(Lifecycle.PER_CLASS)
이 어노테이션도 없어도 되겠네요

2021-06-01 01:49 UTC, kang-hyungu commented on src/test/java/qna/repository/AnswerRepositoryTest.java
> +        entityManager.flush();
모든 테스트 메서드에서 flush, clear를 제거해도 테스트 가능합니다.

2021-06-01 01:49 UTC, kang-hyungu commented on src/test/java/qna/repository/AnswerRepositoryTest.java
> +    void relation_question() {
객체 간의 관계를 설정하고 저장하면 각 객체마다 save하지 않아도 jpa가 자동으로 insert 구문을 실행해줍니다.
아래 예제를 참고해서 다른 테스트도 불필요한 save 구문은 제거해보아요

```java
    @Test
    @DisplayName("question 연관관계")
    void relation_question() {
        //Given
        User user1 = new User("test1", "1234", "홍길동", "hong@test.com");
        User user2 = new User("test2", "1234", "정훈희", "jhh992000@gmail.com");
        Question question = new Question("질문있어요", "내용입니다.", user2);
        Answer answer = new Answer(user1, question, "답변입니다.");
        question.addAnswer(answer);

        questionRepository.save(question);

        //When
        Question savedQuestion = questionRepository.findById(question.getId()).get();
        List<Answer> answers = savedQuestion.getAnswers();

        //Then
        assertAll(
            () -> assertThat(answers).isNotNull(),
            () -> assertThat(answers).hasSize(1)
        );
    }
```

2021-06-01 01:49 UTC, kang-hyungu commented on src/test/java/qna/repository/AnswerRepositoryTest.java
> +        User user1 = new User("test1", "1234", "홍길동", "hong@test.com");
클린코드 25p

의미 있게 구분하라
컴파일러나 인터프리터만 통과하려는 생각으로 코드를 구현하는 프로그래머는 스스로 문제를 일으킨다.
예를 들어, 동일한 범위 안에서 다른 두 개념에 같은 이름을 사용하지 못한다.
...

컴파일러를 통과할지라도 연속된 숫자를 덧붙이거나 불용어(noise word)를 추가하는 방식은 적절하지 못하다.
이름이 달라야 한다면 의미도 달라져야 한다.

연속적인 숫자를 덧붙인 이름(a1, a2 ... aN)은 의도적인 이름과 정반대다.
이런 이름은 그릇된 정보를 제공하는 이름도 아니며, 아무런 정보를 제공하지 못하는 이름일 뿐이다.
저자 의도가 전혀 드러나지 않는다.

---

클린코드 157p

테스트 코드는 실제 코드 못지 않게 중요하다. 테스트 코드는 이류 시민이 아니다.
테스트 코드는 사고와 설계와 주의가 필요하다.
실제 코드 못지 않게 깨끗하게 짜야한다.

테스트는 유연성, 유지보수성, 재사용성을 제공한다. 테스트 케이스가 있으면 변경이 쉬워지기 때문이다.
따라서 테스트 코드가 지저분하면 코드를 변경하는 능력이 떨어지며 코드 구조를 개선하는 능력도 떨어진다.
테스트 코드가 지저분할수록 실제 코드도 지저분해진다.
결국 테스트 코드를 잃어버리고 실제 코드도 망가진다.

2021-06-01 02:18 UTC, jhh992000 commented on src/main/java/qna/domain/Answer.java
>      private Long writerId;
아 그렇네요. 제거했습니다.

2021-06-01 02:18 UTC, jhh992000 commented on src/main/java/qna/domain/Answer.java
>      private Long questionId;
네넵. 제거했습니다~!

2021-06-01 02:18 UTC, jhh992000 commented on src/main/java/qna/domain/Answer.java
> +    public void setQuestion(Question question) {
getter는 필요할것 같아서 남겨주고 setter 들은 제거 했습니다.

2021-06-01 02:20 UTC, jhh992000 commented on src/main/java/qna/domain/DeleteHistory.java
>      private Long deletedById;
네 연관객체를 추가했으니 제거해야겟네요.

2021-06-01 02:22 UTC, jhh992000 commented on src/test/java/qna/repository/AnswerRepositoryTest.java
> +    EntityManager entityManager;
entityManager를 사용한 이유는,
1차 캐시에서 엔티티변경에 대한 처리가 되면 sql이 실행되지 않아서, 실행되는 SQL을 확인해보고 싶어서 추가했습니다.
해당 코드들은 모두 제거하겠습니다~

2021-06-01 02:27 UTC, jhh992000 commented on src/main/java/qna/domain/Question.java
>      private Long writerId;
넵 제거했습니다.

2021-06-01 02:29 UTC, jhh992000 commented on src/test/java/qna/repository/AnswerRepositoryTest.java
> +@TestInstance(Lifecycle.PER_CLASS)
아 테스트코드들이 독립적으로 실행되도록 리팩토링하면서 빼먹은게 있었네요.  제거하겠습니다.

2021-06-01 02:29 UTC, jhh992000 commented on src/test/java/qna/repository/AnswerRepositoryTest.java
> +        entityManager.flush();
넵 제거했습니다.

2021-06-01 02:32 UTC, jhh992000 commented on src/test/java/qna/repository/AnswerRepositoryTest.java
> +    void relation_question() {
넵 영속컨텍스트에 들어간 question 객체에 answer를 add만 해주고 트랜잭션이 끝나면 자동으로 question에 등록된 answer들을 db에 반영(insert or update)해준다.
알고는 있었는데 테스트코드에 반영을 하지 못했네요ㅜ
수정하겠습니다~!

2021-06-01 02:38 UTC, jhh992000 commented on src/test/java/qna/repository/AnswerRepositoryTest.java
> +        User user1 = new User("test1", "1234", "홍길동", "hong@test.com");
question과 answer의 작성자 데이터를 초기화해주려는 의도였는데, 
일단 등록만 해두면 된다고 생각을 해서 변수명에 큰 의미를 두지 않았었네요.
저도 요즘 클린코드 책을 구해서 읽고있습니다. 
`테스트 코드는 이류 시민이 아니다.`
사소한 테스트코드라도 클린하게 작성할 수 있도록 노력해야겠네요.👍

2021-06-01 03:02 UTC, jhh992000 commented on src/test/java/qna/repository/AnswerRepositoryTest.java
> +        entityManager.flush();
아 이부분은 Given 부분에서 초기화한 데이터들을 영속화를 해제한 상태에서 이후의 테스트를 진행하려고 했었습니다.
이 부분에 대해서는 DM으로 따로 문의를 드리도록 할께요.

2021-06-01 04:38 UTC, jhh992000 commented on src/test/java/qna/repository/AnswerRepositoryTest.java
> +    void relation_question() {
아 여기서 새로운걸 하나 알아가네요! 영속성전이에 대해서 알게 되었습니다.
가이드 잡아주셔서 감사드립니다. 🙏

2021-06-01 04:45 UTC, jhh992000 commented
현구님 안녕하세요.
JPA 2단계 피드백 주셔서 감사드립니다.
방금 피드백 주신사항들 반영하여 리뷰 다시 요청드렸습니다.
덕분에 새로운 것들을 알아가고 있습니다.
한가지 여쭙고 싶은게 있는데요.
테스트코드에서 entityManager를 사용한 부분에 대해서 궁금증이 있습니다.
제가 테스트코드 entityManager를 사용한 이유는 Given 부분에서 초기화한 데이터들의 영속화를 해제한 상태에서
다시 DB의 데이터를 불러와서 영속화 시키고 값들을 확인하는 방식의 테스트코드를 작성했었는데요.
`영속화해제` -> `DB호출` -> `영속화 상태의 데이터 확인`
보통 이런식의 JPA Repository 테스트는 하지 않는지요?
불필요한 테스트인걸까요?

2021-06-01 04:50 UTC, jhh992000 commented on src/test/java/qna/repository/AnswerRepositoryTest.java
> +    EntityManager entityManager;
영속성전이에 대해서 알게되었습니다. 감사합니다. 👍

2021-06-02 01:27 UTC, kang-hyungu commented
> 현구님 안녕하세요.
> JPA 2단계 피드백 주셔서 감사드립니다.
> 방금 피드백 주신사항들 반영하여 리뷰 다시 요청드렸습니다.
> 덕분에 새로운 것들을 알아가고 있습니다.
> 한가지 여쭙고 싶은게 있는데요.
> 테스트코드에서 entityManager를 사용한 부분에 대해서 궁금증이 있습니다.
> 제가 테스트코드 entityManager를 사용한 이유는 Given 부분에서 초기화한 데이터들의 영속화를 해제한 상태에서
> 다시 DB의 데이터를 불러와서 영속화 시키고 값들을 확인하는 방식의 테스트코드를 작성했었는데요.
> `영속화해제` -> `DB조회(동기화, 영속화)` -> `영속화 상태의 데이터 확인`
> 보통 이런식의 JPA Repository 테스트는 하지 않는지요?
> 불필요한 테스트인걸까요?

영속화 해제를 하시는 이유가 무엇인가요?
각 테스트마다 격리된 상태를 유지하시는게 목적일가요?
DataJpaTest 어노테이션을 보시면 트랜잭션 어노테이션이 포함되어 있어서 매 테스트마다 쿼리 수행하고 다시 롤백됩니다.
롤백이 진행되니 다른 테스트에 영향 받지 않고 테스트 가능할 것으로 생각되네요

2021-06-02 01:37 UTC, kang-hyungu approved these changes
훈희님 피드백 반영 잘 하셨어요 👍 
질문 주신 내용은 코멘트 남겼으니 참고하세요.
pr은 머지 처리하겠습니다. 수고하셨어요~

2021-06-02 01:37 UTC, kang-hyungu commented on src/main/java/qna/domain/Answer.java
>          this.deleted = deleted;
setContents, setId, getContents 메서드는 안쓰는 것 같은데 같이 정리해보면 어떨까요

2021-06-02 01:37 UTC, kang-hyungu commented on src/main/java/qna/domain/Question.java
>          this.contents = contents;
setId, setContents 메서드를 안쓰고 있는데 같이 정리해보면 좋겠네요

2021-06-02 01:37 UTC, merged

2021-06-02 04:37 UTC, jhh992000 commented on src/main/java/qna/domain/Answer.java
>          this.deleted = deleted;
네 불필요한 getter/setter는 지양하겠습니다.
해당 메서드들은 제거했습니다.

2021-06-02 05:40 UTC, jhh992000 commented
> > 현구님 안녕하세요.
> > JPA 2단계 피드백 주셔서 감사드립니다.
> > 방금 피드백 주신사항들 반영하여 리뷰 다시 요청드렸습니다.
> > 덕분에 새로운 것들을 알아가고 있습니다.
> > 한가지 여쭙고 싶은게 있는데요.
> > 테스트코드에서 entityManager를 사용한 부분에 대해서 궁금증이 있습니다.
> > 제가 테스트코드 entityManager를 사용한 이유는 Given 부분에서 초기화한 데이터들의 영속화를 해제한 상태에서
> > 다시 DB의 데이터를 불러와서 영속화 시키고 값들을 확인하는 방식의 테스트코드를 작성했었는데요.
> > `영속화해제` -> `DB조회(동기화, 영속화)` -> `영속화 상태의 데이터 확인`
> > 보통 이런식의 JPA Repository 테스트는 하지 않는지요?
> > 불필요한 테스트인걸까요?
> 
> 영속화 해제를 하시는 이유가 무엇인가요?
> 각 테스트마다 격리된 상태를 유지하시는게 목적일가요?
> DataJpaTest 어노테이션을 보시면 트랜잭션 어노테이션이 포함되어 있어서 매 테스트마다 쿼리 수행하고 다시 롤백됩니다.
> 롤백이 진행되니 다른 테스트에 영향 받지 않고 테스트 가능할 것으로 생각되네요



> > 현구님 안녕하세요.
> > JPA 2단계 피드백 주셔서 감사드립니다.
> > 방금 피드백 주신사항들 반영하여 리뷰 다시 요청드렸습니다.
> > 덕분에 새로운 것들을 알아가고 있습니다.
> > 한가지 여쭙고 싶은게 있는데요.
> > 테스트코드에서 entityManager를 사용한 부분에 대해서 궁금증이 있습니다.
> > 제가 테스트코드 entityManager를 사용한 이유는 Given 부분에서 초기화한 데이터들의 영속화를 해제한 상태에서
> > 다시 DB의 데이터를 불러와서 영속화 시키고 값들을 확인하는 방식의 테스트코드를 작성했었는데요.
> > `영속화해제` -> `DB조회(동기화, 영속화)` -> `영속화 상태의 데이터 확인`
> > 보통 이런식의 JPA Repository 테스트는 하지 않는지요?
> > 불필요한 테스트인걸까요?
> 
> 영속화 해제를 하시는 이유가 무엇인가요?
> 각 테스트마다 격리된 상태를 유지하시는게 목적일가요?
> DataJpaTest 어노테이션을 보시면 트랜잭션 어노테이션이 포함되어 있어서 매 테스트마다 쿼리 수행하고 다시 롤백됩니다.
> 롤백이 진행되니 다른 테스트에 영향 받지 않고 테스트 가능할 것으로 생각되네요

실제 운영에서 동작하는 코드는 영속화되지 않은 상태에서 DB를 조회해오는부분부터 시작을 할거라 생각을 해서
//Given절의 테스트시 필요한 데이터를 초기화하고나서 영속화해제를 먼저 해야하지 싶은 생각을 했었습니다.
어차피 DB조회해오고나서부터는 영속화상태이니 불필요할것 같기도 합니다.