[JPA] Step2 PR 리뷰 부탁드립니다.
next-step/jwp-qna pull request #717
Opened 2022-11-13 09:38 UTC by SanghoonSon

안녕하세요 우빈님 😄 

이전 스텝에서 남겨주신 피드백은 반영하였습니다 :)

아래 테스트 코드가 실패한다고 남겨주셨었는데요~

금번 미션 반영 후 전체 테스트해보니 저는 성공이라고 나오긴합니다만
혹시나 실패로 뜨면 말씀부탁드립니다!
```java
@DataJpaTest
class AnswerRepositoryTest {
    ....

    @Test
    @DisplayName("주어진 답변 ID로 조회한다")
    void find_answer_with_id_test() {
        Answer expectedAnswer = new Answer(writer, question, "content");
        expectedAnswer = answerRepository.save(expectedAnswer);
        Answer answer = answerRepository.findByIdAndDeletedFalse(question.getId()).get();
        assertThat(answer).isEqualTo(expectedAnswer);
    }
}
```

이번 리뷰도 잘부탁드립니다. 😄

2022-11-13 12:03 UTC, limwoobin requested changes
안녕하세요 상훈님
2단계 미션 잘 수행해주셨습니다 ㅎㅎ

몇가지 코멘트를 드렸으니 확인부탁드립니다.

2022-11-13 12:03 UTC, limwoobin commented on src/main/java/qna/domain/Answers.java
> +    }
answers 선언시 바로 new ArrayList() 로 선언하는건 어떨까요??

2022-11-13 12:03 UTC, limwoobin commented on src/main/java/qna/domain/Answers.java
> +    }
여기도 `new Answers()` 로 사용하면 필요없지 않을까 싶습니다!

2022-11-13 12:03 UTC, limwoobin commented on src/main/java/qna/domain/DeleteHistories.java
> +    private final List<DeleteHistory> deleteHistories;
일급컬렉션으로 래핑해주셨네요 ㅎㅎ
클래스명과 변수명이 같아 좀 어색한데.. values, items 와 같은 이름은 어떨까요??

2022-11-13 12:03 UTC, limwoobin commented on src/main/java/qna/service/QnaService.java
>          deleteHistoryService.saveAll(deleteHistories);
해당 부분은 3단계 미션인데 2단계로 pr을 올려주셨네요...

2022-11-13 12:03 UTC, limwoobin commented on src/main/java/qna/domain/Answers.java
> +    private List<Answer> answers;
cascade 설정 없이 저장이 될까요..?

2022-11-13 12:04 UTC, limwoobin commented
테스트코드는 이번에도 실패하네요 ㅎㅎ
클래스단위가 아닌 패키지단위로 전체로 돌린다음에 한번 확인해보시면 좋을것같습니다

2022-11-14 12:42 UTC, SanghoonSon commented on src/main/java/qna/domain/Answers.java
> +    }
step3 진행시 피드백 주신내용 반영해보도록 하겠습니다.

2022-11-14 12:42 UTC, SanghoonSon commented on src/main/java/qna/service/QnaService.java
>          deleteHistoryService.saveAll(deleteHistories);
해당 부분은 원복후 PR 재요청 드리겠습니다~

2022-11-14 14:40 UTC, SanghoonSon commented on src/main/java/qna/domain/Answers.java
> +    private List<Answer> answers;
앗 그렇네요..
삭제의 경우에는 Flag 처리와 삭제 이력을 생성하는것으로 보이기에, ```CascadeType.PERSIST``` 옵션만 추가하였습니다 😄

2022-11-14 14:43 UTC, SanghoonSon commented
2단계 요구사항에 맞춰 PR 재요청드립니다!

남겨주신 피드백 반영해보았고,
Step1 에서 테스트 오류난건 다시 수정해보았습니다 🙏 

일급 컬렉션은 다음 단계에서 만들도록 하겠습니다. 😅

2022-11-14 15:43 UTC, limwoobin approved these changes
안녕하세요 상훈님
2단계 미션 잘 진행해주셔서 크게 드릴 피드백이 없네요ㅎㅎ 💯💯 
그럼 다음 미션도 화이팅입니다!

2022-11-14 15:43 UTC, limwoobin commented on src/test/java/qna/domain/QuestionTest.java
> +    }
QuestionTest는 Question에 대한 단위테스트의 역할을 수행하는 것으로 알고있는데요
repository에서 해당 테스트 클래스의 코드를 의존하고있네요 ㅎㅎ
questionSample을 사용하시려는거라면 repositoryTest 내에서 직접 사용하거나
`QuestionTestFixture` 와 같은 클래스를 만들어 해당 값을 제공하는것은 어떨까요??

2022-11-14 15:43 UTC, limwoobin commented on src/main/java/qna/domain/Question.java
> +
해당 객체는 `Answers`로 유지해주셔도 좋았을것같네요 
다음단계에서는 다시 `Answers`로 래핑해서 한번 사용해보시죠! ㅎㅎ

2022-11-14 15:43 UTC, merged

2022-11-15 12:23 UTC, sanghun92 commented on src/test/java/qna/domain/QuestionTest.java
> +    }
QuestionTestFixture를 만들어서 사용해볼 생각은 못하였네요 감사합니다 😀