Step1 엔티티 매핑
next-step/jwp-qna pull request #728
Opened 2022-11-15 14:19 UTC by msares

안녕하세요.
JPA를 처음하는 거라 부족한게 많은것 같습니다.
step1 엔티티 매핑 리뷰 부탁드립니다.
감사합니다.

2022-11-16 14:21 UTC, chae-yh requested changes
형간님 안녕하세요 JPA 미션의 리뷰를 맡은 채영훈입니다. 반갑습니다 ㅎㅎ
그리고, 전체적으로 코드 잘 작성해주셨네요 👍 바로 merge해도 될 것 같지만, 조금만 더 고민해주시면 좋을만한 내용들이 있어 코멘트 드렸으니 확인 부탁드립니다.

감사합니다 : )

2022-11-16 14:21 UTC, chae-yh commented on src/main/java/qna/Application.java
> +@EnableJpaAuditing
auditing을 위해서 추가 해주셨군요 👍

2022-11-16 14:21 UTC, chae-yh commented on src/main/java/qna/domain/Answer.java
> +    @Lob
적절하게 어노테이션을 주셨네요 👍

2022-11-16 14:21 UTC, chae-yh commented on src/main/java/qna/domain/Answer.java
> +    protected Answer() {
엔티티를 위한 성생자 👍 
```suggestion
    protected Answer() {}
```
[컨벤션](https://naver.github.io/hackday-conventions-java/#permit-concise-empty-block)에 따르면 이렇게 줘도 좋을 것 같아요...!

2022-11-16 14:21 UTC, chae-yh commented on src/main/java/qna/domain/BaseTimeEntity.java
> +@MappedSuperclass
중복 코드 분리 👍

2022-11-16 14:21 UTC, chae-yh commented on src/main/java/qna/domain/DeleteHistory.java
>      private ContentType contentType;
Enum값에 대해서 줄 수 있는 어노테이션이 있을 것 같습니다..!

2022-11-16 14:21 UTC, chae-yh commented on src/test/java/qna/domain/AnswerRepositoryTest.java
> +                () -> assertThat(answer.getWriterId()).isEqualTo(AnswerTest.A1.getWriterId()),
A1 객체는 현재 Repository 테스트를 위해서 사용하는데, AnswerRepositoryTest 에서 선언하고 사용해줄 수 있지 않을까요..?
추가로, A1과 같은 축약어보다는 해당 객체를 잘 표현할 수 있는 변수명이 있을 것 같습니다..!

2022-11-16 14:21 UTC, chae-yh commented on src/test/java/qna/domain/QuestionRepositoryTest.java
> +    void 질문_저장() {
이 부분은 개개인마다 다르겠지만, 이미 `@DisplayName에서 잘 설명해주고 있으니, 메서드명은 영어로하면 어떨까요...?

2022-11-16 14:21 UTC, chae-yh commented on src/test/java/qna/domain/UserRepositoryTest.java
> +class UserRepositoryTest {
전체적으로 jpa 테스트 시 영속성 컨텍스트에 있는 캐시된 데이터에 대해서 테스트를 해주고 있습니다.
영속성 컨텍스트를 비우고, 실제 db에서 데이터를 가져와서 테스트를 해보는 것은 어떨까요...? 두 객체의 동등성 테스트 같은게 들어가면 좋을 것 같습니다..!

2022-11-17 13:50 UTC, msares commented on src/test/java/qna/domain/AnswerRepositoryTest.java
> +                () -> assertThat(answer.getWriterId()).isEqualTo(AnswerTest.A1.getWriterId()),
AnswerTest가 qna main에 있어서 그대로 가져다가 썼는데 AnswerRepositoryTest에 선언해서 쓰는게 좋은가요???

2022-11-17 14:08 UTC, msares commented on src/test/java/qna/domain/UserRepositoryTest.java
> +class UserRepositoryTest {
동등성 테스트를 위해 equals를 만들었는데 class 변수가 많아서 메서드 길이가 길어지는데 괜찮은건가요??
다른 방법이 있을까요??

2022-11-17 14:08 UTC, msares commented
수정하여 다시 올렸습니다.
리뷰 부탁드립니다.

2022-11-18 15:11 UTC, chae-yh approved these changes
형간님 안녕하세요. 피드백 잘 반영해주셨습니다 ㅎㅎ 👍 질문주신 내용에 대해서는 코멘트드렸으니 확인 부탁드리고, 미션의 목적은 달성한 것으로 생각이 되어 merge 하겠습니다...!

다음 step 진행 부탁드립니다 : )

2022-11-18 15:11 UTC, chae-yh commented on src/test/java/qna/domain/UserRepositoryTest.java
> +class UserRepositoryTest {
여기서는 Entity를 다루고 있으므로, [id 값만을 비교](https://www.baeldung.com/jpa-entity-equality)해줄 수도 있을 것 같아요..!

2022-11-18 15:11 UTC, chae-yh commented on src/test/java/qna/domain/UserRepositoryTest.java
> +    void 유저_영속성_초기화후_같은객채_조회() {
피드백 반영 👍

2022-11-18 15:11 UTC, chae-yh commented on src/test/java/qna/domain/AnswerRepositoryTest.java
> +                () -> assertThat(answer.getWriterId()).isEqualTo(AnswerTest.A1.getWriterId()),
AnswerRepository 테스트에서 사용하는데, AnswerTest에 굳이 있을 필요가 없다고 생각했습니다..!

2022-11-18 15:11 UTC, merged