[OptimistLabyrinth] 🚀 3단계 - 질문 삭제하기 리팩터링
next-step/jwp-qna pull request #747
Opened 2022-11-25 23:18 UTC by OptimistLabyrinth

2022-11-26 17:36 UTC, mskangg requested changes
3단계 미션 잘 구현해주셨습니다.
다만, 테스트코드가 동작하지 않는 것들이 있습니다.

<img width="311" alt="image" src="https://user-images.githubusercontent.com/27044096/204101669-b383b6ec-57a9-47bc-98ca-a1492c1a11f6.png">

테스트는 독립적인 환경에서 돌아가야하니 꼭 확인 부탁드려요!

그리고 몇가지 피드백 드렸으니 확인 부탁드립니다.

2022-11-26 17:36 UTC, mskangg commented on src/main/java/qna/domain/Question.java
> +    }
domain 객체에 dto를 추가하셨네요.
내부 상태로 갖고있는 answers와는 무엇이 다른가요?? 🤔

2022-11-26 17:36 UTC, mskangg commented on src/main/java/qna/domain/Question.java
> +        }
질문 삭제시 연관된 답변들을 삭제하는 로직 중 `answer.delete(loginUser)` 에서 리턴값을 `DeleteHistory`로 구현한다면  `DeleteResultDto`은 필요하지 않아보입니다.

이런식으로도 구현해볼 수 있을 것 같아요!
이미 지운 답변들의 히스토리를 생성해서 넣는 `getDeleteHistories()` 메서드도 리팩토링 할 수 있어보입니다.

```java
    public List<DeleteHistory> delete2(User loginUser) {
        validateOwner(loginUser);

        List<DeleteHistory> deleteHistories = this.answers.stream()
                .map(answer -> answer.delete2(loginUser))
                .collect(toList());

        setDeleted(true);

        deleteHistories.add(new DeleteHistory(id, ContentType.QUESTION, loginUser));
        return deleteHistories;
    }
```

2022-11-26 17:36 UTC, mskangg commented on src/main/java/qna/domain/Question.java
> +    public DeleteResultDto delete(User loginUser) throws CannotDeleteException {
CanNotDeleteException이 현재 checkedException으로 설정되어있는데, uncheckedException으로 변경해도 좋을 것 같아요 :)
변경하지 않는다면 예외를 전파하는 것이 아닌 check 해서 예외의 책임을 다하게 구현하시는게 좋아보입니다.

2022-11-26 17:36 UTC, mskangg commented on src/main/java/qna/service/QnaService.java
> +        answerRepository.saveAll(deleteResultDto.getAnswers());
question과 answers를 다시 save 하신 이유가 있으실까요??

2022-11-27 01:45 UTC, OptimistLabyrinth commented on src/main/java/qna/domain/Question.java
> +    }
리턴값으로 여러개의 객체를 돌려주고 싶어서 DTO 객체를 만들었어요.
애초에 리턴값이 여러개가 되는 것 자체가 잘못된 설계인걸까요??

2022-11-27 01:56 UTC, OptimistLabyrinth commented on src/main/java/qna/service/QnaService.java
> +        answerRepository.saveAll(deleteResultDto.getAnswers());
제가 JPA 에서 영속성 콘텍스트가 어떻게 운영되는지 확실하게 몰라서 확실하게 하려고
수정한 모든 데이터에 대해서 save 호출했어요.
하나의 엔티티에 대해서만 save 호출하면 연관성 있는 모든 엔티티도 함께 저장이 되나요??

2022-11-27 02:16 UTC, OptimistLabyrinth commented on src/main/java/qna/domain/Question.java
> +        }
수정 완료했습니다.

2022-11-27 02:16 UTC, OptimistLabyrinth commented on src/main/java/qna/domain/Question.java
> +    public DeleteResultDto delete(User loginUser) throws CannotDeleteException {
수정했습니다.

2022-11-27 02:17 UTC, OptimistLabyrinth commented on src/main/java/qna/service/QnaService.java
> +        answerRepository.saveAll(deleteResultDto.getAnswers());
redundant XXXRepository.save( ) 메서드 호출 제거 완료했습니다 ㅎㅎ

2022-11-27 02:21 UTC, OptimistLabyrinth commented
application.properties 파일이 문제였을까요??

spring.datasource.url 만 세팅하는 경우에 통합테스트에서 오류가 발생하나요??

- spring.datasource.driverClassName
- spring.jpa.database-platform

이 두 개의 값도 세팅한 뒤에 다시 PR 요청드려봅니다.

![Screenshot 2022-11-27 at 11 18 00 AM](https://user-images.githubusercontent.com/16411622/204116276-49be6b06-db6a-46bd-a2dc-e3c87f8bd3a9.png)

2022-11-27 12:15 UTC, mskangg approved these changes
피드백반영 잘해주셨어요! 👍 
모든 미션 완료하셨습니다,,!
과정의 절반이 지나고 있는 시점이니 시작보단 지치셨을 것 같아요!
페이스 조절 잘하셔서 꼭 마지막 미션까지 완료하셨으면 좋겠습니다!! 🙇‍♂️
이번 JPA 과정 정말정말 고생하셨고 남은 미션들도 화이팅입니다! 🔥

2022-11-27 12:15 UTC, merged