Step3 질문 삭제하기 리팩터링
next-step/jwp-qna pull request #76
Opened 2021-05-31 14:21 UTC by etff

안녕하세요, step3 리팩터링 요구사항 반영하여 PR 보냅니다.

2021-06-01 03:01 UTC, slamdunk7575 requested changes
리팩토링 깔끔하게 잘해주셨네요 🥇
개선해보면 좋을 포인트에 몇가지 코멘트 남겨드렸는데 확인해보시면 좋겠네요.
끝까지 화이팅 입니다! 💪

2021-06-01 03:01 UTC, slamdunk7575 commented on src/main/java/qna/domain/Question.java
> +        deleteHistories.add(new DeleteHistory(ContentType.QUESTION, this.id, loginUser));
`DeleteHistory` 내에 아래와 같은 `정적 팩토리 메소드`를 만들어보면
인자수도 줄면서 코드의 가독성을 높여줄수 있겠네요 :)

```
    public static DeleteHistory ofQuestion(Long contentId, User deletedBy) {
        return new DeleteHistory(ContentType.QUESTION, contentId, deletedBy);
    }

    public static DeleteHistory ofAnswer(Long contentId, User deletedBy) {
        return new DeleteHistory(ContentType.ANSWER, contentId, deletedBy);
    }
```

2021-06-01 03:01 UTC, slamdunk7575 commented on src/main/java/qna/domain/Question.java
> +        List<DeleteHistory> deleteHistories = new ArrayList<>();
`List<DeleteHistory>`를 `일급 컬렉션`으로 만들어 리턴해보면 어떨까요?

[일급 컬렉션을 사용하는 이유](https://woowacourse.github.io/javable/post/2020-05-08-First-Class-Collection/)
[일급 컬렉션 (First Class Collection)의 소개와 써야할 이유](https://jojoldu.tistory.com/412)

2021-06-01 03:01 UTC, slamdunk7575 commented on src/main/java/qna/domain/Answers.java
> +    private List<Answer> answers;
분리 잘해주셨네요 👍

2021-06-01 03:01 UTC, slamdunk7575 commented on src/main/java/qna/domain/Answer.java
>      @ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
지난번에 `Cascade` 사용 관련해서 객체의 라이프 사이클에 대해 고민해보시면 좋을것 같다고 말씀드렸었는데요.

JPA를 배제하고 서비스의 흐름으로 봤을때
일반적으로 `질문(Question)`이 먼저 생성되고 `답변(Answer)`이 생성되는 순서가 될 것 같아요.

이부분에서 `Answer`가 Cascade를 통해 `Question`의 라이프 사이클을 관리하는 부분은 제거하는게 좋을듯 한데요.
병호님 생각은 어떠신가요? 😄

아래는 참고해보시면 좋을것 같아요.
[[JPA] 프록시와 연관관계 관리](https://joont92.github.io/jpa/%ED%94%84%EB%A1%9D%EC%8B%9C%EC%99%80-%EC%97%B0%EA%B4%80%EA%B4%80%EA%B3%84-%EA%B4%80%EB%A6%AC/)

2021-06-01 03:01 UTC, slamdunk7575 commented on src/main/java/qna/domain/Email.java
> +    private String email;
👍

2021-06-01 03:01 UTC, slamdunk7575 commented on src/test/java/qna/domain/AnswersTest.java
> +        }
도메인 테스트도 잘 작성해주셨네요 👍

2021-06-01 05:38 UTC, slamdunk7575 commented on src/main/java/qna/service/QnAService.java
> +                .orElseThrow(NotFoundException::new);
참고로 아래와 같이 `Entity`에 추가해볼 수도 있습니다 :)

```java
@Where(clause = "deleted = false")
```

2021-06-01 11:46 UTC, etff commented on src/main/java/qna/domain/Question.java
> +        deleteHistories.add(new DeleteHistory(ContentType.QUESTION, this.id, loginUser));
정적팩터리 메서드로 의도를 나타낸다고 알고있는데, 이렇게 보니 더 와닿네요. 감사합니다!

2021-06-01 11:48 UTC, etff commented on src/main/java/qna/domain/Question.java
> +        List<DeleteHistory> deleteHistories = new ArrayList<>();
수정했습니다!

2021-06-01 12:31 UTC, etff commented on src/main/java/qna/domain/Answer.java
>      @ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
아, 어떤점인지 캐치했습니다! 처음에 단방향 관계만 생각하다보니 이상하게 되었네요. 삭제했습니다!

2021-06-01 12:50 UTC, etff commented
리뷰에 남기신 엔티티 delete = false 도 확인했습니다. 감사합니다. 
저는 개인적으로 repository에서 삭제여부를 명시하는게 더 나은 것같아 쓰지않았습니다.

2021-06-02 02:26 UTC, slamdunk7575 approved these changes
피드백 반영 열심히 해주셨네요 👍 

저 또한 리뷰를 하면서 많이 배울 수 있었습니다.
제가 드렸던 피드백들이 앞으로 병호님께 조금이라도 도움이 되었으면 좋겠네요!

그동안 고생 많으셨습니다. 감사합니다. 🙇

저와의 미션은 종료되었지만, 궁금한점이나 어려운점 있으면 언제든 편하게 DM 주세요!
남은 미션도 꾸준히 진행하시고 끝까지 완주하시길 응원하겠습니다! 🎉

2021-06-02 02:26 UTC, slamdunk7575 commented on src/main/java/qna/service/QnAService.java
> +        deleteHistoryService.saveAll((question.delete(loginUser)).getHistories());
개인취향일 수 있겠지만 아래처럼 작성해볼 수 있겠네요 😄

```java
DeleteHistories deleteHistories = findQuestionById(questionId).delete(loginUser);
deleteHistoryService.saveAll(deleteHistories.getHistories());
```

2021-06-02 02:26 UTC, slamdunk7575 commented on src/main/java/qna/domain/DeleteHistories.java
> +    }
`Collections.unmodifiableList()`를 활용하여 외부에서 컬렉션을 건드리지 못하도록 `read-only`로 리턴하면 좋을 것 같아요!

재 초기화 할 수 없도록 위에 `final` 키워드까지 붙여주시면 좋을 것 같습니다 :)

2021-06-02 02:26 UTC, merged