[Step2] 2단계 - 연관 관계 매핑
next-step/jwp-qna pull request #78
Opened 2021-05-31 14:30 UTC by Lee-Chungsun

안녕하세요! 리뷰어님

2단계 연관 관계 매핑 코드 요청 드립니다!!

연관 관계를 매핑하는 데에는 그렇게 어려움은 없었는데 Service쪽에 Mock 개념이 들어가고 나니 너무 어렵네요,, ㅠ
Mock 관련 한 부분에서 쉽게 참고할만한 곳이 있을까요??

테스트 관련해서 한가지 질문이 있습니다!

void test 1() {
    Answer actual = answer.save(A1);
    actual.setName("B");
}

void test 2() {
    Answer actual = answer.findByName("A");
}

2 가지 테스트 코드가 있을때 처음에 "A"라는 Name 갖는 answer를 저장 후에 테스트 2에서 "A"를 조회할 때 오류가 발생하는 것 같은데 한번에 테스트를 실행하게 되면 1번 이후 COMMIT 2번 실행 으로 처리가 되어서 오류가 발생하는 것일까요,,?? 아니면 제가 테스트를 잘 못 한 것일까요,,? 테스트 코드도 한번에 쭉 실행하면 서로 연관이 생기는 건가요?

2021-05-31 15:12 UTC, JunilHwang requested changes
안녕하세요 충선님! 연관 관계 매핑 미션 잘 진행해주셨네요 👍 
간단한 리뷰 몇 가지 남겼으니 확인 후 다시 피드백 요청 부탁드립니다 🙇‍♂️

> 연관 관계를 매핑하는 데에는 그렇게 어려움은 없었는데 Service쪽에 Mock 개념이 들어가고 나니 너무 어렵네요,, ㅠ Mock 관련 한 부분에서 쉽게 참고할만한 곳이 있을까요??

음 보통 Mockito를 많이 사용한답니다. 

![image](https://user-images.githubusercontent.com/18749057/120213027-b6db9600-c26d-
11eb-868e-c8982624336d.png)

![image](https://user-images.githubusercontent.com/18749057/120213114-ca86fc80-c26d-11eb-9cbd-f341ea9e093d.png)

Spring을 사용하는 경우라면, MockBean을 사용하기도 한답니다.

![image](https://user-images.githubusercontent.com/18749057/120213142-d672be80-c26d-11eb-9c84-2efe8a9adcd8.png)

> 2 가지 테스트 코드가 있을때 처음에 "A"라는 Name 갖는 answer를 저장 후에 테스트 2에서 "A"를 조회할 때 오류가 발생하는 것 같은데 한번에 테스트를 실행하게 되면 1번 이후 COMMIT 2번 실행 으로 처리가 되어서 오류가 발생하는 것일까요,,?? 아니면 제가 테스트를 잘 못 한 것일까요,,? 테스트 코드도 한번에 쭉 실행하면 서로 연관이 생기는 건가요?

`@BeforeEach` 혹은 `@Before` 같은 어노테이션을 이용해서 각각의 테스트 코드 마다 Entity를 초기화해주는 작업이 필요하답니다. 테스트코드도 결국 실제로 코드를 실행하는 것이기 때문에 JPA 코드를 실행할 경우 DB에 반영되고, 보통 테스트 순서가 보장되지 않기 때문에(병렬로 진행)  데이터를 초기화해주지 않으면 다른 테스트 코드에 영향을 주게 됩니다!

2021-05-31 15:12 UTC, JunilHwang commented on src/main/java/qna/domain/Answer.java
> +    private User writer;
LazyLoad 설정도 있으면 어떨까요?

2021-05-31 15:12 UTC, JunilHwang commented on src/main/java/qna/domain/Answer.java
> +    private Question question;
`@Where` 어노태이션을 이용해서 조건에 맞는 것들만 매핑되도록 하면 어떨까요?

2021-05-31 15:12 UTC, JunilHwang commented on src/main/java/qna/domain/QnaAbstract.java
> +    @Column(name = "created_at", nullable = false)
`@CreatedDate` 어노테이션도 붙여보면 어떨까요?

2021-06-01 04:46 UTC, Lee-Chungsun commented on src/main/java/qna/domain/Answer.java
> +    private User writer;
LazyLoad 와 EAGER 에 대해서 고민을 많이 해봤는데 즉시 로딩 시 비용도 많이 들고 그런 문제들로 기본적으로 LazyLoad를 설정한 뒤에 @EntityGraph 로 필요한 메서드들에 한해서 사용하는 걸로 이해가 되었습니다!
LazyLoad 적용하였습니다~

2021-06-01 05:32 UTC, Lee-Chungsun commented on src/main/java/qna/domain/QnaAbstract.java
> +    @Column(name = "created_at", nullable = false)
@EnableJpaAuditing 과 @EntityListeners(AuditingEntityListener.class)를 이용해서 createAt 와 updateAt 자동 insert 되도록 반영하였습니다~
리뷰 감사드립니다!!😊

2021-06-01 06:05 UTC, Lee-Chungsun commented on src/main/java/qna/domain/Answer.java
> +    private Question question;
```@Where``` annotation 으로 deleted = false 인 조건을 붙여서 조회하도록 반영하였습니다!
리뷰 감사드립니다~!😊

2021-06-01 06:25 UTC, JunilHwang approved these changes
안녕하세요 충선님! 피드백 반영 잘 해주셨네요 👍 
Step2는 여기서 마무리하겠습니다. 다음 스텝 바로 진행해주세요!

2021-06-01 06:25 UTC, merged