[2주차 3단계] 질문 삭제하기 리팩토링
next-step/jwp-qna pull request #79
Opened 2021-05-31 14:33 UTC by AppleMango2021

휘준님 안녕하세요. 3단계 리뷰 요청드립니다!

기능 요구사항이 특별히 어려웠던 것은 아니지만, JPA가 익숙하지 않다 보니 어떤식으로 접근을 해야할 지 고민하는데 가장 시간이 많이 걸렸던 것 같습니다. 여러모로 검색을 하면서 구현해보기는 했는데, 미흡한 부분이 많을것으로 생각됩니다.
미리 리뷰 감사드립니다😂

이번에도 구현하면서 궁금했던 점과 [지난 단계에 남겨주신 코멘트](https://github.com/next-step/jwp-qna/pull/51#discussion_r642145733)에 대한 제 나름의 코멘트도 남겨두었으니 확인 부탁드립니다!

2021-05-31 15:06 UTC, AppleMango2021 commented on src/main/java/qna/domain/AnswerRepository.java
> -
[2단계의 힌트](https://edu.nextstep.camp/s/ffeVDScX/ls/gULJdWFU)에서도 나왔듯이, `Question`의 `id`를 인자로 전달하여 DB로부터 `List<Answer>` 데이터를 가져오는 것은 객체지향적이지 않은 것이 맞다고 생각합니다. 그래서 이번 과제에서도 `AnswerRepository`를 통하지 않고, `Question` 객체에 `deleteBy` 메소드를 구현하여 연관된 `Answers`의 삭제처리까지 구현하는 걸로 진행하였는데요,

그렇다면 실제 서비스에서  `Question` 엔티티와 연관되어 있는 `Answer` 엔티티들이 실제 DB에서 조회되는 시점이 궁금합니다. `QuestionRepository`의 `findById()`를 통해 `Question` 엔티티가 DB에서 조회되는 순간에, `answer` 테이블을 훑어서 외래키값으로 해당 `Question`의 `id`를 가지고 있는 `Answer` 엔티티들을 모두 가져오는건지 아니면 특정 시점이 정해져 있는 건지....이 부분이 아직 와닿지가 않는데, 어떤 키워드로 검색해야 할지도 막막합니다😭

2021-05-31 15:12 UTC, AppleMango2021 commented on src/main/java/qna/domain/User.java
> +        return this.userId.equals(target.userId);
[지난 코멘트](https://github.com/next-step/jwp-qna/pull/51#discussion_r642145733)에서 "내가 이 객체를 왜 설계하고 사용하는가"에 집중해보라는 코멘트를 받고 User라는 객체가 왜 필요한가에 대해서 생각했습니다. 

우선 현재 서비스에 한해서는 질문/답변 작성자와 동일한 사용자만 삭제할 수 있도록 제한을 걸기 위해 별도로 User 객체를 만들어 관리하고 있다고 생각합니다. 그렇다면 동일한 사용자임을 어떻게 판단할 수 있는지가 관건이라고 생각하였는데,  `userId`에 유니크 제약조건이 걸려있기 때문에,  _동일한 `userId`를 가진 사용자라면 동일한 사용자이다_ 라는 판단하에 `equals()`에 `userId`만 비교하도록 수정하였습니다.

2021-06-02 12:39 UTC, wheejuni requested changes
마지막 스텝까지 대단히 잘 구현해 주셨습니다. 💯 
몇 가지 피드백과, 질문하신 부분에 대한 답변 함께 남겼습니다.
리뷰가 늦어져서 죄송하고요, ㅠㅠ 확인을 부탁드립니다!

2021-06-02 12:39 UTC, wheejuni commented on src/main/java/qna/domain/AnswerRepository.java
> -
@AppleMango2021 우선 늦게 확인하여 정말 죄송합니다. ㅠㅠ
`JPA Lazy Fetch, Eager Fetch` 등의 키워드로 검색해보시면 관련 자료가 많이 나올 거고요,
이렇게 설계할 때에 어떤 기준을 가져야 하는지, 어떤 성능상의 리스크를 갖는지도 같이 학습해보시면 정말 좋겠습니다.

2021-06-02 12:39 UTC, wheejuni commented on src/main/java/qna/domain/Question.java
> +    * → 하지만 순수자바객체 입장에서는 Question의 Answers에도 answer를 추가해주어야 한다.
좋네요. 👍 스스로 추가 학습을 진행하신 건가요?

2021-06-02 12:39 UTC, wheejuni commented on src/main/java/qna/domain/Question.java
> +        deleteHistories.add(new DeleteHistory(ContentType.QUESTION, this.id, this.writer, LocalDateTime.now()));
지금 보면 이 생성자 파라메터 중 동적으로 변화해야 할 값은 `id` 와 `writer` 말고는 없어보이는군요.
질문에 관한 히스토리라면 계속해서 `ContentType.QUESTION` 으로 부여될 거고요, 시간도 당연히 `.now()` 로 찍히겠죠.
그렇다면 이런 상황을 위한 스태틱 팩토리 메소드가 구현되어 있으면 어떨까요?

```java
public static DeleteHistory fromQuestion(Long id, User writer);

2021-06-02 12:39 UTC, wheejuni commented on src/main/java/qna/domain/User.java
> +        return this.userId.equals(target.userId);
@AppleMango2021 좋은 고민이십니다.
그런데 이 로직을 직접 구현하지 말고 IDE의 자동 생성 등으로 구현하시는 것이 항상 안전합니다. 
이 부분만 다시 고려해보시면 좋겠습니다.

2021-06-03 14:07 UTC, AppleMango2021 commented on src/main/java/qna/domain/Question.java
> +    * → 하지만 순수자바객체 입장에서는 Question의 Answers에도 answer를 추가해주어야 한다.
넵 QuestionTest를 진행하는데 생각했던 것과 다른 결과가 나와 편의메소드에 대해 좀더 알아보았습니다!

2021-06-03 14:08 UTC, AppleMango2021 commented on src/main/java/qna/domain/Question.java
> +        deleteHistories.add(new DeleteHistory(ContentType.QUESTION, this.id, this.writer, LocalDateTime.now()));
스태틱 팩토리 메소드에 대해 설명은 많이 들었어도 언제 사용할지가 와닿지 않았는데 이렇게 사용하면 되는거라는 걸 알았습니다 ㅎㅎ 감사합니다!

2021-06-03 14:14 UTC, AppleMango2021 commented
휘준님 안녕하세요!

제가 PR만 날리고 요청을 안 드린줄 알고 다시 눌렀는데, 재촉한 셈이 된거같아 죄송합니다 ㅠㅠ 슬랙에서 메세지 찾기가 어려워서 요청 드린걸 못 찾았습니다.

달아주신 코멘트를 바탕으로 수정 진행하였습니다. JPA 검색하면서 fetch전략과 관련된 어노테이션을 많이 보기는 했지만 내용은 몰랐는데, 덕분에 이번 기회에 이론적인 내용을 조금 공부할 수 있었습니다. @OneToMany는 기본전략이 Lazy이고, @ManyToOne은 Eager여서 @ManyToOne 엔티티에 해당하는 fetch 전략만 수정하였습니다. 

미리 피드백 감사드립니다!

2021-06-03 14:41 UTC, wheejuni approved these changes
대단히 수고 많으셨습니다 👍 
무리없이 잘 구현해 주셨습니다. 머지하도록 할게요.

2021-06-03 14:41 UTC, merged