JPA Step2 PR 입니다. pr 날릴때마다. next step upstream에서 컨플릭트가 나는 이유는 무엇일까요?
next-step/jwp-qna pull request #88
Opened 2021-06-01 03:07 UTC by accidentlywoo

2021-06-01 03:24 UTC, LenKIM commented
Reviwer 에 의해서 브랜치가 upstream 에 머지되었습니다. 머지커밋이 찍혔을 테고, 거기서부터 새로운 브랜치를 생성하여 작업하신 내역을 cherry-pick 하시면 문제가 발생하지 않을거예요!

2021-06-02 01:20 UTC, kang-hyungu requested changes
연희님 구현하신 2단계 코드 확인했습니다.
몇 가지 피드백 남겼는데 수정하시고 리뷰 재요청 주세요
궁금한 점이 생기면 dm 주시거나 코멘트 남겨주세요

2021-06-02 01:20 UTC, kang-hyungu commented on src/main/java/qna/domain/Answer.java
> +    private User user;
변수명을 user로 바꾸신 이유가 있을까요?

2021-06-02 01:20 UTC, kang-hyungu commented on src/main/java/qna/domain/Answer.java
toString 메서드가 리뷰 남기는 곳에 안보여서 여기에 코멘트 남겨요
toString 메서드에서 컴파일 에러가 발생하는데 확인 부탁드려요

2021-06-02 01:20 UTC, kang-hyungu commented on src/main/java/qna/domain/Answer.java
>      private Question question;
객체 관계를 설정하셨는데 getter, setter 용도로 사용하는 메서드는 questionId를 사용하고 계시군요.
이 부분도 변경이 필요하지 않을까요?

2021-06-02 01:20 UTC, kang-hyungu commented on src/main/java/qna/domain/Answer.java
>      protected Answer () { }
지난 미션에도 코멘트 남긴 내용입니다
각 엔티티에 매핑되는 테이블 이름에 t를 붙이신 이유가 있을까요?
t를 붙이게 된 이유 또는 배경 설명 부탁드려요

2021-06-02 01:20 UTC, kang-hyungu commented on src/test/java/qna/domain/AnswerTest.java
>      private AnswerRepository answerRepository;
AnswerTest는 Answer에 대한 테스트만 존재하는게 좋지 않을까요?
AnswerRepository는 AnswerRepositoryTest 클래스를 추가해서 테스트 코드를 작성해보아요

2021-06-02 01:20 UTC, kang-hyungu commented on src/test/java/qna/domain/AnswerTest.java
>      private AnswerRepository answerRepository;
그리고 사용하지 않는 import 구문은 제거해보아요

2021-06-02 01:20 UTC, kang-hyungu commented on src/test/java/qna/domain/QuestionTest.java
> +    private TestEntityManager entityManager;
TestEntityManager가 없어도 테스트가 정상 동작할텐데... 추가하신 이유가 있을까요?

2021-06-02 01:20 UTC, kang-hyungu commented on src/main/java/qna/domain/Answer.java
이 코드뿐만 아니라 다른 코드도 컴파일 에러가 발생하네요
미션 제출하시기 전에 코드가 정상 동작하는지 확인하시고 제출 부탁드려요.

2021-06-02 07:26 UTC, accidentlywoo commented on src/main/java/qna/domain/Answer.java
음... 컴파일에러도 없고, toString 오버라이딩되있는데... 이상하네요.

2021-06-02 07:29 UTC, accidentlywoo commented on src/main/java/qna/domain/Answer.java
>      protected Answer () { }
테이블명을 명시적으로 't_'를 붙이면 테이블 네이밍이 편하더라구요! 그냥 이전회사의 DBA님 컨벤션이 맘에들어 사용하고있습니다.

2021-06-02 12:33 UTC, accidentlywoo commented on src/main/java/qna/domain/Answer.java
> +    private User user;
writer로 쓰면 오히려 순간적으로 혼란스럽고, 엔티티명을 그대로 쓰는게 나을것같아서 썼습니다

2021-06-02 12:36 UTC, accidentlywoo commented on src/test/java/qna/domain/QuestionTest.java
> +    private TestEntityManager entityManager;
H2 디비가 MySQL과 동작차이가 생각보다 많이 일어나서 깔끔하게 flush를 했습니다.

2021-06-03 07:46 UTC, kang-hyungu commented on src/main/java/qna/domain/Answer.java
> +    private User user;
답변을 작성한 사람을 뜻하는 변수이니 writer가 혼란스럽지 않을 것 같은데...
user라고 쓰면 Answer와 어떤 관계의 객체인지 바로 파악이 안되지 않을까요?

2021-06-03 07:48 UTC, kang-hyungu requested changes
연희님 커밋한 내용이 없는걸로 나오네요
깃헙에 작업하신 내용 push하시고 코드가 깃헙 브랜치에 잘 반영되었는지 확인 후 리뷰 요청 부탁드려요~!

2021-06-03 07:49 UTC, kang-hyungu commented on src/main/java/qna/domain/Answer.java
userId를 User로 객체 관계로 설정하면서 toString에 수정하지 않은 부분이 있네요

<img width="342" alt="image" src="https://user-images.githubusercontent.com/15669435/120607816-8113f880-c48b-11eb-844b-01843c82f372.png">

2021-06-03 07:51 UTC, kang-hyungu commented on src/main/java/qna/domain/Answer.java
>      protected Answer () { }
't_'가 어떤 점에서 테이블 네이밍을 편하게 하나요? 저 부분 제외하면 테이블 이름 붙이는건 동일하게 클래스명 또는 사용자가 지정한 이름일텐데...

클린코드에 불용어(noise word)와 관련된 내용이 있으니 참고하세요

클린코드 25p
...
불용어를 추가한 이름 역시 아무런 정보도 제공하지 못한다.
Product라는 클래스가 있다고 가정하자.
다른 클래스를 ProductInfo 혹은 ProductData라 부른다면 개념을 구분하지 않은 채 이름만 달리한 경우다.
Info나 Data는 a, an, the와 마찬가지로 의미가 불분명한 불용어다.
a나 the와 같은 접두어를 사용하지 말라는 소리가 아니다.
의미가 분명히 다르다면 사용해도 무방하다. 예를 들어, 모든 지역 변수는 a를 사용하고 모든 함수 인수는 the를 사용해도 되겠다.
요지는 zork라는 변수가 있다는 이유만으로 theZork라 이름 지어서는 안 된다는 말이다.
...

2021-06-03 07:55 UTC, kang-hyungu commented on src/test/java/qna/domain/QuestionTest.java
> +    private TestEntityManager entityManager;
`H2 디비가 MySQL과 동작차이`가 발생해서 엔티티 매니저가 필요한 상황이 있나요?
실제 어떤 차이가 있었는지 알려주시겠어요?

2021-06-03 08:03 UTC, kang-hyungu approved these changes
연희님 피드백 반영하신 내용 확인했습니다~!
추가로 남긴 코멘트는 다음 미션 진행하실 때 참고하세요
pr 머지 처리하겠습니다. 수고하셨어요~!

2021-06-03 08:03 UTC, kang-hyungu commented on src/test/java/qna/domain/AnswerRepositoryTest.java
> +    public void save(){
```suggestion
    public void save() {
```

https://google.github.io/styleguide/javaguide.html#s4.6.2-horizontal-whitespace

다른 코드도 같이 수정해보아요

2021-06-03 08:03 UTC, merged

2021-06-03 08:12 UTC, accidentlywoo commented on src/test/java/qna/domain/AnswerRepositoryTest.java
> +    public void save(){
훔훔.. 코드 스타일맞추고, 포맷을 돌리는데도 하나씩 걸리네용 ㅠ

2021-06-04 06:05 UTC, accidentlywoo commented on src/test/java/qna/domain/QuestionTest.java
> +    private TestEntityManager entityManager;
MySQL에서 Id가 GenerationType.IDENTITY 설정으로 되있으면 id값을 미리 설정했을때, 에러가 발생하고 자동으로 flush가 날라가는데, H2디비는 GenerationType.IDENTITY로 설정되있어도 id값을 세팅할 수 있드라구요! mysql은 id값을 받아오기위해서 자동으로 flush가되서 디비에서 id값을 가져오는 걸로알고있습니다.

2021-06-04 06:07 UTC, accidentlywoo commented on src/main/java/qna/domain/Answer.java
>      protected Answer () { }
불용어와는 상관없는 테이블 네이밍 컨벤션이라고 생각했습니다. 테이블명은 클래스가 아니니깐요. 불필요해보이니 삭제하겠습니다~

2021-06-04 06:09 UTC, accidentlywoo commented on src/main/java/qna/domain/Answer.java
흠... 뭔가 이상하네요..